### ISSUE TITLE
Potential invalid error

### ISSUE THREAD

**Issue by RCalocaO** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1001]
[SC] Code 3 : Attachment 1 not written by FS
When we set a render pass for MRTs (G Buffers), some shaders will not write into some of the attachments. for optimization reasons. It would be bad on tiled architectures to have to switch render passes because of this. Is this a real error or a perf warning? Other shaders might write into them, so maybe the validation layer can check on the whole set of shaders inside the render pass if what it wants to find is uninitialized attachments.

**Comment by chrisforbes** [comment]
This area is actually a bit underspecified - it's an interface mismatch, but the degree of bad behavior allowed is murky. My interpretation is that you may get undefined junk in those attachments, unless you've also configured the blend state to mask off all the channels that are present. SC currently doesn't consider the blend state though, so you can get false positives here.

**Comment by karl-lunarg** [comment]
@RCalocaO, can you close this if you agree?

**Comment by RCalocaO** [comment]
I'll bring it up on Khronos for clarity.
