### ISSUE TITLE
Mem tracker layer: "Invalid usage flag for buffer X used by vkCmdCopyQueryPoolResults()" error incorrectly reported

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#101]
In the debug call-back, the layer informs the target buffer should have VK_BUFFER_USAGE_TRANSFER_DST_BIT usage set during creation. I believe this used to be a requirement back in the days, but has eventually been lifted. Checked the latest spec language, but I wasn't able to find any language backing this error.

Proposal is to remove the check:

![image](https://cloud.githubusercontent.com/assets/17761066/13666864/feb47a64-e6b3-11e5-957f-c9be13340f28.png)

**Comment by lentinem** [comment]
Can you post the error that was output? It would be easier to trace down if it's correct or not with that information.

**Comment by DominikWitczakAMD** [comment]
Sorry, of course:

![image](https://cloud.githubusercontent.com/assets/17761066/13698802/a719b6d4-e776-11e5-9a0f-92090918940f.png)

**Comment by lentinem** [comment]
Spec MR has been submitted so closing.
