### ISSUE TITLE
DrawState layer: As opposed to what the debug call-back claims, initial renderpass attachment layout does not need to match its starting layout

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#102]
Consider a renderpass, for which we define a single renderpass. The renderpass uses a single color attachment, whose initialLayout is set to A. Furthermore, we define a single subpass for the discussed renderpass, and set that attachment's layout to B.

For the discussed configuration, we get the following call-back at vkCmdBeginRenderPass() call time:

![image](https://cloud.githubusercontent.com/assets/17761066/13668737/fff2f940-e6be-11e5-880e-9ea8a22c877c.png)

![image](https://cloud.githubusercontent.com/assets/17761066/13668728/f386a792-e6be-11e5-91ed-7ff554ae59e4.png)

This is not true, and has no backing in the actual specification. Vulkan implementation should implicitly perform the initialLayout->layout transition for the application.

Proposal is to remove the check.

**Comment by lentinem** [comment]
This is saying initialLayout doesn't match the layout of the attachment prior to the start of the renderpass not that it doesn't match the attachment's layout.

**Comment by lentinem** [comment]
The message is confusing though; let me know if you think this is still wrong. Either way we can update the message.

**Comment by DominikWitczakAMD** [comment]
Ah, yes, there was a bug in one of our test apps. I'd appreciate if we could make this call-back more meaningful though.

**Comment by lentinem** [comment]
Message updated. Closing.
