### ISSUE TITLE
cube demo has no-op barrier

### ISSUE THREAD

**Issue by janharaldfredriksen-arm** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1024]
demos/cube.c does this:
```
    VkPipelineStageFlags src_stages = VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT;
    VkPipelineStageFlags dest_stages = VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT;

    vkCmdPipelineBarrier(demo->cmd, src_stages, dest_stages, 0, 0, NULL, 0,
                         NULL, 1, pmemory_barrier);
```
.. which is a no-op per the explanation in #1006.

At least one of these barriers are inserted after a vkCmdCopyImage command, so src_stages must include at least VK_PIPELINE_STAGE_TRANSFER_BIT. Having dest_stages be TOP_OF_PIPE is overly conservative, but not wrong. (I'm guessing FRAGMENT_SHADER_BIT|TRANSFER_BIT would be sufficient, but I haven't checked in detail.)

**Comment by Tony-LunarG** [comment]
Fixed with df484631
