### ISSUE TITLE
Lots of Warnings in the Build

### ISSUE THREAD

**Issue by FireBurn** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1026]
There's quite a lot of warnings in the build - I'm not sure if any of them are serious or not

[build.txt](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/files/514565/build.txt)

**Comment by MarkY-LunarG** [comment]
I'll take care of the loader warnings.

**Comment by mark-lunarg** [comment]
Looks like a lot of these are glslang, which is in a different repo but I can take care of the V-LaVL ones.  Thanks!

**Comment by MarkY-LunarG** [comment]
Yes, I should have mentioned that.  You should submit the glslang warnings in their [GitHub](https://github.com/KhronosGroup/glslang)

**Comment by MarkY-LunarG** [comment]
Loader changes committed: f2d7e5451a695a9230867f64e281d7f09df831b5

**Comment by jeremy-lunarg** [comment]
I've got some PRs on the glslang repo. That should fix all but one of the warnings from GCC. The last warning is interesting. As far as I can tell, it's a GCC bug. It's getting confused by an operator| overload and treating a constant in the header incorrectly. There are some workarounds, but they feel contentious. As such, I'm inclined to leave it be. I'm going to close this issue. Thanks!
