### ISSUE TITLE
Layers: sparse buffer size not tracked

### ISSUE THREAD

**Issue by yavn** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1030]
I'm getting the following error:

> DS(ERROR): object: 0x0 type: 0 location: 8916 msgCode: 10: vkCmdPipelineBarrier: Buffer Barrier 0x1 has offset 0x0 which is not less than total size 0x0.

This happens because `buffer_node->memSize` is 0 in `ValidateBarriers()`. It could be that size isn't updated correctly when buffer is bound in `QueueBindSparse()`. The same probably happens for sparse images as well.

**Comment by mark-lunarg** [comment]
@yavn. this was likely addressed by PR #1063 which was pushed a week or two after this issue was created.  Please give it another shot with Master or the next SDK and reopen if it is not adequately addressed.

**Comment by yavn** [comment]
Hi, I'm building the layers daily from master and I can't say this is fixed. I'm still getting the very same error message when `vkCmdPipelineBarrier` is called.

I tracked this down to `SetSparseMemBinding` routine where `mem_binding` is set for the buffer. I see that sparse binding is updated, but not the ordinary binding. The verification function `ValidateBarriers` then accessess `buffer_node->binding.size` which is 0.

[code link](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/core_validation.cpp#L832)

I'm not sure how this should be fixed, i.e. should sparse buffers set `binding` field as well, or should the verification logic check `sparse_binding` where applicable.

As a bonus I've found one more error in descriptor set validation:

>DS(ERROR): object: 0xd type: 23 location: 2961 msgCode: 58: Descriptor set 0xd encountered the following validation error at vkCmdDispatch() time: Descriptor in binding #0 at global descriptor index 0 uses buffer 0000000000000001 that references invalid memory 0000000000000000.

But I'm pretty sure it occurs for the very same reason.

I don't seem to have an option to reopen the issue, so please do that on my behalf if you agree with the above. Thanks!

**Comment by tobine** [comment]
I'll take this @MarkY-LunarG

**Comment by tobine** [comment]
And also @mark-lunarg :)
