### ISSUE TITLE
Cube demo WSI barriers

### ISSUE THREAD

**Issue by szdarkhack** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1033]
According to my understanding of the synchronization operations, the image barriers for the acquisition and release of the swapchain images by the application could be improved.

For reference, the issues discussed appear in the function demo_draw_build_cmd().

For starters, and this is not even a sync issue, the acquisition barrier specifies the oldLayout as PRESENT_SRC, while it does not care for preserving the contents (as mentioned in a comment in a subsequent barrier, and evidenced by the lack of ownership transfer). It should, therefore, be set as UNDEFINED, so that the implementation skip the conversion.

Now on to sync. The spec contains the following text (section 6.2 Semaphores):

> This semaphore signal operation defines the first half of a memory dependency, guaranteeing that all memory accesses defined by the submitted queue operations in the batch are made available, and that those queue operations have completed execution.

> Semaphore signal operations for vkQueueSubmit additionally include all queue operations previously submitted via vkQueueSubmit in their half of a memory dependency, and all batches that are stored at a lower index in the same pSubmits array.

> Signaling of semaphores can be waited on by similarly including them in a batch, defining a queue operation to wait for a signal. A semaphore wait operation defines the second half of a memory dependency for the semaphores being waited on. This half of the memory dependency guarantees that the first half has completed execution, and also guarantees that all available memory accesses are made visible to the queue operations in the batch.

> Semaphore wait operations for vkQueueSubmit additionally include all queue operations subsequently submitted via vkQueueSubmit in their half of a memory dependency, and all batches that are stored at a higher index in the same pSubmits array.

That, to me, indicates that the acquisition and release semaphores take care of the memory sync themselves. It seems, therefore, that it would be unnecessary to include anything in srcAccessMask and dstAccessMask in either barrier (of course the barriers themselves are still required for layout transitions and ownership transfer). Of course, it is unclear whether WSI operations count as "queue operations submitted via vkQueueSubmit", so including MEMORY_READ in the dstAccessMask of the present barrier might be necessary (see below). This really needs some clarification in the spec.

Additionally, this (section 6.5.2 Pipeline Stage Flags):

> The VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT is useful for accomplishing memory barriers and layout transitions when the next accesses will be done in a different queue or by a presentation engine; in these cases subsequent commands in the same queue do not need to wait, but the barrier or transition must complete before semaphores associated with the batch signal.

and this (section 29.6 WSI Swapchain):

> Before an application can present an image, the image’s layout must be transitioned to the VK_IMAGE_LAYOUT_PRESENT_SRC_KHR layout. The vkCmdWaitEvents or vkCmdPipelineBarrier that perform the transition must have srcStageMask and srcAccessMask parameters set based on the preceding use of the image. The dstAccessMask must include VK_ACCESS_MEMORY_READ_BIT indicating all prior accesses indicated in srcAccessMask from stages in srcStageMask are to be made available to reads by the presentation engine. Any value of dstStageMask is valid, but should be set to VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT to avoid delaying subsequent commands that do not access the image.

make it pretty clear that the dstStageMask of the release barrier should be set to BOTTOM_OF_PIPE instead of the current COLOR_ATTACHMENT_OUTPUT. In the cube demo the release barrier is manually performed only if there is a need to transfer ownership. The text also raises the above issue about MEMORY_READ. Again, the spec needs clarification on this.

Finally, since the renderpass doesn't use external dependencies it is unclear how to properly extend dependency chains off of it. Specifically, it is unclear what srcStageMask should be used to chain the ownership barrier after the renderpass' ending layout transition (I guess BOTTOM_OF_PIPE should work according to 6.4). This case should probably also be clarified a bit.

In any case, this last bit is probably an actual bug in the current demo which uses COLOR_ATTACHMENT_OUTPUT (if I'm not mistaken, this could in theory allow the barrier to be scheduled before the renderpass' layout transition, which would then find the image in the wrong oldLayout).

**Comment by Tony-LunarG** [comment]
Fixed with 746da8ab2a
