### ISSUE TITLE
Validation assert when multiple memory bindings per image

### ISSUE THREAD

**Issue by Tony-LunarG** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1037]
Running the conformance tests with current validation, I'm seeing an assert in core validation due to assumptions that the is only one memory binding per image, where with sparse memory bindings there can be multiple memory bindings.  I've pushed a branch with a new BindSparse test that mimics the behavior of the CTS test and hits that same assert.  The branch is tony-sparse-test.  Assert is core_validation.c line 728 - the code can't find an image to go with the memory it's freeing and asserts.

**Comment by tobine** [comment]
I'll check this out. I added some exceptions to ValidateMemoryIsBoundTo[Image|Buffer] functions recently for the sparse case, but I'm sure there are other checks that need similar treatment

**Comment by tobine** [comment]
@Tony-LunarG take a look at tobin_gh1037_sparse_as_separate_bindings branch. It adds very initial and very limited support for sparse bindings that fixes the assert in your test. There's now a new error appearing on my dev system which appears be coming out of the driver as it's not a validation error and the debug callback function stack originates below unique_objects:

`Expected to succeed but got error: vkBindSparseImageOpaqueMemory: pBindInfo->size 8000 is not aligned to 10000`

Longer-term we're going to need to overhaul memory binding in validation to add proper support for sparse binding.

If you agree that the branch works I'll put it out for more general review.

**Comment by Tony-LunarG** [comment]
Mixed results.  It does fix the tests that were failing, and now the image_sparse_binding tests pass, but now it gets an access violation in dEQP-VK.sparse_resources.buffer_sparse_binding.buffer_size_2_10 where it used to pass.  It's trying to read 0xffffffffffffffff in invalidateCommandBuffers at cb_node->broken_bindings.push_back(obj), called from DestroyBuffer.  Nothing looks obviously wrong in the variables / call stack.  This is on a Windows 7 Nvidia system.

**Comment by tobine** [comment]
Can you give a bit more detail on where 0xffff... comes from? Is it the buffer handle cast as a unit64_t within the obj?
I reviewed the code and looked at buffer_sparse_binding test in deqp and neither game me any revelations about what may cause an error at the point you're seeing.
The previous line accesses cb_node->state. Did that succeed? Does cb_node look reasonable?
My initial guess would be that the buffer's cb_bindings set has a reference to a stale cmd buffer somehow, but if that's the case then I would think cb_node->state on the previous line would hit an error.

**Comment by Tony-LunarG** [comment]
It looks like the test submits a command buffer referencing the buffer, does a QueueWaitIdle, frees the command buffer and then destroys the buffer.  Should the DestroyBuffer code be referencing cb_nodes when all of the command buffers have already been freed?  Large potions of the cb_node have been freed or are garbage.

**Comment by tobine** [comment]
No, an object's cmd buffer reference in cb_bindings should get removed when that cmd buffer is freed. This should occur for every object that references the cmd buffer being freed. The flow in core_validation is:

1. FreeCommandBuffers() calls resetCB() prior to deletion
2. Near the end of resetCB() there's a loop over pCB->object_bindings() that calls removeCommandBufferBinding() for each object binding
3. removeCommandBufferBinding() will erase the cmd buffer being freed from that objects cb_bindings set.

Something in that flow must be broken to cause the error you're seeing. Can you walk through the cmd buffer getting freed and see if these steps appear to be occurring correctly?

**Comment by Tony-LunarG** [comment]
The problem is that because the buffer in question uses QueueBindSparse to bind its memory, its buf_node->binding.mem is not set and left at 0, then in AddCommandBufferBindingBuffer, getMemObjInfo returns NULL and the buffer's buf_node is not put into cb_node's object_bindings, but cb_node is put into buf_node's cb_bindings.  So resetCB never sees the buffer's buf_node in object_bindings, but DestroyBuffer sees the (now freed)  cb_node in buf_node's cb_bindings and bad pointers are dereferenced

**Comment by tobine** [comment]
Great job, @Tony-LunarG you nailed it. I've pushed a fix for this binding imbalance to the branch. Please check it out.

**Comment by Tony-LunarG** [comment]
That gets all of the sparse tests passing.  I'll do a full mustpass run over the weekend.

**Comment by tobine** [comment]
Cool, sounds good. Report results and I can merge next week as it will have some conflicts with recent changes.

**Comment by Tony-LunarG** [comment]
Tests ran all the way through - looks good

**Comment by tobine** [comment]
Fix was cherry-picked and pushed to master
