### ISSUE TITLE
Issues building cube.cpp

### ISSUE THREAD

**Issue by FireBurn** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1046]
I receive the following warning when building cube.c

[ 57%] Building C object demos/CMakeFiles/cube.dir/cube.c.o
/var/tmp/portage/media-libs/vulkan-base-9999/work/vulkan-base-9999/demos/cube.cpp:2826:36: error: expected ‘,’ or ‘...’ before ‘UNUSED’
 static void handle_ping(void *data UNUSED, wl_shell_surface *shell_surface,
                                    ^~~~~~
/var/tmp/portage/media-libs/vulkan-base-9999/work/vulkan-base-9999/demos/cube.cpp: In function ‘void handle_ping(void*)’:
/var/tmp/portage/media-libs/vulkan-base-9999/work/vulkan-base-9999/demos/cube.cpp:2828:27: error: ‘shell_surface’ was not declared in this scope
     wl_shell_surface_pong(shell_surface, serial);
                           ^~~~~~~~~~~~~
/var/tmp/portage/media-libs/vulkan-base-9999/work/vulkan-base-9999/demos/cube.cpp:2828:42: error: ‘serial’ was not declared in this scope
     wl_shell_surface_pong(shell_surface, serial);
                                          ^~~~~~
/var/tmp/portage/media-libs/vulkan-base-9999/work/vulkan-base-9999/demos/cube.cpp: At global scope:
/var/tmp/portage/media-libs/vulkan-base-9999/work/vulkan-base-9999/demos/cube.cpp:2831:41: error: expected ‘,’ or ‘...’ before ‘UNUSED’
 static void handle_configure(void *data UNUSED,
                                         ^~~~~~
/var/tmp/portage/media-libs/vulkan-base-9999/work/vulkan-base-9999/demos/cube.cpp:2836:42: error: expected ‘,’ or ‘...’ before ‘UNUSED’
 static void handle_popup_done(void *data UNUSED,
                                          ^~~~~~
/var/tmp/portage/media-libs/vulkan-base-9999/work/vulkan-base-9999/demos/cube.cpp:2840:53: warning: invalid conversion from ‘void (*)(void*)’ to ‘void (*)(void*, wl_shell_surface*, uint32_t) {aka void (*)(void*, wl_shell_surface*, unsigned int)}’ [-fpermissive]
     handle_ping, handle_configure, handle_popup_done};
                                                     ^
/var/tmp/portage/media-libs/vulkan-base-9999/work/vulkan-base-9999/demos/cube.cpp:2840:53: warning: invalid conversion from ‘void (*)(void*)’ to ‘void (*)(void*, wl_shell_surface*, uint32_t, int32_t, int32_t) {aka void (*)(void*, wl_shell_surface*, unsigned int, int, int)}’ [-fpermissive]
/var/tmp/portage/media-libs/vulkan-base-9999/work/vulkan-base-9999/demos/cube.cpp:2840:53: warning: invalid conversion from ‘void (*)(void*)’ to ‘void (*)(void*, wl_shell_surface*)’ [-fpermissive]
[ 58%] Linking C executable cube
[ 60%] Built target cube
make[2]: *** [demos/CMakeFiles/cubepp.dir/build.make:73: demos/CMakeFiles/cubepp.dir/cube.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1623: demos/CMakeFiles/cubepp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

This is on GCC 6.2

**Comment by jeremy-lunarg** [comment]
These errors are against the cpp version and appear to be wayland specific. I'll take a look at this. Thanks.

**Comment by jeremy-lunarg** [comment]
I pushed a patch that should clear these errors up. Thanks!
