### ISSUE TITLE
DrawState layer: Crash in vkGetQueryPoolResults() handler

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#105]
Potentially related to #68.

I'm getting a crash at vkGetQueryPoolResults() call time because of pCB being NULL and the layer handler's implementation assuming it to be always valid:

![image](https://cloud.githubusercontent.com/assets/17761066/13669821/4f4d5b50-e6c6-11e5-8f65-f3a80eb5d611.png)

Right before the crash, I receive a call-back from DS saying "Attempt to use CommandBuffer X that doesn't exist!".

**Comment by lentinem** [comment]
This will likely be fixed with MR 110 (it now should be removed from globalInFlightCmdBuffers).

**Comment by DominikWitczakAMD** [comment]
Issue fixed, closing
