### ISSUE TITLE
Validation layer for VkGraphicsPipelineCreateInfo should check for qualifier 'flat' in shaders

### ISSUE THREAD

**Issue by FslNopper** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1052]
When calling vkCreateGraphicsPipelines, the shader modules of VkGraphicsPipelineCreateInfo should be checked, if outgoing and incoming qualifiers like 'flat' do match.

**Comment by chrisforbes** [comment]
No, this isn't correct.

14.1.3 says:
> ... except that interpolation decorations are not required to match.

**Comment by FslNopper** [comment]
I revisited the specification and you are right.

So, it is a driver bug.

**Comment by chrisforbes** [comment]
If CTS isn't covering this case, we should probably fix that...
