### ISSUE TITLE
Embed cube-frag.spv  cube-vert.spv into the cube demo to make it more portible

### ISSUE THREAD

**Issue by FireBurn** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1054]
Is it possible to embed cube-frag.spv  cube-vert.spv into the cube demo so the executable can be run from anywhere, currently it must be loaded when the two shaders are in the current directory

**Comment by karl-lunarg** [comment]
This is a good idea and I've thought of it too.   The SPIR-V could be generated and copied into a .h file at build time and then that .h file could be included by cube.c.  This also saves the cube program the task of opening and reading the files at run time.

This also could lend itself to an alternate way of delivering sources for cube.  The SPIR-V could be generated and inserted into the header, and then the header and C file provided together, obviating the need to run the glslang to spirv conversion, which reduces the need for that tool.  (This wouldn't take place in the repo.   But it would be good if you wanted to minimally wrap cube up and take it someplace else.)

The catch is that the cube demo also uses an image file for the texture map that the cube program loads at run-time.  So even if the shader programs are embedded in the C file, there is still another file that needs to be present to run the program.  And that keeps your goal from being reached completely.

The image file could be embedded into source, but that's not a great idea.  The cube program could be written to simply skip the texture map if it can't find the image file and go ahead and draw without it.

**Comment by karl-lunarg** [comment]
Sorry, clicked 'Close issue' by accident.

All that being said, I don't know how important it is to do all of this, just to gain the convenience of not copying the supporting files along for this simple demo program.

Let us know if there is a more compelling use case.

**Comment by FireBurn** [comment]
Maybe the demo could look in a particular place for it's files then, /usr/share/vulkan/demos is where I'm currently installing to, but unless I'm in that directory I can't run cube

Like glxgears cube is a great way of quickly checking vulkan is rendering correctly

**Comment by karl-lunarg** [comment]
Yes, I can see the value in having a single standalone binary, like glxgears.   Even if got it down to one binary and one image file, there's still the step of putting the image file someplace, and that's an extra step.

Note that there's another demo that meets your criteria.  It is called smoke/smoketest and is a bit more interesting than cube.  It generates headers containing the spirv at build time and has no other file dependencies.

**Comment by Tony-LunarG** [comment]
Jeremy volunteered for this one

**Comment by mark-lunarg** [comment]
Bump.
