### ISSUE TITLE
Check for the existence of Location decoration(s) on a Block

### ISSUE THREAD

**Issue by martty** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1065]
When loading a Shader Module, the following must hold according to the spec:

"The layout of a structure type used as an Input or Output depends on whether it is also a Block (i.e. has a Block decoration).

If it is a not a Block, then the structure type must have a Location decoration. Its members are assigned consecutive locations in their declaration order, with the first member assigned to the location specified for the structure type. The members, and their nested types, must not themselves have Location decorations.

If the structure type is a Block but without a Location, then each of its members must have a Location decoration. If it is a Block with a Location decoration, then its members are assigned consecutive locations in declaration order, starting from the first member which is initially assigned the location specified for the Block. Any member with its own Location decoration is assigned that location. Each remaining member is assigned the location after the immediately preceding member in declaration order."

Currently there is no validation error when loading a SPIR-V module that has a Block type without Location decoration(s). This is not valid SPIR-V for Vulkan and should be a validation error.

Example vertex shader:

```
#version 450 core
layout(location = 0) in vec2 aPos;
layout(location = 1) in vec2 aUV;
layout(location = 2) in vec4 aColor;

layout(push_constant) uniform uPushConstant{
    vec2 uScale;
    vec2 uTranslate;
} pc;

out block{
    vec4 Color;
    vec2 UV;
} Out;

void main()
{
    Out.Color = aColor;
    Out.UV = aUV;
    gl_Position = vec4(aPos*pc.uScale+pc.uTranslate, 0, 1);
}
```

**Comment by chrisforbes** [comment]
Question is whether we should do this in LVL, or in SPIRV-Tools.

**Comment by martty** [comment]
The subtle thing about this is that this is valid GLSL 4.50 (OpenGL would accept it), producing valid SPIR-V, just not Vulkan compatible.

**Comment by karl-lunarg** [comment]
@chrisforbes Who should follow up on this?

**Comment by chrisforbes** [comment]
@karl-lunarg I've filed a corresponding issue in SPIRV-Tools. I believe this can be handled properly on their side -- the validator knows what environment the module is to be used in, so @martty's concern shouldn't be a problem.

**Comment by karl-lunarg** [comment]
@chrisforbes Is this issue going to be sufficiently handled on the SPIRV-Tools side so that we can close this issue here?   (I think that the KhronosGroup/SPIRV-Tools#454 issue can still point at this one if this one is closed.)

**Comment by chrisforbes** [comment]
Yes, this can be closed.
