### ISSUE TITLE
Validation layers don't handle NULL func ptrs in dispatch table for extensions

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1074]
The validation layers contain code like this:

``` cpp
VKAPI_ATTR void VKAPI_CALL CmdDebugMarkerBeginEXT(VkCommandBuffer commandBuffer, VkDebugMarkerMarkerInfoEXT *pMarkerInfo) {
    bool skip_call = false;
    layer_data *my_data = get_my_data_ptr(get_dispatch_key(commandBuffer), layer_data_map);
    assert(my_data != NULL);

    skip_call |= parameter_validation_vkCmdDebugMarkerBeginEXT(my_data->report_data, pMarkerInfo);

    if (!skip_call) {
        get_dispatch_table(pc_device_table_map, commandBuffer)->CmdDebugMarkerBeginEXT(commandBuffer, pMarkerInfo);
    }
}
```

I found it in `parameter_validation.cpp` and `object_tracker.cpp` at least.

Since these are extension functions there is no guarantee the ICD or loader will implement them, so the dispatch chain may end in NULL instead of a terminating function and the layer has to handle that and return without calling onwards.

**Comment by lentinem** [comment]
I believe in this case the intent was such that these functions would not be called - not sure how this ended up though.

**Comment by baldurk** [comment]
I don't understand what you mean, why wouldn't you want these functions be called? It's certainly worthwhile to have the validation layers checking e.g. that the object exists or the command buffer is valid or other things about the calls. They just need to be able to handle the case when there's nothing further down the chain to pass along to.

**Comment by lentinem** [comment]
Perhaps I misunderstood. Is the extension enabled or disabled? Calling an extension function when it's not enabled is an error itself.

**Comment by baldurk** [comment]
Yes the extension is enabled. I didn't try calling the functions without it enabled, but as you say that's a different class of error.

**Comment by courtney-g** [comment]
It's possible to have extensions that are not supported in the ICD. In those cases, there needs to be an alternative terminator function to put at the end of the chain instead of the ICD.
We do that for the debug_report extension. It does require that the loader know about an extension though. If the layer were to check that the pointer is valid that might allow things to work without a specific terminator.

**Comment by lentinem** [comment]
Can we blanked initialize all of these pointers to a noop function if they would otherwise be null? We could also use that function to emit a warning which might be sensible.

**Comment by courtney-g** [comment]
That will probably work for most, but not all. What if the function needs to return a particular value?
What if it's supposed to fill in data? Those will need the appropriate terminator to provide the correct behavior. But most will probably be okay with a No-op function that returns VK_SUCCESS.

**Comment by cdwfs** [comment]
Was this issue resolved/fixed? It's definitely still causing problems in the 1.0.30 SDK; enabling VK_EXT_debug_marker and trying to set an object's debug name crashes RenderDoc at capture time unless I disable validation layers, due to get_dispatch_table()->CmdDebugMarkerBeginEXT being NULL.

**Comment by gwihlidal** [comment]
I have hit this issue now, as well (same situation and repro as previously mentioned); getting this resolved would be great.

**Comment by baldurk** [comment]
I'm not sure why this can't be fixed just with a simple `if()` in the layer code, to check that the function pointer being called is non-NULL. This is causing crashes for people and it's not exactly easy to diagnose if you don't know what's happening.

In 99% of cases, any layer that intercepts a function can just return after doing its work if there's nothing further in the dispatch chain. Adding a null check is strictly conservative - it prevents crashes, and if for some reason in future the loader implements no-op stubs then the check is still safe and won't break anything, even if it's perhaps redundant.

In a minority of cases where the return value or output parameters have to be set, this by definition will have to be handled by _something_ on the dispatch chain. If the ICD isn't providing the extension, then some other layer is, so it will be responsible for that output/return value. In those cases it's unfortunate that layer ordering means the validation layers might be later in the chain and so the "terminator" isn't on the end, but that's in some ways irrelevant - the layers can just check any parameters they want, and skip over the NULL next pointer in the dispatch chain, and return to let whichever layer is actually doing the implementation do the work.

**Comment by tobine** [comment]
Since the examples given here are all for the DebugMarker extension, I'm planning to implement Baldur's suggestion of adding the "if()" check for those extension functions in the layers as an initial solution.
If people are seeing issues with other extensions, please bring those cases up on this issue.

**Comment by tobine** [comment]
Just created #1219 to address this. Please give it a look.

**Comment by farnoy** [comment]
I believe this has resurfaced, probably around the time `object_tracker` was rewritten with a generator. On 6d3938172cba2d9235f258efa1db1c16443c66c6, `VK_EXT_debug_marker` is not advertised under `vkEnumerateDeviceExtensionProperties`, but can be activated without an error. It then fails during use:


```
(lldb) bt
error: need to add support for DW_TAG_base_type '()' encoded with DW_ATE = 0x7, bit_size = 0
* thread #1, name = 'v3', stop reason = signal SIGSEGV: invalid address (fault address: 0x0)
  * frame #0: 0x0000000000000000
    frame #1: 0x00007fffee1b1c21 libVkLayer_core_validation.so`core_validation::CmdDebugMarkerBeginEXT(commandBuffer=0x00007fffec274800, pMarkerInfo=0x00007fffffff83b0) at core_validation.cpp:12292
    frame #2: 0x00007fffedbd2471 libVkLayer_object_tracker.so`object_tracker::CmdDebugMarkerBeginEXT(commandBuffer=0x00007fffec274800, pMarkerInfo=0x00007fffffff83b0) at object_tracker.cpp:4298
    frame #3: 0x00007fffed65d6ad libVkLayer_parameter_validation.so`parameter_validation::vkCmdDebugMarkerBeginEXT(commandBuffer=0x00007fffec274800, pMarkerInfo=0x00007fffffff83b0) at parameter_validation.cpp:9469
    frame #4: 0x00005555558f036e v3`ash::vk::cmds::DebugMarkerFn::cmd_debug_marker_begin_ext::h823b0dea36f98a25(self=0x00007fffed38ce08, command_buffer=(ptr = ""), p_marker_info=0x00007fffffff83b0) at vk.rs:3848
...
(lldb) frame select 1
frame #1: 0x00007fffee1b1c21 libVkLayer_core_validation.so`core_validation::CmdDebugMarkerBeginEXT(commandBuffer=0x00007fffec274800, pMarkerInfo=0x00007fffffff83b0) at core_validation.cpp:12292
   12289	    }
   12290	    lock.unlock();
   12291	    if (!skip) {
-> 12292	        device_data->dispatch_table.CmdDebugMarkerBeginEXT(commandBuffer, pMarkerInfo);
   12293	    }
   12294	}
   12295	
```

Am I missing something? Without a profiler running, I would expect this to be a noop or give me a `VK_ERROR_EXTENSION_NOT_PRESENT` when creating a device.

**Comment by mark-lunarg** [comment]
Thanks @farnoy, will take a new look.

**Comment by mark-lunarg** [comment]
@mdinkov, not sure yet -- we need to first arrive at a solid solution.  This is a grey area not yet covered by the Vulkan spec or the canonical Loader/Layer interface.  None of the solutions are particularly appealing but we plan to address it (or at least, work around it), likely in the next or next-next SDK.

**Comment by Themaister** [comment]
Also ran into this issue when using VK_EXT_debug_marker with RenderDoc and having layers enabled.

**Comment by gwihlidal** [comment]
I just hit this issue again, too (using VK_EXT_debug_marker)

**Comment by gwihlidal** [comment]
Note, this also crashes other tools like Nvidia NSight

**Comment by mark-lunarg** [comment]
In work, should have a PR up shortly.
