### ISSUE TITLE
Transitioning a depth- or stencil-only image with a vkCmdPipelineBarrier() calls confuse core validation layer

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1079]
Say my image X uses a DEPTH16_UNORM format and my command buffer wants to transition the image to layout 1. As per the following spec language for valid usage of VkImageMemoryBarrier:

```
If image has a depth/stencil format with both depth and stencil components, then aspectMask member of subresourceRange must include both VK_IMAGE_ASPECT_DEPTH_BIT and VK_IMAGE_ASPECT_STENCIL_BIT
```

I specify both DS aspects when defining the subresource range. This, however, has a detrimental effect on the validation layer which outputs an error saying:

![image](https://cloud.githubusercontent.com/assets/17761066/19597028/4faa0a44-9792-11e6-9be1-d54757ecdc7b.png)

This is with the latest build of the layers, as obtained from the repo.

I can provide a repro for this issue if necessary.

**Comment by DominikWitczakAMD** [comment]
I vaguely recall hitting this issue in the past. Could this possibly be a regression in the layers?

**Comment by tobine** [comment]
Seems familiar but I'm pretty sure we added a test for the previous case to prevent regressions. Please do provide repro.

**Comment by DominikWitczakAMD** [comment]
Sent the repro by email

**Comment by chrisforbes** [comment]
This doesn't sound sensible-- `DEPTH16_UNORM` is a depth-only format. It shouldn't be legal to use `VK_IMAGE_ASPECT_STENCIL_BIT` with it. We check for that at `vkCreateImageView` time, but `ValidateBarriers` in core_validation doesn't check that the provided aspect mask for the barrier makes sense -- we just get confused and emit a nonsense error further downstream instead.

**Comment by DominikWitczakAMD** [comment]
Well, that language above was grabbed straight from the spec.. :-)

**Comment by janharaldfredriksen-arm** [comment]
I don't think that Valid Usage language applies to DEPTH16_UNORM.
DEPTH16_UNORM is a depth/stencil format but does _not_ have both depth and stencil components.

**Comment by DominikWitczakAMD** [comment]
Oh, now that you mention this, I may have misread the spec. My interpretation for depth/stencil format was that it can be either depth or either stencil or both, not that it's got to be DS. If we assumed the latter, then yeah, I guess that makes sense.

**Comment by DominikWitczakAMD** [comment]
Still, would you agree this kind of error should nevertheless be captured by validation layers & reported with a more meaningful debug callback?

**Comment by chrisforbes** [comment]
I definitely agree that the layer getting confused is rubbish. We should have a clean error emitted at the barrier call, pointing out that the aspect mask you provided doesn't make sense for the format.

**Comment by tobine** [comment]
#1102 was merged that will now flag an error at barrier validation time if STENCIL aspect bit is used for a depth-only image.
