### ISSUE TITLE
Need to be validating the aspectMask in vkCmdClearAttachments

### ISSUE THREAD

**Issue by jekstrand** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1085]
While reworking our attachment clearing code this week, I discovered that the CTS has tests which are using `vkCmdClearAttachments` to clear a depth-only buffer but including both `VK_IMAGE_ASPECT_DEPTH_BIT` and `VK_IMAGE_ASPECT_STENCIL_BIT` in `VkClearAttachment::aspectMask`.  However, according to the spec for `VkImageAspectFlagBits`:

> The mask must be only `VK_IMAGE_ASPECT_COLOR_BIT`, `VK_IMAGE_ASPECT_DEPTH_BIT` or `VK_IMAGE_ASPECT_STENCIL_BIT` if format is a color, depth-only or stencil-only format, respectively. If using a depth/stencil format with both depth and stencil components, aspectMask must include at least one of `VK_IMAGE_ASPECT_DEPTH_BIT` and `VK_IMAGE_ASPECT_STENCIL_BIT`, and can include both.

The CTS test passes the version of the validation layers I have on my laptop (1.0.30) so this must not be getting validated.  I have no idea how the validation layers work internally, but the rule above applies to all instances of VkImageAspectFlagBits so there may be others that aren't getting validated correctly.

**Comment by chrisforbes** [comment]
I have a branch with patches to fix this.
