### ISSUE TITLE
Standardised ICD loading approach for OS X

### ISSUE THREAD

**Issue by petmac** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1087]
I'm aware of the [MoltenVK](https://moltengl.com/moltenvk/) product from Brenwill Workshop, but I'm not a user of MoltenVK.

I think it looks like an excellent project that has a strong future on OS X, but I expect they face a struggle to get 3rd parties (game engines, other frameworks) to support their ICD as long as it isn't loaded by the standard loader.

Apple haven't indicated that they would like to support Vulkan, but if there is an ICD available (e.g., MoltenVK) that is considered standard (i.e., the standard loader finds it), it will back Vulkan as a usable graphics API on OS X.

I forked the Loader and Validation Layers repo and made enough changes to generate the project files for OS X and build with Xcode and Clang.

However, rather than me submitting a pull request with OS X changes for WSI and yet another mechanism for loading ICDs that will no doubt differ from the Linux and MoltenVK methods, I wanted to ask about gaining official support for loading ICDs on OS X.

Thank you,
Peter

**Comment by karl-lunarg** [comment]
The Vulkan driver situation for iOS and macOS is being monitored and so far, there are no plans to implement or adapt a loader for these platforms.
