### ISSUE TITLE
windows runtime installler  copies wrong file to vulkan-1.dll sometimes

### ISSUE THREAD

**Issue by jon-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#109]
In windows/system32, 
1) copy vulkan-l.dll to vulkan-1A.dll
2) uinstall runtime
3) install a newer version of the runtime
4) will see vulkan-1.dll is a copy of vulkan-1A.dll instead of the newer vulkan-1.dll from the newer runtime

**Comment by davidlunarg** [comment]
This bug had been fixed. The next Vulkan SDK release will include a fix for this bug.
