### ISSUE TITLE
Implement validation checks for Graphics Pipelines

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1092]
Implement checks for spec section 9.2.  If the check already is implemented, then modify the error reporting to use the error enums.
Update the error database file to indicate Y for all checks that are implemented (and use error enums).
Use N to indicate that the check is known not to exist.
It may be advisable to mark param checker codegen'd checks with N until we figure out how to propagate error enums.

**Comment by mikew-lunarg** [comment]
synced database status and check enums with a15d5dbb21cc99da0e791a694815ac96ba2a6591

**Comment by mark-lunarg** [comment]
Remaining/unimplemented checks for section 9.2 will be addressed in a follow-on issue/PR at a later date.
