### ISSUE TITLE
Improve version identification

### ISSUE THREAD

**Issue by elfring** [KhronosGroup/Vulkan-LoaderAndValidationLayers#11]
Would you like to [extend the specification of version information](https://cmake.org/cmake/help/v3.5/command/project.html "General project settings") for [the involved software components](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/3510b1966dc0eb046b5216a3ab5e47f1906a3e77/CMakeLists.txt#L4 "Build specification")?

**Comment by karl-lunarg** [comment]
Could you please give an example and/or explain what is gained by doing this?

**Comment by elfring** [comment]
The CMake software build system stores some data in variables. If further programming conventions would be followed, the corresponding information could be used in more places.
Would you like to improve the build scripts in such a direction?

**Comment by MarkY-LunarG** [comment]
What's the advantage of setting these version settings, though?  Does this do something extra we're currently not providing?  Does it define a version in the generated EXE?  Please elaborate.

**Comment by elfring** [comment]
>Does it define a version in the generated EXE?

Data could be integrated from further CMake variables also into executable files.

I got the impression from [other feedback](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/12 "Further possibilities by CPack?") that extensions for the build process might be harder than I hoped.

**Comment by karl-lunarg** [comment]
It looks like we could specify:

project (VULKAN VERSION 1.2.3.4)

Then there would be a cmake variable that could be passed as a compiler option:

set(COMMON_COMPILE_FLAGS "${COMMON_COMPILE_FLAGS} -DMAJOR_VERSION=${PROJECT_VERSION_MAJOR}"

or something like this.

**Comment by elfring** [comment]
>project (VULKAN VERSION 1.2.3.4)

My proposal was to take also another look at parameters for this command at the beginning of CMake scripts.

**Comment by karl-lunarg** [comment]
Specifying a version in the project() command would enable the passing of version info to steps that create build artifacts.  I gave the compilation example above.  Another could be passing version info on a linker directive to write version info into an executable, as MarkY suggested.  The catch here is that build steps would have to be explicitly modified to use the version info.  OTOH, having it there when needed might be nice.

This could easily be done by adding a CMAKE_PROJECT_VULKAN_INCLUDE [file](https://cmake.org/cmake/help/v3.5/command/project.html) that contains the VERSION portion of the project() command.  This way, we would not need to edit the CMakeLists.txt file for each version update.  But we would have to remember to change CMAKE_PROJECT_VULKAN_INCLUDE.

I suppose another use is changing the logic in CMake scripts, based on the version.  Is this what your proposal involves?  It would help to give an example and something more concrete than "take another look".

**Comment by elfring** [comment]
>I suppose another use is changing the logic in CMake scripts, based on the version.

My suggestion depends also on the willingness of the involved software developers also for further fine-tuning of build scripts.


>Is this what your proposal involves?

Yes. - Will any more safety checks evolve for this software?

Another design option could be to store special version data in external files so that their information can be reused in more places besides the CMake command "project".

**Comment by karl-lunarg** [comment]
Thanks for the suggestions.   Right now I don't see a real need for adding the VERSION data to the project() command.  There's no known pending change to the CMake files that would need this.  In the absence of a specific need, it is difficult to come up with a version scheme that would meet unforeseen requirements.  While it may seem trivial to add this version data, along with that action must come an understanding of what the version data means and implies.  This understanding must include what sort of changes would justify the incrementing of each of the 4 version levels as well as a plan and owner for making these changes to the version numbers.

One possible approach that many would suggest is to mirror the Vulkan header version.  But then, does/must the change activity within the project mirror the change activity in the Vulkan header?  Probably not.

I'd rather not add this until we understand the requirement.

**Comment by elfring** [comment]
* Would you like to consider parallel versioning of the involved software components?
* Does your software build process need its own version identification?
