### ISSUE TITLE
make lib directory destination customizable

### ISSUE THREAD

**Issue by sl1pkn07** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1100]
Hi

when try install the libs of loader in other directory, for example, in lib32 (if build with 32 bits compiller on 64 bits system), the path is hardcoded in the CMakeLists.txt:

https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/loader/CMakeLists.txt#L88

is possible change the path via cmake option -DCMAKE_INSTALL_LIBDIR=path ?

https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html

greetings

EDIT: bin, include, and other directories can set by same way with -DCMAKE_INSTALL_BINDIR, -DCMAKE_INSTALL_INCLUDEDIR, etc

**Comment by johnzupin** [comment]
I believe that should work.

If you want to specify the path of your directory I think you will need to define CMAKE_INSTALL_PREFIX 
(https://cmake.org/cmake/help/v3.0/variable/CMAKE_INSTALL_PREFIX.html#cmake-install-prefix)
(https://cmake.org/cmake/help/v3.0/command/install.html#install)

Let me know if that doesn't work for you

**Comment by sl1pkn07** [comment]
i don't talk about the general prefix (-DCMAKE_INSTALL_PREFIX=/usr), im talking about the system lib subdirectories

in the cmakelist.txt only show this:

![](http://wstaw.org/m/2016/10/26/Screenshot_20161026_200112.png)

i whant to set

```
-DCMAKE_INSTALL_PREFIX=/usr
-DCMAKE_INSTALL_LIBDIRS=lib32
```

for install the libs in ```/usr/lib32```

**Comment by sl1pkn07** [comment]
example in other (unrelated) project

https://sourceforge.net/p/cdemu/code/ci/master/tree/libmirage/CMakeLists.txt#l174

**Comment by karl-lunarg** [comment]
I think that the problem is that the "lib" is hard-coded in our CMake file:

`install(TARGETS vulkan LIBRARY DESTINATION lib)`

should be:

`install(TARGETS vulkan LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR} )`

${CMAKE_INSTALL_LIBDIR} is lib by default, so this should be a safe change.

Note that we've only recently been adding support for "make install", so there will be issues like this.
Also, other install dirs are hard coded, like include, so they may need to be replaced with CMake vars as well.

**Comment by sl1pkn07** [comment]
exactly


also
```
DESTINATION bin
DESTINATION etc
```
(`DESTINATION /etc` in your cmakelists)
can change to

```
DESTINATION ${CMAKE_INSTALL_BINDIR}
DESTINATION ${CMAKE_INSTALL_SYSCONFIGDIR}
```


vulkan subprojects gslang and SPIRV-Tools i think need make this change

**Comment by johnzupin** [comment]
#1106

**Comment by karl-lunarg** [comment]
#1106 pushed.
