### ISSUE TITLE
Classify validation checks for Compute Pipelines

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1105]
Implement checks for spec section 9.1. If the check already is implemented, then modify the error reporting to use the error enums.
Update the error database file to indicate Y for all checks that are implemented (and use error enums).
Use N to indicate that the check is known not to exist.
It may be advisable to mark param checker codegen'd checks with N until we figure out how to propagate error enums.

**Comment by jeremy-lunarg** [comment]
Many of these check will require param checker changes which we are postponing for now.
