### ISSUE TITLE
Why was "AllPlatforms" removed from vk-generate.py

### ISSUE THREAD

**Issue by mre4ce** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1111]
This broke the Vulkan-Samples repository. For proper CI you want to be able to generate a single header for all platforms.

The usage is also displayed as:

"Usage: %s < wsi > < subcommand > [options]"

However, the options are _not_ optional.

**Comment by mre4ce** [comment]
Pull request #1112: Re-added AllPlatforms as a wsi option to vk-generate.py

**Comment by mark-lunarg** [comment]
Johannes -- there is a set of changes in flight related to handling extensions in the codegen - I overlooked their effect on VulkanSamples.  Allplatforms will still be supported - I'll fix up Samples in the morning and will take what still applies from the PR after the changes land.  Sorry for the trouble.

**Comment by mre4ce** [comment]
Thanks Mark!

I always wondered why we have the wsi parameter considering that all platform specific functions are always wrapped with the appropriate conditional compilation. Can't we have a single header file for all platforms or am I missing something?

**Comment by mre4ce** [comment]
Is there anything I can do to help? I'm presenting a paper tomorrow and will reference the Vulkan-Samples repository. It would be nice if the repository is healthy at that time.

**Comment by mark-lunarg** [comment]
Pushed #1112.
