### ISSUE TITLE
FTBFS c9aa010

### ISSUE THREAD

**Issue by jengelh** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1115]
The source fails to build. Vulkan-LAVL c9aa010d3e31384be53d9fdeb9e1e9ec60a99dea with glslang e19e68d4313617b8fe8bb68578d2de51507e603f .
```
[  127s] /usr/bin/c++  -fPIC -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -g -DNDEBUG -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -std=c++11 -fno-rtti -fvisibility=hidden -Wpointer-arith -Wno-unused-function -Wno-sign-compare -O2 -g -DNDEBUG -Wl,-Bsymbolic,--exclude-libs,ALL -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now -shared -Wl,-soname,libVkLayer_core_validation.so -o libVkLayer_core_validation.so CMakeFiles/VkLayer_core_validation.dir/core_validation.cpp.o CMakeFiles/VkLayer_core_validation.dir/vk_layer_table.cpp.o CMakeFiles/VkLayer_core_validation.dir/vk_safe_struct.cpp.o CMakeFiles/VkLayer_core_validation.dir/descriptor_sets.cpp.o libVkLayer_utils.so -lSPIRV-Tools-1.1 
[  128s] /home/abuild/rpmbuild/BUILD/Vulkan-LoaderAndValidationLayers-1.0.32.g14/layers/core_validation.cpp:11972: undefined reference to `util_GetExtensionProperties'
[and others!]
[  128s] collect2: error: ld returned 1 exit status
```

**Comment by karl-lunarg** [comment]
I cannot reproduce this problem and all of our CI machines are building the repo without failure.

```
karl@cartman:~/src/Vulkan-LoaderAndValidationLayers/build/layers$ nm libVkLayer_utils.so | grep util*
000000000001f7bd t _GLOBAL__sub_I_vk_layer_utils.cpp
000000000001da68 t util_GetExtensionProperties
000000000001daf9 t util_GetLayerProperties

```

The symbols seem to be in one of the files used to build the target in question.

Can you share more info, such as what OS you are on, what commands used to build, etc?

**Comment by karl-lunarg** [comment]
Cannot reproduce the problem, and no response to request for more info in three days.  Please reopen and supply the requested info if the problem still persists.

**Comment by jengelh** [comment]
The problem is that the symbol has type 't' (visibility=hidden) instead of 'T', which is why ld cannot bind to it.

**Comment by karl-lunarg** [comment]
OK, thanks, that helps a lot.  I might know where that problem got introduced.  But it is odd that it works on (most) other systems.

**Comment by jengelh** [comment]
Can I somehow have a look at these "other" systems? I'd be curious why it does not ocurr there.

**Comment by karl-lunarg** [comment]
One example is Ubuntu 16.04 LTS.

**Comment by jengelh** [comment]
Do you have a link to the build log?

**Comment by karl-lunarg** [comment]
I just pushed 5338f69a0a3dcc8527d81ca5f936b0e066a3d7f7.  We had a couple of functions that didn't have the macros used to decorate them with export attributes.  nm -D shows them now as T.   I don't know if this will solve all missing symbols, but should help.  Can you try building again with this commit?

**Comment by jengelh** [comment]
I can confirm ld is able to link it now.

**Comment by karl-lunarg** [comment]
> (Thirdly, are your CI machines actually using -fvisibility= at all? Because that was part of my initial report.)

(I didn't see this in the initial report)

The top-level CMake file sets -fvisibility=hidden in the C and CXX flags.  The CI machines use the same CMake configuration.  The functions meant to be exported are decorated with the appropriate attributes.  In this case, there were 2 functions missing this decoration.

I can share a log if there is still a problem.

**Comment by karl-lunarg** [comment]
> I can confirm ld is able to link it now.

OK, thanks.  Please let us know if you need anything further.

**Comment by stroyan** [comment]
The difference that brought on this error is using -Wl,--no-undefined .
That immediately flagged the missing util_* functions.
Without that option the linker allows the unresolved functions until they are called.
It seems that validation tests don't yet exercise the functions that would make those calls.
