### ISSUE TITLE
Secondary cmd buffer image layout transitions aren't reflected in primary cmd buffer

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1124]
Consider a case where a secondary command buffer includes a PipelineBarrier that transitions an image from VK_IMAGE_LAYOUT_UNDEFINED to VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL.

This secondary command buffer is then included in a primary command buffer.
Next, a PipelineBarrier is bound to the primary cmd buffer that transitions the same image from VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL to VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL.

When this primary cmd buffer is submitted, validation will report something similar to `VULKAN DEBUG: ERROR:  [DS, 6]: Cannot submit cmd buffer using image (0xfe) [sub-resource: aspectMask 0x4 array layer 0, mip level 0], with layout VK_IMAGE_LAYOUT_UNDEFINED when first use is VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL.`

I believe this is incorrect, however, as validation didn't correctly take into account the image layout transitions from the secondary cmd buffer that was executed as part of the primary cmd buffer.

**Comment by chrisforbes** [comment]
Fixed by #1127.
