### ISSUE TITLE
VkPositiveLayerTest.ResetEventThenSet -- multiple bugs

### ISSUE THREAD

**Issue by chrisforbes** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1126]
This test and the validation code it exercises are dubious in a number of ways.

1. Claims to be a positive test, then uses `SetDesiredFailureMsg`
2. Expects (and receives) an error from `vkSetEvent` for usage that's not described as invalid in the spec (there are restrictions on `vkResetEvent`, but not on `vkSetEvent`)
3. Expects `vkSetEvent`'s side effects to have been performed, even though it expects an error from the call.
4. Passes `VK_PIPELINE_STAGE_ALL_COMMANDS_BIT` rather than `VK_PIPELINE_STAGE_HOST_BIT`, when waiting on an event from the host. [Note: if I just adjust /this/ issue, nvidia/linux/x64 hangs for 12-13 seconds on this test.]

**Comment by mark-lunarg** [comment]
I made a bad assumption and thought this was a change that @Tony-LunarG made -- it's not his test, but he has _most_ graciously agreed to fix the problems.  However, item 1 is my fault, I should have split up this into separate tests with the negative part in VkLayerTest and the remainder in VkPositiveLayerTest.

**Comment by chrisforbes** [comment]
I missed one -- if the vkSetEvent is to succeed, then there's also a race -- nothing guarantees that vkSetEvent occurs after the gpu completes the vkCmdResetEvent. In practice on a quiet system you get away with it,, but it's not good...

**Comment by Tony-LunarG** [comment]
It's odd that vkCmdWaitEvent in the command buffer with vkSetEvent on the CPU doesn't generate a validation error, but vkResetEvent, vkCmdWaitEvent in the command buffer with vkSetEvent on the CPU does (Cannot call vkSetEvent on event that is already in use by a command buffer).  Isn't the event "in use" in both cases?
Also it appears that the Nvidia driver does not take well to vkCmdResetEvent followed by vkCmdWaitEvent on an event that has not been set, though I can't find anything in the spec that calls that out as disallowed. The same command buffer with the event pre-set by the CPU works fine.

**Comment by Tony-LunarG** [comment]
I've created pull request #1132 to make this a negative test that detects the race condition that Chris noted, and doesn't cause the GPU to wait for an event that never gets set

**Comment by Tony-LunarG** [comment]
Fixed with PR #1132
