### ISSUE TITLE
Debug report flags cant be disabled after being enabled.

### ISSUE THREAD

**Issue by renelindsay** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1129]
When creating a debug report callback, with vkCreateDebugReportCallbackEXT, the flags parameter in the VkDebugReportCallbackCreateInfoEXT structure is used to select which types of messages to return. (Errors / Warnings / Info / ...)

However, if you then destroy the debug report, using vkDestroyDebugReportCallbackEXT, and re-create it with different flag settings, any previously enabled message types will still be enabled.  
It seems destroying debug report does not reset the flags.

**Comment by karl-lunarg** [comment]
This is very likely a problem in the layers, and not the loader.

In vk_layer_logging.h:

```
static inline void layer_destroy_msg_callback(debug_report_data *debug_data, VkDebugReportCallbackEXT callback,
                                              const VkAllocationCallbacks *pAllocator) {
    RemoveDebugMessageCallback(debug_data, &debug_data->debug_callback_list, callback);
    RemoveDebugMessageCallback(debug_data, &debug_data->default_debug_callback_list, callback);
}

```
The first call clears the debug_data->active_flags and the second call ORs in the flags from the default callback.

It seems that the addition of the default callback had an unintended side effect of "putting back" the flags from the default callback.

**Comment by mark-lunarg** [comment]
PR pushed to Master.
