### ISSUE TITLE
DrawState layer: "Cannot get query results on queryPool X with index Y which is uninitialized" error is misleading

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#113]
If an app tries to (incorrectly) begin a query in a cmd buffer A and finish it in a different cmd buffer B, the error as per ticket title is reported at vkGetQueryPoolResults() time. I find it slightly misleading, since, at first glimpse, it seems to suggest no query has ever been fired.

Can we adjust the mechanism to detect the described situation and report it more clearly?

**Comment by lentinem** [comment]
What is the exact error reported?

**Comment by DominikWitczakAMD** [comment]
As per the issue's title: ""Cannot get query results on queryPool X with index Y which is uninitialized" :)

**Comment by lentinem** [comment]
So this particular error should throw after two earlier errors which would complain in the following situations 1) on vkEndCommandBuffer if you have a query that has started but not ended and 2) on vkCmdEndQuery if you have not started a query. These should both throw before the error you get on results which is saying that the query you are asking for has not been written to. I did make a change to the message to clarify though.
