### ISSUE TITLE
Object wrapping issue on devices

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1134]
There's a corruption problem that can happen with any layer that wraps VkDevice objects.

1. In `terminator_CreateDevice` the ICD's CreateDevice function is called, and the result is stored in the `VkDevice device` in the `struct loader_device`, as well as being passed back up the dispatch chain through all the layers.
2. Any layer can wrap the object, producing a different pointer as long as the dispatch table remains the same.
3. When we emerge in `vkCreateDevice` in `trampoline.c`, the above `dev->device` is overwritten with the result of `*pDevice` - the resulting wrapped object from the layers. This is the right thing to do because almost always we want to pass the wrapped device down through the dispatch chain - which progressively unwraps it until it reaches the ICD unwrapped.
4. However there's a recently added function `loader_override_terminating_device_proc` which takes the wrapped VkDevice and passes it directly to the ICD without going through the dispatch chain. This pointer is essentially nonsense for the ICD, so it can easily crash.

I don't know the exact fix you want, but here's a rough patch against master which stores the icd_device separately for any occasions where the trampoline side needs to skip the dispatch chain:

```diff
diff --git a/loader/loader.c b/loader/loader.c
index 7c69775..c83d9ba 100644
--- a/loader/loader.c
+++ b/loader/loader.c
@@ -3275,7 +3275,7 @@ void loader_override_terminating_device_proc(
     // along to the ICD.
     if ((PFN_vkVoidFunction)disp_table->core_dispatch.CreateSwapchainKHR ==
         (PFN_vkVoidFunction)icd_term->GetDeviceProcAddr(
-            device, "vkCreateSwapchainKHR")) {
+            dev->icd_device, "vkCreateSwapchainKHR")) {
         disp_table->core_dispatch.CreateSwapchainKHR =
             terminator_vkCreateSwapchainKHR;
     }
@@ -4396,6 +4396,9 @@ VKAPI_ATTR VkResult VKAPI_CALL terminator_CreateDevice(
         goto out;
     }

+    // store the icd's device here for later use
+    dev->icd_device = dev->device;
+
     *pDevice = dev->device;
     loader_add_logical_device(icd_term->this_instance, icd_term, dev);

diff --git a/loader/loader.h b/loader/loader.h
index daf663e..3c06cc1 100644
--- a/loader/loader.h
+++ b/loader/loader.h
@@ -166,7 +166,8 @@ struct loader_dev_dispatch_table {
 // per CreateDevice structure
 struct loader_device {
     struct loader_dev_dispatch_table loader_dispatch;
-    VkDevice device; // device object from the icd
+    VkDevice device; // device object from the dispatch chain, possibly wrapped
+    VkDevice icd_device; // device object from the icd

     struct loader_layer_list activated_layer_list;
```

Which seems to fix any problems for me.

As a side note, I think it is worthwhile adding testing for dispatchable object wrapping, to make sure the loader obeys all the proper rules. I don't know if that's correct to go in the CTS so maybe it needs to go somewhere else. The unique_objects layer only wraps non-dispatchable objects, and dispatchable objects are the only type the loader deals with.

The test wouldn't need to be very sophisticated - just using a null driver and a layer that wraps all objects dispatchable or not, to verify that a) the layer always see wrapped objects, never loader structures or unwrapped ICD objects, and b) the ICD always sees its own objects, not loader structures or wrapped objects.

**Comment by kbiElude** [comment]
This one is fairly critical from our perspective. Please consider making it a P1.

**Comment by DominikWitczakAMD** [comment]
This one is fairly critical from our perspective. Please consider making it a P1.

**Comment by MarkY-LunarG** [comment]
I think it might be better for a GetInstanceProcAddr call instead of using a GetDeviceProcAddr call.  The changes your suggesting seem a little dangerous.  

Dominick, will the ICD return the same function pointer for a GetInstanceProcAddr versus a GetDeviceProcAddr call on the same function name?

**Comment by baldurk** [comment]
I'm confused, why does it break if the unique object layer (or any layer for that matter) is enabled? terminator_CreateDevice is on the other end of the dispatch chain, so that fpCreateDevice calls into the ICD and the resulting device that's stored in icd_device is the ICD's handle:

![image](https://cloud.githubusercontent.com/assets/661798/20224704/07c55a4e-a840-11e6-8488-605022375ce3.png)

Which is the same situation as loader_override_terminating_device_proc which also calls into the ICD so the handle will match. I don't think you can assume that in all cases GIPA will return the same pointer as GDPA (it might be true now, but not in future or for someone else's ICD), and I think GetInstanceProcAddr has exactly the same problem as you are still calling directly into the ICD bypassing the dispatch chain:

![image](https://cloud.githubusercontent.com/assets/661798/20224777/743682f2-a840-11e6-995e-b7f09fe2778e.png)

**Comment by MarkY-LunarG** [comment]
I was unaware that we allowed objects to be passed down the CreateInstance and CreateDevice callstacks without being molested.  This seems like a fragile proposition unless it's well documented somewhere.  Anyway, I have a different fix which I think is cleaner, you actually can use the device object that's already a part of the loader_device because you're talking directly to the ICD here.  I just updated my marky_working branch with the fix.

**Comment by baldurk** [comment]
Yeh I don't know the context or reasoning behind the `loader_override_terminating_device_proc` function skipping the chain and going straight to the ICD, but I assumed it was for a good reason so I just made my patch to just get the matching device.

I don't think your change will work. The reason I stored the ICD's device separately in `terminator_CreateDevice` is because the contents of `dev->device` [gets reassigned](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/f52564a158235295ffe71a98f75bf59c0a8f53b4/loader/loader.c#L4004) in `loader_create_device_chain` to contain the fully wrapped device. I think this is fine as that's the 'normal' device, since most of the time the loader will call down the dispatch chain. This special case function needs the ICD device handle separately.

**Comment by DominikWitczakAMD** [comment]
@MarkY-LunarG : Sorry, I was OOO on Friday so couldn't get back to you on time

**Comment by MarkY-LunarG** [comment]
@baldurk, you're correct, the `loader_create_device_chain`  does override it.  I agree now, your change looks most correct.

**Comment by MarkY-LunarG** [comment]
Try branch "marky_gh1120_gh1134".  I fixed the issue you mentioned, but found the more correct way to intercept the terminator funcs as well.

**Comment by baldurk** [comment]
I verified the fix for #1120 - everything seems fine there!

I can't check the fix for this bug so easily - the code with the original problem was removed and I can't see obviously in the change where it was moved to, if anywhere. I guess that's the more correct interception you mentioned? I'd say wait for @DominikWitczakAMD to double check as I never got the original crash due to mismatched objects.

**Comment by MarkY-LunarG** [comment]
Actually, this fixes and cleans up several things.  I went ahead and submitted the fix to master.  @DominikWitczakAMD, let me know if you see other issues, and I'll fix those.

**Comment by DominikWitczakAMD** [comment]
Will do it first thing in the morning tomorrow, guys. Thanks for all the work!

**Comment by MarkY-LunarG** [comment]
@DominikWitczakAMD, were you able to determine if the master changes resolve your issues?

**Comment by DominikWitczakAMD** [comment]
This has gotten off my radar somehow, will check now.

**Comment by DominikWitczakAMD** [comment]
Aye, works like a charm. Safe to close!
