### ISSUE TITLE
Destroying Debug Report does not remove callbacks.

### ISSUE THREAD

**Issue by renelindsay** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1138]
If you created a debug report with vkCreateDebugReportCallbackEXT , and later call vkDestroyInstance, the debug report will list all the layers being unloaded, with messages similar to this:
Unloading layer library ./libVkLayer_threading.so

However, if you delete the debug report with : vkDestroyDebugReportCallbackEXT
and create a new instance, again with : vkCreateDebugReportCallbackEXT,
then, when vkDestroyInstance is called, each unload message appears twice.

Does this mean each call to vkCreateDebugReportCallbackEXT added callbacks for each layer, but vkDestroyDebugReportCallbackEXT failed to remove them?

**Comment by mark-lunarg** [comment]
We believe this to be related to a configuration issue and are closing for now.  Will reopen if further testing warrants.
