### ISSUE TITLE
Crash in DrawStateLayer::VkDeviceWaitIdle() handler

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#114]
After I get three or four errors described in the latest comment under #99, I'm seeing a crash in draw state layer's decrementResources() func due to a NPE:

![image](https://cloud.githubusercontent.com/assets/17761066/13700233/fc0f75f8-e77f-11e5-9897-ecf5f053f30b.png)

![image](https://cloud.githubusercontent.com/assets/17761066/13700237/05e70f50-e780-11e5-8049-b5bbf39c4921.png)

**Comment by tobine** [comment]
Dominik, can you re-check this and close if fixed?
Thanks

**Comment by DominikWitczakAMD** [comment]
Cannot repro, closing.
