### ISSUE TITLE
VK_ACCESS_HOST_WRITE_BIT needed when layout is VK_IMAGE_LAYOUT_PREINITIALIZED

### ISSUE THREAD

**Issue by qnope** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1141]
Validation layers gives me the following warning when I want to transition one image layout from PREINITIALIZED with srcAccessMask = 0:
> validation layer: Source AccessMask 0 [None] must have required access bit 16384 [VK_ACCESS_HOST_WRITE_BIT] when layout is VK_IMAGE_LAYOUT_PREINITIALIZED, unless the app has previously added a barrier for this transition.

In the spec it is write :
> For host writes to be seen by subsequent command buffer operations, a pipeline barrier from a source of VK_ACCESS_HOST_WRITE_BIT and VK_PIPELINE_STAGE_HOST_BIT to a destination of the relevant device pipeline stages and access types must be performed. Note that such a barrier is performed implicitly upon each command buffer submission, so an explicit barrier is only rarely needed

Since the barrier should be done implicitly when I submit the commandBuffer, this message from the validation layers should not exist.

The initial discussion was in : [HOST_WRITE useful or validation layers wrong?](https://github.com/KhronosGroup/Vulkan-Docs/issues/406)

**Comment by mark-lunarg** [comment]
Fixed by pr #1142 .
