### ISSUE TITLE
READ_BIT in srcAccessMask

### ISSUE THREAD

**Issue by qnope** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1146]
When I read the [code](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/core_validation.cpp#L8987) we can see that for most layout requires a `READ_BIT`.

However, I think using a READ_BIT for a srcAccessMask is not useful.

Take for example the `VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL`. It means that before the barrier, the image was used in source for transfer.
However, a transfer does not perform any write to the src, thus I do not see WHY should we use a READ_BIT in this case.
If we are reasonning with flush/invalidation cache, the first half of a memory dependency is a flush (since it makes the memory available), that's it, we do not need to have a `READ_BIT`.
However, we still need to have an execution barrier with `srcStage = TRANSFER`.

Is this a bug? Or did I just miss something?

**Comment by TobiasHector** [comment]
The spec is kind of unclear here (as roughly discussed here: https://github.com/KhronosGroup/Vulkan-Docs/issues/261). But read bits are actually useless in the source stage masks. We're currently deciding whether to make them outright invalid or not, or to add some sort of note. At the moment they're harmless - they won't actually *do* anything if you include them. The code samples should probably remove them.

**Comment by qnope** [comment]
If they do not anything, why deciding to put them invalid or not as we know the answer?
(It is a weird question I know ^^, but there nothing mean in what I asked :p)

**Comment by TobiasHector** [comment]
The spec previously read like you *did* need those bits there, which was incorrect - which is why it throws an error.

**Comment by TobiasHector** [comment]
Oh wait - ignore my last comment (which I promptly deleted :P) You meant why would we make them invalid?

Anything that is "valid but no-op" needs two things - CTS tests covering their behaviour, and implementations have to write code to ensure the behaviour works. Unless there's a compelling case for making them work (e.g. like with a draw indirect call of 0), it's beneficial to explicitly make them invalid.

**Comment by lentinem** [comment]
I don't think I fully understand what is being said here. The srcAccessMask in this case is transferring from reading as part of a copy to something else. The spec says "VK_ACCESS_TRANSFER_READ_BIT indicates that the access is a read from a transfer (copy, blit, resolve, etc.) operation." which is true in this case. We additionally have cases where we define READ_BITS as part of srcAccessMask in the spec (e.g. srcAccessMask = VK_ACCESS_MEMORY_READ_BIT). If we elect to remove this as there is no benefit that is fine and the code can be updated but I do not see how this isn't required based on what is currently written.

**Comment by TobiasHector** [comment]
@lentinem the source stage masks does one thing - says via which access types that **writes are made available**. That's it.  There's no concept of making a read "available" because it does not alter values. The current spec says that in a relatively convoluted way, but it does say that.

**Comment by lentinem** [comment]
I'm having a hard time finding that although it probably is there. This seems like a bit of a contradiction with the other text in the spec. At the minimum the spec needs to make this much more clear.

**Comment by TobiasHector** [comment]
Such changes are in flight already.

**Comment by lentinem** [comment]
Can you link to that from here?

**Comment by TobiasHector** [comment]
Not much I can link to at the moment unfortunately, because it's spread across a number of internal issues and MRs without much centralization for the timebeing - should be a single MR probably next week though.

**Comment by TobiasHector** [comment]
We resolved in the WG that this is not something that should be invalid - so it's ok to do it. The main motivation is that existing content likely already does this because the spec implied that it should. If we went back and started again, we'd probably just make them invalid.

The other half of the resolution was that it should be a warning in the validation layers if you *are* doing it (that can be turned off), in the validation layers. The reason for this is that it's possible that you're not doing something even though you think you are. So AFAICT this is a straightforward reversal of what currently exists in the layers (for READ access)?

The validations layers should definitely *not* warn you if you're not adding these access types.

Does that make sense?

**Comment by lentinem** [comment]
This is fine but IMO the spec should be updated to make this more clear.

**Comment by qnope** [comment]
That is why I open this issue aejsmith ;)

**Comment by aejsmith** [comment]
Right, but the later comments seem to imply that the validation layers shouldn't be warning any more. But, a git build as of 2 days ago still warns, so I was looking for some clarification.

**Comment by mark-lunarg** [comment]
@TobiasHector, I'm removing the warnings for setting READ_BITs in SrcAccessMasks, but haven't been able to find any spec language that says we should warn if they ARE set (from your 2016/11/14 comment).  Did the warnings actually make it into the spec?
