### ISSUE TITLE
DrawState: ValidateBarriers reports errors for image subresources when using VK_REMAINING* to select subresource

### ISSUE THREAD

**Issue by TiemoJung** [KhronosGroup/Vulkan-LoaderAndValidationLayers#115]
Hi,

ValidateBarriers of the DrawState validate will report errors for invalid ranges of images for image barriers for the cases when the mip range is VK_REMAINING_MIP_LEVELS and/or the array range is
VK_REMAINING_ARRAY_LAYERS.

**Comment by lentinem** [comment]
Can you please provide more information as to which errors you are seeing?

**Comment by TiemoJung** [comment]
The tests at https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/draw_state.cpp#L6784 : `if ((mem_barrier->subresourceRange.baseArrayLayer + mem_barrier->subresourceRange.layerCount) > arrayLayers)`
and
https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/draw_state.cpp#L6792 : `if ((mem_barrier->subresourceRange.baseMipLevel + mem_barrier->subresourceRange.levelCount) > mipLevels)`
do not check if the count is the corresponding VK_REMAINING*

**Comment by lentinem** [comment]
Submitted MR 154 to address this.

**Comment by tobine** [comment]
Fix merged to master
