### ISSUE TITLE
Expand Windows Loader Search Path to Include Paths in User-writable Registry Keys

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1153]
When discussing how to properly register and activate an implicit layer, @Anteru and I realised there's a gap in support on windows.

On linux the search path goes roughly: `/usr/local/`, `/etc`, `/usr`, then `~/.local`. This gives a nice ability to install things system-wide at different levels as well as user-local without root privileges.

But on windows, the search path is _only_ HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan (and corresponding Wow6432Node). This is OK for system-wide installation of layers, but it means if a user wants to be able to register a layer without having administrator privileges they are out of luck.

The only options are setting environment variables each time which is awkward and a bit error prone, since I think implicit layers don't get located by VK_LAYER_PATH.

I'd suggest that the search path be expanded to HKEY_CURRENT_USER\SOFTWARE\Khronos\Vulkan with exactly the same ExplicitLayers/ImplicitLayers tree structure. This key can be written by users without escalation, and it can be second in the search order just the same as linux.

**Comment by lenny-lunarg** [comment]
Enhancement made in commit 1b9da316f15b56b52cdaae0f5056cca0f9de1791
