### ISSUE TITLE
Performance warning: High number of memory objects

### ISSUE THREAD

**Issue by TobiasHector** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1155]
I believe it's generally agreed that many memory objects == bad; we really want developers to be sub-allocating from a small number of large allocations, rather than a large number of small ones.

So some sort of performance warning if an app goes above some relatively low threshold would probably be good. If they're doing more than, say a few hundred allocations, I'd guess they're probably doing something wrong? It would be really good to call this out in the layers. To be really robust the number of allocations should be based on the number of memory types | heaps on each device, and should also probably be user-tweakable (though with sensible defaults and warnings against tweaking it!). We'll need to solicit feedback about what the default should be from various hardware vendors.

I'm not sure if something like this lives directly in the validation layer, or if we need some sort of "performance warning" layer. Having such a layer would provide a good place for vendors to start putting their performance recommendations into something testable, which would hopefully lead to vendors not diverging too much :)

**Comment by lentinem** [comment]
I think this could live within the layers; there are other such restrictions currently. The main question I have which you allude to here is would there be vendor agreement on the order of that number?

When there is disagreement this becomes hard. We don't want to hurt developers using other architectures but at the same time we don't want each vendor to have their own warning layer specific for that vendor.

**Comment by TobiasHector** [comment]
I think the agreement of the number isn't going to be too hard in this case - there shouldn't be any reason anyone wants a large number of small allocations, so from a pure IHV PoV we should all be either arguing it down, or not caring - so we hopefully could just take the lowest number someone throws out. Practical experience with ISVs may cause us to push the number up a bit, but that should be the only thing that drives it upwards.

Regardless it can't hurt to ask the question - though I'm not sure what the best route to do that is... Maybe @slippah can help out here :)?

**Comment by mark-lunarg** [comment]
This is a great idea, and we have medium-term plans to implement a performance or efficiency utility layer that would contain these types of checks -- it's possible that the infrastructure for this may be added sooner rather than later.  However, priority-wise it's going to be a while before resources become available.  If this is needed in the near-term, a pull-request would suffice, or even a larger coordinated effort for checks of this type.  Likewise for issue #1253.

**Comment by mark-lunarg** [comment]
This issue is now tracked via issue #1612.

**Comment by mark-lunarg** [comment]
This check is now available in the Assistant Layer, hosted in the [Github VulkanTools repository](https://github.com/LunarG/VulkanTools), and soon to be available in the Vulkan SDK.
