### ISSUE TITLE
loader: createdevice needs fix for handling ICD extensions from multiple devices per ICD

### ISSUE THREAD

**Issue by jon-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#116]
CreateDevice, in process of filtering out extensions needs to get the ICDs VkPyhsicalDevice object. The way this is done currently only works if the ICD has one physicalDevice rather than multiple physicalDevices.

**Comment by courtney-g** [comment]
Need to also consider Instance layer(s) that may wrap the PhysicalDevice object(s) returned by the ICD.

**Comment by jon-lunarg** [comment]
Yes, I think the layer wrapping is already handled properly.

**Comment by jon-lunarg** [comment]
pushed fix to master
