### ISSUE TITLE
Complete VU checks for BindImageMemory

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1171]
Image version of #1170. BindImageMemory needs to be updated to check all the VUs from the spec, and should also be refactored to use the Pre/Post pattern.

**Comment by mark-lunarg** [comment]
In progress.

**Comment by tobine** [comment]
@cdwfs Mark has pushed mark-master-GH1171 to master which has some refactoring and re-naming but no new checks. You can use that as a starting point or start from scratch if you'd like.
This issue includes the fact that all [vkBindImageMemory](https://www.khronos.org/registry/vulkan/specs/1.0-extensions/xhtml/vkspec.html#vkBindImageMemory) valid usage requirements need to have checks and tests implemented for them. The key checks of interest for this issue are [VALIDATION_ERROR_00803-VALIDATION_ERROR_00806](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/vk_validation_error_database.txt#L795)
There are extension and implicit valid usages beyond that. Don't worry about either of those for this issue as extension only applies to particular devices and the implicit cases should all be handed already by parameter_checker and object_tracker.

For an initial PR, I recommend just doing the Pre/Post refactor and adding a single check and test. Then we can review and any feedback may apply to further checks and tests.
Some checks may already be implemented in which case make sure they're using the correct VALIDATION_ERROR_##### and that the database file is correctly updated to reflect that they're implemented.

No rush on this. Should provide some steady work to help you continue growing in the codebase. I'll also assign #1171 to you which is similar but for BindBufferMemory. You can do that as a follow-on once this is complete.

**Comment by cdwfs** [comment]
Fixed by #1446
