### ISSUE TITLE
Performance warnings shouldn't cause call to be skipped.

### ISSUE THREAD

**Issue by schwa423** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1173]
I ran into this issue when using multiple render passes in a single command buffer.  The second render pass used a different pipeline layout than the first.  As a result, the following code in core_validation.cpp caused a command to be skipped, and therefore caused my rendering to be completely screwed up:

```C++
// Check if newly last bound set invalidates any remaining bound sets
if ((pCB->lastBound[pipelineBindPoint].boundDescriptorSets.size() - 1) > (lastSetIndex)) {
    if (oldFinalBoundSet &&
        !verify_set_layout_compatibility(dev_data, dev_data->setMap[oldFinalBoundSet], layout, lastSetIndex,
                                         errorString)) {
        skipCall |=
            log_msg(dev_data->report_data, VK_DEBUG_REPORT_PERFORMANCE_WARNING_BIT_EXT,
                    VK_DEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_SET_EXT, (uint64_t)oldFinalBoundSet, __LINE__,
                    DRAWSTATE_NONE, "DS", "DescriptorSetDS %#" PRIxLEAST64
                                          " previously bound as set #%u is incompatible with set %#" PRIxLEAST64
                                          " newly bound as set #%u so set #%u and any subsequent sets were "
                                          "disturbed by newly bound pipelineLayout (%#" PRIxLEAST64 ")",
                    (uint64_t)oldFinalBoundSet, lastSetIndex,
                    (uint64_t)pCB->lastBound[pipelineBindPoint].boundDescriptorSets[lastSetIndex], lastSetIndex,
                    lastSetIndex + 1, (uint64_t)layout);
        pCB->lastBound[pipelineBindPoint].boundDescriptorSets.resize(lastSetIndex + 1);
    }
}
``` 

I thought that I was doing something else wrong, but couldn't figure out what.  Finally, I found myself looking at the code above, and shaking my head in frustration.  I turned off the validation layer, and my code suddently behaved as intended.

In my opinion, "performance warnings" should be just that.  They MUST not affect the behavior of the running program, otherwise they are nearly useless (if you see one, you must fix it immediately, because you have no idea what other havoc it is wreaking upon the semantics of your program).

**Comment by lentinem** [comment]
The decision as to weather they affect the application is specified via the callback. To achieve the effect of what you want you need to return false if the flags passed back contain the performance warning bit.

**Comment by mark-lunarg** [comment]
@schwa423 , as @lentinem mentioned this is intended behavior.  The only way API calls will be skipped for perf warnings is if the registered callback returns TRUE when encountering a warning of this type.  The callback could print out the perf warning and return FALSE which would not affect the behavior of the running program, or the callback can ignore perf warnings entirely.  That said, this is not entirely obvious and we have it in our medium-term plans to make this more clear.

**Comment by schwa423** [comment]
Thanks for the clarification!
