### ISSUE TITLE
vkCmdCopyBufferToImage with VkBufferImageCopy.imageExtent.depth == 0

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1182]
We received a report from an IHV that we were making invalid use of vkCmdCopyBufferToImage because we set VkBufferImageCopy.imageExtent.depth == 0.  The validation layers don't currently check for this error condition and it wasn't clear to me from the spec whether this is an error.

Should this be caught by validation?  Do we need spec clarification?

**Comment by mark-lunarg** [comment]
When in image is created, valid usage specifies that extent.depth must be >= 1, implying that 0 is not valid.  But more specifically, in VkBufferImageCopy it says "imageExtent is the size in texels of the image to copy in width, height and depth", which I'd take to mean a zero in any of these fields would mean 0 texels copied.  I believe this is needs to be added to validation.

**Comment by danginsburg** [comment]
After further discussion, we determined that this is a driver bug and not something validation needs to catch.  The spec says, "imageExtent is the size in texels of the image to copy in width, height and depth. 1D images use only x and width. 2D images use x, y, width and height. 3D images use x, y, z, width, height and depth.”  So for a 2D image a 0 depth is valid.

**Comment by jeffbolznv** [comment]
Dan, you're looking at an old version of this spec. This was changed a month ago in MR 1620. The validation layers do need to be updated if they haven't already.

**Comment by mark-lunarg** [comment]
Addressed by #1189.
