### ISSUE TITLE
Unify validation printing of dispatchable handles

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1188]
I believe that since dispatchable handles are always pointers, they can all just be printed with the "%p" specifier as in [this code](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/core_validation.cpp#L7341).

Would be nice to unify all of the printing of dispatchable handles to uniformly use "%p".

**Comment by mark-lunarg** [comment]
It'd be nice to have a unified solution for handling the related casting noise and output differences for the different handle types.
