### ISSUE TITLE
No warning/error when sampler2D params are missing

### ISSUE THREAD

**Issue by cippyboy** [KhronosGroup/Vulkan-LoaderAndValidationLayers#119]
I was porting a GLSL shader to vulkan and was wondering why my vulkan code crashes in vkCreateGraphicsPipelines. After hours of debugging I figured it out. I didn't knew I have to mark-up the samplers with bindings and location :

Before :
uniform sampler2D   Texture0;
After
layout( location = 0, binding = 2, set = 0 ) uniform sampler2D   Texture0;

I assume that by default, glslang puts the binding = 0, but that's where I have uniform buffers set up in my descriptor layout (0 is for VS UB, 1 is FS UB and 2 is for combined samplers )

It would've been nice if the validation could detect cases like this.

**Comment by chrisforbes** [comment]
By default, Texture0 will indeed get set=0, binding=0. This should now be picked up by validation on master: most likely you will be setting the stage flags for the VS UB to VK_SHADER_STAGE_VERTEX_BIT, so you'll get SHADER_CHECKER_DESCRIPTOR_NOT_ACCESSIBLE_FROM_STAGE; if you ignore that error, you'll then get SHADER_CHECKER_DESCRIPTOR_TYPE_MISMATCH.

If you could retest with current master and verify that you are getting the expected validation errors, that would be great.

One additional observation though -- the location layout qualifier makes no sense on this declaration; only binding and set are meaningful. glslang should not allow it.

**Comment by cippyboy** [comment]
Ok, I'll try the next lunarg SDK that comes out. I don't feel like compiling the validation layers myself just yet :)

**Comment by chrisforbes** [comment]
Closing this as fixed. Feel free to reopen or create a new issue if you have further problems.
