### ISSUE TITLE
Crossfire False Validation Layer Message (Bug)

### ISSUE THREAD

**Issue by Synicix** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1192]
Current System: 
2x RX480

Validation Layer: vkQueuePresentKHR() called with a swapchain whose surface is not supported for presention on this device with the queueFamilyIndex (i.e. 0) of the given queue.

This only happens when I have crossfire enable, I been digging around and trying different setup for swapchain and it still result the same problem.

Is there a specific way to deal with this message without disabling crossfire? 

I am trying to deal with the case if the user have crossfire enable. Even though it should be off when running Vulkan since Vulkan bypass crossfire.

Additional Information:

Primary GPU Engine Output Logs:

* Physical Device Address: 000001F20A399CA0
* Surface Address: 000001F205C2DA48
* GLFW Address: 000001F205C09160
* Graphics Queue Support: 1
* Graphics Queue Index: 0
* Present Queue Support: 1
* Present Queue Index: 0
* Swapchain Support: 1

Secondary (Linked) GPU:

* Physical Device Address: 000001F20A399CA8
* Surface Address: 000001F205C2DA48
* GLFW Address: 000001F205C09160
* Graphics Queue Support: 1
* Graphics Queue Index: 0
* Present Queue Support: 0
* Present Queue Index: 0
* Swapchain Support: 0

--------------------------------------------------------------
- Swapchain is created only on the Primary GPU.
- Each Vulkan Physical Device has exactly 1 Logical Device and 1 Queue.
- Using an additional RX480 family queue that only support Present and not Graphics for the present

     * Queue.at(0) = Graphics Queue
     * Queue.at(1) = Present queue

Still result in the same layer error.

----------------------
Update: Just tested it with Vulkan 1.0.33 libraries, same issues. Will report it as a bug.
Github Bug Report Link : https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1192

Update 2: My System Info (VIA.html):
 https://drive.google.com/file/d/0BzgszgjTmatKZEthdTBSSy1idVU/view?usp=sharing

**Comment by mark-lunarg** [comment]
@Synicix, which application are you running?  Does the application run in spite of the validation error?  If you think the error is not valid, it would help if you could get us an api_dump of the application up to and through the validation error.

**Comment by Synicix** [comment]
The application is my own prototype engine, it works as expected without any errors aside from that layer message. 

Sorry, but I am not entirely sure how to get the api_dump of the application. Never done that before. Will look around for instructions on how to do that.

**Comment by chrisforbes** [comment]
The rework I'm doing in parameter_validation and core_validation to replace the old swapchain layer should address this. Previously some of the checks were quite confused about per-instance vs per-physicaldevice data.

**Comment by ianelliottus** [comment]
I just saw this.  Vulkan 1.0 WSI does not support multiple-GPU configurations.  That was a conscious trade-off made in order to get Vulkan 1.0 out sooner.  You can think of this as an undefined behavior case.

I don't believe that the validation layers are doing anything wrong in reporting this, assuming that if you properly query things you would see the same info that the validation layer is using in order to generate this message.  Please report back if you see something different.  Either way, this is an unsupported configuration at this point (sorry to be the bearer of bad news).
