### ISSUE TITLE
Using VK_KHR_display extension causes validation layers to crash

### ISSUE THREAD

**Issue by FslNopper** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1197]
On our platform, the VK_KHR_display is used and working.
But as soon as the validation layers are used, they do crash.

Fix is available here:
https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/1196

**Comment by chrisforbes** [comment]
#1196 is in master now.
