### ISSUE TITLE
Spammy parameter_validator VkResult warnings

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1198]
`parameter_validator` seems to check `VkResult` results and issue a `WARNING` if it is one of `VK_ERROR_*`.

Considering some of those errors are perfectly normal situations and can (and should) be handled as part of a good application, and considering not doing so will likely result in an `ERROR` message later on, shouldn't these messages be perhaps downgraded to `INFO` or `DEBUG`?

I was testing on a platform that seems to make use of `VK_ERROR_OUT_OF_DATE_KHR`. And warnings were spammed every time the window was resized, while the application was (assumably) perfectly fine and could do little to avoid the `WARNING`.

**Comment by mark-lunarg** [comment]
@krOoze, as they are presently defined, this is pretty much what warnings are for and these messages don't fit well into the info/error buckets as _they_ are defined.  There are facilities available to disable output of warning messages entirely through use of the vk_layer_settings.txt config file, or by filtering them out in a more specific way through a debug report callback and for the time being we recommend one of these solutions.

**Comment by krOoze** [comment]
> `VK_DEBUG_REPORT_WARNING_BIT_EXT` **indicates an unexpected use**. E.g. Not destroying objects prior to destroying the containing object or potential inconsistencies between descriptor set layout and the layout in the corresponding shader, etc. 

> `VK_DEBUG_REPORT_INFORMATION_BIT_EXT` indicates an informational message such as resource details that may be **handy when debugging an application**. 

How is `VK_ERROR_OUT_OF_DATE_KHR` an "unexpected use"?
Though sure "handy when debugging" (e.g. if I forget to handle it).
<hr/>
But I suppose I should be able to use `EnumeratePhysicalDevices` + `messageCode` to filter them....
<hr/>

Weird. I see in the layer code that `vkCreateDevice` is similarly checked, but I can't force it to show similar message for `VK_ERROR_EXTENSION_NOT_PRESENT`.

**Comment by lentinem** [comment]
I'm curious where you found that definition for WARNING. That differs slightly from how we have been using it and may mean that the definition should be updated.

**Comment by krOoze** [comment]
@lentinem 
Vulkan 1.0.35 - A Specification (with all registered Vulkan extensions)
33.2. Debug Report Callbacks
`VkDebugReportFlagBitsEXT` descriptions

**Comment by courtney-g** [comment]
That makes me think that this should not be an error return, but rather more like VK_SUBOPTIMAL_KHR. It's just an informational return code, not an error condition.

**Comment by krOoze** [comment]
It is an error return condition. Command returning it failed to do its job. E.g. would not return the image index on `vkAcquireNextImage()`. It is on the same level as e.g. `OUT_OF_MEMORY`.

**Comment by ianelliottus** [comment]
I just saw this issue.

FYI ... VK_SUBOPTIMAL_KHR is more informational.  An app can continue to use the swapchain.  VK_ERROR_OUT_OF_DATE_KHR is an error.  The swapchain can't be used anymore, and must be re-created.

I'm just curious @krOoze, can you share the message that was output?  I'm suspecting that the validation layer needs to be fixed.

**Comment by krOoze** [comment]
@ianelliottus 
I did not copy the message and it is a bit of hassle to set the environment again.
But the text was same as this:
https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/sdk-1.0.33/layers/parameter_validation_utils.h#L813
with this:
https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/sdk-1.0.33/layers/parameter_validation_utils.h#L781
and it was from the `ParameterValidation`.


Am I missing something? It looks to me pretty consistent with the layer source code that it would write that, so I assumed it was correct (though as the Issue says; potentially undesired) behavior.

But I was surprised I failed to reproduce with a different error (a `VK_ERROR_EXTENSION_NOT_PRESENT` on `vkCreateDevice`).

So even now is it actually supposed to  show a layer `WARNING` anytime a `VK_ERROR_*` is returned?

**Comment by mark-lunarg** [comment]
The layer presently outputs a Warning if the return code is negative, i.e., it starts with VK_ERROR_*.  Other non-success return codes produce no output including those for VK_SUBOPTIMAL_KHR, VK_NOT_READY, VK_TIMEOUT, etc.  The definitions of Error and Warning aside, we feel these VK_ERROR_* messages are important enough to warrant a Warning.
