### ISSUE TITLE
CPack usage

### ISSUE THREAD

**Issue by elfring** [KhronosGroup/Vulkan-LoaderAndValidationLayers#12]
How do you think about to [reuse the software "CPack"](https://cmake.org/Wiki/CMake:Packaging_With_CPack "CMake: Packaging with CPack")?

**Comment by karl-lunarg** [comment]
What would be the benefit of using CPack?

**Comment by elfring** [comment]
Are you interested in [the support for a variety of package formats by this software module](https://cmake.org/Wiki/CMake:CPackPackageGenerators#CPack_Package_Generators "Selection of package formats")?

**Comment by karl-lunarg** [comment]
CPack doesn't seem to accomplish the same thing LunarG is doing with its Windows installer, so no help there.

While there may be some interest in generating various Unix packages, some package maintainers are pulling from the sources in the githubs themselves.  And LunarG is already providing ".run" packages for debian-based systems.  In addition, the LunarG SDK is generated using content from several repos.  So, it seems that package generation within a single repo won't be a complete solution for the SDK.

If you have a specific requirement for the build to generate a specific package, then please let us know.

Or better, please submit a pull request for the same.  

Thanks!
