### ISSUE TITLE
Fix WriteDescriptorSetIntegrityCheck test

### ISSUE THREAD

**Issue by chrisforbes** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1201]
This test case is horribly confused.

**Comment by mark-lunarg** [comment]
@chrisforbes, do you want this one?  If not, add your observations in the comments and we'll assign it to somebody here.

**Comment by chrisforbes** [comment]
I'll add some notes here, hang on.

**Comment by chrisforbes** [comment]
Surface stuff:
- The pool does not contain any descriptors of type `VK_DESCRIPTOR_TYPE_SAMPLER`, but the layouts used do.
-  Descriptor count of 2 is used in subtest 2, which makes some sense, but binding this would spill over to is also of a different type, and the array of updates only contains one element, so this is asking for trouble. This needs to be focused so it only has one thing wrong.

**Comment by Tony-LunarG** [comment]
Fixed with 150d2b55a2
