### ISSUE TITLE
DrawState: False positives for "Cannot map an image with layout..." when the implementation re-uses handles

### ISSUE THREAD

**Issue by hrydgard** [KhronosGroup/Vulkan-LoaderAndValidationLayers#121]
When an image is bound to memory, the following mapping is added to keep track:

    dev_data->memImageMap[mem] = image;

When the image and memory are later deleted, they are never removed from this map. Then, if the implementation later reuses handles (for example when these images have been deleted and new ones allocated), this can cause false layout warnings and possibly other problems.

Also, ValidateMapImageLayouts should take the offset and size into account, to correctly track suballocations.

Could possibly be related to #46 .

Search for memImageMap in
https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/draw_state.cpp
to see that the mappings never get removed.

**Comment by lentinem** [comment]
Thanks. Adding the unique objects layer before the draw state layer should remove this issue. There should also be a warning if that isn't the case which was just added a few days ago.

**Comment by hrydgard** [comment]
I'm using VK_LAYER_LUNARG_standard_validation, SDK 1.0.5.

Even if unique_objects solves this, I think that when an image is deleted, the mappings should still be removed - as otherwise the memory usage of this map can just grow indefinitely.

**Comment by lentinem** [comment]
Absolutely true. There are a number of known issues similar to this. The unique objects layer can avoid these for the time being until the are all addressed.

**Comment by hrydgard** [comment]
Just confirmed that unique_objects does resolve it. Maybe that layer should be included in VK_LAYER_LUNARG_standard_validation?  Or maybe not as that could mask issues like this...

**Comment by lentinem** [comment]
Yes it should; I filed another bug to track that as this one is going to remain open until the map removal is fixed. We currently want to provide as bug free of an experience as possible and it's fairly easy to turn it off when trying to detect issues such as this.

**Comment by hrydgard** [comment]
https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/tree/master/layers states that it is already included in the standard validation, but in the last position instead of the first so it indeed won't work around this problem.

**Comment by hrydgard** [comment]
Sorry - Adding the layer first does not actually fix the issue, as this is an object lifetime issue rather than a unique handle issue. I just thought it did because my initialization code got VK_ERROR_LAYER_NOT_PRESENT (because I accidentally used VK_LAYER_LUNARG_unique_objects instead of VK_LAYER_GOOGLE_unique_objects) and fell back to not using the layers at all.

**Comment by dustin-lunarg** [comment]
Pull request [#131](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/131) should have resolved this issue.
