### ISSUE TITLE
Validation layer incorrectly reporting fillModeNonSolid = false

### ISSUE THREAD

**Issue by disks86** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1224]
I'm seeing warnings like the following when I use point or line but as you can see from the attached json my card has "fillModeNonSolid" set to true.

DebugReport(Error): vkCreateGraphicsPipelines parameter, VkPolygonMode pCreateInfos->pRasterizationState->polygonMode cannot be VK_POLYGON_MODE_POINT or VK_POLYGON_MODE_LINE if VkPhysicalDeviceFeatures->fillModeNonSolid is false.

Vulkan SDK: 1.0.33.0

[Radeon (TM) RX 480 Graphics.zip](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/files/626192/Radeon.TM.RX.480.Graphics.zip)

**Comment by mark-lunarg** [comment]
@disks86, can you please run vulkaninfo from your Vulkan SDK on this system and attach the results here?

**Comment by chrisforbes** [comment]
@disks86, are you enabling the feature at device creation time?

**Comment by disks86** [comment]
That was it, I've always passed null and it renders properly however I started getting spammed when this validation was added. Apparently the implementations I've tested on don't require the features to be enabled. I apologize this appears to be my issue not a bug in the validation layer.
