### ISSUE TITLE
errorMonitor not correctly flagging errors on positive tests

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1228]
Noticed this in updating DynamicOffsetWithInactiveBinding for #1212 

On branch tobin_gh1212_positive_test_unexpected_errors I've pushed the updated version of that test without my fix. This causes unexpected errors in the test but even though it's ExpectSuccess() the test does not fail.

**Comment by Tony-LunarG** [comment]
Fixed with 689ea76741
