### ISSUE TITLE
Add lower bounds validation for VkFramebuffer dimensions

### ISSUE THREAD

**Issue by gfxguymatt** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1230]
If an application creates a VkFramebuffer with layers = 0, the validation layer for VulkanSDK 1.0.33.0 does not generate an error. Although the Vulkan spec does not state that this is an error, attempting to render to the VkFramebuffer will result in VK_ERROR_DEVICE_LOST on my GeForce GTX 980. Although I have not tested it I assume the same would occur if width/height were also 0.

**Comment by lentinem** [comment]
This can be address in two ways, either we can add a check and change the spec (most likely) or add a CTS test and enforce that drivers can handle this. I don't have a strong preference.

**Comment by mark-lunarg** [comment]
@gfxguymatt, you'll need to open an issue with the spec in the [Github/Vulkan-Docs](https://github.com/KhronosGroup/Vulkan-Docs/issues) repo.  Once there is clear language in the spec, we can reopen this issue or create a new one to add the new checks.
