### ISSUE TITLE
vkCmdWaitEvents/vkCmdPipelineBarrier validation improvement request

### ISSUE THREAD

**Issue by pdaniell-nv** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1233]
The validation for the srcStageMask and dstStageMask parameter doesn't currently check for the following valid usage:
* Any pipeline stage included in srcStageMask or dstStageMask must be supported by the capabilities of the queue family specified by the queueFamilyIndex member of the VkCommandPoolCreateInfo structure that was used to create the VkCommandPool that commandBuffer was allocated from, as specified in the table of supported pipeline stages.

The reason I'm reporting this is because I'm seeing several apps which violate this valid usage.

**Comment by mark-lunarg** [comment]
Addressed in pull request #1258.
