### ISSUE TITLE
Make VALIDATION_ERROR_UNDEFINED first-class enum

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1240]
VALIDATION_ERROR_UNDEFINED currently is custom defined in object_tracker.cpp. Need to integrate into codegen and make it an actual enum in UNIQUE_VALIDATION_ERROR_CODE so all layers can use it.

**Comment by tobine** [comment]
This was added a week or so ago

**Comment by mikew-lunarg** [comment]
Does that make it possible to pass that enum as an index for messages?; i.e.: validation_error_map[VALIDATION_ERROR_UNDEFINED]

**Comment by tobine** [comment]
That may currently work, although not intentionally. It's defined as "-1" which doesn't have an  explicit corresponding error message. However, I think the [] operator on an unordered map will cause the entry to be default constructed, which I think would give a null string which would probably be the desired behavior.

Do you want to test it out?
If it doesn't work, we can add in an explicit entry to the validation_error_map where -1 maps to an empty string or some appropriate "error undefined" type of message.

**Comment by mikew-lunarg** [comment]
Will do, I'll give it a try.
I recently had a case where it would have been useful for a helper function.
