### ISSUE TITLE
Performance warning: Pipeline barriers used for layout transitions instead of Render Passes

### ISSUE THREAD

**Issue by TobiasHector** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1253]
I've seen a large number of apps doing "the dumb thing" by putting a constant layout transition from say, present to renderable (and back again), by using a pipeline barrier. The cube demo does the more useful thing (awesome!) by putting these transitions into the render pass, which should allow more implementation flexibility (read: better perf/efficiency) than a pipeline barrier.

Ideally the layers should try to detect this case and hint to developers that they should be able to do this more efficiently with a render pass.

Understandably this is probably quite a complex thing to detect, though I think the 99% case shouldn't be too difficult to figure out? The usual case I've seen is this:

* PipelineBarrier: PRESENT/UNDEFINED -> RENDERABLE
* Begin/EndRenderPass (initialLayout == RENDERABLE, finalLayout== RENDERABLE, subpass layout == RENDERABLE)
* PipelineBarrier: RENDERABLE -> PRESENT

There's undoubtedly going to be other cases, but usually I suspect that looking for a render pass with initialLayout == subpass layout or finalLayout == subpassLayout is at least a useful indicator that this *might* be happening, if detecting anything beyond that is tricky.

**Comment by mark-lunarg** [comment]
This issue is now tracked via issue #1612.
