### ISSUE TITLE
DrawState layer: Layer reports an invalid layout mismatch problem

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#126]
I believe I came across a corner case which is not correctly handled by the layer. Consider the following:

1. Create an image A with D16_UNORM_S8_UINT format, initialLayout set to VK_IMAGE_LAYOUT_UNDEFINED.
2. Issue a memory barrier, which moves it to a TRANSFER_DST_OPTIMAL layout.
3. Create an image view X off image A, with aspectMask set to DEPTH_BIT only.
4. Use the view X as a subpass attachment. The corresponding renderpass attachment's initialLayout should be set to TRANSFER_DST_OPTIMAL.

At vkQueueSubmit(), where the renderpass is used, I'm getting the following call-back, which is invalid:

![image](https://cloud.githubusercontent.com/assets/17761066/13744162/507122f0-e9e6-11e5-871d-318ae3e5b48b.png)

**Comment by DominikWitczakAMD** [comment]
I think the layers are ignoring the following spec language:

```
When an imageView of a depth/stencil image is used as a depth/stencil framebuffer attachment,
                 *  the aspectMask is ignored and both depth and stencil subresources are used.
```

**Comment by DominikWitczakAMD** [comment]
Please consider making this a P1. I'm presuming this call-back is going to backfire on anyone trying to use depth+stencil images for anything more complex than just mere rasterization.

**Comment by lentinem** [comment]
I've started trying to repro this with no success and am also not sure that bit of spec is relevant to this issue as that should be handled correctly. The image barrier should (and seems to in my case) transition the layout from UNDEFINIED to DST_OPTIMAL. If my example is similar, the way I get this error is by making src layout is DST_OPTIMAL and not UNDEFINIED. Can you give a bit more detail as to how to repro this? Do you use multiple command buffers here?

**Comment by DominikWitczakAMD** [comment]
I'll get back to you on this tomorrow. Sorry, been busy with other stuff for the last couple of days.

**Comment by DominikWitczakAMD** [comment]
We might be talking about two different use cases here, Michael. Allow me to elaborate about how I get to reproduce this issue.

1. Here's how the image is created:

![image](https://cloud.githubusercontent.com/assets/17761066/13990781/e1d8dd92-f115-11e5-9f0d-87f8d1c030cd.png)

I then record the following image barrier via a vkCmdPipelineBarrier() call in a universal queue command buffer, submit it to the queue and wait on a fence until that buffer finishes executing server-side:

![image](https://cloud.githubusercontent.com/assets/17761066/13990844/274a5c2a-f116-11e5-8e5b-804bc92c81c9.png)

Note the aspectMask is set to 6 there, which corresponds to VK_IMAGE_ASPECT_DEPTH_BIT | VK_IMAGE_ASPECT_STENCIL_BIT

The image view is set up as below:

![image](https://cloud.githubusercontent.com/assets/17761066/13992419/5142a1a8-f11c-11e5-95fe-06f6b5714286.png)

**NOTE**: After I wrote down the whole comment, it just occurred to me that the core_validation layer **probably** ignores the following spec statement:

```
When an imageView of a depth/stencil image is used as a depth/stencil framebuffer attachment, the aspectMask is ignored and both depth and stencil subresources are used."
```

So, that aspectMask of 2 I'm using here is just as good as 6, but this is not as clear to the validation layer, as it is to me :)

2. Then, we set up the renderpass. It uses two attachments, from which we're only interested in the zeroth one:

![image](https://cloud.githubusercontent.com/assets/17761066/13991143/478f1704-f117-11e5-97ae-7db050463360.png)

The renderpass defines two subpasses. The zeroth one accesses the DS image view via the DS attachment:

![image](https://cloud.githubusercontent.com/assets/17761066/13991214/8b56f42a-f117-11e5-8827-e2a97852a597.png)

It needs to be noted that the first subpass samples from that image view. So, we transition the image to SHADER_READ_ONLY_OPTIMAL layout at the beginning of the first subpass with the following image barrier, issued via the vkCmdPipelineBarrier() call:

![image](https://cloud.githubusercontent.com/assets/17761066/13991993/8836e450-f11a-11e5-9dba-38b0247df7cb.png)

Of course, the relevant subpass 0->1 dependency is also defined, but I don't think it's relevant for the purpose of our discussion.

3. In the command buffer, when we begin the renderpass, we additionally specify a FB, to which the image view (specified as shown in step 1) is bound as the zeroth attachment.

4. The problematic call-back occurs at vkQueueSubmit() call time. A few interesting observations:

![image](https://cloud.githubusercontent.com/assets/17761066/13992226/9686a29c-f11b-11e5-8069-07b50db82968.png)

![image](https://cloud.githubusercontent.com/assets/17761066/13992264/b2648d8a-f11b-11e5-957a-0e62453511e3.png)

![image](https://cloud.githubusercontent.com/assets/17761066/13992274/bd2ee22e-f11b-11e5-9828-5c12bc0b9886.png)
![image](https://cloud.githubusercontent.com/assets/17761066/13992281/c5ec06da-f11b-11e5-89db-276f0cd92711.png)

**Comment by DominikWitczakAMD** [comment]
Did the description above help in reproducing the issue?

**Comment by lentinem** [comment]
Yes, sorry; this should have been merged but I forgot to update the bug.

**Comment by DominikWitczakAMD** [comment]
Yeah, I think this one no longer reproduces. Thanks for fixing this, Michael!
