### ISSUE TITLE
Layers: vkCreateBuffer is missing check for VALIDATION_ERROR_00669

### ISSUE THREAD

**Issue by yavn** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1260]
> If flags contains VK_BUFFER_CREATE_SPARSE_RESIDENCY_BIT or VK_BUFFER_CREATE_SPARSE_ALIASED_BIT, it must also contain VK_BUFFER_CREATE_SPARSE_BINDING_BIT

I can propose a PR to cover that tomorrow if needed. This part isn't autogenerated if I see correctly.

**Comment by mark-lunarg** [comment]
Maciej, a PR would be great and I can handle it right away, thanks...

**Comment by yavn** [comment]
BTW, I've noticed that if SPARSE_BINDING flag is not set, the layer will not treat the memory binding as sparse, and that later results in an assert firing in `SetSparseMemBinding` (core_validation.cpp):

```
assert(mem_binding->sparse);    // boom
```

That is fine I suppose, but usually layers don't crash the process, so I thought I should might mention that.

**Comment by mark-lunarg** [comment]
Closed with PR #1278.
