### ISSUE TITLE
Parameter Validation: Incorrectly complains about missing viewport/scissor when using dynamic state

### ISSUE THREAD

**Issue by hesiod** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1261]
When using dynamic state for the viewport and scissor (`VK_DYNAMIC_STATE_VIEWPORT/SCISSOR`) and consequently not setting them at pipeline creation time, the parameter validation layer incorrectly complains that one has to set the initial viewport and scissor. It claims that the relevant flags were not included in the dynamic state configuration, even if they were.

> vkCreateGraphicsPipelines: if pCreateInfos[0].pDynamicState->pDynamicStates does not contain VK_DYNAMIC_STATE_VIEWPORT, pCreateInfos[0].pViewportState->viewportCount must be greater than 0
> vkCreateGraphicsPipelines: if pCreateInfos[0].pDynamicState->pDynamicStates does not contain VK_DYNAMIC_STATE_SCISSOR, pCreateInfos[0].pViewportState->scissorCount must be greater than 0

The cause seems to lie in lines [2918](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/parameter_validation.cpp#L2918) and [2940](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/parameter_validation.cpp#L2940). The errors are generated whether `has_dynamic_viewport`/`has_dynamic_scissor` are true or not.

**Comment by mark-lunarg** [comment]
@hesiod.  

Even if dynamic state is being used for (let's say) viewports, the corresponding viewportcount _must_ be non-zero.  From the spec:
`If the multiple viewports feature is not enabled, viewportCount must be 1`  
That said, the error message you received is incorrect -- it has nothing to do with dynamic state.  I'll file a PR shortly to fix the message text.

**Comment by mark-lunarg** [comment]
Fixed and pushed to Master.  Thanks @hesiod.

**Comment by hesiod** [comment]
A bit late, but thanks @mark-lunarg for the clarification anyways!
