### ISSUE TITLE
clang-format now broken on OSX

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1268]
When I attempt to run "git clang-format --style=file" from and iTerm2 window on OSX I now get the error:

> YAML:6:15: error: unknown key 'SortIncludes'
> SortIncludes: false
>               ^~~~~

This was caused by #1262

**Comment by mark-lunarg** [comment]
What version of c-f is this and where does the tool come from?  I think this option was added to 3.8.  Is there an updated version of your tool?

**Comment by jeremy-lunarg** [comment]
Do we really want to turn off sorting for all includes? Most of time I'm okay with the way CF resorts them. We could just turn it off around the includes that break.

**Comment by tobine** [comment]
@mark-lunarg I had clang-format 3.7 from homebrew. `brew upgrade clang-format` did the trick and it's now working for me again.
