### ISSUE TITLE
DrawState layer: "Attachment X not written by FS" is reported for renderpass attachments with store op set to DONT_CARE

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#127]
Consider a renderpass with an attachment, whose corresponding store op has been configured to DONT_CARE at renderpass creation time.

If we issue a draw call inside a subpass with that attachment activated, and the GFX pipeline's fragment shader does NOT write to that attachment, we are reported the following error:

![image](https://cloud.githubusercontent.com/assets/17761066/13744646/6fe1b4f8-e9e9-11e5-86e3-6e9eb045d25f.png)

Formally speaking, given the attachment's store op has been set to DONT_CARE, this error is irrelevant.

**Comment by lentinem** [comment]
IMO this should at the very least be a perf warning.

**Comment by DominikWitczakAMD** [comment]
Yup, that's fine by me!

**Comment by chrisforbes** [comment]
I don't think this is valid.

Suppose a render pass with multiple subpasses -- any kind of deferred setup, or some postfx stuff you're trying to fold in for a tiler. All of the attachments which are not the final rendered image can have their store op set to DONT_CARE -- the data does not need to be in the surface after the renderpass ends.
That /doesn't/ mean that we don't care whether or not the shader writes them!

This would suggest that the minimum bar for relaxing this error should be that there is also no later use of that attachment.

However, even that seems fishy. This is a shader interface mismatch. The Vulkan spec says very little about the degree of misbehavior acceptable, but it doesn't seem unreasonable that missing FS exports might hang some hardware.

**Comment by chrisforbes** [comment]
Passing back to @DominikWitczakAMD for an opinion.

**Comment by DominikWitczakAMD** [comment]
Tried to look for some pointers in the spec (I think I can recall seeing some language a long time ago about the effects of leaving FS output variables untouched) but either it's been wiped out or it's my bad memory again. Either way, what Chris says makes sense.
