### ISSUE TITLE
'encoding' is an invalid keyword argument in generator.py

### ISSUE THREAD

**Issue by mre4ce** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1270]
File "/home/travis/build/KhronosGroup/Vulkan-LoaderAndValidationLayers/scripts/generator.py", line 322, in beginFile
    self.outFile = open(filename, 'w', encoding='utf-8')
TypeError: 'encoding' is an invalid keyword argument for this function

**Comment by mark-lunarg** [comment]
@mre4ce, Python 3 is required to build the repo as described in BUILD.md.  If you are using python 2 you will see this error.  This particular file comes straight from the Khronos Vulkan-Docs repo (we update it with each header update) and we do not modify it.

**Comment by mre4ce** [comment]
Thanks Mark. Not your fault but now I'm back to continuously switching between Python 2 and 3 :/

**Comment by mre4ce** [comment]
Do I need a particular version? I switch both AppVeyor and TravisCI to Python 3.5 and it fails just the same.

**Comment by mre4ce** [comment]
Sorry, user error. The scripts were still calling python.

**Comment by mark-lunarg** [comment]
Ah!  You had me running scared.  OK.  I imagine that Jon Leech at Khronos would be receptive to your patch -- let us know if there's anything we can do.
