### ISSUE TITLE
Memory layer: "Cannot read invalid memory X, please fill the memory before using" is incorrectly reported

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#128]
Consider a renderpass which consists of a single subpass, with a single color attachment and a single input attachment:
* The color attachment uses a DONT_CARE load op value.
* The FS uses a predefined value IF the draw call's instance index is 0, otherwise the value is loaded from a subpass input uniform, which refers to the input attachment.
* The subpass issues a number of instanced draw calls, each instanced draw call using an instanceCount value equal to 1, and having firstInstance argument assigned consecutive values (with the first subpass using a number of 0 for this arg). An image memory barrier follows each draw call, so that following draw calls can correctly read back data rasterized in the previous subpass.
* Both color & input attachments refer to the same image view.
* Assume all dependencies are correctly defined for the renderpass.

In this scenario, I'm seeing a "Cannot read invalid memory X, please fill the memory before using" error being raised by the DrawState layer, even though the logic in the app is not flawed. In principle, it is an example of a feedback loop, which is legal in Vulkan.

Given that it will be very tricky, if not impossible, for the validation layer to detect a read-before-write condition if the same attachment is used in the same pass as a color & an input attachment and the FS features a special logic to prevent the hazard from happening, I would either recommend to disable the error call-back in such case, or decrease its level to a warning.

**Comment by lentinem** [comment]
I think it would be ok that have a special exception that doesn't require it in this case (both input and output) but I'd rather not decrease it to a warning or disable as this has caught numerous bugs with app code.

**Comment by DominikWitczakAMD** [comment]
Sounds good to me :)

**Comment by lentinem** [comment]
Is this still an issue? It looks like this was fixed a while ago but it's still listed as open.

**Comment by lentinem** [comment]
Closing. Please re-open if problem persists.
