### ISSUE TITLE
Layers: performance warning about unused vertex buffers, but no way to unbind them?

### ISSUE THREAD

**Issue by cdwfs** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1282]
Context: I have a VkRenderPass with two subpasses; the first renders some geometry, and the second does some simple post-processing. There's only one VkPipeline used in the second pass, and it has no vertex attribute bindings defined; the only draw call is a full-screen triangle which generates its VS output procedurally.

Today, I enabled PERFORMANCE_WARNING messages in the validation layers, and started receiving the following warning inside the second subpass's vkCmdDraw():
`PERFORMANCE WARNING: [DS] Code 24 : Vertex buffers are bound to command buffer (
0x5b00700) but no vertex buffers are attached to this Pipeline State Object (0x3
0).`
It looks like it's complaining that the vertex buffer bindings from a VkPipeline of the previous subpass are still active, even though the post-processing subpass isn't using them. Assuming that's accurate, what's the right way to unbind the buffers to avoid this warning? Calling vkCmdBindVertexBuffers with pBindings=NULL is an error; so is setting pBindings[0]=VK_NULL_HANDLE, or bindingCount=0 (though I'd expect that to be a no-op, if anything). Am I missing something, or is this a spurious warning?

**Comment by chrisforbes** [comment]
Yeah, this warning logic falls apart for more complex recordings. @tobine, thoughts?

**Comment by tobine** [comment]
Gave this some thought. Tried to think of a good way to update the message to allow for custom cases like this but don't have a great idea of wording. If anyone has an idea we can certainly tweak the message.
For now, I'm just thinking ignore it as you know what you're doing. In general for warnings and perf warnings, if you know what you're doing, you can ignore them. They're primarily intended for novice users. Here's the definition from spec for perf warning which allows for some leeway in what's reported:

`VK_DEBUG_REPORT_PERFORMANCE_WARNING_BIT_EXT indicates a potentially non-optimal use of Vulkan.`

**Comment by cdwfs** [comment]
I don't mind performance warnings being ignorable, though if I'm regularly ignoring 90% of the warnings, I'm likely to start ignoring 100% of them. I don't plan to leave PERFORMANCE_WARNING enabled all the time (as I currently do with ERROR and WARNING during development); I'll save it for occasional spot checks.

My concern in this specific case is that it wasn't clear what the layers would like me to do differently here; it seems the only way to remove unused vertex buffer bindings is to start a new command buffer whenever I change vertex layouts, but that seems like overkill. If it's a potential performance issue to leave state like this bound across draws within a CB, should the spec provide a way to explicitly unbind it?

**Comment by tobine** [comment]
In this case the layer sees that the bound vtx buffers aren't used for the current draw call, so the main concern is that you meant to bind the vtx buffers at all.
Would it be better with the following additional text `If the bound vertex buffers are not used for a previous draw of this cmd buffer, then it is recommended that you do not bind them at all.`

Now that I write that out, I think the perf warning could be limited if we add a bool to the cmd buffer state tracking if/when vtx buffers are used. Then only flag the perf warning if we hit a case where a draw occurs and the vtx buffers have NEVER been used.

I've just pushed tobin_gh1282_perf_warn_cleanup branch that should only flag the perf warning if the vtx buffers are NEVER used. Please give that a try and verify if it clears the perf warning.

**Comment by cdwfs** [comment]
I love this plan! I tested your branch, and it does indeed prevent the warning from appearing. I tried commenting out the draw calls in my main pass (so the vertex buffers really _aren't_ used), and the warning reappeared as expected. Thanks Tobin!
