### ISSUE TITLE
Draw State: Type mismatch incorrectly reported if sparse descriptor set bindings are used

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#130]
Consider the following descriptor set layout configuration:

![image](https://cloud.githubusercontent.com/assets/17761066/13749643/a4e7301a-ea02-11e5-99d1-ef308fd7f6c0.png)

..and the following excerpt from the fragment shader, used to initialize a GFX pipeline:

![image](https://cloud.githubusercontent.com/assets/17761066/13749755/0df95c18-ea03-11e5-9bcc-7ffa5d698d8b.png)

If I try to use the two together when creating a GFX pipeline, I'm getting the following error call-back:

![image](https://cloud.githubusercontent.com/assets/17761066/13749802/460b74ec-ea03-11e5-9449-6994f4109682.png)

The call-stack is:

![image](https://cloud.githubusercontent.com/assets/17761066/13749851/6537c46a-ea03-11e5-9099-c5af4d254e84.png)

![image](https://cloud.githubusercontent.com/assets/17761066/13749866/7517adf0-ea03-11e5-8f50-28e7f68fd8af.png)

I did a very quick investigation and it seems like layout_node->descriptorTypes keys do not take sparse bindings into consideration.. See the sshots below:

![image](https://cloud.githubusercontent.com/assets/17761066/13749932/b54bd1bc-ea03-11e5-9419-a829f55e922e.png)

![image](https://cloud.githubusercontent.com/assets/17761066/13749970/db831da4-ea03-11e5-9812-91b168494447.png)

![image](https://cloud.githubusercontent.com/assets/17761066/13749946/c3f456ee-ea03-11e5-962f-aa66b8842885.png)

In this case, slot = (0, 2) for the second storage image, but has_descriptor_binding() seems to consider it a uniform buffer, which leads to the invalid call-back:

![image](https://cloud.githubusercontent.com/assets/17761066/13750035/1b976292-ea04-11e5-8ac3-07083dc78776.png)

**Comment by DominikWitczakAMD** [comment]
This actually results in a crash later on, where at some point the layer tries to access _layout_node->descriptorTypes[3]_ which gives an access violation error under VS CRT 2013:

![image](https://cloud.githubusercontent.com/assets/17761066/13750286/1cc22ffc-ea05-11e5-9bc3-d2902645735e.png)

**Comment by tobine** [comment]
Submitted #135 to fix this.
Dominik, if you can test that out for your specific failing case, please do.

**Comment by tobine** [comment]
This first fix is wrong. Let me work on a better fix.

**Comment by DominikWitczakAMD** [comment]
All right, I'll just wait patiently in my corner then.

**Comment by tobine** [comment]
Alright, I have a correct fix. See #137.

**Comment by DominikWitczakAMD** [comment]
With the fix in, the misleading call-back is gone. Thanks!

**Comment by tobine** [comment]
Fix pushed to master
