### ISSUE TITLE
vkCmdDispatch does not mark target image region as valid anymore

### ISSUE THREAD

**Issue by McNopper** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1311]
Used to work and latest refactoring did break functionality.

**Comment by tobine** [comment]
I had a blatant cut-and-paste bug that I just pushed a fix for. Not positive that addresses the issue but seems like the likely culprit. @McNopper can you check with latest master and confirm if issue still exists?

**Comment by McNopper** [comment]
Does not fix it.

If you want, you can test by yourself:
https://github.com/McNopper/Vulkan

It is example 8, which reports:
MEM(WARN): object: 0x5 type: 8 location: 528 msgCode: 15: vkCmdCopyImage(): Cannot read invalid region of memory allocation 0x5 for bound image object 0x4, please fill the memory before using.

The image is filled/written by the compute shader.

**Comment by tobine** [comment]
Thanks, @McNopper I'm out today but will check this out tomorrow.

**Comment by tobine** [comment]
Alright, #1319 should fix the issue. @McNopper please give it a look. Issue was pretty clear after some digging.

Unfortunately I was unable to verify the fix with your example. I did get your example running on Windows, but for some reason the loader is refusing to load my custom-built layers. I tried a bunch of tricks but they just wouldn't work.

I primarily work in Linux, but have cmake 2.8 so I couldn't easily build your examples on Linux. Is there a simple way to build with older cmake? Also, is the build documentation up-to-date for your examples? I see that there are a number of create_* scripts that appear to automate the build but I didn't see them documented in the Build.md.

**Comment by McNopper** [comment]
Unfortunatelly, CMake 3.2 is required - because of the find and C++11 features. 
I am using for desktop Linux Ubuntu 16.04, where the required CMake is by default installed. Which Linux derivate and version are you using?

Beside CMake, the examples can be build with Eclipse - Windows and Linux. The Eclipse project files are included.


I just cross checked my BUILD.md document. The build for Linux and make is up to date but the create_* scripts are not yet documented.

Calling

python3 create_build_all_make.py

does create all CMake project files and does build the libraries and finally the examples.

By default, the windowing system is for XCB/XLib WSI.

For Wayland WSI, please execute:

python3 create_build_all_make.py VKTS_WAYLAND_VISUAL

For the Display WSI, please execute:

python3 create_build_all_make.py VKTS_DISPLAY_VISUAL

**Comment by McNopper** [comment]
Thanks for fixing the issue.
