### ISSUE TITLE
Cube example uniform buffer update synchronization

### ISSUE THREAD

**Issue by tksuoran** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1330]
It is not clear to me how the cube example synchronizes uniform buffer updates from CPU and reads from GPU. Shouldn't demo_update_data_buffer() wait for last previous command that reads from uniforms to be completed before it can go modify uniform memory? And once there is such synchronization, the same memory probably should not be used in subsequent draws, otherwise CPU and GPU execution gets effectively serialized.

**Comment by Tony-LunarG** [comment]
Fixed with c44ffcd5
