### ISSUE TITLE
Draw State: Ref counters are not decremented correctly if more complex cmd buf chains are submitted

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#134]
Consider command buffers A and B, a fence F, and an event S. Let:

1. Command buffer A set the event S.
2. Command buffer B wait on the event S.
3. The app do the following:

a) Issue two command buffers, each command buffer submitted with a separate vkQueueSubmit() call with fence F being set after the second command buffer finishes executing.
b) Wait on the fence F.
c) Destroy both command buffers A and B, and then destroy the event S.

The in_use counter for the event S is only decremented once at step 3b, even though it is increased by 1 for each vkQueueSubmit() call. This leads to the following incorrect error, which is reported at vkDestroyEvent() call time:

![image](https://cloud.githubusercontent.com/assets/17761066/13777148/81d10d9c-eaae-11e5-81c9-0e795ae645f6.png)

**Comment by DominikWitczakAMD** [comment]
It seems that this issue also affects buffer object ref counters. To reproduce, just stick a non-redundant vkCmdBindVertexBuffers() call somewhere into the cmd buffer A.  

In this scenario, the ref counter is only incremented, and never gets reset back to 0, ultimately leading to:

![image](https://cloud.githubusercontent.com/assets/17761066/13777549/1f783bcc-eab1-11e5-890c-e005011db845.png)

**Comment by lentinem** [comment]
Yes; there are two primary issues with lifetime which need to be addressed which should fix most of the open issues. I've been a little swamped this week but hope to get them done somewhat shortly. Sorry for the delay.

**Comment by lentinem** [comment]
MR has been submitted.

**Comment by DominikWitczakAMD** [comment]
Continues to repro, most likeyl due to unsolved #99 and #100. Let's leave this open for now.

**Comment by lentinem** [comment]
This should be fixed now.

**Comment by DominikWitczakAMD** [comment]
Works like a charm! Many thanks :)
