### ISSUE TITLE
Incorrect vkCmdDraw[Indexed]IndirectCountAMD object validation

### ISSUE THREAD

**Issue by mhogdahl** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1342]
The object tracker complains about invalid device object when using these functions. I think it has to do with the commandbuffer argument being tested as a device.

i.e this line:
skip_call |= ValidateObject(commandBuffer, commandBuffer, VK_DEBUG_REPORT_OBJECT_TYPE_DEVICE_EXT, false);

**Comment by mark-lunarg** [comment]
Fixed and pushed.  Thanks!
