### ISSUE TITLE
Runtime installer does not write a log file

### ISSUE THREAD

**Issue by jjulianoatnv** [KhronosGroup/Vulkan-LoaderAndValidationLayers#136]
Robust installers generate log files. They can be helpful to debugging system-specific issues that happen outside of the test lab, e.g. on end user systems.

A few bugs have been found in the Vulkan runtime installer which were more difficult to debug than they would have been if the installer wrote a good log file.

The uninstaller could optionally write a log file that is left on disk after the uninstaller has completed if an optional command line argument or registry key is set up.

This issue was raised prior to Vulkan launch day. It was agreed we put off logging capability until post-launch. This issue tracks the post-launch task.

**Comment by davidlunarg** [comment]
Logging has been added to the Vulkan Runtime Installer
