### ISSUE TITLE
Loader's EnumeratePhysicalDevices breaks dEQP-VK.api.info.instance.physical_devices

### ISSUE THREAD

**Issue by djdeath** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1368]
In the case you call EnumeratePhysicalDevices with a 0 device count and a non null pointer for devices, the loader seems to interfere with the response of the driver and makes the dEQP-VK.api.info.instance.physical_devices test fail.

**Comment by MarkY-LunarG** [comment]
This is fixed with commit d4dc58b9ae008d6fad2eb24602b61a75b3186423.
