### ISSUE TITLE
Layers: vkCmdBlitImage does not appear to have image bound checking

### ISSUE THREAD

**Issue by RickvanMiltenburg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1376]
Hi,

I am working on a small software rasterizer in my spare time, and use Vulkan as a backend to get the result on display, since I already had a Vulkan application lying around for a lecture I did recently.

This worked well until I resized the window, at which point there was a certain likelyhood of a Blue Screen of Death.

After some reworking of the Vulkan code, I stumbled upon an easy way to obtain a Blue Screen of Death involving vkCmdBlitImage. Now, what I am demonstrating below is of course not the exact application error, but the case below has had a 100% success rate in crashing and burning in more than 5 test runs:

```
vkCmdBlitImage (
	frameCommandBuffer,
	api->uploadBuffers[i].image, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
	api->swapchain.images[i],    VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
    1, (VkImageBlit[1]){
        {
            .srcSubresource = {
                .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                .mipLevel = 0, .baseArrayLayer = 0, .layerCount = 1,
            },
            .srcOffsets[0] = { 0, 0, 0 },
            .srcOffsets[1] = { renderWidth, renderHeight, 1 },
            .dstSubresource = {
                .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                .mipLevel = 0, .baseArrayLayer = 0, .layerCount = 1,
            },
            .dstOffsets[0] = { 0, 0, 0 },
            .dstOffsets[1] = { windowWidth+1, windowHeight+1, 1 }, // +1 to demonstrate overflow not being caught by the validation layers
        },
    }, VK_FILTER_NEAREST
);
```

**Context**

- uploadBuffers[i].image is an image of renderWidth x renderHeight
- swapchain.images[i] is an image of windowWidth x windowHeight
- The application crashes if .dstOffsets[1] is out of bounds of swapchain.images[i]. I did not test the other properties, but I would expect similar results.
- Similarly, I only tested this with a copy from a non-backbuffer texture, to a backbuffer texture acquired with vkAcquireSwapchainImage
- Removing the +1, +1 restores non-crashing behaviour
- OS: Windows 10 (Build 14393)
- Installed Vulkan version: 1.0.37.0
- GPU + Driver: GTX 1080 (MSI Aero), NVidia Geforce 376.33

I have no issue sharing the rest of the project in case it helps in tracking down the problem, is it best practice to just zip these up and provide them as an attachment or is another method preferred?

**Comment by daveh-lunarg** [comment]
I believe this issue will now be caught by validation, as of PR #1829.  Closing.
