### ISSUE TITLE
Trying to clear stencil aspect of a combined depth/stencil image causes validation error, if image view is lacking VK_IMAGE_ASPECT_STENCIL_BIT bit in aspectMask.

### ISSUE THREAD

**Issue by MarcinKantochAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1377]
Consider an app which creates a combined depth/stencil image. It then creates an image view with only VK_IMAGE_ASPECT_DEPTH_BIT bit set in aspectMask. It is legal to use such image view as a framebuffer attachment.

Chapter 11.5. Image Views states that:

"When an imageView of a depth/stencil image is used as a depth/stencil framebuffer attachment, the aspectMask is ignored and both depth and stencil image subresources are used."

It means that although only VK_IMAGE_ASPECT_DEPTH_BIT bit was set, both depth and stencil image subresources should be used for depth/stencil framebuffer attachment.

Calling vkCmdClearAttachments() to clear the depth/stencil attachment with aspectMask set to VK_IMAGE_ASPECT_DEPTH_BIT |   VK_IMAGE_ASPECT_STENCIL_BIT triggers a validation error:

Error reported by layer [DS] for [Image view]: vkCmdClearAttachments() with aspects not present in image view: VK_IMAGE_ASPECT_STENCIL_BIT.

According to the spec aspectMask in the image view should be ignored. It means that even if image view is lacking VK_IMAGE_ASPECT_STENCIL_BIT bit, it should not be an error to try to clear the stencil aspect of a depth/stencil attachment.

**Comment by mark-lunarg** [comment]
@MarcinKantochAMD, this invalid check was removed in a recent scrub (as part of commit `da2d496fca2a`).  If you continue to see this issue with the Master branch of Vulkan-LoaderAndValidationLayers, or in the next version of the SDK, please reopen this issue.  Thanks!
