### ISSUE TITLE
Validate Spirv decorations

### ISSUE THREAD

**Issue by djdeath** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1378]
Hi,

I just encountered a spirv module which contains a sampler but also adds a location decoration for that sampler.
I don't think it is something that makes sense. The spirv documentation says [1] that location decoration "Only valid for the Input, Output, and UniformConstant Storage Classes."

It would make sense to have some validation on the different kind of decorations there is.
Thanks!

[1] : https://www.khronos.org/registry/spir-v/specs/1.1/SPIRV.html#_a_id_decoration_a_decoration

**Comment by chrisforbes** [comment]
I agree that location decorations on samplers don't make sense, but that sampler is presumably in the UniformConstant storage class, so that rule doesn't help.

**Comment by djdeath** [comment]
If it helps the discussion, here is a simple example of the kind of location decoration on samplers that seems meaningless : 
```
#version 450

layout(location = 0, binding = 0) uniform sampler2D _13;

layout(location = 1) in vec2 _17;
layout(location = 0) in vec4 _26;
layout(location = 0) out vec4 _30;
vec4 _9;
vec4 _20;

void main()
{
    _9 = texture(_13, _17);
    _20 = _9 + _9;
    _20 *= _26;
    _30 = _20;
}
```
