### ISSUE TITLE
Dota2 trace playback doesn't render with Release validation layers

### ISSUE THREAD

**Issue by Tony-LunarG** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1383]
Playing back the Dota2 trace from our trace archive with Release validation layers enabled, almost nothing is rendered.  Playback without validation renders as expected.  Depending on the LVL commit used, random splotches of landscape are sometimes rendered but never a whole frame. Playback with Debug validation layers seems to render as expected, but the slowness of playback make this hard to be sure of.  This is on Windows, I haven't tried Linux. This started happening with commit b06851c3 "layers: Update cmake for safe_struct codegen" and it doesn't happen using the commit previous to that one.  Removing the unique_objects layer made playback work as expected.  It's understood that the Dota2 trace is old and may not reflect current Dota2 Vulkan usage, and that the trace gets validation errors as a matter of course, but it has always rendered with validation layers enabled until the above commit. 
As another data point, I traced today's Dota2 with the end of VulkanTools master and tried to play it back with validation layers and it would not play back with either debug or release layers.  It plays back fine without validation enabled. I didn't do anything to be sure it's the same issue as seen with the old trace.
The old Dota trace is available on lunarg-backup3:~dropbox/Tony/dota2.vktrace

**Comment by mark-lunarg** [comment]
Fix pushed to Master and SDK branches.
