### ISSUE TITLE
Add additional compiler warnings / errors to cmake build

### ISSUE THREAD

**Issue by null77** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1388]
Often I update ANGLE's build of the layers to latest and I find a common warning:

..\third_party\vulkan-validation-layers\src\loader\loader.c(5006): warning C4456: declaration of 'i' hides previous local declaration

Assuming this isn't a desired programming practice (making multiple nested "i" iteration variables) then it would be nice if there was a way to enable this warning in the default Vulkan build, potentially so it could be caught during the submission step by an automated builder. At least it would be useful to know how to control warnings from the cmake files.

Any interest in taking on this work from the maintainers?

**Comment by karl-lunarg** [comment]
CMake sets the MSVC warning level to 3 by default.  W3 doesn't report C4456.

The warning level can be set when generating the project files with CMake by setting CMAKE_C_FLAGS and CMAKE_CXX_FLAGS on the CMake invocation:

`cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_C_FLAGS="/W4"`

(The loader project is a "C" project, while most of the others are "C++".  The above would only affect the "C" projects and you would supply a similar CMAKE_CXX_FLAGS for setting for the rest.)

Also, one can add a warning to a warning level:

`cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_C_FLAGS="/W34456"`

Which would compile with level 3, but add a check for the declaration hiding problem as well.

We can also add compiler options to enable warnings like the ones explained above to the CMakeLists.txt file by appending to the CMAKE_C_FLAGS/CMAKE_CXX_FLAGS variables in the cmake code, or by using the `add_compile_options` or `set_target_properties` cmake commands.

Turning on W4 causes a large number of warnings to be generated besides the hiding warning and it would take a LOT of work to clear them.  Many of these warnings are pretty benign and some may be in files outside our control to change.  The ROI for clearing the W4 warnings is a bit dubious, even considering that we'd like to get to that point.

Are you asking to move to W4 or are you asking to add some specific checks to W3?

How did you end up with compiler options that detected C4456 but didn't get all the spew from W4?

**Comment by null77** [comment]
Karl, to answer your last question, I write my own build scripts for the layers with GN for Chromium/ANGLE (moving away from GYP). We use a different set of warnings.

We use WL4 in ANGLE with a set of warnings disabled, but I think the loader as you said has too many warnings to enable this easily, since it would mean sorting through the spurious and serious warnings. Maybe a good plan is to just enable the specific warning in question (4456) since this seems to pop up, and then add the 'good' warnings to the set of enabled warnings as they pop up?

**Comment by karl-lunarg** [comment]
> Maybe a good plan is to just enable the specific warning in question (4456) since this seems to pop up, and then add the 'good' warnings to the set of enabled warnings as they pop up?

Sure, this seems reasonable.  I'll use `set_target_properties` in the CMakeList.txt file because it offers pretty precise control of what it affects.   Modifying/Appending CMAKE_?_FLAGS strings can be tricky wrt cases where the user overrides them at the command line.  `set_target_properties` is good for appending options.  And finally /W34456 is a good way to enable this one warning.

I know that enabling this warning will expose a couple of places where the code is still triggering this warning, so I'll include fixes for those as well.

**Comment by null77** [comment]
Great, thank you Karl.

**Comment by karl-lunarg** [comment]
Some implementation notes.... (mainly me thinking out loud and recording these details)

* In order for this to be effective, we'll have to turn on "treat warnings as errors", else the CI machines won't notice, and developers are more likely to miss warnings as well.
    * There have been some lingering warnings in the Windows builds that need to be fixed first. 
    * We should probably get some buy-in from the more active developers about this
* In general, we should probably turn on similar settings for builds other than Windows
* It will probably be best to add the compiler options in the LVL subprojects (e.g., loader, demos, layers) rather than the top-level
    * LVL is an upstream repo for LunarG/VulkanTools and LunarG/VulkanSamples and when the downstream updates happen, a top-level setting will suddenly apply to VT and VS subprojects that are not in LVL
    * Careful merging to not pick up the settings in the downstream merge can avoid this
    * We could look at "promoting" the settings to the top level when possible
    * Allows for a more incremental approach for turning this on

**Comment by tobine** [comment]
Android build has always used "treat warnings as errors." I'd be fully in support of enabling that across all builds. I believe we've discussed this in the past and agreed that it should be done but perhaps some lingering windows warnings have prevented it.

**Comment by karl-lunarg** [comment]
I just built LVL with "treat warnings as errors" with VS 2015 Release and Debug and both succeeded.

IIRC, the lingering Windows warning was with VS 2013 Debug builds and had to do with the fast-terminator return optimization (or something like that).

The AppVeyor config asks for a VS 2013 build.  Perhaps the best route is to see if AppVeyor can do VS 2015 builds and let it go at that.  If that's not possible, then figure out a way to turn off those specific warnings.  I know other people have tried to do this, so it may not be straightforward.

We also have other CI servers that may be using VS 2013 that we may need to consider.

**Comment by karl-lunarg** [comment]
Windows builds now have the compiler flag to "treat warnings as errors" turned on (#1413).

Now we can chip away at turning on the declaration hiding warning.

**Comment by null77** [comment]
Thanks very much for pushing this through Karl.
