### ISSUE TITLE
Draw State: "Type mismatch" error incorrectly reported if one of the uniforms is an array

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#139]
Consider the following descriptor set layout:

![image](https://cloud.githubusercontent.com/assets/17761066/13783604/514932b2-eacc-11e5-9d2a-80e37e027c73.png)

We will use this layout alongside the following fragment shader:

![image](https://cloud.githubusercontent.com/assets/17761066/13783732/cce0273c-eacc-11e5-808c-3b1ce383f49f.png)

However, when creating a GFX pipeline with a vkCreateGraphicsPipeline(), the app receives a debug call-back, reporting the following error:

![image](https://cloud.githubusercontent.com/assets/17761066/13783535/20f021f2-eacc-11e5-9a00-83ac148a4a0d.png)

The call-back is wrong, as only a single binding is assigned to all four array items. Perhaps the layer implementation asserts the bindings work just like locations in GL land, where texture_data[0] would get a location 0, texture_data[1] would be assigned 1, and so on? I made that mistake myself once when I was starting to fiddle around with Vulkan. :)

**Comment by tobine** [comment]
I believe this should also have been fixed by #137

**Comment by chrisforbes** [comment]
@DominikWitczakAMD, could you verify that #137 fixed this for you?

**Comment by DominikWitczakAMD** [comment]
Chris: Sure, I'm going to have a look at this tomorrow if you don't mind

**Comment by DominikWitczakAMD** [comment]
No longer reproduces. Thanks!
