### ISSUE TITLE
Incorrect error message from vkCmdBeginRenderPass related to LOAD_OP

### ISSUE THREAD

**Issue by Slagh** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1390]
There appears to be two issues with the message: e.g.
"In vkCmdBeginRenderPass() the VkRenderPassBeginInfo struct has a clearValueCount of 2 but only first 1 entries in pClearValues array are used. The highest index attachment in renderPass 0x5c6f14d230 that uses VK_ATTACHMENT_LOAD_OP_CLEAR is 1 - other pClearValues are ignored."

The first is the highest index attachment that uses LOAD_OP_CLEAR appears to be one higher than the actual value, I suspect because the printf is composed with clear_op_size, and a highest index of 0 necessarily means a size of 1.

The second is the renderPass handle (as above, 0x5c6f14d230) has no resemblance to the created handle as seen from the client code, in my case 0x6b7. I am unsure of the cause. Locally I can see from the callstack that it has passed through:

 	VkLayer_core_validation.dll!00007fff7a41eac0() 	
 	[Frames below may be incorrect and/or missing, no symbols loaded for VkLayer_core_validation.dll]	
 	VkLayer_core_validation.dll!00007fff7a4997ff() 	
 	VkLayer_core_validation.dll!00007fff7a3e0042() 	
 	VkLayer_object_tracker.dll!00007fff8308dffd() 	
 	VkLayer_parameter_validation.dll!00007fff7a214342() 	
 	VkLayer_threading.dll!00007fff9889bb92() 	

so perhaps another layer has messed with it, and/or my layer order is incorrect.

**Comment by mark-lunarg** [comment]
Fixed by PR #1431.  Thanks @Slagh!
