### ISSUE TITLE
Signed/unsigned mismatch warning with VC++ 2017

### ISSUE THREAD

**Issue by randomascii** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1395]
In the FindDependency function, currently at line 10220:

https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/core_validation.cpp#L10220

an int (dependent) is used to call std::find on a std::vector of unsigned int types, leading to "warning C4389: '==': signed/unsigned mismatch" with VC++ 2017. The warning is correct so a cast or some other workaround would seem appropriate.

static bool FindDependency(const int index, const int dependent, const std::vector<DAGNode> &subpass_to_node,
                           std::unordered_set<uint32_t> &processed_nodes) {
    // If we have already checked this node we have not found a dependency path so return false.
    if (processed_nodes.count(index))
        return false;
    processed_nodes.insert(index);
    const DAGNode &node = subpass_to_node[index];
    // Look for a dependency path. If one exists return true else recurse on the previous nodes.
    if (std::find(node.prev.begin(), node.prev.end(), dependent) == node.prev.end()) {

**Comment by randomascii** [comment]
I can't upload a patch to my fork right now for some reason but this works:

    Suppress VC++ 2017 signed/unsigned warning

    When building Chrome with VC++ 2017 there is one warning, from passing
    an int to a call to std::vector<uint32_t>::find. This change adds a cast
    to avoid that warning, thus fixing issue #1395.

diff --git a/layers/core_validation.cpp b/layers/core_validation.cpp
index fd21f01..2d15031 100644
--- a/layers/core_validation.cpp
+++ b/layers/core_validation.cpp
@@ -10217,7 +10217,7 @@ static bool FindDependency(const int index, const int dependent, const std::vect
     processed_nodes.insert(index);
     const DAGNode &node = subpass_to_node[index];
     // Look for a dependency path. If one exists return true else recurse on the previous nodes.
-    if (std::find(node.prev.begin(), node.prev.end(), dependent) == node.prev.end()) {
+    if (std::find(node.prev.begin(), node.prev.end(), static_cast<uint32_t>(dependent)) == node.prev.end()) {
         for (auto elem : node.prev) {
             if (FindDependency(elem, dependent, subpass_to_node, processed_nodes))
                 return true;

**Comment by randomascii** [comment]
Pull request should be good to go.

**Comment by mark-lunarg** [comment]
This issue has been fixed.
