### ISSUE TITLE
older MSVC redist is uninstalled but newer version not actually installed

### ISSUE THREAD

**Issue by jjulianoatnv** [KhronosGroup/Vulkan-LoaderAndValidationLayers#140]
We have having difficulty incorporating the VulkanRT installer into our IHV display driver package in a different manner than how it is currently integrated into our package. We need to move to the newer method. This has the effect of executing the VulkanRT installer later than it was previously executed. And that triggers a bug in the VulkanRT installer. That bug is the topic of this issue.

In the new order, at the time my installer invokes the VulkanRT installer my own installer has already installed a version of the 64-bit MSVC 2013 redist that is an older patch level than MSVC 2013 redist that is included inside the VulkanRT installer. After the VulkanRT installer is done executing no version of the 64-bit MSVC 2013 redist remains. That's the bug: the VulkanRT installer removes the (older patch level) 64-bit MSVC redist, but it does not install a (newer patch level) replacement.

I might be able to work around the problem by updating my own installer to use the same version of the MSVC redist that is used by the VulkanRT installer. I have not tested this yet so I don't know if it will succeed. However, that would not really fix the issue because the versions are bound to diverge again in the future.

Versions installed by 1.0.5.0 VulkanRT are:
* Microsoft Visual C++ 2013 Redistributable (x64) - 12.0.30501
* Microsoft Visual C++ 2013 Redistributable (x86) - 12.0.30501

Steps to reproduce this outside of my installer framework:

0) Uninstall any previous MSVC redist. Uninstall previous VulkanRT version(s).

1) Install an old patch level of 32-bit and 64-bit MSVC redist

2) Install VulkanRT (contains newer patch level of MSVC redist, both 32-bit and 64-bit versions)

3) Observe:

3a) No 64-bit MSVC redist remains in Apps&Features

3b) The 32-bit MSVC redist has been updated to newer patch level

3c) The log inside the VulkanRT installer's window indicates that the 32-bit MSVC redist was updated, but there is no mentoin of the 64-bit MSVC redist.

When performing a non-silent, interactive, install of the VulkanRT, a log is printed in the installer's GUI window. It is this information to which step 3c refers. I don't see this information content written anywhere on disk, and writing it to disk is the topic of #136 . 

In the log is a line which reads:

> Extract: vcredist_x86.exe
> Execute: "C:\Users\jjuliano\AppData\Local\Temp\vcredist_x86.exe" /quie...

I cannot figure out a way to scroll horizontally to see the rest of the line.

There is no mention of vcredist_x64.exe. However if I execute the VulkanRT installer at a time when no version of the MSVC 2013 redist is present, i.e. if I skip step 1, then the following additional lines are present in the log, and the 64-bit redist does get installed.

> Extract: vcredist_x64.exe
> Execute: "C:\Users\jjuliano\AppData\Local\Temp\vcredist_x64.exe" /quie...

**Comment by jjulianoatnv** [comment]
Looking at InstallerRT.nsi, I see that a goto is used to break out of an if/else block. I'm not familiar with this scripting language, and I'm unable to say whether or not that is a valid action to perform. If if/else is itself implemented in terms of "implicit goto" then maybe it's OK. I was unable to find the nsis documentation for the library that imports the if/else constructs into the script.

**Comment by jjulianoatnv** [comment]
David, thanks for giving this quick attention. In our testing, the "release candiate" build of VulkanRT that you shared with me does solve the problem.  We are looking forward to you publishing a new version that includes this change.

**Comment by davidlunarg** [comment]
A release of the Windows Vulkan Runtime addressing this issue is now available. Window Vulkan Runtime 1.0.5.1 can be downloaded from Issue #443 on LunarXchange (htts://vulkan.lunarg.com).
