### ISSUE TITLE
Performance warning: VK_PIPELINE_STAGE_ALL_COMMANDS_BIT or VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT

### ISSUE THREAD

**Issue by TobiasHector** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1401]
Generally speaking, using one of these bits in a stage mask (queue submits, events, pipeline barriers) is done as a shorthand for the actual synchronization required - usually used during development until they are refactored to allow more overlap.

It would be useful to add a performance warning to the tools that can detect this usage and suggest alternatives (or at least ask a user to look at it).

In theory, if the validation layers detect missing dependencies, that code can be re-used in some way to suggest the minimum set of dependencies required.

**Comment by mark-lunarg** [comment]
This issue is now tracked via issue #1612.

**Comment by mark-lunarg** [comment]
This check is now available in the Assistant Layer, hosted in the [Github VulkanTools repository](https://github.com/LunarG/VulkanTools), and soon to be available in the Vulkan SDK.
