### ISSUE TITLE
Performance warning: Detect over-synchronization

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1407]
Suggested by @TobiasHector and could be implemented in a layer similar to one suggested in #1155.

Implement, probably in a performance tuning layer, checks for cases where applications are choosing synchronization mechanisms that are too heavyweight for the task and/or cause waits for too long of a time.  The intent is to help developers remove unneeded serialization in their applications.

**Comment by TobiasHector** [comment]
Note that #1401 covers one of the simplest cases - but certainly there are other more complex cases. Ideally the layer could try to figure out the minimum set of synchronization required and recommend that, I think such a thing would be hugely powerful. This probably will need splitting into a heck of a lot of sub tasks, at least for the different synchronization primitives.

Couple of things that we've agreed in the past which could help guide this:
 * Synchronization within render passes using subpass dependencies is the most optimal type of synchronization.
 * Pipeline Barriers are most efficient when there's no work that can be done between two tasks that need synchronizing.
 * Set/WaitEvents are most efficient when there IS work that can be done between two tasks that need synchronizing.
 * Semaphores are big hammers, developers sticking semaphores arbitrarily between command buffers that they've submitted is bad, ideally the layer should detect this type of over-synchronization and recommend one of the finer grained sync primitives for a single queue, if practical.

**Comment by mark-lunarg** [comment]
This issue is now tracked via issue #1612.
