### ISSUE TITLE
Validation layer does not check image alignment

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1412]
vkBindImageMemory can fail when memoryOffset is not suitably aligned according to memory requirements for the image. Validation layer, however, does not catch that - specifically, on AMD drivers vkBindImageMemory would fail with VK_ERROR_INITIALIZATION_FAILED.

The spec does not mention that it's valid for this function to return this error so I'm guessing this driver handling is optional. It would be nice for the validation layer to catch this and report the misaligned offset and required alignment.

**Comment by jeremy-lunarg** [comment]
I believe @cdwfs added this in #1495. Feel free to reopen if I'm wrong.
