### ISSUE TITLE
Unique objects layer reports an error when shader subgroup ballot/vote extensions are enabled

### ISSUE THREAD

**Issue by ArtVandelae** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1417]
When creating a device with the VK_EXT_shader_subgroup_ballot and/or VK_EXT_shader_subgroup_vote extensions enabled the unique objects layer reports an error stating that these extensions are unsupported by it.  Given that these are strictly shader capability extensions, there isn't anything that the unique objects layer can do with them so they should be whitelisted like the AMD shader ballot extension.

**Comment by pdaniell-nv** [comment]
Was this with the latest 1.0.39.0 SDK?

**Comment by ArtVandelae** [comment]
Yes.  Looking at layers/unique_objects.h/cpp it seems that all enabled extensions must be whitelisted or an error will be emitted regardless of whether or not they are relevant to the layer.

**Comment by mark-lunarg** [comment]
This was missed in the 1.0.39 SDK madness.  It has already been added (along with all other official extensions) in Master and an interim release is in testing and will show up soon.
