### ISSUE TITLE
VkBufferImageCopy::bufferOffset don't have to be a multiple of the format’s element size, if VkImage format is combined depth/stencil

### ISSUE THREAD

**Issue by MarcinKantochAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1418]
According to the Vulkan spec:

"If the the calling command’s VkImage parameter’s format is not a depth/stencil format, then VkBufferImageCopy::bufferOffset must be a multiple of the format’s element size"

Currently the image validation layer is checking unconditionally if VkBufferImageCopy::bufferOffset is a multiple of the format’s element size and reporting error otherwise. This check should only be performed if VkImage parameter’s format is not combined depth/stencil.

**Comment by MarcinKantochAMD** [comment]
Created pull request: https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/1419

**Comment by mark-lunarg** [comment]
Fixed by this PR.  Thanks agian.
