### ISSUE TITLE
vkCreateDescriptorPool fails if VkDebugReportCallbackExt with information flag bit set is attached

### ISSUE THREAD

**Issue by discosultan** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1420]
I'm having an issue where the command `vkCreateDescriptorPool` fails with **error code -1000011001** (`VK_ERROR_VALIDATION_FAILED_EXT`) **only if** I've created a `VkDebugReportCallbackExt` on the `VkInstance` with `VK_DEBUG_REPORT_INFORMATION_BIT_EXT` flag set.

There are no errors/warnings raised by the LunarG standard validation layers. I'm running on 1.0.39 runtime libraries. I'm also accessing the API through custom bindings, meaning that there is chance that a bug is there instead.

**Comment by mark-lunarg** [comment]
@discosultan, tried this here (using the cube demo) and cannot reproduce.  My guess is that you are returning TRUE from your callback which you should only do if you do NOT want to make the API call.  Typically, you'd return TRUE for an ERROR and FALSE for warnings, info, etc.  

If this is not the case and you can set this up in a debugger, I'd suggest breaking at the log_msg call in CreateDescriptorPool and seeing what specifically is causing the failure.  Thanks!

**Comment by discosultan** [comment]
@mark-lunarg Aha, I've been misunderstanding the purpose of the return value for debug callback. I do indeed return TRUE in all the cases atm.

Thanks for clearing this up!
