### ISSUE TITLE
Error message at PSO create time instead of runtime

### ISSUE THREAD

**Issue by dankbaker** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1424]
I got the message:
Render pass subpass 0 mismatch with blending state defined and blend state attachment count 1 while subpass color attachment count 0 in Pipeline (0x7f81)!

Which took me a while to figure out because the mistmach is between the renderpass and the color attachment on the blendstate, which are both known at PSO creation time, but it looks like there is no matching here, instead it matches the bound renderpass against the color attachment count at runtime. It would be far easier to debug if a check happened at creation time.

**Comment by tobine** [comment]
This is VALIDATION_ERROR_02109. I'll move the check to CreateGraphicsPipelines() time as Dan suggests.
