### ISSUE TITLE
Error message: PSO with VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST when patchControlPoints = 0

### ISSUE THREAD

**Issue by ParticlePeter** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1425]
LunarG SDK 1.0.39.1. In my test I use one `PSO` with `VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST` and `patchControlPoints` set to 0. No error message when I set `patchControlPoints` to 1 with the same triangle list input assembly. Please note the different input assemblies.

`Invalid Pipeline CreateInfo State: VK_PRIMITIVE_TOPOLOGY_PATCH_LIST primitive topology used with patchControlPoints value 0. patchControlPoints should be >0 and <=32. For more information refer to Vulkan Spec Section '21.7. Tessellation Pipeline State' which states 'patchControlPoints must be greater than zero and less than or equal to VkPhysicalDeviceLimits::maxTessellationPatchSize' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/xhtml/vkspec.html#VkPipelineTessellationStateCreateInfo)`

My mistake is that I do attach a default  `VkPipelineTessellationStateCreateInfo` with `patchControlPoints=0` to my `PSO` even if no tessellation is used. Per spec the `PSO::pTessellationState` should be `NULL` if no tessellation is used. However, the error message is misleading. I suggest to additionally check if the `inputAssembly` is compatible if `PSO::pTessellationState` is not `NULL`

**Comment by mark-lunarg** [comment]
This issue has been resolved.
