### ISSUE TITLE
CMAKE_SOURCE_DIR vs. CMAKE_CURRENT_SOURCE_DIR

### ISSUE THREAD

**Issue by Delwin9999** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1428]
the top level CMakeLists.txt line 43 is setting the scripts directory based on CMAKE_SOURCE_DIR.  This will cause failure to find the scripts if this project is included as a subproject of another.

Using CMAKE_CURRENT_SOURCE_DIR instead fixes this issue.

Unfortunately I can't make pull requests from here or I'd throw one.

**Comment by mark-lunarg** [comment]
Fix pushed to Master -- Thanks @Delwin9999.

commit 3e0a252daa55dc92df88aadf1507df9b382633a8
Author: Mark Lobodzinski <mark@lunarg.com>
Date:   Tue Jan 31 07:35:19 2017 -0700

    cmake: GH1428, Reenable subproject builds

    SCRIPTS dir was defined using CMAKE_SOURCE_DIR which prevented LVL
    from building correctly if used as a subproject. Changed to use
    CMAKE_CURRENT_SOURCE_DIR.

    Change-Id: I201fcfde78b65df80c3c74373a26e4d518770806
