### ISSUE TITLE
Confusing messages when command buffer is in CB_INVALID state

### ISSUE THREAD

**Issue by Novum** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1478]
In case a CB gets invalidated the validation layer will complain about 
    "You must call vkBeginCommandBuffer() before this call to %s"

This is really confusing. It should say "the command buffer was invalidated" or something similar. I spent quite some time trying to figure out why the CB was not started before realizing this.

**Comment by mark-lunarg** [comment]
Fixed in PR #1479.
