### ISSUE TITLE
PreCallValidateCmdClearAttachments - validating clear rectangles against unset render area, if vkCmdClearAttachments was recorded to a secondary command buffer

### ISSUE THREAD

**Issue by MarcinKantochAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1489]
The PreCallValidateCmdClearAttachments does the following check:

if(cb_node->activeRenderPass) 
{
   for (uint32_t j = 0; j < rectCount; j++)  
   {
      if (false == ContainsRect(cb_node->activeRenderPassBeginInfo.renderArea, pRects[j].rect)) { // code }
   }
}

The check is only valid if both activeRenderPass and activeRenderPassBeginInfo are set. If vkCmdClearAttachments is recorded to a secondary command buffer, vkCmdBeginRenderPass has not been called yet, therefore activeRenderPassBeginInfo is not set. On the other hand activeRenderPass is set as it is taken from VkCommandBufferBeginInfo::pInheritanceInfo::renderPass. It causes a situation in which the clear rectangles are compared against a zero render area, which triggers a validation error.

**Comment by mark-lunarg** [comment]
Created issue #1501 to track the missing validation.

**Comment by mark-lunarg** [comment]
Fixed by PR#1500.
