### ISSUE TITLE
VkWriteDescriptorSet: descriptorCount == 0

### ISSUE THREAD

**Issue by martty** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1506]
The spec in '13.2.4. Descriptor Set Updates' explicitly allows descriptorCount == 0:

> If a binding has a descriptorCount of zero, it is skipped. This behavior applies recursively, with the update affecting consecutive bindings as needed to update all descriptorCount descriptors. All consecutive bindings updated via a single VkWriteDescriptorSet structure, except those with a descriptorCount of zero, must have identical descriptorType and stageFlags, and must all either use immutable samplers or must all not use immutable samplers.

But currently this is a validation error. I agree that this might be suspicious, but shouldn't this be a warning instead?

**Comment by tobine** [comment]
@martty Can you tell me which version of validation you're using and what is the exact error you're seeing? Note that there are different "descriptorCount" values. The "descriptorCount" that is a member of the VkWriteDescriptorSet struct is must be greater than 0 according to the spec. See the Implicit Valid Usage for that struct [here](https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkWriteDescriptorSet).
I agree that a binding with a descriptorCount of 0 should be allowed, but I don't know of validation code that currently flags an empty binding as an error.

**Comment by martty** [comment]
Oops, I did indeed misread the spec, confusing the two descriptorCounts. Sorry about that!
