### ISSUE TITLE
Threading layer does not account for null pointer in GetSwapchainImages

### ISSUE THREAD

**Issue by Tony-LunarG** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1513]
vkGetSwapchainImagesKHR should first be called with a NULL pSwapchainImages to retrieve the number of images that will be returned in a subsequent call when pSwapchainImages is not NULL.  The threading layer will dereference pSwapchainImages unconditionally if pSwapchainImageCount is positive, which it will be after the call to the driver

**Comment by stroyan** [comment]
This parameter is very like the pPipelines parameter from vkCreateGraphicsPipelines and vkCreateComputePipelines.  They are rare cases of returned handles that are passed back in an array.

These parameters do not need to be counted with startReadObject and finishReadObject.
They don't even have well defined values before returning from the wrapped create call.
Almost all of the returned handles from create calls are returned through non-array pointer parameters.
That type of parameter is treated as a special case in threading_generator.py and not passed to *ReadObject.
There is an extra-special case for parameters named pPipelines that was the only array returning handles.

vkGetSwapchainImagesKHR can be handled by one of two approaches.
Either add of "pSwapchainImages" to a list of special parameter names at line 208 of threading_generator.py, or add vkGetSwapchainImagesKHR to special_functions at line 367 and move the code for it into layers/threading.cpp.

A special case for the parameter name is a smaller change.  But it may go wrong in the future if a new function is defined with a "pSwapchainImages" parameter which is an input instead just an output.

**Comment by stroyan** [comment]
There are examples of the "special_functions" approach in vkAllocateCommandBuffers and vkAllocateDescriptorSets.  Those are implemented in layers/threading.cpp because they have complicated handling of implicit locking dependency tracking to their related pools.

**Comment by mark-lunarg** [comment]
Fixed by
commit a00917b8295326a0c0501aefe5ab4c12a501a4c5
Author: Mark Lobodzinski <mark@lunarg.com>
Date:   Tue Feb 28 15:09:31 2017 -0700

    layers: Special-case threading GetSwapchainImages

    This API is a special-case for the code-gen in that it sometimes
    returns an array of images. These do not need to be counted by
    start/finishReadObject and so were moved into the non-generated
    part of the layer source.

    Change-Id: Iaaab9143abadbf025b5f3c118aa26dae3c6f1bec
