### ISSUE TITLE
Layer freezes during vkCmdBeginRenderPass

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1522]
On Windows 10 my app freezes inside `core_validation` layer while calling `vkCmdBeginRenderPass`.

The full code is here (I use VS2015 to compile):
https://github.com/krOoze/Hello_Triangle/tree/f787f50daee923a8ce7f87944bc89329a92984fc

The specific line:
https://github.com/krOoze/Hello_Triangle/blob/f787f50daee923a8ce7f87944bc89329a92984fc/HelloTriangle.cpp#L1509

It is called in response to a first swapchain (re)creation event, which needs (re)building the cmdbuffer.

The app works well with layers disabled, as well as worked well before SDK 1.0.42.

(I could use help on how to debug layers themselves. I tried setting `VK_LAYER_PATH` to the debugging versions of the layers in LunarG SDK, but the loader prints errors that it cannot load them.)

**Comment by krOoze** [comment]
I managed to debug the layers (something wrong with the SDK provided debug ones &mdash; had to compile my own).

The issue is actually tied to #1523.
On `vkCmdBeginRenderPass` the layers call `VerifyFramebufferAndRenderPassLayouts` which freezes trying to iterate 0xFFFFFFFF subrange levels and layers (while the real count should be 1).
And indeed replacing all `VK_REMAINING_*` with 1s in my app works around the issue.

**Comment by mark-lunarg** [comment]
Thanks Petr!  I'm closing these guys, just reopen if that's the wrong thing to do.
