### ISSUE TITLE
Layer complains about framebuffer mipmap count with VK_REMAINING_MIP_LEVELS

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1523]
If I use `VK_REMAINING_MIP_LEVELS` in `VkImageViewCreateInfo` during creation of `VkImageView`s from swapchain `VkImage`s (which are guaranteed to have exactly 1 miplevel) and then use it in `VkFramebufferCreateInfo` then the layers complain that framebuffer has to have only one miplevel:

`ERROR: unknown0: 411, DS, vkCreateFramebuffer(): VkFramebufferCreateInfo attachment #0 has mip levelCount of 4294967295 but only a single mip level (levelCount ==  1) is allowed when creating a Framebuffer. For more information refer to Vulkan Spec Section '7.3. Framebuffers' which states 'Any given element of pAttachments must only specify a single mip level' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/xhtml/vkspec.html#VkFramebufferCreateInfo)`

**Comment by mark-lunarg** [comment]
Sweet!
