### ISSUE TITLE
Layer reports error: vkCmdClearColorImage with image from vkAcquireNextImageKHR

### ISSUE THREAD

**Issue by MOARdV** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1524]
The error string reported is 

```
vkCmdClearColorImage called with image created without VK_IMAGE_USAGE_TRANSFER_DST_BIT.. For more information refer to Vulkan Spec Section '17.1. Clearing Images Outside A Render Pass Instance' which states 'image must have been created with VK_IMAGE_USAGE_TRANSFER_DST_BIT usage flag' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/xhtml/vkspec.html#vkCmdClearColorImage)
```

The image (acquired using vkAcquireNextImageKHR) is still cleared.  I'm not sure if this is a validation layer issue or a driver issue (I don't know how to determine which it is):

NVIDIA driver 378.66.0, reported Vulkan version: 1.0.37, SDK version 1.0.42.  I do not recall seeing this message with SDK 1.0.39.1.

**Comment by mark-lunarg** [comment]
This may be a new validation check.  In order to correctly use CmdClearColorImage, the image must have been created with the VK_IMAGE_USAGE_TRANSER_DST_BIT.  What are the usage flags used when the swapchain was created?

**Comment by MOARdV** [comment]
Arg!  Stupid coder error.  I didn't have the bit set, and I even left myself a comment "should I set other bits"?  With the bit set, the error disappears.  Sorry about that.
