### ISSUE TITLE
Add layer check for vkUpdateDescriptorSets updating VK_DESCRIPTOR_TYPE_STORAGE_IMAGE with layout VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL.

### ISSUE THREAD

**Issue by scyganINTEL** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1526]
This is a spin-off from bug #760 

Layers do not warn, when vkUpdateDescriptorSets try to update descriptor of type VK_DESCRIPTOR_TYPE_STORAGE_IMAGE with layout VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL. (only GENERIC is allowed for image load store).

Spec language "Load and store operations on storage images can only be done on images in VK_IMAGE_LAYOUT_GENERAL layout."

**Comment by tobine** [comment]
I think the correct action here is to trigger a validation error at QueueSubmit time is a STORAGE_IMAGE descriptor is not in GENERIC layout. I believe at update time, the layout is not an immediate issue, as it could be transitioned prior to the actual use of the descriptor.

This is potentially a subset of #1476 but I'll keep both open until I at least have a better plan to get these checks in.

**Comment by tobine** [comment]
@chrisforbes any thoughts on this guy? I'm looking at it again and my current thinking is that we should warn on any vkUpdateDescriptorSets() to a STORAGE_IMAGE descriptor that doesn't use LAYOUT_GENERAL.

Then at draw time we should throw error on any active STORAGE_IMAGE descriptor that's not in LAYOUT_GENERAL.

Agree?

There's a potential usage case where a STORAGE_IMAGE descriptor is used in a non-GENERAL layout but has no load or store operations performed on it... Usage masks could verify this, but that seems like an uninteresting/unrealistic case though and not something to be too concerned about.

**Comment by chrisforbes** [comment]
@tobine "used" then is just size/samples/etc queries in the shader? I think that's narrow enough that you'd get away with leaving that hole until we are tracking the types of operations performed on each descriptor properly.

For the early check, do we mean the layout in the VkDescriptorImageInfo structure, or the actual layout of the image?

**Comment by chrisforbes** [comment]
(I'm not convinced it's a good idea to warn on image actual layout being wrong at the time of vkUpdateDescriptorSets; however I think VkDescriptorImageInfo::imageLayout != VK_IMAGE_LAYOUT_GENERAL for a storage image descriptor is pretty much guaranteed nonsense)

**Comment by chrisforbes** [comment]
@tobine we could possibly get a spec change to close the used-in-queries-only loophole?

**Comment by tobine** [comment]
@chrisforbes for the early check I was refering to the imageLayout given in the VkDescriptorImageInfo struct at update time. That's the layout that the image should be in at the time that it's used.

**Comment by tobine** [comment]
Looking at this further it should now be handled. Note that there was already a [check](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/descriptor_sets.cpp#L909) to make sure that UpdateDescriptorSets() on a STORAGE_IMAGE use LAYOUT_GENERAL.
When you combine this with the recently added [check](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/descriptor_sets.cpp#L518) to make sure that draw-time layout matched actual layout, there is now no way to use a STORAGE_IMAGE in a layout other than GENERAL without hitting a validation error.

I'll file a spec change to add VU language on the first check referenced above and may make some changes to how these checks are handled depending on what the workgroup says.
