### ISSUE TITLE
Android build from Ubuntu 14.04 fails with "LOCAL_SRC_FILES points to a missing file libshaderc.a"

### ISSUE THREAD

**Issue by cirosantilli** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1532]
Tried following the steps, then at `ndk-build` it breaks with:

```
Android NDK: ERROR:jni/Android.mk:shaderc-prebuilt: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that [...]/Vulkan-LoaderAndValidationLayers/build-android/jni/../..//build-android/external/shaderc/android_test/obj/local/armeabi-v7a/libshaderc.a exists  or that its path is correct   
[...]/android-sdk/ndk-bundle/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
```

Windows build appears to build from source at `build-android/update_external_sources_android.bat`, but couldn't find the Linux analogue.

**Comment by tobine** [comment]
Did you explicitly run `./update_external_sources_android.sh` from the build-android dir?
I use Ubuntu 14.04 and just pulled a fresh repo and was able to build with latest master. Three commands I ran from android-build dir:
`./update_external_sources_android.sh
./android-generate.sh
ndk-build -j16`

**Comment by cirosantilli** [comment]
@tobine hmmm, ah, run `./update_external_sources_android.sh` again, and the problem is     

    cores=$(ncpu || echo 4)

and I had a crazy command for `ncpu` in path.

Any reason to not use `nproc` instead, which is in coreutils, which is installed by default on Ubuntu 14.04, unlike `nproc` from the mdm package, which is not? See: http://releases.ubuntu.com/14.04/ubuntu-14.04.5-desktop-amd64.manifest for the default installed package list.

**Comment by tobine** [comment]
@cirosantilli No reason to not use `nproc`. Feel free to submit a patch to update the script.
