### ISSUE TITLE
Check needed for linear filtering support

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1537]
Came up in
http://stackoverflow.com/questions/42641966/vk-format-r16-uint-texture-format-in-vulkan

Need to check that linear filtering is available for a format used by a sampler.   Probably need to see if similar checks are needed for the other format features.

**Comment by mark-lunarg** [comment]
This check is now present in buffer_validation.cpp in the core_validation layer.
