### ISSUE TITLE
Fails to build with musl libc

### ISSUE THREAD

**Issue by jku** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1538]
`| ../loader/libvulkan.so.1.0.39: undefined reference to '__secure_getenv'`

musl libc does not provide secure_getenv() or __secure_getenv() so linking the loader fails.

Would you accept a patch that uses getenv() instead in this case?

**Comment by MarkY-LunarG** [comment]
I've pushed commit f7a2742355bb67cd3f2d7a7e3dce36f7249f8bd5 up.  Can you verify if that fixes the issue for you?

**Comment by jku** [comment]
I've made a PR on top of current master: the current code mistakenly checks for __GNUC__ when the original author probably wanted __GLIBC__. My fix doesn't do that either though as checking for features is just better.

My musl build is not running master but I verified a backported version: works with musl and modern glibc.

**Comment by MarkY-LunarG** [comment]
This should now be fixed, so closing issue.
