### ISSUE TITLE
Support negative viewport height if VK_KHR_maintenace1 is enabled

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1540]
Currently in master parameter_validation.cpp, there is this check in preCmdSetViewport:

           if (my_data->enables.amd_negative_viewport_height && (viewport.height < 0)) {
                // VALIDATION_ERROR_01790
                invalid_height = false;
            }

VK_KHR_maintenance1 allows negative viewport height:

"Allow negative height to be specified in the slink::VkViewport::height field to perform y-inversion of the clip-space to framebuffer-space transform. This allows apps to avoid having to use gl_Position.y = -gl_Position.y in shaders also targeting other APIs."

I think the check in preCmdSetViewport should be amended to check whether VK_KHR_maintenace1 is enabled to allow negative viewport heights.

**Comment by phaulos** [comment]
This can be tested with dEQP-VK.draw.negative_viewport_height.* tests that currently trigger validation errors due to lack of support for VK_KHR_maintenance1

**Comment by mark-lunarg** [comment]
Adding Maintenance1 support will also fix #1547.

**Comment by mark-lunarg** [comment]
Fixed by PR #1574.
