### ISSUE TITLE
Support VK_KHR_shader_draw_parameters

### ISSUE THREAD

**Issue by phaulos** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1541]
dEQP-VK.draw.shader_draw_parameters.* tests in CTS are failing validation, most likely due to lack of support for VK_KHR_shader_draw_parameters.

```
ERROR: Shader declares capability 4427, not supported in Vulkan. (code 0x00000010 from SC at Unknown:2518)
```

**Comment by chrisforbes** [comment]
@karl-lunarg do you want this bug, or shall I deal with it? Will likely be 1-2d before I can get to it.

**Comment by karl-lunarg** [comment]
@chrisforbes My plan is to look at it today.   I think that the fix is just to add a missing member to an enum type.  (I had thought I made a similar fix for a similar problem.)   If I don't get to it or it turns out that you're the better person to fix, I'll hand it over to you.  Thanks!

**Comment by karl-lunarg** [comment]
Chris is fixing this via #1553

**Comment by mark-lunarg** [comment]
Pushed @chrisforbes fix.
