### ISSUE TITLE
VK_KHR_maintenance1: copies between 2D and 3D images

### ISSUE THREAD

**Issue by phaulos** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1547]
CTS tests under `dEQP-VK.api.copy_and_blit.image_to_image.3d_images` are failing with validation errors. It appears that validation layers do not take into account that VK_KHR_maintenance1 allows copies between 2D array image slices and 3D images.

**Comment by mark-lunarg** [comment]
This should be addressed by #1617.
