### ISSUE TITLE
swapchain unable to validate if extensions are enabled

### ISSUE THREAD

**Issue by courtney-g** [KhronosGroup/Vulkan-LoaderAndValidationLayers#155]
The swapchain layer cannot validate that the extension is being called without enabling the extension.
The layer will only return function pointers if the extension is enabled but it's inside those functions that we check that the function isn't being called without enabling the layer. Need to always hook these functions to allow those checks to catch invalid use.

**Comment by ianelliottus** [comment]
I cherry-picked and pushed change !156 that fixes this.
