### ISSUE TITLE
Confusing mix between decimal and hex in validation error message

### ISSUE THREAD

**Issue by hrydgard** [KhronosGroup/Vulkan-LoaderAndValidationLayers#157]
Here's an example:

ERROR: [DS] DescriptorSet Code 62 : VkDescriptorSet (0xe5e5370) bound as set #0 has dynamic offset 1048576. Combined with offet 0 and range 0x40 from its update, this oversteps its buffer (0xab0ab30) which has a size of 0x100000.

The dynamic offset is in decimal while the size is hex, making a quick mental comparison hard.

**Comment by hrydgard** [comment]
Also the second instance of "offset" is misspelled as "offet" :)

**Comment by tobine** [comment]
Submitted #158 to fix the offset error messages so they consistently use HEX as well as fixing typos.

**Comment by tobine** [comment]
Fix pushed to master
