### ISSUE TITLE
cube: Swap chain alpha compositing mode selection instead of fixed mode

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1570]
The cube demo always assumes VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR for the swap chain's alpha compositing mode ([see here](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/85d81f43efa200d9d907a020e34c1ad0efabcc7a/demos/cube.c#L965)), which may not be supported by all devices. 

This will trigger the following alidation layer error:

	ERROR: [DS] Code 2340 : vkCreateSwapChainKHR() called with a non-supported pCreateInfo->compositeAlpha (i.e. VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR).  Supported values are:
		 VK_COMPOSITE_ALPHA_INHERIT_BIT_KHR
	. For more information refer to Vulkan Spec Section '30.6. WSI Swapchain' which states 'compositeAlpha must be one of the bits present in the supportedCompositeAlpha member of the VkSurfaceCapabilitiesKHR structure 
	returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR for the surface' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/xhtml/vkspec.html#VkSwapchainCreateInfoKHR)

Just noticed this while getting my examples run on a certain mobile devices. For simplicity I changed my swap chain code to simple select the first alpha compositing mode that's available (see [this commit](https://github.com/SaschaWillems/Vulkan/commit/5443c01f079025eedfc4827197bae1ffa3bfe239)).

**Comment by Tony-LunarG** [comment]
Addressed in  6c86e3c - thanks!
