### ISSUE TITLE
vkCreateFramebuffer triggers error on single-mip image with VK_REMAINING_MIP_LEVELS view

### ISSUE THREAD

**Issue by Themaister** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1571]
Framebuffer attachments which have a single mip-level image and an image view created with VK_REMAINING_MIP_LEVELS triggers validation (4 billion mip levels), this seems a bit wrong.

**Comment by krOoze** [comment]
Hmm, I thought I fixed that with #1564.
Are you using the regular SDK or master from this repo?

**Comment by Tony-LunarG** [comment]
I agree that krOoze's commit fixed this issue.  I changed the cube demo to specify VK_REMAINING_MIP_LEVELS when creating image views for the framebuffers and before the referenced commit I get the validation errors you mention, but after the referenced commit, I don't.  Closing but feel free to re-open if I missed something.
