### ISSUE TITLE
unique layer not unwrapping objects

### ISSUE THREAD

**Issue by RCalocaO** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1592]
Win7 SDK 1.0.42.1, using RenderDoc and trying to debug a UE4 app (which enables the RenderDoc capture) I get a crash; after talking to Baldur sounds like "there's no debug marker entry points in unique_objects*.*, so I think the bug is just that they're wrapping the image at creation time, but not intercepting this entry point to unwrap the struct."

 	nvoglv64.dll!0000000069ea8d59()	Unknown
 	nvoglv64.dll!0000000069e9f6b1()	Unknown
 	VkLayer_object_tracker.dll!000007feb686c5b3()	Unknown
 	VkLayer_parameter_validation.dll!000007feb6635bc6()	Unknown
>	renderdoc.dll!WrappedVulkan::vkDebugMarkerSetObjectNameEXT(device, pNameInfo) Line 1132	C++
 	renderdoc.dll!hooked_vkDebugMarkerSetObjectNameEXT(device, pNameInfo) Line 157	C++
 	UE4Editor-VulkanRHI-Win64-Debug.dll!FVulkanDynamicRHI::RHIBindDebugLabelName(TextureRHI, Name) Line 1570	C++

RenderDoc code, while calling the extension:
if(ObjDisp(device)->DebugMarkerSetObjectNameEXT)
  ObjDisp(device)->DebugMarkerSetObjectNameEXT(device, &unwrapped);
From the disasm in the crash at the driver side:
0000000069EA8D59 4C 8B 41 38          mov         r8,qword ptr [rcx+38h]  
rcx is 331, which is the unique object:
-		&unwrapped	0x0000000000561f08 {sType=VK_STRUCTURE_TYPE_DEBUG_MARKER_OBJECT_NAME_INFO_EXT (1000022000) pNext=0x0000000000000000 ...}	VkDebugMarkerObjectNameInfoEXT *
		sType	VK_STRUCTURE_TYPE_DEBUG_MARKER_OBJECT_NAME_INFO_EXT (1000022000)	VkStructureType
		pNext	0x0000000000000000	const void *
		objectType	VK_DEBUG_REPORT_OBJECT_TYPE_IMAGE_EXT (10)	VkDebugReportObjectTypeEXT
		object	331	unsigned __int64
+		pObjectName	0x0000000000562210 "T_Default_Material_Grid_M"	const char *

**Comment by mark-lunarg** [comment]
@RCalocaO , @baldurk , can y'all see if this ( #1595  ) helps with the failures and let me know?  Thanks!

**Comment by mark-lunarg** [comment]
Hey Guys, went ahead an pushed the changes.  If it doesn't work for you please reopen this issue or create another one.
