### ISSUE TITLE
Should be OK for fragment program to not write when VK_ATTACHMENT_STORE_OP_DONT_CARE

### ISSUE THREAD

**Issue by schwa423** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1597]
I have a depth-only pass where the color attachment uses VK_ATTACHMENT_STORE_OP_DONT_CARE (and, probably not relevantly) VK_ATTACHMENT_LOAD_OP_DONT_CARE.

I noticed that the depth pass was not significantly faster than a subsequent pass that wrote to the color attachment, and after some experimentation found that I could speed it up by changing my fragment shader to not write a color value.  In other words, I replaced:
```GLSL
  layout(location = 0) out vec4 outColor;
  void main() {
    outColor = vec4(1.f, 1.f, 1.f, 1.f);
  }
``` 
... with:
```GLSL
  void main() {}
```

This resulted in the desired performance improvement (on the Mesa 13.0 Intel Vulkan driver, not that it matters).  However, the core validation layer complains with the error "Attachment 0 not written by fragment shader".

I looked in the 1.0.43 spec, and couldn't find the reason for this validation failure (in fact, I didn't see any language in sections 8.9 or 9.2 that requires the fragment shader to write to an attachment, regardless of the store-op specified by the render-pass).  As a result, I'm not sure if this is a validation bug, a spec bug, or whether my program is actually non-compliant with the intended interpretation of the spec.

If this validation error matches some wording in the spec, I suppose I have two choices:

1) file a performance bug against Mesa, reasoning that vkCreateGraphicsPipeline() should notice the VK_ATTACHMENT_STORE_OP_DONT_CARE and avoid writing to the attachment even though the fragment shader produces an output value.

2) file a bug against the spec, reasoning that a fragment shader shouldn't be required to write to an attachment with VK_ATTACHMENT_STORE_OP_DONT_CARE

**Comment by mark-lunarg** [comment]
@chrisforbes, should this be a warning instead of an error?

**Comment by schwa423** [comment]
(until someone points out where the spec prohibits fragment shaders that don't write a value, I'll assume that it is legal not to)

This should not even be a warning, I believe, since it warns against perfectly reasonable usage scenarios. I mentioned one in the original bug report, where I improved performance by not wastefully writing an unused value to the color attachment.

Another scenario is using the stencil buffer to implement clipping in a 2D renderer: it may be useful to update the stencil buffer without touching the color attachment.  This second scenario doesn't assume VK_ATTACHMENT_STORE_OP_DONT_CARE, so maybe this bug should be renamed to "Should be OK for fragment program to not write to color attachment".

**Comment by chrisforbes** [comment]
If you're doing a depth-only pass, why does the subpass include the color attachment at all?

Shouldn't interpret what you're doing as "not writing to color attachment" -- it's really "may write undefined junk to color attachment".

**Comment by schwa423** [comment]
I think you're right about the behavior being undefined.  As you see above, I just filed an issue against the spec, using the stencil-clipping scenario to focus the discussion. 

Re: why use a color attachment with a depth-only pass, let's just say "historical reasons"; the full answer is irrelevant.

**Comment by mark-lunarg** [comment]
@schwa423, if you're OK with it, we'd prefer to close this until the spec issue is resolved and we have a clear direction on what the layers should complain about, but I will leave it up to you.

**Comment by schwa423** [comment]
Sure, that's fine.  Thanks for helping to refine my understanding of this issue!

**Comment by chrisforbes** [comment]
@mark-lunarg would be good to get all the interface matching stuff nailed down a bit more -- we define what matches are, but not the scope of the misbehavior if a mismatch exists.

I don't have the spare cycles to drive the spec side.
