### ISSUE TITLE
SC layer: GS output to FS input not taken into account (refs VS instead)

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1600]
I'm currently working on a viewport array example ([source](https://github.com/SaschaWillems/Vulkan/tree/master/viewportarray), [shaders](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/viewportarray)) that uses a geometry shader with multiple invocations to output geometry to multiple view ports in a single pass and noticed validation error messages from SC about FS shader input locations not being written by the VS:

	ERROR: [SC] Code 3 : fragment shader consumes input location 2.0 which is not written by vertex shader
	ERROR: [SC] Code 3 : fragment shader consumes input location 3.0 which is not written by vertex shader

While true to the wording (as the outputs are not written by the VS) I'd say this is technically wrong as those outputs are written, but by the geometry shader instead.

These are the interfaces for in- and outputs of the shaders used in the pipeline:

VS:

	layout (location = 0) out vec3 outNormal;
	layout (location = 1) out vec3 outColor;

GS:

	layout (location = 0) in vec3 inNormal[];
	layout (location = 1) in vec3 inColor[];

	layout (location = 0) out vec3 outNormal;
	layout (location = 1) out vec3 outColor;
	layout (location = 2) out vec3 outViewVec;
	layout (location = 3) out vec3 outLightVec;

FS:

	layout (location = 0) in vec3 inNormal;
	layout (location = 1) in vec3 inColor;
	layout (location = 2) in vec3 inViewVec;
	layout (location = 3) in vec3 inLightVec;

So from my understanding all in- and outputs of the pipeline are correctly "wired" and the validation layer message may be misleading.

Instead the SC layer should not only check for connections from VS to FS but instead should take a GS sitting between them into account.

**Comment by chrisforbes** [comment]
What version of LoaderAndValidationLayers are you testing this with?

**Comment by SaschaWillems** [comment]
Built from sources (master) right before posting the issue.

**Comment by chrisforbes** [comment]
And your shaders compiled with the version of glslang LVL master uses, or something else?

I've only poked at your test case briefly, but I'm seeing very different failures -- LVL's glslang is dropping NV-specific members into the gl_PerVertex block, and things go poorly from that point on.

**Comment by SaschaWillems** [comment]
I'm building the glslang stand alone compiler from source, but it's not the most recent one. I'll test with the most recent one today and see if it changes anything.

I also noticed the warning about an NV specific SPIR-V op, so that seems to be an additional issue.

**Comment by SaschaWillems** [comment]
Just did a clean built for the glslang stand alone compiler from master and I still get the validation layer errors described in my initial post.

As for the invalid built-in, this seems to be a bug in the current glslang compiler version, I have opened an [an issue](https://github.com/KhronosGroup/glslang/issues/790) for this.

**Comment by chrisforbes** [comment]
Doesn't repro with current layers. Reopen if you need this looked at some more.

**Comment by ArkadiuszSarwa** [comment]
I have still that problem with the layers describe in this issue. 

1. When vertex doesn't have outputs but geometry has the outputs:
> SC(ERROR): fragment shader consumes input location 0.0 which is not written by vertex shader

2. When tessellation control has outputs not the vertex 
> SC(ERROR):  tessellation evaluation shader consumes input location 0.0 which is not written by vertex shader

**Comment by chrisforbes** [comment]
@ArkadiuszSarwa can you share your repro case?

**Comment by tobine** [comment]
Closing as obsolete as we didn't get repro case.
