### ISSUE TITLE
PRIxLEAST64 undeclared on Ubuntu 16.04

### ISSUE THREAD

**Issue by strassek** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1602]
With the latest sources I'm hitting the following build error:
`Vulkan-LoaderAndValidationLayers/tests/loader_validation_tests.cpp:316:101: error: ‘PRIxLEAST64’ was not declared in this scope`

I was able to work around the issue locally by removing the #ifdef like so:
```
diff --git a/tests/loader_validation_tests.cpp b/tests/loader_validation_tests.cpp
index 3f2bf9c..f3af796 100644
--- a/tests/loader_validation_tests.cpp
+++ b/tests/loader_validation_tests.cpp
@@ -26,9 +26,7 @@
  * Author: Mark Young <marky@lunarG.com>
  */
 
-#ifdef _WIN32
 #include <inttypes.h>  //Needed for PRIxLEAST64
-#endif
 #include <stdint.h> // For UINT32_MAX
 
 #include <algorithm>
```
I tested on tag sdk-1.0.42.0, and the issue is not present.

**Comment by MarkY-LunarG** [comment]
Fixed with commit c0bf67abd0db83723d0a27e9841ecf30819b87a7.

Weird that this was an issue.  We're building without defining this on Ubuntu and Fedora Core.  However, enabling it didn't break anything either, so I just removed the ifdef as you suggested.

**Comment by 10110111** [comment]
I still do have a problem with this on my BLFS with gcc 5.2. I noticed that there's no definition of `__STDC_FORMAT_MACROS` in the whole project, which is required for these macros to be present. After I added it to `CMAKE_CXX_FLAGS`, it compiled normally for me.

**Comment by MarkY-LunarG** [comment]
Ok.  I added it directly to the source file (not via CMAKE) in commit 44a918406c3baebe4e3ab911f91cf4d13642ea67.  This should resolve your last issue.

**Comment by 10110111** [comment]
Thanks, it did resolve it.

As for why some platforms require it while others don't, this mess seems to be the fault of the standard committee: see the comment thread to [this answer at StackOverflow](http://stackoverflow.com/a/8132440/673852).

Most recent glibc doesn't require this macro, while my 2.14.1 does.
