### ISSUE TITLE
Buffer validation not passing command buffer as srcObject to validation callback

### ISSUE THREAD

**Issue by Novum** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1604]
E.g. ValidateCmdBufImageLayouts, VerifySourceImageLayout, VerifyClearImageLayout & VerifyDestImageLayout do not pass the CB handle in all cases to log_msg. Instead they just pass 0.

**Comment by Novum** [comment]
TransitionImageAspectLayout is also not reporting the image or the command buffer. Handle is not in the text nor in srcObject.

**Comment by Novum** [comment]
ValidateMaskBits also has the same problem. Better check that file thoroughly :)

**Comment by mark-lunarg** [comment]
OK, thanks.  I'm actually going through core validation to check all the places where there's a 0 for the object handle and seeing if it makes sense to correct those, but will pay special attention to the things you have noticed.

**Comment by mark-lunarg** [comment]
Improved by PR #1610.
