### ISSUE TITLE
Consider passing image handle instead of CB handle for certain validation messages

### ISSUE THREAD

**Issue by Novum** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1605]
E.g. I get messages like this:
> Cannot submit cmd buffer using image (0x166347b0) [sub-resource: aspectMask 0x1 array layer 0, mip level 0], with layout VK_IMAGE_LAYOUT_GENERAL when first use is VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL.

The objType & srcObject is pointing to the command buffer. This is kind of useful, but it would be way more useful to get the image that is causing the problem.

Slightly unrelated, but is the format of the returned addresses consistent? In that case we could parse the text, but it's not ideal.

**Comment by mark-lunarg** [comment]
Axel, until we add an extension to debug_report allowing the return of multiple objects, we'll have to address this on a case-by-case basis.  I can make the changes for the above message and take a quick look around, but if you have a list of messages you'd like changed I can hit them all at once...

**Comment by Novum** [comment]
Please don't just take my suggestions as the perfect solutions, there might always be better ways.

**Comment by Novum** [comment]
I now added code to parse the hex strings in the messages and matches them with object handles, so as long as everything is in a consistent format (like 0xABCD1234) it's fine for us.

**Comment by mark-lunarg** [comment]
Our goal is for all the returned addresses to be consistent in the format you noted above.  If you find any that don't follow that format create an issue and I'll fix them straightaway.
