### ISSUE TITLE
Consider returning warning/error numbers for validation messages

### ISSUE THREAD

**Issue by Novum** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1606]
In #1605 you mentioned you are working on an extension to VkDebugReportCallbackCreateInfoEXT.

What also would be really useful is a consistent error number for each error reported. That way we can more easily filter instead of having to rely on string compares.

**Comment by mark-lunarg** [comment]
Greate idea!  We do this now for most of the Valid Usage messages -- these numbers will change once more when they are added to the spec in a month or so.  Unfortunately, the spec also contains many validation checks which are not part of Valid Usage and which will not have (at least in the near future) unique IDs.  What we have been doing is batching up requests for spec text to get turned into valid usage on the spec side -- Vulkan-Docs or Vulkan-Vulkan.  Once the IDs are in the spec, we are good-to-go.

**Comment by Novum** [comment]
How is that number going to be passed? The messageCode?

**Comment by mark-lunarg** [comment]
Yep.  If you look in the repo, the numbers are all defined in Vulkan-LoaderAndValidationLayers/layers/vk_validation_error_database.txt.  Jon Leech and Tobin Ehlis are working on getting these 3500 or so IDs into the spec for the Valid Usage and Valid Usage (Implicit) sections, at least as a start.

**Comment by Novum** [comment]
Awesome, thanks
