### ISSUE TITLE
SC layer: Report required capabilities for SPIR-V module errors

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1611]
Linked to #1600 and [this issue for glslang](https://github.com/KhronosGroup/glslang/issues/790) it would be nice if the SC layer would also report required capabilities for e.g. invalid built-in operands.

So this:
```ERROR: [SC] Code 5 : SPIR-V module not valid: Invalid built-in operand: 5257```

Would become something like:
```ERROR: [SC] Code 5 : SPIR-V module not valid: Invalid built-in operand: SecondaryPositionNV (5257) requires ShaderStereoViewNV```

**Comment by chrisforbes** [comment]
This needs to be done in spirv-tools.

**Comment by mark-lunarg** [comment]
Yikes!  @SaschaWillems, can you replace this issue with one in that repo?
