### ISSUE TITLE
Add validation support for SPV_KHR_storage_buffer_storage_class

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1618]
Tracking issue to make sure support for SPV_KHR_storage_buffer_storage_class is added.

**Comment by mark-lunarg** [comment]
@tobine, can you add some context?  this extension doesn't appear to be in the registry, and we cover SPIRV extensions when they show up in the Vulkan header as extensions containing new shader capabilities.  Is there something special about this extension and if not, do we need an issue for this?

**Comment by tobine** [comment]
This is an upcoming extension that adds new descriptor type and will impact validation. As long as it gets tracked when it shows up in the registry that's fine and we can pick up then.

**Comment by mark-lunarg** [comment]
OK, cool.  Maybe @karl-lunarg's wiki on Gitlab/LVL would be a good spot for this kind of stuff, and we have an internal process in place to track new stuff as well.  So I'll close this one at least for now.
