### ISSUE TITLE
VK_LAYER_LUNARG_standard_validation list of layers should not be in the loader

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1620]
Currently the loader is responsible for enumerating the list of layers that comprises `VK_LAYER_LUNARG_standard_validation`. This means though that if the list changes and you build the latest validation layers, standard validation no longer works. Either by omitting a layer that's needed, or completely disappearing if a layer is removed.

It'd be better if there was a new `MetaLayers` registry the same as `ImplicitLayers` and `ExplicitLayers` that handled this logic with a json that simply lists a name (VK_LAYER_LUNARG_standard_validation) and the list of dependencies. When you point the env var at a local build of the layers while running then the existing loader would be able to figure out that the list of layers for standard validation had changed and just work without needing to be updated.

**Comment by mark-lunarg** [comment]
The standard_validation meta-layer was added _specifically_ to insulate applications from the appearance/disappearance of layers.  When the layers are built, the corresponding loader is also built and will always work with those layers.  Running locally-built layers with an incompatible loader can lead to issues in any case.

**Comment by punkUser** [comment]
> Running locally-built layers with an incompatible loader can lead to issues in any case.

Right, this is the problem that needs to be fixed. There are a variety of reasons why, but ultimately there shouldn't be a dependency between the layers and the loader. The only thing you should have to do to use the layers is set the LAYER_PATH and everything else should "just work" regardless of the loader (post whatever update to make this decoupled).

One potential solution for the standard layers is to promote them to a "real" layer with a JSON file that specifies the other layers to load.

**Comment by baldurk** [comment]
Yeh, the loader-layer interface is a strongly defined ABI that is backwards/forwards compatible, so we shouldn't weaken that ABI guarantee for the standard validation layer.

If I just build the layers and run my program with VK_LAYER_PATH then I will use the system (older) loader with new layers. Or perhaps I have them registered directly in place so there's nothing to do but run my application unomdified. I shouldn't also have to copy in the vulkan loader to my linker search path as well. It's a minor thing and easy to fix, but removing this extra manual step is a good quality-of-life improvement.

Not to mention it also means that if someone else wants to be able to create a meta-layer they can't, and we already know that it can be a useful concept.

**Comment by mark-lunarg** [comment]
I think I understand the goal and moving the definition of standard_validation out of the loader will get us a bit closer.  Even aside from this issue, the layers and loader remain closely coupled in many ways (not the least of which are header updates) and running them out of sync can still cause problems.

**Comment by punkUser** [comment]
If there is further coupling we should definitely strive to fix that too :) This is just the first such issue we've run into, but conceptually there doesn't seem to be a reason why the two should be coupled long term.

**Comment by MarkY-LunarG** [comment]
@lenny-lunarg is currently working on the ability to define "meta-layers" in JSON.  That would resolve this issue because VK_LAYER_LUNARG_standard_validation would then just become a file.  It is likely at least a month out, but is one of our items of interest at this time.

**Comment by lenny-lunarg** [comment]
To elaborate on what @MarkY-LunarG said, the current plan is to define metalayers with a JSON file, like @punkUser suggested. The new definition for standard validation should look something like:

```json
{
    "file_format_version": "1.1.1",
    "metalayer": {
        "name": "VK_LAYER_LUNARG_standard_validation",
        "type": "GLOBAL",
        "api_version": "1.0.44",
        "implementation_version": "1",
        "description": "LunarG Validation Metalayer",
        "component_layers": [
            "VK_LAYER_GOOGLE_threading",
            "VK_LAYER_LUNARG_parameter_validation",
            "VK_LAYER_LUNARG_object_tracker",
            "VK_LAYER_LUNARG_core_validation",
            "VK_LAYER_LUNARG_swapchain",
            "VK_LAYER_GOOGLE_unique_objects"
        ]
    }
}
```

I believe that should cover the issues people have described here, but if anyone thinks we need extra functionality in the metalayers, feel free to respond. Also, like @MarkY-LunarG said, it'll be a bit before the change is ready, since I've had a number of other things going on.

**Comment by punkUser** [comment]
Yeah I think that would solve our immediate issue. As mentioned we'd like to get to the point that @baldurk described: that the validation layers don't weaken the decoupled API of the vulkan layering model.

This isn't blocking us today (it's just an annoyance) so we don't need it fixed ASAP.

**Comment by MarkY-LunarG** [comment]
Meta-layer support is now in as of commit 227aa781e1bd1c485332025c2fc32fb88a15c2fb.  We chose not to do a different folder `MetaLayers` because we wanted to support both `ImplicitLayers` and `ExplicitLayers` meta-layers.  These changes also include support for nested meta-layers, however, I've only tested one meta-layer inside another (so one level deep).
