### ISSUE TITLE
cyclic pNext chain should be an error

### ISSUE THREAD

**Issue by ratchetfreak** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1621]
When a pNext chain has a cycle the layers currently hang or spams validation messages.

Instead the validation layer should detect that and issue an error.

Test case:

```
struct fakeExtension{
VkStructureType sType;
void* pNext;
}
std::vector<fakeExtension> chain(5);
for(int i = 0; i< chain.size(); i++){
    chain[i].sType = 0xFFFFFFFF;//invalid ext type;
    if(i>0)
        chain[i].pNext = &chain[i-1];
}
chain[0].pNext = &chain[3];

VkInstanceCreateInfo createInfo = {};
//fill createInfo properly

createInfo.pNext = &chain.back();
VkInstance inst;
vkCreateInstance(&createInfo, null, &inst);
//should emit error.
```

**Comment by mark-lunarg** [comment]
I believe you will always get an error in this case because any cycle should include an invalid sType.  However, adding a check to prevent the layers from getting stuck.  Will also add a check for duplicate sTypes while I'm in here, since that's coming soon.
