### ISSUE TITLE
image_validation: error report for an 2d view of a 3d image if maintenance1 is present 

### ISSUE THREAD

**Issue by TiemoJung** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1623]
Hi,

the image layer reports an error if a 2d image view of a 3d image is created when maintenance1 extension is enabled.
maintenance1 allows the creation of 2d (and array) image views of 3d images if the flag VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT_KHR is set on creation of the 3d image.

Message code 769

**Comment by mark-lunarg** [comment]
Hey @TiemoJung, this should be addressed by PR #1617, which has been approved and is just awaiting a final push.

**Comment by mark-lunarg** [comment]
Pushed #1617, please let us know if this does not resolve your issue.
