### ISSUE TITLE
SDK 1.0.42.1 missing release tag

### ISSUE THREAD

**Issue by gfxguymatt** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1624]
I would like to make my own build of the validation layers for release 1.0.42.1 but I do not see a release tag or branch that corresponds to the sources in the Windows SDK. I see a release tag and branch for 1.0.42.0 but these are missing source changes in layers/ that are in the official release package.

**Comment by MarkY-LunarG** [comment]
Tag and changes pushed up.  Thanks for catching this.
