### ISSUE TITLE
VK_LAYER_LUNARG_core_validation queue submissions list grows forever and causes crash

### ISSUE THREAD

**Issue by Overv** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1628]
I have a "Hello Triangle" Vulkan application that uses the following pattern to draw every frame:

* `vkAcquireNextImageKHR`
* `vkQueueSubmit`
* `vkQueuePresentKHR`

The *VK_LAYER_LUNARG_core_validation* validation layer will append each command buffer submission to a queue when `vkQueueSubmit` is called:

https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/core_validation.cpp#L4495

Unfortunately, it only removes items from that queue when `RetireWorkOnQueue` is called. This function is only called when the host program calls one of the following functions:

* `vkQueueWaitIdle`
* `vkDeviceWaitIdle`
* `vkWaitForFences`
* `vkGetFenceStatus`

My program does not rely on any of these for synchronization while drawing frames, so the command buffer submission queue grows forever and eventually the validation layer + program crashes because it runs out of memory.

I could not find anything in the Vulkan specification that requires a program to use these calls. I simply rely on image presentation and acquisition semaphores, so I think the validation layer should be fixed to also check for finished command buffers in other calls.

**Comment by chrisforbes** [comment]
A couple of thoughts here:

* We've got some holes in how we track things through AcquireNextImage/QueuePresent (short version: "we dont"), which I need to fix.

* You have a very odd case. Something of the complexity of Hello Triangle can fall into this gap because you can create everything you'll ever use upfront and then just let it rip--, but as soon as it grows a bit more, you end up having to drop fences in so you can reclaim some of your transient resources. Technically the layer is correct in what it's doing -- you're producing a huge stream of work with no proof that any of it has completed, but that's fine because you don't care -- but it's still unhelpful if we consume all the memory and crash.

**Comment by chrisforbes** [comment]
One further note here: the layer isn't tracking what has /actually completed/. It doesn't care what the GPU does. All it's interested in is whether the app can prove that some resource is no longer in flight, based on the synchronization it has observed.

**Comment by Overv** [comment]
Do you recommend using a `vkDeviceWaitIdle` or `vkQueueWaitIdle` call in a Hello Triangle style application for now?

**Comment by tobine** [comment]
Using a *WaitIdle() call is the heavy-handed way to work around the validation crash. A lighter-handed work around would be to send a fence with your submission every N frames and at the same time check the status of the fence from the previous N frames. N should be sufficiently large to know that the fence will have completed, but small enough to avoid the crash.
For example, if you submit a fence every 100 frames and check the fence status from 100 frames previous then that old frame should be done and checking the fence will allow validation to clean up the last 100 submissions.

**Comment by Tony-LunarG** [comment]
I suspect that not removing work from the queue when QueuePresent waits for a semaphore signalled by a previously submitted QueueSubmit is also causing many errors in dEQP-VK.wsi.win32.swapchain.render.basic

**Comment by chrisforbes** [comment]
@Tony-LunarG it /can't/. QueuePresentKHR's semaphore waits order the presentation against the previous work, but not any future CPU work against either.

**Comment by mark-lunarg** [comment]
If we agree to address this particular case, it will be handled in the assistant layer.  Formally adding it to that list to be tracked there (in issue #1612).

**Comment by krOoze** [comment]
Seems to me though that the memory usage should be proportionate to the objects in-flight (and not submission count).

Isn't it theoretically fixable by proper implementation in the core layer? If it properly tracks the synchronization chain and culls old irrelevant data, then it should not "leak" (for a valid app).

Only place for the assistant layer I see to detect broken synchronization chains (e.g. chains that were not chained to anything new for X seconds)

**Comment by chrisforbes** [comment]
Petr, it's possible to build a model that would cope better with this, but the added complexity carries a cost. I'd only consider doing it if it significantly improved real cases as well.

Apps like this which do no pacing are simply /broken/. There is no spec guarantee of any back pressure to the app through either vkQueuePresentKHR or vkAcquireNextImageKHR -- although many implementations do provide some.

**Comment by chrisforbes** [comment]
@mark-lunarg this has been churning away in the back of my mind for a couple of days and I think there are some changes we can make which will enable both constant-space handling of these cases AND spending a lot less time frobbing in_use refcounts on everything. Will file more bugs with a real proposal once it crystallizes a bit more.
