### ISSUE TITLE
Error enum is not consistent between releases/commits

### ISSUE THREAD

**Issue by punkUser** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1631]
We've noticed that the error numbers don't appear to be consistent between commits/releases of the layers. Looking through the commit history of layers/core_validation_error_enums.h indicates that various errors are just inserted or removed with no consideration of consistency here.

It's important that going forward we maintain consistency of error IDs so that we have a good way to filter and database them. Ex. we ignore certain harmless warnings based on their ID, and in the future we will likely integrated validation layer errors with our automated testing, both of which require some stability here.

We can update the IDs for now, but I wanted this issue to serve as an agreement to keep them stable going forward; there are many pros to this and few cons.

**Comment by tobine** [comment]
Note that all validation error messages are moving to the codes defined in layers/vk_validation_error_messages.h. Great efforts are made to keep those IDs consistent.

#780 discussed this transition previously.

The goal is eventually kill the error codes in layers/core_validation_error_enums.h which have been ad-hoc, changing as you noted and often aliasing multiple separate issues to a single id.

In cases where layers/core_validation_error_enums.h is still used I'll push for the creation of new enums only and no further changes to existing enums.
