### ISSUE TITLE
Loader crashes if multiple VkSurfaces are created from more than one VkInstance

### ISSUE THREAD

**Issue by scyganINTEL** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1642]
The code in `vkCreateWin32SurfaceKHR` terminator, in AllocateIcdSurfaceStruct function
```
        pIcdSurface->real_icd_surfaces = loader_instance_heap_alloc(instance, sizeof(VkSurfaceKHR) * instance->total_icd_count, VK_SYSTEM_ALLOCATION_SCOPE_OBJECT);
```

allocates one entry in `real_icd_surfaces` array per-`ICD`.

However the code in `vkCreateSwapchainKHR` terminator:
```
struct loader_icd_term *icd_term = loader_get_icd_and_device(device, &dev, &icd_index);
...
pCreateCopy->surface = icd_surface->real_icd_surfaces[icd_index];
```
Accesses this table with index pointing to one of *ICD x Instance* combinations.

In case of having more than one VkInstance, this causes `real_icd_surfaces` array overrun in `vkCreateSwapchainKHR ` and garbage VkSurfaces being passed to the ICD

**Comment by lenny-lunarg** [comment]
I believe I have a fix for this bug. I pushed the fix to branch `lenny_gh1642`. Would you mind testing that branch whenever you have the chance to see if it solves the problem on your end?

**Comment by scyganINTEL** [comment]
The problem is solved with above change. Thanks!

**Comment by lenny-lunarg** [comment]
Awesome. I just pushed the change to master with commit 9a3b43bc96f43bbfea0827a8c06a9b5a7f7811b8.
