### ISSUE TITLE
core_validation: Possible bug when validation image layout state when using 2d view of a 3d image

### ISSUE THREAD

**Issue by TiemoJung** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1650]
Hi,

as with the maintenance1 extension, it is possible to use a slice of a 3d image as a 2d (array) view.
And if you try to use as 2d image view of a 3d image slice, the the lookup for slice 1 >= always returns VK_IMAGE_LAYOUT_UNDEFINED and the layout validation reports an error even if the complete 3d image is in the needed layout.

**Comment by DominikWitczakAMD** [comment]
Ha, I was just intending to report this bug as well :-)
