### ISSUE TITLE
Error messages limited to 1024 characters?

### ISSUE THREAD

**Issue by ioquatix** [KhronosGroup/Vulkan-LoaderAndValidationLayers#166]
We are trying to debug and the error messages are often truncated:

```
{DS}sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO
{DS}pNext = 0
{DS}flags = 0
{DS}stageCount = 2
{DS}pStages = 0x15f92e0
{DS}pVertexInputState = 0x15f8f58
{DS}pInputAssemblyState = 0x15f8f88
{DS}pTessellationState = 0
{DS}pViewportState = 0x15f8fc0
{DS}pRasterizationState = 0x15f8ff0
{DS}pMultisampleState = 0x15f9030
{DS}pDepthStencilState = 0x15f9098
{DS}pColorBlendState = 0x15f9060
{DS}pDynamicState = 0x15f9100
{DS}layout = 0x15f21c0
{DS}renderPass = 0x15ed3f0
{DS}subpass = 0
{DS}basePipelineHandle = 0
{DS}basePipelineIndex = 0
 {DS}pDynamicState (0x15f8f28)
  {DS}sType = VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO
  {DS}pNext = 0
  {DS}flags = 0
  {DS}dynamicStateCount = 2
  {DS}pDynamicStates = 0x15f3a00 (See individual array values below)
   {DS}pDynamicStates[0] = VK_DYNAMIC_STATE_VIEWPORT
   {DS}pDynamicStates[1] = VK_DYNAMIC_STATE_SCISSOR
 {DS}pColorBlendState (0x15f8f20)
  {DS}sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO
  {DS}pNext = 0
  {DS}flags = 0
  {DS}lo
```

A cursory glance at the SDK reveals many places where 1024 byte buffers are hard coded. Not sure if this is really ideal?

**Comment by lentinem** [comment]
Yes; this is not ideal and we are removing them when they come up but it hasn't been a high priority issue for now. If you feel like it should be please let us know.

**Comment by ioquatix** [comment]
Yes I think this should be high priority because it makes debugging hard.

**Comment by jon-lunarg** [comment]
Looks like Chris has a fix for this; assigning to Chris.

**Comment by ioquatix** [comment]
Any update?

**Comment by jon-lunarg** [comment]
A fix to the debug_report logging has been done and pushed to master branch.  Give this a try and let us know if you are still seeing the issue.

**Comment by ioquatix** [comment]
Ah yep, if you close an issue it would be nice if you reference the commit so I could see what was done :)

**Comment by ioquatix** [comment]
When you make the commit, you can actually do something like "Message, closes #bug id" and it will all happen automatically.
