### ISSUE TITLE
vkQueuePresentKHR doesn't write to pResults with enabled VK_LAYER_GOOGLE_unique_objects layer

### ISSUE THREAD

**Issue by RippeR37** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1670]
I've stumbled recently on a problem with `vkQueuePresentKHR()` function when supplying `pResults` pointer. Problem is that after calling this function with valid `pResults` pointer pointing to element of `VkResult` type (I use only one swapchain), the value in the object pointer by this pointer is not modified.

For example if I have a call:
```cpp
uint32_t imageIndex = /* index acquired before */;
VkResult presentResult = static_cast<VkResult>(some_invalid_value_like_9000); // happens also with valid values

VkPresentInfoKHR presentInfo;
presentInfo.sType = VK_STRUCTURE_TYPE_PRESENT_INFO_KHR;
presentInfo.pNext = nullptr;
presentInfo.waitSemaphoreCount = 1;
presentInfo.pWaitSemaphores = &waitSemaphore;
presentInfo.swapchainCount = 1;
presentInfo.pSwapchains = &swapchain;
presentInfo.pImageIndices = &imageIndex;
presentInfo.pResults = &presentResult;

VkResult presentAllResult = vkQueuePresentKHR(queue, &presentInfo);
```

then when I inspect values without that layer enabled I get:
```
presentResult == 0 (success)
presentAllResult == 0 (success)
```
but if I enable some layers including unique_objects one (it might be just it!) it is:
```
presentResults == 9000 (or whatever value was there before the call)
presentAllResult == 0 (succcess)
```

Because of that, I get a lot of warnings from other validation layers:
```
DS(ERROR): object: 0x2 type: 27 location: 11109 msgCode: 108: vkAcquireNextImageKHR: Application has already acquired the maximum number of images (0x2)
DS(ERROR): object: 0x2 type: 27 location: 11109 msgCode: 108: vkAcquireNextImageKHR: Application has already acquired the maximum number of images (0x3)
DS(ERROR): object: 0x2 type: 27 location: 11109 msgCode: 108: vkAcquireNextImageKHR: Application has already acquired the maximum number of images (0x3)
DS(ERROR): object: 0x2 type: 27 location: 11109 msgCode: 108: vkAcquireNextImageKHR: Application has already acquired the maximum number of images (0x3)
```

Of course everything works beside these warnings and these return values...

My SW/HW:
* Windows 7 x64
* Nvidia 660M GTX
* Checked on SDK 1.0.42.2 and 1.0.46.0, same on both
* Checked on drivers 375.* and newest 381.65

I've also checked code of `unique_objects.(h|cpp)` but I can't find anything that could be the reason without actually debugging whole thing.

**Comment by chrisforbes** [comment]
Quick 5 minute debugging session:

In (generated) build/layers/unique_objects_wrappers.h, before calling down the chain, we make our own copy of the VkPresentInfo [as a safe_VkPresentInfo]. This includes making a copy of the array pointed to by VkPresentInfo::pResults.

Lower layer then populates the copy, and we forget to copy it back to the original. *facepalm*

**Comment by RippeR37** [comment]
@chrisforbes that explains why I havn't found anything in code available on GitHub. :)
I suspected something like that or simply forgetting that there was `pResults` given and setting `nullptr` in its place.

Thanks for fast reply anyway. :+1:

**Comment by chrisforbes** [comment]
Working on a fix now.

**Comment by mark-lunarg** [comment]
Thanks a bunch @chrisforbes for handling this!
