### ISSUE TITLE
validation: device_limits : BindDescriptorSet could assert dynamic offsets are multiple of minUniformBufferOffsetAlignment

### ISSUE THREAD

**Issue by mccaffrey-jonathan** [KhronosGroup/Vulkan-LoaderAndValidationLayers#168]
layers/device_limits.cpp contains checks that the offset  member of the VkDescriptorBufferInfo structure is a multiple of minUniformBufferOffsetAlignment .

Another requirement that could be checked is that dynamic offsets for dynamic uniform buffer passed in BindDescriptorSet are multiples of minUniformBufferOffsetAlignment .

**Comment by dustin-lunarg** [comment]
It looks like the core_validation layer is already validating the vkCmdBindDescriptorSets pDynamicOffsets values against the minUniformBufferOffsetAlignment limit.  See [here](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/core_validation.cpp#L7416).

@mccaffrey-jonathan Did you encounter a case where a dynamic offset was invalid and no validation error was generated?

**Comment by dustin-lunarg** [comment]
This case is handled by the core_validation layer.
