### ISSUE TITLE
Stale Driver entry causing vkCreateInstance failure

### ISSUE THREAD

**Issue by darrelpalke** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1681]
In HKLM\Khronos\Vulkan\Drivers, stale references to uninstalled GPUs will cause vkCreateInstance to fail.  The scenario is as follows:
Have system with IHV1 Card
Replace card with IHV2 Card
Run simple Vulkan app
Fail vkCreateInstance.

When you run vulkaninfo.exe, you get the attached log.
[log.txt](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/files/945322/log.txt)

If the stale entry is removed, vulkaninfo.exe succeeds and normal apps run.

The behavior should probably ignore stale references if there is at least one valid reference.  Or cross reference with the manifest files round earlier.  I can see in the log file that it finds the nv-vk64.json file in system32 before searching the registry.

**Comment by MarkY-LunarG** [comment]
Commit 121224ba0ee0f72af3517b508b85e672d71ebff7 should fix this.  Now, as long as you get at least one valid JSON and ICD, it shouldn't error out.  Unless it ran out of memory which can be another issue.
