### ISSUE TITLE
Validation layers do not restict pipeline barriers inside render passes

### ISSUE THREAD

**Issue by scyganINTEL** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1687]
There are certain restrictions to pipeline barriers inside renderpasses. At least this one:
```
 vkCmdPipelineBarrier is called within a render pass instance, the oldLayout and newLayout members of an element of pImageMemoryBarriers must be equal
```
is not checked by standard validation layers.

Example of invalid barrier: https://github.com/KhronosGroup/VK-GL-CTS/blob/2795d6ce25af5357a0c34d0fa3d4a3e891d78f1a/external/vulkancts/modules/vulkan/pipeline/vktPipelineMultisampleBaseResolveAndPerSampleFetch.cpp#L844

**Comment by tobine** [comment]
This is VALIDATION_ERROR_1b80093a, implemented [here](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/core_validation.cpp#L6207).
