### ISSUE TITLE
When creating a framebuffer, VKFramebufferCreateInfo.layers is not checked to be > 0

### ISSUE THREAD

**Issue by hrydgard** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1701]
https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkFramebufferCreateInfo.html says:

    layers must be greater than 0.

But if I try to create a framebuffer with validation enabled and layers = 0, no warning is issued.

Making a draw call with such a framebuffer bound crashes the driver on at least one major GPU family. I accidentally did this and had tons of "fun" debugging... Oh well :)

**Comment by cdwfs** [comment]
width and height are also not currently validated as nonzero. I can take care of all three checks later today.

**Comment by hrydgard** [comment]
Those are harder to accidentally leave out though :) But yeah, they should of course be checked too.

**Comment by mikew-lunarg** [comment]
@hrydgard @cdwfs If resolved, could you close this issue?  Thanks
