### ISSUE TITLE
Windows Remote Desktop Compatibility

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1714]
Currently, Vulkan device creation fails over Windows Remote Desktop where vkEnumeratePhysicalDevices returns VK_ERROR_INITIALIZATION_FAILED.

There are underlying OS reasons why this is believed to be the case, but it also is expected that this should work for non-windowing Vulkan applications.  Is there anything that needs to be done in the loader to address this?

**Comment by lenny-lunarg** [comment]
As far as I can tell, the loader seems to be fine for remote desktops. I tried debugging this, and I'm seeing the exact same error you reported, but the error is coming from the Nvidia driver. As a result, I can't really debug past physical device enumeration so I can't guarantee that everything else will work. But the immediate issue you reported is coming from the driver. If you can find a driver which doesn't have this issue, or if Nvidia fixes the current issue, then I'd be happy to make sure that the rest of the loader works with a remote desktop.

**Comment by danginsburg** [comment]
@jjulianoatnv Would you be able to look at this?

**Comment by jjulianoatnv** [comment]
@danginsburg Yes, I'll take a look from inside the NV ICD.

**Comment by lenny-lunarg** [comment]
@jjulianoatnv, have you had a chance to look into this yet? I'd like to close this issue, but I'm not confident that we won't discover loader issues once the driver issue I described above is fixed. As a result, I'd like to get a driver that is working so I can verify that the loader is behaving

**Comment by jjulianoatnv** [comment]
Sorry, I got busy then forgot to look into this. I do plan to look into it during the next couple weeks, and I'll report back here after I have some concrete info.

**Comment by jjulianoatnv** [comment]
This seems possible. We implemented preliminary support in the Vulkan beta driver 382.96 which was just published to https://developer.nvidia.com/vulkan-driver.

There are some known issues:
- Might crash during window resize.
- Might crash if RDP session is established while app is already running.

Not sure yet if there are driver bugs here, only app bugs, or some of each.

**Comment by jjulianoatnv** [comment]
> Is there anything that needs to be done in the loader to address this?

No changes to the loader were needed.

**Comment by lenny-lunarg** [comment]
That's good news to hear. Since it sounds like the loader is working fine with remote desktops I'm going to close this issue. If anyone finds issues with the loader or validations layers on remote desktops, feel free to open a new issue for that specific problem.

**Comment by rob-avalon** [comment]
Apologies if this is no longer the place to discuss this, but I'm still experiencing this issue and I was confused about where to bring it to Nvidia's attention.

I'm using Vulkan SDK: 1.0.57.0, and Nvidia beta driver: 382.96, Windows 10, and a GeForce GTX 980 Ti card.

Even this trivial program returns VK_ERROR_INITIALIZATION_FAILED from vkEnumeratePhysicalDevices 

```
#include "vulkan\vulkan.h"
#include <assert.h>

int main(int argc, char* argv[])
{
    VkApplicationInfo AppInfo = {};
    AppInfo.sType = VK_STRUCTURE_TYPE_APPLICATION_INFO;
    AppInfo.pApplicationName = "RemoteDektopTest";
    AppInfo.applicationVersion = VK_MAKE_VERSION(1, 0, 0);
    AppInfo.pEngineName = "No Engine";
    AppInfo.engineVersion = VK_MAKE_VERSION(1, 0, 0);
    AppInfo.apiVersion = VK_API_VERSION_1_0;

    VkInstanceCreateInfo CreateInfo = {};
    CreateInfo.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
    CreateInfo.pApplicationInfo = &AppInfo;
    CreateInfo.enabledLayerCount = 0;

    VkInstance Instance;
    VkResult result = vkCreateInstance(&CreateInfo, nullptr, &Instance);
    assert(result == VK_SUCCESS);

    uint32_t DeviceCount = 0;
    result = vkEnumeratePhysicalDevices(Instance, &DeviceCount, nullptr);
    assert(result == VK_SUCCESS);

    return 0;
}
```

**Comment by pdaniell-nv** [comment]
I apologize, there was a mistake in the 382.96 release that kept RDP working on some GPUs, including the GTX 980. The next release should have RDP support.
