### ISSUE TITLE
VK_ACCESS_MEMORY_READ_BIT warning for transition to VK_IMAGE_LAYOUT_PRESENT_SRC_KHR

### ISSUE THREAD

**Issue by IanLilleyT** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1717]
I'm writing to a swapchain image from a compute shader and my code for the final image layout transition is:

```
VkImageMemoryBarrier barrier;
barrier.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
barrier.pNext = nullptr;
barrier.srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
barrier.dstAccessMask = 0;
barrier.oldLayout = VK_IMAGE_LAYOUT_GENERAL;
barrier.newLayout = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR;
barrier.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
barrier.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
barrier.image = swapchainImages[i];
barrier.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
barrier.subresourceRange.baseMipLevel = 0;
barrier.subresourceRange.levelCount = 1;
barrier.subresourceRange.baseArrayLayer = 0;
barrier.subresourceRange.layerCount = 1;

vkCmdPipelineBarrier(swapchainCommandBuffers[i], VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT, 0, 0, nullptr, 0, nullptr, 1, &barrier);
```
And I'm getting the warning (SDK version 1.0.46): 

> VULKAN: !!! WARNING !!! DS: Dest AccessMask 0 [None] must have required access bit 32768 [VK_ACCESS_MEMORY_READ_BIT]  when layout is VK_IMAGE_LAYOUT_PRESENT_SRC_KHR, unless the app has previously added a barrier for this transition.

But according to section 29.6 of the spec (version 1.0.48): 

> When transitioning the image to VK_IMAGE_LAYOUT_PRESENT_SRC_KHR, there is no need to delay subsequent processing, or perform any visibility operations (as vkQueuePresentKHR performs automatic visibility operations). To achieve this, the dstAccessMask member of the VkImageMemoryBarrier should be set to 0, and the dstStageMask parameter should be set to VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT.

If I understand correctly, there's a disconnect between the spec and the validation.

**Comment by chrisforbes** [comment]
I agree with you. This used to be less clear.

**Comment by IanLilleyT** [comment]
Cool! Thanks for the (eventual) fix
