### ISSUE TITLE
Better handling of driver installs in inconsistent state

### ISSUE THREAD

**Issue by nsubtil** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1726]
The Vulkan loader right now seems a bit too restrictive when handling driver installs left in an inconsistent state. On Windows, we recently found that the loader will fail to create an instance when there are two driver JSON file references in the registry, but the first one points at a file that doesn't exist on the system anymore.

This was a result of having two vendor drivers installed while swapping physical hardware around, then uninstalling one of the vendor drivers when that particular hardware was no longer required. The end result is that Vulkan is made unusable on the system until the user manually cleans up the stale registry entry.

In this scenario, it seems reasonable to have the loader ignore the first JSON entry in the registry. This would make it more robust to driver installer bugs.

**Comment by jjulianoatnv** [comment]
Dumping some thoughts into the issue.

The documentation relevant to this issue, specifically for Windows OS, is here:
https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/loader/LoaderAndLayerInterface.md#icd-discovery-on-windows

Ideally, it seems the loader should do this for ICD discovery:
1. If the registry names a .json file that cannot be opened for read, then treat that as a non-fatal error. Specifically, behave as if the registry entry did not exist.
1. If a .json file references an ICD .dll that cannot be opened for read, then treat that as a non-fatal error. Specifically, behave as if the .json file did not exist.

When logging/validation is enabled then the above conditions should emit a warning.

Apply similar rules to layers.

Apply similar rules to non-Windows OS ICD discovery.

**Comment by jjulianoatnv** [comment]
Does the commit from #1681 address all of my recommendations or only a subset? I wasn't able to answer this from inspecting the commit.

**Comment by jjulianoatnv** [comment]
Also, I'm unclear if the IHV's ICD failed to init, or if the ICD is missing from the file system yet the registry key and/or .json is still present. Both failure modes are possible.

**Comment by MarkY-LunarG** [comment]
@jjulianoatnv, I believe #1681 should resolve the 2 items you explicitly mentioned.  Also, I believe the logic is already in place to do the same for layers.

I have seen cases where the ICD fails to handle the calls properly if both the JSON and library file are present, but nothing actionable here for now.

**Comment by MarkY-LunarG** [comment]
@nsubtil, have you verified that the fix for #1681 either did or did not fix your issue?

**Comment by MarkY-LunarG** [comment]
@nsubtil , I plan on closing this issue next week if I don't hear back from you.  I believe all these issues are resolved, but I would like to hear back from you just to be sure you're not continuing to have problems.

**Comment by MarkY-LunarG** [comment]
Just fixed another issue with a bad driver install discovered by Pierre-Loup @ Valve.  We had been using dlopen with RTLD_LAZY which would not validate all the ICD symbols at load time.  This resulted in the loader failing at an un-recoverable time.  Based on his suggestion, we've switch to RTLD_NOW to resolve this.  All fixes are in as of commit 0345b8925d79e175a000ff7c87b7a82bd5e91ff0.  I'm closing this because I believe all issues are resolved, and I haven't heard back otherwise.  If you discover anything new, please create a new bug with the specific details.
