### ISSUE TITLE
VkPipelineTessellationStateCreateInfo sType is not validated

### ISSUE THREAD

**Issue by cdwfs** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1736]
I expected to find a validate_struct_type() for it in parameter_validation.h, but no such luck. It looks like other optional pipeline state structs (like pDepthStencilState) are handled manually in parameter_validation.cpp; should I add checks for tessellation state there as well, or would it be better to fix the codegen script?

**Comment by tobine** [comment]
My recommendation is adding manual check in parameter_validation.cpp

**Comment by cdwfs** [comment]
Oops, please disregard, it's already there. Nothing to see here.
