### ISSUE TITLE
Validate that codeSize is a multiple of 4 for SPIR-V

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1739]
Unless the application is using `VK_NV_glsl_shader` (which hopefully no-one is, but it's easy to handle if they do) the `VkShaderModuleCreateInfo::codeSize` member should be a multiple of 4, since it's a byte count of a stream of 32-bit words.

It would also be nice to validate that the SPIR-V is legal too, but that's obviously a larger task.

**Comment by chrisforbes** [comment]
We already pass the module through the SPIRV-Tools validator. It looks like we lost the multiple of 4 size validation when we put that in, and they can't implement it on their side, since they take the size as a count of words rather than of bytes. Can put that back in on our side.

**Comment by mark-lunarg** [comment]
Fix pushed to Master -- Thanks for the report!
