### ISSUE TITLE
Execution of secondary command buffer in the initial state crashes validation

### ISSUE THREAD

**Issue by martty** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1756]
If you allocate and execute a secondary command buffer without ever recording into it, the validation code looks into VkCommandBufferInheritanceInfo inside the VkCommandBufferBeginInfo during vkCmdExecute without checking the pointer for null (core_validation.cpp:9457), causing a crash.

Per the spec: "Any given element of pCommandBuffers must be in the pending or executable state.", so this is definitely an error, but I think there should be a diagnostic for this case instead of the crash.

**Comment by mark-lunarg** [comment]
@martty  -- what version of the layers are you using (from an SDK maybe)?  I tried a test case and get a validation error that says I have to call EndCommandBuffer on the secondary CB before calling CmdExecuteCommands (and no crash).  This is on Master.  I'll look into adding a null ptr check in any case.

**Comment by martty** [comment]
Thanks for looking into it. It is on Master, but it seems since then the line numbers moved, I am sorry for linking it incorrectly. The crash happens on https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/f25d461667ca2db55147d2be49f179945edf24db/layers/core_validation.cpp#L9568 .
Does the Primary CB have an active RenderPass? I seems to me from the code that the dereference is only hit if it does.

**Comment by mark-lunarg** [comment]
Fixed by PR #1773.  Thanks @martty for the report and information!
