### ISSUE TITLE
core_layer: Deadlocks

### ISSUE THREAD

**Issue by TiemoJung** [KhronosGroup/Vulkan-LoaderAndValidationLayers#177]
Hi,

while using the core_layer, we encountered multiple locking problems within the layer. those will lead to deadlocks eventually.

Locations:
vkAllocateDescriptorSets:
- on some error cases the locks are not unlocked (in the `if (VK_SUCCESS == result)` block)

vkCmdCopyBuffer:
- When MTMERGESOURCE is set to 1 (default) then the code will take the global lock twice and release it once.

vkCreateRenderPass:
- at the check for any validation errors the lock is released after the return with the error code

As a side note, why not use RAII constructs to avoid such bugs in the first place?

**Comment by mark-lunarg** [comment]
I'd already found one of these and have more that he missed.  Together, these appear to fix my Dota2 issues.

**Comment by tobine** [comment]
Mark, I just pushed #182 to fix these. Do with it what you will.

**Comment by mark-lunarg** [comment]
Pushed Tobin's fixes to Master.  TiemoJung, we are moving to a more robust solution to this problem soon.  Thanks for the bug report.
