### ISSUE TITLE
is_extension_added_token() is true for all VK_*_MAX_ENUM values

### ISSUE THREAD

**Issue by cdwfs** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1770]
The parameter_validation layer uses is_extension_added_token() checks for inputs larger than ExtEnumBaseValue to see whether an enum value was added by an extension (and can thus safely be outside of [VK_xxx_BEGIN_RANGE  ... VK_xxx_END_RANGE]. However, the special value VK_xxx_MAX_ENUM is always defined to be 0x7FFFFFFF, and is thus treated as an extension-added token. This means MAX_ENUM can be passed to *any* Vulkan enum parameter without triggering a validation failure (and in some cases leading to an immediate driver crash).

An easy fix would be to add a check for value < 0x7FFFFFFF in is_extension_added_token(); assuming we can count on that as the value of MAX_ENUM in all cases. A safer fix would be for validate_ranged_enum() to take a new "max_value" parameter that can be specified per-test, but that would involve a lot of extra work. Any other ideas?

**Comment by mark-lunarg** [comment]
This came up yesterday in a user complaint about validation.  I would vote for some kind of easy fix to start with just to have the thing sooner rather than later.

**Comment by cdwfs** [comment]
Okay, I'll submit a PR this morning.
