### ISSUE TITLE
Validate resetting a secondary command buffer before the primary buffer is submitted

### ISSUE THREAD

**Issue by Dolphiniac** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1780]
Hi, I just spent a few days chasing down a bug with the lovely folks making RenderDoc.

The issue was that I had recorded secondary command buffers for draw commands, called vkCmdExecuteCommands with my primary buffer, but before I submitted the primary buffer, I reset and re-recorded in the executed secondary buffers.

More specifically, I did a depth prepass with the secondary buffers, then called vkCmdExecuteCommands, then vkCmdNextSubpass, and then did a G-Buffer pass with the same reset buffers

The result was that the old commands were not executed at all.  The depth prepass never happened, as the contents were overwritten with the G-Buffer draw calls.

Anyway, this screams that validation should have caught it, so I'd appreciate this in there.

**Comment by chrisforbes** [comment]
Reproduced this:

We're very noisy about this if you just call BeginCommandBuffer the second time, but it's masked if you explicitly reset the command buffer first.

**Comment by chrisforbes** [comment]
WIP test case in `rerecord` branch. This is bringing various bits of bad behavior out of the woodwork.

**Comment by mark-lunarg** [comment]
@chrisforbes, is it against the spec to reset a secondary CB (or do anything else to it) before submitting its primary CB?  If this is going to be a warning/perf warning it should be consolidated with the issues in the Assistant Layer #1612.  CmdExecuteCommands says that all secondary CBs must be in pending or executable state, but I'd assumed that was at submit-time.

**Comment by tobine** [comment]
I believe the validation hole here come from this language in 5.1. Command Buffer Lifecycle section of spec:

> If a secondary moves to any other state whilst it is recorded to another command buffer, the primary moves to the invalid state.

We should be invalidating the PrimaryCB at the time the secondary is reset, but don't currently do that.

That fix, in isolation, is straightforward, but @chrisforbes is correctly noting that this bug highlights some further limitations in how modifications to secondary command buffers propagate.

**Comment by mark-lunarg** [comment]
👍

**Comment by chrisforbes** [comment]
@mark-lunarg I've added some more of the untangling work to the `rerecord` branch. We're still not invalidating the primary when the secondary is reset/invalidated, but some of the surrounding mess is getting clearer.
