### ISSUE TITLE
get_format_type() doesn't handle S8_UINT

### ISSUE THREAD

**Issue by MaciejJesionowskiAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1797]
I think there's an error in get_format_type() function in core_validation.cpp. For stencil-only format it resolves to a floating-point format type rather than an uint. It leads to this error message:

> SC(ERROR): object: 0x0 type: 0 location: 2371 msgCode: 18: Subpass input attachment 0 format of VK_FORMAT_S8_UINT does not match type used in shader `ptr to const uniform image(dim=6, sampled=2)`

Looks like none of the utility functions in there take S8_UINT into account.

**Comment by daveh-lunarg** [comment]
Fixed in PR #1802.
