### ISSUE TITLE
buffer_validation: wrong vkCmdClearAttachment [baseArrayLayer, baseArrayLayer + layerCount] range validation

### ISSUE THREAD

**Issue by scyganINTEL** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1798]
This is a validation check from master version of buffer_validation.cpp:
```
auto attachment_base_array_layer = image_view_state->create_info.subresourceRange.baseArrayLayer; 
auto attachment_layer_count = image_view_state->create_info.subresourceRange.layerCount;
if ((pRects[j].baseArrayLayer < attachment_base_array_layer) || pRects[j].layerCount > attachment_layer_count) {
    skip |=
        log_msg(report_data, VK_DEBUG_REPORT_ERROR_BIT_EXT, VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT,
                HandleToUint64(commandBuffer), __LINE__, VALIDATION_ERROR_01116, "DS",
                "vkCmdClearAttachments(): The layers defined in pRects[%d] are not contained in the layers of "
                "pAttachment[%d]. %s",
                j, i, validation_error_map[VALIDATION_ERROR_01116]);
}
```
The `if`-condition is wrong, it interprets [baseArrayLayer, baseArrayLayer + layerCount] as if counted from the layer 0 of VkImage. However spec says: 

 > The layers [baseArrayLayer, baseArrayLayer
 > layerCount) counting from the base layer of the **attachment image view** are cleared.

This check should be re-formulated, to check if both `pRects[j].baseArrayLayer` and `pRects[j].baseArrayLayer + pRects[j].layerCount -1` are less than `create_info.subresourceRange.layerCount`.

**Comment by daveh-lunarg** [comment]
Agreed, and nice catch!  Fixed in PR #1803.
