### ISSUE TITLE
VULKAN_WSI environment variable scoping

### ISSUE THREAD

**Issue by jackoalan** [KhronosGroup/Vulkan-LoaderAndValidationLayers#18]
Hello!

I'm aware that XCB is the only Linux WSI with solid support right now, but in attempting to test PR #17, I noticed something that doesn't jive with certain shells and automated packaging systems.

```cmake
set(ENV{VULKAN_WSI} "Wayland")
```

I'm on Arch Linux using a PKGBUILD script from AUR to automate the clone, build and package. When the script finishes executing cmake, the ENV goes out of scope and the makefile rules calling `vk-layer-generate.py` won't propagate VULKAN_WSI, always defaulting to XCB as a result.

In my opinion, having the WSI passed as a CLI argument is a much more stable way to pass this option.. thereby persisting in the makefiles themselves.

**Comment by elongbug** [comment]
Hi! 
I also tested on Arch. below is my test command.
- for wayland 
$  cmake -H. -Bdbuild -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=OFF -DBUILD_DEMOS=OFF  -DBUILD_LAYERS=OFF -DBUILD_WSI_WAYLAND_SUPPORT=ON
$ cd dbuild
$ make
 
- for XCB 
$ cmake -H. -Bdbuild -DCMAKE_BUILD_TYPE=Debug  or  $ cmake -H. -Bdbuild -DCMAKE_BUILD_TYPE=Debug   -DBUILD_WSI_XCB_SUPPORT=ON
$ cd dbuild
$ make

**Comment by jackoalan** [comment]
I see, disabling the layers would certainly help skirt around the build issues. Even still, it seems like a kludgy way to pass the WSI.

**Comment by elongbug** [comment]
Yes, also I agree with your opinion. but for now, I could not find the right way for checking wsi in layer generating scripts.

**Comment by Antidote** [comment]
Passing it as an argument to vk-layer-generate.py, as suggested, is the best approach, it can then be stored in the object like normal.

**Comment by jackoalan** [comment]
I'd like to get some opinions from LunarG maintainers. `sys.argv[1]` could be designated as WSI, then `sys.argv[2]` for the subcmd and so forth

**Comment by elongbug** [comment]
@Antidote, @jackoalan  Thanks for kind guides, I'll fix that with sys.argv[] and push again ^^

**Comment by jackoalan** [comment]
Cool! Yea that'll certainly fall within CMake best-practices that way

**Comment by Antidote** [comment]
Yeah, that mitigates a whole host of issues.

**Comment by jackoalan** [comment]
#17 has addressed the problem
(also, I didn't mean to open a whole separate issue for this, oops)
