### ISSUE TITLE
Change ICD loader interface for version negotiation

### ISSUE THREAD

**Issue by jon-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#180]
First need to change documentation; secondly need to implement this in loader.

From Daniel Rakos' proposal here is the overview of what is being proposed:

I'd like to propose the following API for this:

VKAPI_ATTR VkResult VKAPI_CALL vk_icdNegotiateLoaderICDInterfaceVersion(uint32_t* pSupportedVersion);

This entry point would be exposed by ICDs and would report the "loader-ICD interface" version supported and would be the first entry point called in the ICD by the loader (passing the "loader-ICD interface" version supported by the loader itself). This entry point would not be part of the Vulkan API itself, only a private interface between the loader and ICDs similarly to vk_icdGetInstanceProcAddr.

This way if a loader sees that an ICD does not export this symbol it knows that it's dealing with a legacy ICD. Similarly, if an ICD sees a call to vk_icdGetInstanceProcAddr before a call to vk_icdGetLoaderICDInterfaceVersion then it knows that it's dealing with a legacy loader.

Though even this trick is only necessary when introducing this new loader-ICD interface entry point, as all subsequent changes to the loader-ICD interface can be done by using the value returned by this new entry point. Such an interface could prove useful even in the future as its use isn't limited to resolving this particular issue.

We could eventually think about deprecating old interface versions (e.g. an ICD might decide to no longer to support a very old interface version or we could decide that the loader should drop support for certain legacy interface versions). We probably have quite some time to think about that, but the complete proposal for the semantics of this new entry point would look as follows:

The pSupportedVersion parameter passed should be filled by the loader before the call with the latest interface version supported by the loader.

If the ICD receiving the call no longer supports the interface version provided by the loader (due to deprecation) then it can report VK_ERROR_INCOMPATIBLE_DRIVER error, otherwise it sets the value pointed by pSupportedVersion to the latest interface version supported by the ICD and returns VK_SUCCESS. The ICD should report VK_SUCCESS in case the loader provided interface version is newer than that supported by the ICD, as it's the loader's responsibility to determine whether it can support the older interface version supported by the ICD.

If the loader receives back an interface version from the ICD that the loader no longer supports (due to deprecation) or it receives a VK_ERROR_INCOMPATIBLE_DRIVER error instead of VK_SUCCESS then the loader will treat the ICD as incompatible and will not try to load it for use. This way both cases are handled: when the ICD only supports an interface version deprecated by the loader, and when the loader only supports an interface version deprecated by the ICD.

Just to further clarify the semantics of the negotiation interface and the actual interface version used, here's some pseudo-code:

ICD pseudo-code:

VKAPI_ATTR VkResult VKAPI_CALL vk_icdNegotiateLoaderICDInterfaceVersion(uint32_t* pSupportedVersion)
{
    if (*pSupportedVersion < minSupportedInterfaceVersion)
    {
        // Loader is too old, ICD no longer supports that interface version
        return VK_ERROR_INCOMPATIBLE_DRIVER;
    }
    else
    {
        if (*pSupportedVersion < currentInterfaceVersion)
        {
            // Expect the loader will use its own interface version because it's older than the ICD's
        }
        else
        {
            // Expect the loader will use the ICD's latest interface version because it probably supports that
        }

        // Report the latest supported version
        *pSupportedVersion = currentInterfaceVersion;
    }
}

Loader pseudo-code:

bool GetInterfaceVersionToUseWithICD(ICDHandle icd, uint32_t* pVersion)
{
    vk_icdNegotiateLoaderICDInterfaceVersion = icd.GetProcAddr("vk_icdNegotiateLoaderICDInterfaceVersion");

    if (vk_icdNegotiateLoaderICDInterfaceVersion == nullptr)
    {
        // ICD does not support the negotiation API, i.e. it supports version zero
        *pVersion = 0;
    }
    else
    {
        // ICD supports the negotiation API, so call it with the loader's latest version supported
        *pVersion = currentInterfaceVersion;
        VkResult result = vk_icdNegotiateLoaderICDInterfaceVersion(pVersion);

        if (result == VK_INCOMPATIBLE_DRIVER)
        {
            // ICD no longer supports the loader's latest interface version so fail loading the ICD
            return false;
        }
    }

    if (*pVersion < minSupportedInterfaceVersion)
    {
        // Loader no longer supports the ICD's latest interface version so fail loading the ICD
        return false;
    }
    else if (*pVersion < currentInterfaceVersion)
    {
        // The ICD's latest interface version is older than the loader's latest interface version but still usable as is
        return true;
    }
    else
    {
        // The ICD's latest interface version is the same or newer than the loader's latest interface version so use the latter
        *pVersion = currentInterfaceVersion;
        return true;
    }
}

Clarified by this:
Modify the negotiation rules to say that if the loader's version is supported by the ICD, but less than the ICD's maximum-supported version, the ICD should return back the loader's version, and assume that this is the version that will be used. In other words, the ICD always returns the version that will be used, unless the loader rejects the ICD as being too old.

**Comment by courtney-g** [comment]
Sounds pretty good to me.

I wonder, will a single number always be sufficient?
If we want this interface to be extensible, we may want to define a CreateInfo structure with sType, pNext and data.

**Comment by jon-lunarg** [comment]
That is a good idea for unknown future changes.

**Comment by jon-lunarg** [comment]
Added version negotiation to loader document and source code.
