### ISSUE TITLE
Give error when requesting device extensions on instance creation and vice versa

### ISSUE THREAD

**Issue by ratchetfreak** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1807]
It's a pretty common mistake I see by newcomers.

**Comment by mark-lunarg** [comment]
Added to existing placeholder issue #1612.  Thanks!

**Comment by mark-lunarg** [comment]
This check is now available in the Assistant Layer, hosted in the [Github VulkanTools repository](https://github.com/LunarG/VulkanTools), and soon to be available in the Vulkan SDK.
