### ISSUE TITLE
Change ICD loader interface so VkSurfaceKHR object creation destruction is done by ICD

### ISSUE THREAD

**Issue by jon-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#181]
Currently this object creation and destruction is done by loader rather than the ICD.  Change this so
ICD handles the creation and destruction of these objects.  Loader will need to be able to handle this in multi-ICD  case (ie app see the loaders instance of the object, each ICD sees it's instance of the object).  The loader needs to associate any ICD, VkPhysicalDevice, VkInstance or VkDevice info  with the VKSurfaceKHR object as needed.

First step is issue #180 version negotiation.
Second step is to change the documentation for this.
Third step is to implement this in the loader.

**Comment by MarkY-LunarG** [comment]
Exposed for testing by some IHVs in marky_loader_3 branch.

**Comment by MarkY-LunarG** [comment]
Finally changes committed in 3 commits ending with commit 609c7c1f222f3243f313bb59cf9210466a719530.
