### ISSUE TITLE
Tests: fix general confusion about supported vs enabled extensions

### ISSUE THREAD

**Issue by chrisforbes** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1827]
Various tests check for the physical device supporting an extension to gate some piece of logic, but don't bother to actually enable it.

**Comment by mark-lunarg** [comment]
I am actually fixing this now.  Added validation for enabled extensions and now get 500+ unexpected errors in the LVT.

**Comment by daveh-lunarg** [comment]
Just put up PR #1843 that at least partially addresses this issue.  I don't think it helps with Mark's 500+ errors.

**Comment by mark-lunarg** [comment]
The errors manifested if you tried to verify at getprocaddress time, which is a bad idea.  Shifted to doing this at entrypoint-call-time.
