### ISSUE TITLE
layers: Code should adhere to RAII

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1848]
There's bunch of memory management problems (#1787) and reviewing maze of raw news and deletes is nontrivial (#1841) for puny humans.

I think the layers should make use of the advantages (modern) C++ has to offer and try a RAII approach.
It may also potentially help with making the locking of the layer state more systematic.

I want to experiment with this myself, so I would appreciate information on design and concerns that lead to the current approach.

**Comment by chrisforbes** [comment]
@krOoze no objections. Very slowly heading in that direction already-- feel free to speed it up.

**Comment by tobine** [comment]
@krOoze I'd classify the "design and concerns that lead to the current approach" as "get as many checks in and working as quickly as possible prior to Vulkan 1.0 release." :)

As @chrisforbes said, work is slowly proceeding to clean things up. Any assistance in this area is welcome and encouraged.

BTW, thanks for all of your contributions of both issues and PRs thus far, it's a great help.

**Comment by mark-lunarg** [comment]
@krOoze, any feelings one way or another about closing this issue?

**Comment by krOoze** [comment]
Outright raw pointers seem to have been replaced with `unique_ptr`s, and there was other such changes on that level.

I am not sure where to progress from here. Something could be done with the overall architecture of the layers, but I would expect such Issue to hang here for years (and I don't see myself to do anything about it in forseeable future either), so I think I may as well close this.
