### ISSUE TITLE
core validation: possible image state false positive

### ISSUE THREAD

**Issue by TiemoJung** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1851]
Hi,

we just changed some stuff in our renderer to take advantage of not needing to transfer images to their use state if the operation would replace the complete content of that image anyways. But the layer complains about the wrong layout. In our specific case, we copy our backbuffer color image into the swapchain image. The swapchain image is kept as is after it was acquired. After the copy operation the needed barrier from transfer dst to wsi src is done, as the content of the image should be preserved for presentation (so get from wsi -> copy (and forced state to transfer dst by the copy op) -> barrier (transfer dst -> wsi src) -> submit to wsi).

So this is also a question if this is a bug by us or a bug of the layer?
As i read the spec, there is no requirement to transfer the state away from wsi src.

**Comment by chrisforbes** [comment]
I believe this is your bug.

Even if you don't care about preserving contents, a subresource must be transitioned to the layout you use it under. If you don't need to preserve the contents, it's always valid to specify `VK_IMAGE_LAYOUT_UNDEFINED` as the previous layout, which should make the actual cost of the transition very small, but you must still do it:

> VU for `vkCmdCopyImage`:
>`dstImageLayout` **must** specify the layout of the image subresources of `dstImage` specified in `pRegions` at the time this command is executed on a `VkDevice`

If you disagree, point me at the spec language that supports your theory of not needing a layout transition if you replace the entire content.

**Comment by TiemoJung** [comment]
I think you are correct.
