### ISSUE TITLE
DescriptorSets: Use shared_ptr for DescriptorSetLayout data instead of copies

### ISSUE THREAD

**Issue by mark-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1869]
DescriptorSets need access to DSLayout state, which was handled via pointers (problematic if DSLayouts were destroyed) but is now handled by making copies of the DSLayout data for each descriptorSet.  This could be better managed by using shared_ptrs.

**Comment by tobine** [comment]
I'll take this @mark-lunarg 
Lemme know if you are already into development and want to keep it, otherwise I'll proceed.

**Comment by mark-lunarg** [comment]
No! Forge ahead.
