### ISSUE TITLE
tests: vkvalidatelayerdoc.sh hardcodes path to the layer directory

### ISSUE THREAD

**Issue by jozefkucia** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1878]
`vkvalidatelayerdoc.sh` assumes that a build directory is located in a direct subdirectory of the repository root. It is a bit inconvenient because it prevents from running all tests easily when a directory structure is different.

**Comment by tobine** [comment]
Yeah, I don't like this assumption. Submitted #1883 to disable doc val from run_all_tests scripts temporarily until I have a better solution for running doc val from a build.
