### ISSUE TITLE
Cube built for XLIB gets seg fault at exit

### ISSUE THREAD

**Issue by Tony-LunarG** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1894]
Call to XCloseDisplay seg faults.  Cubepp too. Build with -DDEMOS_WSI_SELECTION=XLIB
 run and then hit esc to reproduce

**Comment by mark-lunarg** [comment]
@Tony-LunarG, can you assign this one please?

**Comment by karl-lunarg** [comment]
http://www.xfree86.org/4.7.0/DRI11.html suggests that the (GL, but Vulkan here) can register a callback with Xlib.  When the application calls XCloseDisplay, this callback is called and will segfault if the driver had already been unloaded, which could happen when the Vulkan instance is destroyed. Fix is to destroy the instance after cleaning up the display connection.

I also added a build/test of this config to CI testing.
