### ISSUE TITLE
Incorrect validation warning with vkAcquireNextImageKHR fence

### ISSUE THREAD

**Issue by MOARdV** [KhronosGroup/Vulkan-LoaderAndValidationLayers#19]
Reposted by request from [this forum thread](https://forums.khronos.org/showthread.php/12971-vkAcquireNextImageKHR-fence):

When supplying a fence to vkAcquireNextImageKHR, later calls to query fence status or wait on the fence generate a validation error:

"[MEM] Code 14: vkGetFenceStatus called for fence 0x26f310b1c40 which has not been submitted on a Queue"

**Comment by karl-lunarg** [comment]
This was fixed right after the code cutoff for the SDK 1.0.3 release in [this commit](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/commit/e1a61848f5d302c52bd4775b6421007498194745).

It is probably best to get the latest code from this repository.

To see this fix working, get the latest code from this repo and make the changes to cube.c described in the attached cube_diff.txt.  Run cube with `cube --validation` and you should not see the validation warning.

You can reverse the effect of the fix by applying the change to the mem_tracker layer, in the attached mem_tracker_diff.txt file.  With that change backed out, you should see the validation warnings.


[cube_diff.txt](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/files/151691/cube_diff.txt)
[mem_tracker_diff.txt](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/files/151692/mem_tracker_diff.txt)
