### ISSUE TITLE
CMake generation code fails since commit 227aa78

### ISSUE THREAD

**Issue by kyrios123** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1909]
Since commit 227aa78, the CMake generation code fails on my computer:
```
CMake Error at layers/CMakeLists.txt:77 (add_dependencies):
  Cannot add target-level dependencies to non-existent target
  "VkLayer_core_validation-json".

  The add_dependencies works for top-level logical targets created by the
  add_executable, add_library, or add_custom_target commands.  If you want to
  add file-level dependencies see the DEPENDS option of the add_custom_target
  and add_custom_command commands.


CMake Error at layers/CMakeLists.txt:77 (add_dependencies):
  Cannot add target-level dependencies to non-existent target
  "VkLayer_object_tracker-json".

  The add_dependencies works for top-level logical targets created by the
  add_executable, add_library, or add_custom_target commands.  If you want to
  add file-level dependencies see the DEPENDS option of the add_custom_target
  and add_custom_command commands.


CMake Error at layers/CMakeLists.txt:77 (add_dependencies):
  Cannot add target-level dependencies to non-existent target
  "VkLayer_unique_objects-json".

  The add_dependencies works for top-level logical targets created by the
  add_executable, add_library, or add_custom_target commands.  If you want to
  add file-level dependencies see the DEPENDS option of the add_custom_target
  and add_custom_command commands.


CMake Error at layers/CMakeLists.txt:77 (add_dependencies):
  Cannot add target-level dependencies to non-existent target
  "VkLayer_parameter_validation-json".

  The add_dependencies works for top-level logical targets created by the
  add_executable, add_library, or add_custom_target commands.  If you want to
  add file-level dependencies see the DEPENDS option of the add_custom_target
  and add_custom_command commands.


CMake Error at layers/CMakeLists.txt:77 (add_dependencies):
  Cannot add target-level dependencies to non-existent target
  "VkLayer_swapchain-json".

  The add_dependencies works for top-level logical targets created by the
  add_executable, add_library, or add_custom_target commands.  If you want to
  add file-level dependencies see the DEPENDS option of the add_custom_target
  and add_custom_command commands.


CMake Error at layers/CMakeLists.txt:77 (add_dependencies):
  Cannot add target-level dependencies to non-existent target
  "VkLayer_threading-json".

  The add_dependencies works for top-level logical targets created by the
  add_executable, add_library, or add_custom_target commands.  If you want to
  add file-level dependencies see the DEPENDS option of the add_custom_target
  and add_custom_command commands.
```
It's obvious I missed something but I can't find what... anyone could help me please ?

**Comment by MarkY-LunarG** [comment]
You would get these errors if the projects for each of the layers failed to build the corresponding layer library and then the dependency check attempted to connect to those libraries.  The actual generated Cmake output files should be identical to before.

1. Have you wiped out your build folder and started again?
2. Is this Linux or Windows?  I'm building on Linux and Windows 64 with no issue.
3. For a clean build (which I do after ever pull/fetch), I do the following on Linux (and similar on Windows):

```
pushd external
rm -rf *
popd
update_external_sources.sh
rm -rf build
cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug
pushd build
make -j4
popd
```

**Comment by karl-lunarg** [comment]
Did you issue the CMake command from the top level directory?  It sort of
looks like you issued it from the layers directory.

It may also be helpful to post the CMake command you used.

**Comment by kyrios123** [comment]
@MarkY-LunarG 
1. Yes, build folder was wiped out
2. Linux x86_64
3. Actually I'm building a Vulkan package and I'm getting the SPIRV tools & headers from another package. I updated that package just before building with the latest available release/commit just before building Vulkan, so I know it is up-to-date but now you point this out, I guess this is where I should look for.

@karl-lunarg 
Yes I did issue the CMake from the top level directory. Here is the command I use:
```
cmake -DBUILD_WSI_MIR_SUPPORT=OFF \
            -DBUILD_WSI_WAYLAND_SUPPORT=ON . \
            -DGLSLANG_SPIRV_INCLUDE_DIR=/usr/include/spirv-tools \
            -DBUILD_TESTS=OFF \
            -DBUILD_LAYERS=ON
```

* [output of the command](https://hastebin.com/ojirecosil) (on screen)
* [CMakeError.log](https://hastebin.com/alasoleved)
* [CMakeOutput.log](https://hastebin.com/nefevahagu)

Thanks for the help, I really appreciate !

**Comment by karl-lunarg** [comment]
If I issue the exact same cmake command you give, I get the same result you posted.

If I add `-H. -Bbuild`  (the specification of the out-of-build build folder being the important item here), then cmake completes OK.

Any chance you somehow forgot to specify the build dir?

**Comment by kyrios123** [comment]
@karl-lunarg Thanks! This was indeed the problem. 
The issue can be closed.
