### ISSUE TITLE
Crash inside object_tracker

### ISSUE THREAD

**Issue by RCalocaO** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1911]
SDK 1.0.51.0

> Obj 0000000000000000 Loc 2751 Msg 364905094 ParameterValidation vkUpdateDescriptorSets(): if pDescriptorWrites[0].descriptorType is VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER or VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER, pDescriptorWrites[0].pTexelBufferView must not be NULL. The spec valid usage text states 'If descriptorType is VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER or VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER, pTexelBufferView must be a pointer to an array of descriptorCount valid VkBufferView handles' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkWriteDescriptorSet-descriptorType-00323)
> Exception thrown at 0x000007FEAB822FD4 (VkLayer_object_tracker.dll) in UE4Editor-Win64-Debug.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

It will crash here on UpdateDescriptorSets() trying to dereference pTexelBufferView when it's NULL.
                        

> skip |= ValidateObject(device, pDescriptorWrites[idx1].pTexelBufferView[idx2], kVulkanObjectTypeBufferView,
>                                                false, VALIDATION_ERROR_15c00286, VALIDATION_ERROR_15c00009);

**Comment by Tony-LunarG** [comment]
So are you saying that for a descriptor of type UNIFORM_TEXEL_BUFFER or STORAGE_TEXEL_BUFFER, you pass NULL for pTexelBufferView and the layers crash?  If so, before the crash do you see an error message from ParameterValidation explaining that pTexelBufferView must not be NULL?

**Comment by RCalocaO** [comment]
Yes you are correct.
