### ISSUE TITLE
Add warning when a parameter of vkCmdDispatch is 0

### ISSUE THREAD

**Issue by RenatoUtsch** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1912]
I'm currently getting images from the swapchain, drawing to them with a **compute** shader and sending them for presentation. When I first implemented this, my application would inexplicably **freeze** my windowing system, and there were no messages from the validation layers to help me discover the problem. I initially thought I was transitioning the swapchain images wrongly, but after some hours of debugging I discovered that the problem was this call:

```c
vkCmdDispatch(commandBuffer, width, height, 0);
```

By setting the z dimension work groups to 0, I was effectively skipping my compute shader, and this would somehow freeze the windowing system (until my application crashed due to connection lost to the device).

It looks likethe vkCmdDispatch documentation doesn't specify that the group counts *can't* be 0, but why would someone want to dispatch a shader with 0 work groups? The shader would effectively be skipped.

That's why I'm proposing to add a warning when any of the group counts of the vkCmdDispatch call are 0. This would have saved me hours of debugging and will probably help a lot of people in the future.

Does this sounds like a good idea?

**Comment by RenatoUtsch** [comment]
I can implement this and submit a pull request if it sounds a good idea.

If I'm not mistaken, it would just be needed to add checks in this function, right?
https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/d2ecdb33a78ea2a0a8f868497448d0df627fc5ac/layers/parameter_validation.cpp#L3454

**Comment by tobine** [comment]
This sounds like a good idea to me. Yes, the code you flagged in parameter_validation.cpp would be a good place to add the warning. Here's an [example warning](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/d2ecdb33a78ea2a0a8f868497448d0df627fc5ac/layers/parameter_validation.cpp#L3388) from that same file.

**Comment by chrisforbes** [comment]
:+1: from me. I think you want to report that crash to your driver vendor too though; that sounds completely broken.

**Comment by RenatoUtsch** [comment]
Yeah. I'll try to narrow it out first though. My first guess is that trying to call vkQueueWaitIdle() on a queue where I dispatched a compute shader with a work group count of 0 makes the device freeze and I lose connection to it device.

**Comment by mark-lunarg** [comment]
Moving to the assistant layer -- to be tracked in issue #1612.
