### ISSUE TITLE
Potentially invalid fence warning

### ISSUE THREAD

**Issue by RCalocaO** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1914]
Trying to delete a fence I had been using with vkAcquireNextImageKHR, and after calling vkDestroySwapchainKHR, and trying to delete the fence, I get

> *** [ERROR] DS618662080 Obj 0x000000000000052A Loc 3088 Fence 0x52a is in use. The spec valid usage text states 'All queue submission commands that refer to fence must have completed execution' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyFence-fence-01120)

I would expect I don't have to wait for the fence as I deleted the swapchain?

**Comment by TiemoJung** [comment]
Is your chain of commands like this?:
1. acquire swapchain image and passing fence with it
2. delete swapchain
3. delete fence

If yes, it would be probably best to wait first for the fence and then delete anything.

Besides that, using a fence to sync an swapimage is not optimal, using a semaphore is always preferable.

**Comment by RCalocaO** [comment]
Thanks, I will confirm. We use a fence since we sometimes need to control the locked framerate.

**Comment by chrisforbes** [comment]
Closing as WAI -- you must not delete the fence when there is an operation in flight which will signal it.
