### ISSUE TITLE
CMake out of tree build has errors

### ISSUE THREAD

**Issue by MaciejJesionowskiAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1922]
This started happening a few days ago. My compilation is failing with this error:

> CUSTOMBUILD : error : Could not find vk_validation_error_messages.h [C:\Users\Maciek\Builds\vulkan-lvl\layers\VkLayer_parameter_validation.vcxproj]

This is on Windows. I like to build the loader and layers with CMake without using the provided scripts:

1. I create a separate build directory, not inside the source tree.
2. I set it up with: cmake -G "Visual Studio 14 Win64" PATH_TO_SOURCE
3. Then I simply build with: cmake --build . -- /m

The problem is the script `parameter_validation_generator.py` has a few relative paths to the `vk_validation_error_messages.h` file, but with this build method the current working directory is the build directory rather than the source directory. Consequently, the script cannot find the file.

This could be fixed by adding the header file to the outputs, so it ends up in the build directory, or maybe by passing the path to the original file. Not sure what works best for you, so I'm not trying to propose a fix for this.

**Comment by sl1pkn07** [comment]
same here in linux box

**Comment by mark-lunarg** [comment]
Hey @MaciejJesionowskiAMD, @sl1pkn07, can you guys give this a quick checkout?

**Comment by MaciejJesionowskiAMD** [comment]
Yep, it's working again, thanks.

It would also be awesome if there was an option to choose which arch and config is built for dependencies with update_external_sources.bat. For example, to only build x64 Debug. This isn't a big deal, but saves time and space on a clean checkout.

**Comment by mark-lunarg** [comment]
@MaciejJesionowskiAMD, yeah, the amount of time it takes to run that script on Windows drives me crazy.  Thanks for checking out the PR!
