### ISSUE TITLE
Some comments in C header files are not C-style

### ISSUE THREAD

**Issue by grim210** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1926]
To be able to compile my Vulkan project with GCC flag -std=c90, all comments in the vulkan header files must conform to using C-style comments.  Comments that
`// look like this`
will not compile.  However, if they
`/* look like this */`
it will compile perfectly.  My use case is probably rare, but compiling with clean C90 makes me feel warm inside.

**Comment by mark-lunarg** [comment]
@grim210, outside of the loader, we don't have a bunch of these files.  Can you enumerate the ones that are giving you trouble?  Our coding standards enforce //-style comments universally, except in copyright notices or file headers and currently make no exceptions for the older C standards.

**Comment by MarkY-LunarG** [comment]
Some of the files aren't owned by us, the come from Khronos.  The others, as @mark-lunarg points out, is based on our coding standard.

Looking at the top-level CMakeLists.txt file, -std=c99 should be automatically set.  Are you not using CMake?

**Comment by mark-lunarg** [comment]
As I mentioned in the PR, I'm closing this issue for now, at least until the main Vulkan working group updates their header files.
