### ISSUE TITLE
Enabling both VK_KHR_maintenance1 and VK_AMD_negative_viewport_height at the same time does not fail validation

### ISSUE THREAD

**Issue by marco-we** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1933]

**Comment by marco-we** [comment]
Enabling both VK_KHR_maintenance1 and VK_AMD_negative_viewport_height at the same time does not fail validation.

It should according to the valid usage section of **VkDeviceCreateInfo**:

> * **ppEnabledExtensionNames** must not contain both VK_KHR_maintenance1 and VK_AMD_negative_viewport_height

**Comment by tobine** [comment]
This is VALIDATION_ERROR_056002ec, needs to be implemented.

**Comment by mark-lunarg** [comment]
@marco-we, the fix has been pushed to Master -- thanks for opening the issue!
