### ISSUE TITLE
Implement VUID-VkImageViewCreateInfo-image-01014  validation check

### ISSUE THREAD

**Issue by jlegg0** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1937]
Several validation checks for vkCreateImageView are not currently implemented, among them is VUID-VkImageViewCreateInfo-image-01014:

>  If image was created with VK_IMAGE_TILING_OPTIMAL and usage contains VK_IMAGE_USAGE_STORAGE_BIT, format must be supported for storage images, as specified by the VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT flag in VkFormatProperties::optimalTilingFeatures returned by vkGetPhysicalDeviceFormatProperties with the same value of format

On all of the 3 Vulkan implementations I checked, this would make creation of an FORMAT_R8G8B8A8_SRGB view of a FORMAT_R8G8B8A8_UNORM image created with with VK_IMAGE_USAGE_STORAGE_BIT invalid, but the validation layer did not report an issue.

**Comment by jeremyk-lunarg** [comment]
#1957 Should take care of this issue.
