### ISSUE TITLE
Writable and executable sections in libvulkan.so

### ISSUE THREAD

**Issue by mattst88** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1956]
Gentoo's package manager warns:

 * QA Notice: The following files contain writable and executable sections
 *  Files with such sections will not work properly (or at all!) on some
 *  architectures/operating systems.  A bug should be filed at
 *  https://bugs.gentoo.org/ to make sure the issue is fixed.
 *  For more information, see:
 * 
 *    https://wiki.gentoo.org/wiki/Hardened/GNU_stack_quickstart
 * 
 *  Please include the following list of files in your report:
 *  Note: Bugs should be filed for the respective maintainers
 *  of the package in question and not hardened@g.o.
 * RWX --- --- usr/lib64/libvulkan.so.1.0.54

It does not occur with 1.0.51.0 but does with 1.0.54.0. Looking through git, I assume it is a result of commit 1b88cb983ece32b88bea4d5ee5b107e53705a226 and the follow-on commits.

**Comment by lenny-lunarg** [comment]
The pull request I created that just referenced this issue should be a fix for your problem. I ran `scanelf` as the article you linked shows, and the problem appears to be resolved. Do you have any other way I can verify that the problem is resolved, or is running `scanelf` good enough?

**Comment by mattst88** [comment]
Nope, that's works great.

Thanks for the really quick turn-around!

If you want, feel free to add a

Tested-by: Matt Turner <mattst88@gmail.com>

tag to your commit.

**Comment by lenny-lunarg** [comment]
The fix is now on master as commit 75645294adadeac5779e7939a4637e5ed256f9db.
