### ISSUE TITLE
Validation layer: Load / store ops are not verified at vkCreateRenderPass() call time

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1967]
Seems like a trivial omission.

**Comment by tobine** [comment]
Generated parameter_validation.h verifies that the loadOp and storeOp values are valid enums.
These are VUIDs VALIDATION_ERROR_0080c201 & VALIDATION_ERROR_0082e401.

Is this what you're referring to?
Here's the code:

`skipCall |= validate_ranged_enum(layer_data->report_data, "vkCreateRenderPass", ParameterName("pCreateInfo->pAttachments[%i].loadOp", ParameterName::IndexVector{ attachmentIndex }), "VkAttachmentLoadOp", VK_ATTACHMENT_LOAD_OP_BEGIN_RANGE, VK_ATTACHMENT_LOAD_OP_END_RANGE, pCreateInfo->pAttachments[attachmentIndex].loadOp, VALIDATION_ERROR_0080c201);`

`skipCall |= validate_ranged_enum(layer_data->report_data, "vkCreateRenderPass", ParameterName("pCreateInfo->pAttachments[%i].storeOp", ParameterName::IndexVector{ attachmentIndex }), "VkAttachmentStoreOp", VK_ATTACHMENT_STORE_OP_BEGIN_RANGE, VK_ATTACHMENT_STORE_OP_END_RANGE, pCreateInfo->pAttachments[attachmentIndex].storeOp, VALIDATION_ERROR_0082e401);`

**Comment by mark-lunarg** [comment]
Assigning @tobine until @DominikWitczakAMD answers -- if work needs to be done I'll reassign.

**Comment by DominikWitczakAMD** [comment]
Let me re-check with the latest version from the headline branch. I'm pretty sure core the version of core validation layer I'm using at the moment did not catch this.

**Comment by DominikWitczakAMD** [comment]
Ah, gotcha! These errors are covered by parameter validation layer which I hadn't enabled when I ran into this issue. After including it in the layer chain, the error is indeed reported. Apologies for the false alarm!
