### ISSUE TITLE
Validation for VK_KHR_PUSH_DESCRIPTOR_EXTENSION_NAME seems broken

### ISSUE THREAD

**Issue by danielmaciel** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1980]
When using 'VK_KHR_PUSH_DESCRIPTOR_EXTENSION_NAME', I get an Object Tracker error:

"ObjectTracker(ERROR): object: 0x0 type: 24 location: 186 msgCode: -1: Invalid DescriptorSet Object 0x0. (null)"

My guess is I get that error for not specifying a Descriptor Set in the conventional way, instead pushing a descriptor write using the aforementioned extension.

The funny thing is, if I do not call vkCmdPushDescriptorSetKHR at all and not set a descriptor set in the conventional way either, I do not get any Object Tracker errors. So maybe there is some inverted logic there somewhere?

I'm using a single Descriptor Set Layout with two bindings, one for an Uniform Buffer and the other one for a Combined Image Sampler (not that it matters?)

**Comment by danielmaciel** [comment]
(I'm using the latest code downloaded from the git repository)

**Comment by Tony-LunarG** [comment]
I believe this to be fixed with PR #1993, commited earlier this afternoon

**Comment by danielmaciel** [comment]
That fixed it for me. Thanks!
