### ISSUE TITLE
VK_DBG_LAYER_ACTION_BREAK not working

### ISSUE THREAD

**Issue by dor666** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1991]
Enabling VK_DBG_LAYER_ACTION_BREAK didn't worked for me.
Also I don't see it used in sources.

**Comment by mark-lunarg** [comment]
@dor666, give the latest Master another shot.

**Comment by dor666** [comment]
Wow, that was fast. Thanks Mark :)
