### ISSUE TITLE
Missing error when freeing a renderpass that was used to create active framebuffers

### ISSUE THREAD

**Issue by haasn** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2016]
In this sequence of events:

1. `vkCreateRenderPass(..., &dummyPass);`
2. `vkCreateFramebuffer(..., {... .renderPass = dummyPass }, &framebuffer);`
3. `vkDestroyRenderPass(..., dummyPass);`
... later
4. `vkCreateRenderPass(..., &realPass);`
5. `vkCmdBeginRenderPass(..., { .renderPass = realPass, .framebuffer = framebuffer });`

I get a segfault in libnvidia-gl.so. I'm not entirely sure if this is legal by spec or not - I was not aware that you had to keep around the “dummy pass” used to determine framebuffer compatibility for as long as you keep the framebuffer around. It certainly surprises me. So in case this is, in fact, undefined behavior (and not an nvidia bug), a warning would be very beneficial.

**Comment by cforfang** [comment]
Based on the discussion in issue #516 I think what you're doing is valid and that is an NVIDIA bug.

**Comment by haasn** [comment]
Okay. What's the status quo of vendor bugs in the layers? Do you bother printing a debug message in cases where code is technically correct but is known to crash on some platforms, or is that considered out-of-scope of the validation layers?

**Comment by haasn** [comment]
Cross-posted to https://devtalk.nvidia.com/default/topic/1022963/linux/vulkan-driver-segfaults-on-spec-compliant-call-sequence/

**Comment by mark-lunarg** [comment]
@haasn, we don't do any vendor-specific stuff in the layers (thank goodness).  Will close this for now, reopen if the focus shifts back to validation.  Thanks!

**Comment by pdaniell-nv** [comment]
@haasn what driver version were you using? We recently fixed a bug in our driver related to this. The fix isn't yet available in a general-release driver, but it is in the latest Vulkan beta driver, if you want to try it out: https://developer.nvidia.com/vulkan-driver.

**Comment by haasn** [comment]
@pdaniell-nv Apologies for not specifying. I was using 384.59-r1.

**Comment by pdaniell-nv** [comment]
@haasn thanks for the follow-up. Driver 384.59 has the bug I was thinking of that's now fixed in the beta driver. A general-release driver with the fix should be coming out soon.
