### ISSUE TITLE
Please remove "any subsequent sets were disturbed by newly bound pipelineLayout" warning

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2020]
We - among many other Vulkan developers - are getting this warning in our code:

> DescriptorSet 0x9dfc6 previously bound as set #0 is incompatible with set 0x392e9478 newly bound as set #0 so set #1 and any subsequent sets were disturbed by newly bound pipelineLayout (0x275)

It happens when we use a pipeline/pipeline layout with two sets, and then switch to a different pipeline layout that just uses set #0. The layers complain about the incompatibility and the fact that set #1 is disturbed by the new binding, however I don't intend to actually use set #1 anyway.

From what I understand, this issue could be solved if there was a way to call vkCmdBindDescriptorSets and say "I don't care about any other sets - this is a complete binding". This requires spec changes.

I believe this warning in its current state is actively harmful - it raises questions among Vulkan developers ("am I doing something wrong?"), followed by finding information that suggests that it's a false positive in validation layers (for example https://stackoverflow.com/questions/38679060/vkdescriptorset-from-previous-pipeline-giving-performance-warning) followed by either living with a stream of validation warnings, or disabling this specific warning in some hacky way in the validation report callback. As such, it seems strictly better to me to just remove this code from validation layers until a better solution for reporting whatever this warning is trying to report (which I must admit I don't fully understand) is found.

**Comment by gwihlidal** [comment]
+1 to remove - this warning is pretty useless (at least for us).

**Comment by Themaister** [comment]
+1, I find the warning more harmful than the problem it tries to warn about.

**Comment by punkUser** [comment]
+1 kill with fire please.

**Comment by zeux** [comment]
Thank you!
