### ISSUE TITLE
Suggestion: The cube demo could use an easier way to upload textures, vkCopyBufferToImage

### ISSUE THREAD

**Issue by hrydgard** [KhronosGroup/Vulkan-LoaderAndValidationLayers#203]
The cube demo uses a complicated method to upload its texture - when only OPTIMAL tiling is supported, it uses a staging image, and if LINEAR tiling is supported, it uses such a texture.

I first adopted this method myself in my project but hit a roadblock pretty quickly when adding mipmap support - LINEAR staging images can't have mipmaps so you need to create a whole bunch of temporary images in order to use that method.

Instead, I found that writing the image data of all the mipmaps to a buffer and using a bunch of vkCopyBufferToImage calls to copy them directly into an OPTIMAL-tiled image was a much more convenient method. Would it not make more sense to showcase that method in one of the first pieces of Vulkan code many developers will come across?

I've found other developers making the same mistake by browsing open source projects that use Vulkan.

**Comment by lentinem** [comment]
The cube demo in validation is not meant to be a sample; going to repurpose this bug to make that more clear and possibly include it in the test directory instead. Please file this in the vulkan samples repo.

**Comment by hrydgard** [comment]
I think many people (including me, previously) will think it's a sample because unlike the API samples that just draw a frame and then exit, it actually runs continuously, and thus seems like a more interesting minimal base to build on.

**Comment by Tony-LunarG** [comment]
Could you be more specific about what you think cube is doing wrong?  If optimal tiling is necessary for a feature, whether textures, mipmaps, etc,  you have to use a staging buffer.  What mistake is it making?

**Comment by hrydgard** [comment]
It's using a staging **image**, which takes a lot more code and is a lot more complex than using a staging **buffer**. The step from there to adding mipmap support is not obvious as you can't reasonably do that with the staging image approach.

**Comment by mre4ce** [comment]
To avoid excessive synchronization, you'd have to use a separate (linear) staging image per mip level, which imho isn't all that bad (really not all that much code). Either way you use the same amount of memory whether you use a staging image or staging buffer.

I think the cube demo has bigger issues like calling demo_set_image_layout and
demo_flush_init_cmd from demo_draw which ends up calling vkQueueWaitIdle for every draw. I know why we have the cube and tri demos, but labeling them as demos is confusing because I wouldn't recommend anyone to look at this code to learn how to use Vulkan.

**Comment by karl-lunarg** [comment]
Closing due to age and subjective nature of the issue.  The cube app has changed a lot and appears to reuse code in a way that may alleviate the concern about more code needed for staging images.  Please reopen if there's still an unresolved problem in this area.
