### ISSUE TITLE
Need validation layer to add redundancy check for vulkan states.

### ISSUE THREAD

**Issue by Evelyn6** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2034]
Such as vertex buffer states: If a test has many draw,  each draw binds the same vb info, only startVertex and startInstance have difference. Therefore, need skip the redundant vertex buffer modification. But Vulkan driver won't to do redundancy check. Can Validation layers report  a new perf warning for the redundancy states so that application developers can do better?

**Comment by mark-lunarg** [comment]
Adding this to the Assistant layer housekeeping task, #1612.
