### ISSUE TITLE
Core / Parameter Validation: Identity swizzle requirement is not checked for framebuffer attachments

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2037]
In the Valid Usage section for VkFramebufferCreateInfo, we have the following language:

``
Any given element of pAttachments must have been created with the identity swizzle
``

However, no error is raised by either of the layers if a non-identity swizzle is specified for image views that are later requested to be treated as attachments at FB create time.

**Comment by jeremyk-lunarg** [comment]
I looked and found that there is a test written for this which gives the proper error message.  I have included a screenshot of the test and the error message.


![issue-2037](https://user-images.githubusercontent.com/28059237/31836324-212b6f72-b592-11e7-8e55-19f20438172d.png)


Please reopen if you are still having this issue.
