### ISSUE TITLE
windows vulkanrt-installer needs to be signed with SHA-2 (not just SHA-1)

### ISSUE THREAD

**Issue by jjulianoatnv** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2060]
This issue requests that the vulkanrt-installer exe, as well as the .exe and .dll files contained within the installer package, be signed using a SHA-2 certificate.

Currently the vulkanrt-installer is only SHA-1-signed. Due to weak security of SHA-1 certificates, Windows is migrating toward a future where SHA-1 is distrusted throughout Windows in all contexts. On Windows, the vulkanrt-installer is run as part of the install for IHV display drivers. Files installed by displays drivers should be signed with a certificate that is stronger than SHA-1. Using a SHA-2 certificate is recommended.

A security advisory against  SHA-1 certificates can be found here:
- https://technet.microsoft.com/library/security/2880823

It recommends migrating to SHA-2 certificates.
It also links to :
- https://social.technet.microsoft.com/wiki/contents/articles/32288.windows-enforcement-of-sha1-certificates.aspx

This page documents a three phase plan for deprecation of SHA-1 certificates.
This page links to a pdf file:
- http://download.microsoft.com/download/4/5/8/458E1F8C-7A36-4285-8EB2-42E6858D06C1/Microsoft_SHA-1_Guidance_E.pdf

Sections from the pdf file that are of particular relevance include:
- Section 5.2 "Code Signing Certificates"
> Long-term, Microsoft intends to distrust SHA-1 throughout Windows in all contexts.

- Section 7 "Recommended Action", subsection 7.1 step 5, "Contact the issuer of the certificate and renew the certificate"
> If the server is using SHA-1 signed certificate, you must replace it with a certificate with new hashing algorithm, such as SHA-2. Contact the CA that issued the certificate, and renew the certificate."

- Section 6.4 "FAQ on Policy Deployment" discusses that SHA-2 support did not ship on Windows 7, but was added by a KB security patch through Windows Update.

I think that in order to be compatible with both windows 7 and newer Windows versions, that the binaries must be "dual signed". Here is some info about dual-signing that may be helpful:
- For DigiCert : https://www.digicert.com/code-signing/code-signing-dual-signing-sha256-sha1.htm 
- For Symantec Certificate: https://knowledge.symantec.com/support/code-signing-support/index?page=content&id=INFO2274&pmv=print&actp=PRINT

**Comment by jjulianoatnv** [comment]
Win7 support poses an interesting problem for display drivers, which I think may get installed onto a Windows 7 OS before the OS has pulled from Windows Update the patch that adds SHA-2 support.  The vulkanrt-installer gets installed as part of IHV display driver packages. There is a concept called "dual signing" that affects kernel display drivers, where the file is signed with both SHA-1 and SHA-2 certificates. I do not know if the vulkanrt-installer needs to be dual-signed, or if it can be signed with just a SHA-2 certificate. This warrants further investigation. I did find a couple articles related to dual signing:
- https://msdn.microsoft.com/en-us/library/windows/desktop/aa387764%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396
- https://docs.microsoft.com/en-us/windows-hardware/drivers/install/appendix-4--driver-signing-issues

**Comment by jjulianoatnv** [comment]
I edited the description explicitly request that SHA-2 signing apply to both the installer .exe and the files contained within (exe and dll files). The older description text mistakenly forgot to make a claim on the files contained within.

**Comment by jjulianoatnv** [comment]
We think that dual-signing is required. Here is some info on dual-signing that may be helpful:

- For DigiCert : https://www.digicert.com/code-signing/code-signing-dual-signing-sha256-sha1.htm 
- For Symantec Certificate: https://knowledge.symantec.com/support/code-signing-support/index?page=content&id=INFO2274&pmv=print&actp=PRINT

**Comment by lenny-lunarg** [comment]
We've updated our internal build process to take all of the files that were being signed with SHA-1, and also sign them with SHA-256. This means that all dll and exe files in the runtime (and SDK, for that matter) should be dual signed. This will apply to all future SDK releases.

**Comment by jjulianoatnv** [comment]
Using a (private) alpha SDK that was built using the new signing method, I verified that the new signature look good and that they seem to adequately address this issue.  Thanks for the quick action on this issue.
