### ISSUE TITLE
Validation layer proposal

### ISSUE THREAD

**Issue by Jasper-Bekkers** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2061]
A while ago I built a small class that does a vkCmdFillBuffer with a unique ID to a cpu visible buffer, for every marker I have in my code.

That way when I get a DEVICE_LOST message, I can peek in the cpu visible buffer and print the last marker I crossed.

I figured it might be a nice feature to have in a validation layer.

**Comment by karl-lunarg** [comment]
Added to #1612

**Comment by mark-lunarg** [comment]
This, or something similar, gets a +1 from Hai.
