### ISSUE TITLE
RenderPassIncompatible test have unexpected validation messages

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2080]
Running `vk_layer_validation_tests` I get:

> [ RUN      ] VkLayerTest.RenderPassIncompatible
Unexpected: vkCmdBeginRenderPass(): RenderPasses incompatible between render pass w/ renderPass 0xe and framebuffer w/ renderPass 0x6 Attachment 0 is not compatible with 4294967295: The second is unused while the first is not.. The spec valid usage text states 'renderPass must be compatible with the renderPass member of the VkFramebufferCreateInfo structure specified when creating framebuffer.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkRenderPassBeginInfo-renderPass-00904)
Unexpected: vkCmdBeginRenderPass(): RenderPasses incompatible between render pass w/ renderPass 0xe and framebuffer w/ renderPass 0x6 Attachment 0 is not compatible with 0: They have different formats.. The spec valid usage text states 'renderPass must be compatible with the renderPass member of the VkFramebufferCreateInfo structure specified when creating framebuffer.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkRenderPassBeginInfo-renderPass-00904)
Unexpected: vkCmdDraw(): RenderPasses incompatible between active render pass w/ renderPass 0xe and pipeline state object w/ renderPass 0x6 Attachment 0 is not compatible with 0: They have different formats.. The spec valid usage text states 'The current render pass must be compatible with the renderPass member of the VkGraphicsPipelineCreateInfo structure specified when creating the VkPipeline currently bound to VK_PIPELINE_BIND_POINT_GRAPHICS.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkCmdDraw-renderPass-00435)
[       OK ] VkLayerTest.RenderPassIncompatible (442 ms)

**Comment by mark-lunarg** [comment]
I believe this has been fixed.

**Comment by krOoze** [comment]
It would seem so.
