### ISSUE TITLE
No error when recreating swapchain while rendering to an existing swapchain image

### ISSUE THREAD

**Issue by haasn** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2089]
The following sequence of calls appears to be UB:

1. `vkAcquireNextImageKHR(swapchain, ...);`
2. Render to this swapchain image
3. `vkQueuePresentKHR(...)`
4. (without delay) `vkCreateSwapchain(..., { .oldSwapchain = swapchain });`

That is to say, it seems to be UB to recreate the swapchain while an image acquisition or rendering command to this swapchain is ongoing; leading to a deadlock on all tested drivers. Inserting a `vkDeviceWaitIdle()` in between steps 3 and 4 solves this issue.

This should be something the layers could easily-ish catch.

**Comment by mark-lunarg** [comment]
Maybe a candidate for the Assistant Layer, #1612.

**Comment by haasn** [comment]
Here is an example of a call sequence that results in a deadlock on current nvidia (384.69):

```
[vo/gpu/vulkan] vkCreateSwapchainKHR (old = 0x7fbbb8fd2ae0, new = 0x7fbbb9151970)
[vo/gpu/vulkan] vkAcquireNextImageKHR(swapchain = 0x7fbbb9151970
[vo/gpu/vulkan] fence signalled for cmd: 'renders to 0x7fbbb8fd2ae0'
[vo/gpu/vulkan] fence signalled for cmd: 'renders to 0x7fbbb8fd2ae0'
[vo/gpu/vulkan] vkDestroySwapchainKHR(0x7fbbb8fd2ae0)
[vo/gpu/vulkan] vkQueueSubmit('renders to 0x7fbbb9151970')
[vo/gpu/vulkan] vkQueuePresentKHR({pSwapchains = &0x7fbbb9151970})
[vo/gpu/vulkan] vkCreateSwapchainKHR (old = 0x7fbbb9151970, new = 0x7fbbb8fbc1b0)
[vo/gpu/vulkan] vkAcquireNextImageKHR(swapchain = 0x7fbbb8fbc1b0
[vo/gpu/vulkan] fence signalled for cmd: 'renders to 0x7fbbb9151970'
[vo/gpu/vulkan] vkDestroySwapchainKHR(0x7fbbb9151970)
[vo/gpu/vulkan] vkQueueSubmit('renders to 0x7fbbb8fbc1b0')
[vo/gpu/vulkan] vkQueuePresentKHR({pSwapchains = &0x7fbbb8fbc1b0})
[vo/gpu/vulkan] vkCreateSwapchainKHR (old = 0x7fbbb8fbc1b0, new = 0x7fbbb8d6e870)
[vo/gpu/vulkan] vkAcquireNextImageKHR(swapchain = 0x7fbbb8d6e870
[vo/gpu/vulkan] fence signalled for cmd: 'renders to 0x7fbbb8fbc1b0'
[vo/gpu/vulkan] vkDestroySwapchainKHR(0x7fbbb8fbc1b0)
[vo/gpu/vulkan] vkQueueSubmit('renders to 0x7fbbb8d6e870')
[vo/gpu/vulkan] vkQueuePresentKHR({pSwapchains = &0x7fbbb8d6e870})
[vo/gpu/vulkan] vkCreateSwapchainKHR (old = 0x7fbbb8d6e870, new = 0x7fbbb8bbe2e0)
[vo/gpu/vulkan] vkAcquireNextImageKHR(swapchain = 0x7fbbb8bbe2e0
[vo/gpu/vulkan] fence signalled for cmd: 'renders to 0x7fbbb8d6e870'
[vo/gpu/vulkan] vkDestroySwapchainKHR(0x7fbbb8d6e870)
[vo/gpu/vulkan] vkQueueSubmit('renders to 0x7fbbb8bbe2e0')
[vo/gpu/vulkan] vkQueuePresentKHR({pSwapchains = &0x7fbbb8bbe2e0})
```

At that point the device just deadlocks completely, and the fences for the last vkQueueSubmit never completes. I have to hammer ^C a few times (while fighting through X being very unresponsive) to terminate the application. On amdgpu, the entire GPU just locks up completely.

This call sequence doesn't seem to disagree with the spec after all, so I assume this bug report is invalid.
