### ISSUE TITLE
Wrong ParameterValidation(ERROR) when using VK_KHR_get_physical_device_properties2

### ISSUE THREAD

**Issue by danielmaciel** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2090]
If one uses VK_KHR_get_physical_device_properties2 and specifies one's features using VkPhysicalDeviceFeatures2KHR instead of VkPhysicalDeviceFeatures and sets 'features. samplerAnisotropy' to VK_TRUE, a 'ParameterValidation(ERROR)' is issued:

ParameterValidation(ERROR): object: 0x0 type: 0 location: 1497 msgCode: 8: vkCreateSampler(): The samplerAnisotropy feature was not enabled at device-creation time, so the maxAnisotropy member of the VkSamplerCreateInfo structure must be 1.0 but is 0.000000.

I suspect this might be true for any feature, not specifically 'samplerAnisotropy', but I might be mistaken as I did not test other cases.

I'm using VkPhysicalDeviceFeatures2KHR by setting VkDeviceCreateInfo 'pEnabledFeatures' to nullptr and 'pNext' to an instance of VkPhysicalDeviceFeatures2KHR, as specified in "4.2.1. Device Creation", "If the pNext chain includes a VkPhysicalDeviceFeatures2KHR structure, then pEnabledFeatures must be NULL".

Best regards,
Daniel

**Comment by jzulauf-lunarg** [comment]
Merged in https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/2160
