### ISSUE TITLE
May have found something that isn't validated.

### ISSUE THREAD

**Issue by Berserker66** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2097]
So, in my project I just messed with the way all my command pools and command buffers are handled.

At the end of the restructure, I now have a vulkan crash on exit. No validation warning of anything being wrong.
https://i.imgur.com/KgqKb2h.png

I use vulkan through a python wrapper, so I don't know much about what seems to have gone wrong on the C level, I also almost never use Visual Studio, so I don't know if I can dump the exception info somehow.

My vulkan info, should it matter:
https://pastebin.com/W0cUTtzd

Edit:
I have fixed the crash - Destroy commands fired in the wrong order, the device and instance were long gone and then two command pools and ~2 command buffers were tried to be cleaned up afterwards, which is wrong. Still, that should have a validation layer message, I think.

**Comment by krOoze** [comment]
AFAIK unfortunatelly the current architecture does not allow validating dispatchable handles (such as device and instance). It simply crashes in the loader trying to use the no-longer-valid instance before it can even get to the validation layer checking function.

It is a bit obvious really. Validatiob layers are *instance layers*. No/destroyed instance -> no layer.

**Comment by Berserker66** [comment]
Mh. Sounds reasonable. But is there a way to hook into the instance destruction and validate things before the instance gets destroyed? Basically as soon as the destroy instance is run, you then check if everything was cleaned up?

**Comment by krOoze** [comment]
@Berserker66 Oh yeah, that should happen. AFAIK all the leaked objects are reported.

**Comment by tobine** [comment]
@Berserker66 yes, object_tracker will [report](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/object_tracker_utils.cpp#L286-L380) undestroyed objects at DestroyInstance() and DestroyDevice() time.

**Comment by krOoze** [comment]
@tobine I have stitched together (not-so-)minimal example testing it:
https://gist.github.com/krOoze/4741b5202e8c07e31bb786b9cb365db1#file-temporarydebugonly-cpp

I leak `VkDevice` child of instance.
I get no validation error.

Also I tried with a debug callback object. I get (for some reason) four errors about the leaked callback object, but still nothing about device.

**Comment by mark-lunarg** [comment]
@krOoze, yup, DestroyInstance calls ReportUndestroyedObjects for each device, and though it will report any objects owned by THAT device as 'leaked' it won't say anything specific about the device itself.  We can certainly make this more clear.
