### ISSUE TITLE
Consistently prefix handle values with 0x

### ISSUE THREAD

**Issue by Novum** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2098]
The layers sometimes outputs handles without 0x before the value. It would be helpful if this would be consistent for parsing issues. Or even better use a more unique prefix.

**Comment by mark-lunarg** [comment]
It'll be 0x for now -- @Novum, can you share some suggestions for a prefix?

**Comment by Novum** [comment]
0x is fine, as long as all handles have it consistently. That way we can parse the handles and replace with our debug names. But if other 64 bit hex values are output that way that would create confusion again.

**Comment by jeremyk-lunarg** [comment]
@Novum, could you give me an example where the layers output handles without 0x?

**Comment by jeremyk-lunarg** [comment]
@Novum, I've looked and haven't been able to find this in code.  Feel free to reopen this if you have an example.
