### ISSUE TITLE
Crash in vkCreateComputePipelines when layout is VK_NULL_HANDLE

### ISSUE THREAD

**Issue by RCalocaO** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2106]
Set PipelineInfo.layout = VK_NULL_HANDLE; and it will crash inside the validation layers on:

        skip |= validate_compute_pipeline(dev_data, pPipeState[i].get());

 	VkLayer_core_validation.dll!PIPELINE_LAYOUT_NODE::operator=(__that)	C++
 	VkLayer_core_validation.dll!core_validation::CreateComputePipelines(device, pipelineCache, count, pCreateInfos, pAllocator, pPipelines) Line 4547	C++

pPipeState's size is 0.

**Comment by RCalocaO** [comment]
SDK 1.0.61.0

**Comment by chrisforbes** [comment]
This requires continuing past the check in parameter validation, yes?

**Comment by mark-lunarg** [comment]
@RCalocaO, as @chrisforbes pointed out, an error _will_ be generated in Parameter Validation saying something like:

> vkCreateComputePipelines: required parameter pCreateInfos[0].layout specified as VK_NULL_HANDLE

The deeper layers rely on PV for just that purpose and do not repeat null checks, so this behavior is by design.
