### ISSUE TITLE
VK_LAYER_LUNARG_api_dump: Allow dumping debug markers

### ISSUE THREAD

**Issue by RCalocaO** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2107]
Supporting VK_EXT_debug_marker would make debugging a *lot* easier since it can easily tell the user where in the frame one is supposed to be when cross referencing draw calls.

**Comment by shannon-lunarg** [comment]
Fixed in VulkanTools PR [#393](https://github.com/LunarG/VulkanTools/pull/393)
