### ISSUE TITLE
Core validation: Report error when an app requests both VK_AMD_negative_viewport_height and VK_KHR_maintenance1 extensions at device creation time.

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2112]
We're seeing some apps out there ignoring the requirement.

**Comment by mark-lunarg** [comment]
@DominikWitczakAMD, this check (VALIDATION_ERROR_056002ec)  is implemented in the parameter_validation layer, and we have a layer test for it (Maintenance1AndNegativeViewport).  Are apps you are seeing ignoring the errors, or not seeing them at all?

**Comment by DominikWitczakAMD** [comment]
Ah, that's good to hear ! Apologies, I should've checked this myself with a ToT version of the layers, prior to opening the ticket.
