### ISSUE TITLE
CoreValidation: vkCmdWaitEvents() caches a pointer to an array which is likely to become invalid by the time validation occurs

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#212]
In core_validation.cpp::vkCmdWaitEvents(), there's an interesting piece of code:

![image](https://cloud.githubusercontent.com/assets/17761066/14140617/628c49ec-f67a-11e5-90c4-620939e4a219.png)

This code assumes **pEvents** will continue to be valid infinitely after vkCmdWaitEvents() call leaves, which is not necessarily true. In my case, I'm passing an array, whose data comes from stack memory of the main thread, so the core_validation.cpp::vkCmdWaitEvents() never crashes. However, the data that function later tries to access is noise, which results in an incorrect debug call-back occuring at queue submission time.

Also, the debug message is invalid (the reported pointer is obviously not a fence handle):

![image](https://cloud.githubusercontent.com/assets/17761066/14140684/cc1ceb50-f67a-11e5-9520-539701fefc85.png)

**Comment by lentinem** [comment]
Chris took this this one over. MR has been uploaded but is awaiting submission.

**Comment by DominikWitczakAMD** [comment]
Issue no longer reproduces, safe to close.
