### ISSUE TITLE
vulkan.pc contains extraneous `Libs`

### ISSUE THREAD

**Issue by haasn** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2121]
The generated vulkan.pc looks like this on my machine:

```
prefix=/usr
exec_prefix=/usr
libdir=${exec_prefix}/lib64
includedir=${prefix}/include

Name: VULKAN
Description: Vulkan Loader
Version: 1.0.62
Libs: -L${libdir} -lvulkan  -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc
Cflags: -I${includedir}
```

But this usage of `Libs:` is wrong. The Libs should only refer to what's needed to link against the actual vulkan.so, i.e. `-L${libdir} -lvulkan`. The rest of the libraries (the ones required *by* vulkan.so for static linking purposes) should go to `Libs.private:`. Compare, for example, libflac's `flac.pc`, which is about as standard as it gets:

```
prefix=/usr
exec_prefix=${prefix}
libdir=/usr/lib64
includedir=${prefix}/include

Name: FLAC
Description: Free Lossless Audio Codec Library
Version: 1.3.2
Requires.private: ogg
Libs: -L${libdir} -lFLAC
Libs.private: -lm
Cflags: -I${includedir}
```

**Comment by johnzupin** [comment]
Created PR #2122

**Comment by johnzupin** [comment]
The PR was merged. Do a pull and build @haasn and let me know if I can close this out.

**Comment by haasn** [comment]
Looks good, thanks. Closing
