### ISSUE TITLE
Core validation layer: Invalid validation error reported for a specific RP configuration

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2123]
1. Let X be a renderpass, built of subpasses 1 and 2.
2. At X's creation time, the following dependencies are specified:

* 1->1 (``srcStageMask`` = 1024, ``dstStageMask`` = 128, ``srcAccessMask`` = 256, ``dstAccessMask`` = 16)
* 1->2 (``srcStageMask`` = 128, ``dstStageMask`` = 128, ``srcAccessMask`` = 256, ``dstAccessMask`` = 16)

When recording the 1->1 image barrier for subpass 1, validation code incorrectly raises the following error:

```
vkCmdPipelineBarrier(): Barrier srcStageMask(0x400) is not a subset of VkSubpassDependency 
srcStageMask(0x80) of subpass 0 of renderPass 0x3c8ece0. The spec valid usage text states 'If 
vkCmdPipelineBarrier is called within a render pass instance, srcStageMask must contain a subset of the
 bit values in thesrcStageMask member of that instance of VkSubpassDependency' (https://www.khrono
s.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkCmdPipelineBarrier-srcSt
ageMask-01173)
```

This appears to be due to ``CreatePassDAG()``'s ``subpass_to_dep_index`` argument. Zeroth element is first written a value of 0, which then gets overwritten by 1, which is why the validation code in ``ValidateRenderPassPipelineBarriers()`` uses incorrect src/dst stage masks for verification.

This is seen with ToT version of the core validation layer, fetched an hour ago.

**Comment by DominikWitczakAMD** [comment]
For a repro, please reach me under the usual e-mail address. :-)

**Comment by chrisforbes** [comment]
Two parts to this:
- We should only be putting self-dependencies in `subpass_to_dep_index`. Other dependencies don't permit barriers. #2131.
- It's possible to have multiple self-dependencies in the same subpass. #2130.
