### ISSUE TITLE
VK_DEBUG_REPORT_INFORMATION_BIT_EXT: Message clarity on successful insertion of validation layer

### ISSUE THREAD

**Issue by kevinend** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2128]
When the loader inserts a validation layer it reports the message in the following manner:
"Insert device layer (*inserts device layer name*).

Would it be better to have the word "Insert" changed to "Inserted"?

I am new to Vulkan and I was initially very confused whether the message was telling me the loader successfully loaded the appropriate layer or needed me to insert the layer.

I know it is a small request but the slight tweak may ease any confusion in the future.

**Comment by lenny-lunarg** [comment]
You're right that this message isn't very accurate, so I've gone and fixed the message with commit a10675bc5993800983d073f5993214e37d6e2eb7.

That being said, the one thing I'd like to point out is that device layers have been deprecated for a while now. The details of this are available [here](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#extended-functionality-device-layer-deprecation). Device layers simply weren't very useful and a current layer can be programmed to do the same thing as a device layer. The spec recommends you make the list of device layers the same as the list of instance layers, but personally I'd recommend just leaving it empty.
