### ISSUE TITLE
Add warning on mismatch between `sharingMode` and `queueFamilyIndexCount`

### ISSUE THREAD

**Issue by haasn** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2137]
Even though the spec explicitly allows it, it should probably generate a warning when setting `queueFamilyIndices > 1` and `sharingMode = VK_SHARING_MODE_EXCLUSIVE`.

Even in the scenario where the user deliberately wants to set both at the same time for whatever convenience-related reasons, silencing this warning would only be a single ternary or conditional away.

(Incidentally, it should also have generated heaps of errors when I ended up actually *using* the EXCLUSIVE sharing mode resource from multiple queue families without queue family transfer operations, but I believe there are already issues tracking that)

**Comment by mark-lunarg** [comment]
@haasn -- great idea.  I'm going to add this to our tracking issue for the Assistant layer, #1612.  We're in-progress on this layer now -- thanks for the suggestion, and please forward any others you may have (by adding to that issue, or just creating a new one).
