### ISSUE TITLE
Scrub error messages and add suggestions where appropriate

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2140]
Tracking issue based on survey feedback. In general make sure that when error messages can give suggestions about *how* to fix the problem they should do so to assist the user.

**Comment by mark-lunarg** [comment]
Maybe we should add this as a requirement to the validation layer best-practices, in lieu of creating an issue that might conceivably remain open indefinitely?

**Comment by tobine** [comment]
@mark-lunarg yes, this should be standard practice going fwd. Where's best-practices doc? [Special Considerations for Validation Layers](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/CONTRIBUTING.md#special-considerations-for-validation-layers) of the CONTRIBUTING.md?
