### ISSUE TITLE
vkCmdCopyImage and compressed texture destination issue

### ISSUE THREAD

**Issue by meup** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2145]
This seems to be a bug in the spec and the validation layer.

We have code to create a BC1 compressed texture from an R16G16B16A16 texture (RGBA16 for short).

Let's suppose we want to create a 12x12 BC1 compressed texture using a 3x3 RGBA16 texture.  This should work, since the compressed texture block size is 4x4.  Now we perform VkCmdCopyImage:

According to the spec, extent is always given in source image size units, so extent = 3x3.
Source subresource = 3x3.  Dest subresource = 12x12.

The validation layer will say:
vkCmdCopyImage(): pRegion[0] extent width (3) must be a multiple of the compressed texture block width (4), or when added to dstOffset.x (0) must equal the image subresource height (12).

The spec says:
"if the srcImage is compressed, then:
* If extent.width is not a multiple of the compressed texel block width, then (extent.width + dstOffset.x) must equal the image subresource width. [...]
Similarly, if the dstImage is compressed, then:
* If extent.width is not a multiple of the compressed texel block width, then (extent.width + dstOffset.x) must equal the image subresource width. [...]"

This makes no sense, since when the dstImage is compressed, the sizes (extent vs dest subresource width) are flipped, and yet the text isn't flipped.  The dest subresource size is what should be a multiple of the block width, not the extent.

Am I missing something here?

**Comment by mark-lunarg** [comment]
Currently in work.

**Comment by mark-lunarg** [comment]
We have a fix in flight for the validation problems you discovered, where the layers were ignoring the special cases for checks between compressed and uncompressed images related to the extent.

I assume that for the spec question, you meant:

> if the srcImage is compressed, then:
> 
> - If extent.width is not a multiple of the compressed texel block width, then (extent.width + **srcOffset**.x) must equal the image subresource width.
> 
> Similarly, if the dstImage is compressed, then:
> 
> - If extent.width is not a multiple of the compressed texel block width, then (extent.width + dstOffset.x) must equal the image subresource width.

We think you're probably right about this and that you should file an issue on the [Khronos Github repo for Vulkan-Docs ](https://github.com/KhronosGroup/Vulkan-Docs/issues).  If this is not possible let me know and we'll try to get somebody to do it from this end.

**Comment by meup** [comment]
Filed as issue #593 there.  Thanks for getting to this so quickly.

(And yes, that was my copy/paste error for the spec.)
