### ISSUE TITLE
Validation layers have multiple bugs with destroyed render passes

### ISSUE THREAD

**Issue by Novum** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2146]
The validation layers incorrectly assume that the render pass that a pipeline was created from must be valid or even the same at the time of vkCmdBindPipeline.

This is wrong. The spec specifically says that the render pass may be deleted or the pipeline used with another compatible render pass.

E.g. in CmdBindPipeline:
`auto rp_state = GetRenderPassState(dev_data, pipe_state->graphicsPipelineCI.renderPass);`
`if (rp_state) {`
`addCommandBufferBinding(&rp_state->cb_bindings, {HandleToUint64(rp_state->renderPass), kVulkanObjectTypeRenderPass}, cb_state);`
`}`

You cannot assume that the renderPass used to create the pipeline (graphicsPipelineCI) is related to the render pass used in the draw.

I have found similar bugs in other places.

**Comment by mark-lunarg** [comment]
@tobine, I thought this was recently addressed... Maybe e03f0c649d ?

**Comment by Novum** [comment]
I'm using 1.0.61.1 layers, this might be fixed in top of tree.

**Comment by tobine** [comment]
Yes, all the renderPass lifetime bugs should be fixed in ToT
