### ISSUE TITLE
CoreValidation: vkCmdBindDescriptorSets() has an invalid per-DS check

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#215]
In core_validation.cpp, vkCmdBindDescriptorSets() issues the following check in a loop which iterates over all defined descriptor sets:

![image](https://cloud.githubusercontent.com/assets/17761066/14142934/d9d29412-f688-11e5-8abf-2f5175827826.png)

The block I marked with red color seems to be a copy-paste of the green block. The check on its own definitely makes sense, but only if the red block is removed.

PR coming in a bit..

**Comment by tobine** [comment]
Dominik fixed this with #217 
Sorry I hadn't seen this issue when I first closed that PR.
