### ISSUE TITLE
maxAnisotropy should be ignored if anisotropyEnable is false

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2166]
vkCreateSampler does the following validation:

https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/7c9fade205e78431e6d025885d764c443b69848f/layers/parameter_validation_utils.cpp#L1496-L1502

Vulkan spec 1.0.65 fixed the following spec issue https://github.com/KhronosGroup/Vulkan-Docs/issues/503#event-1315072933 and now maxAnisotropy should be ignored if sampler state specifies that anisotropyEnable is false.

**Comment by mark-lunarg** [comment]
@jzulauf-lunarg, will this be addressed by the fixes for #2090?

**Comment by jzulauf-lunarg** [comment]
@mark-lunarg . no, they are in the next PR from me.

**Comment by jzulauf-lunarg** [comment]
In pull request https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/2183
