### ISSUE TITLE
Primitive topology not validated?

### ISSUE THREAD

**Issue by meup** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2175]
In our translation layer, we were using -1 for unsupported primitive types.  When we accidentally passed that in as the primitive topology, we got a device lost error from the driver, as the error wasn't caught by the validation layer.  Seems like an easy check that should be there.

**Comment by tobine** [comment]
I confirmed that this check is in the generated parameter_validation.cpp layer:

`skip |= validate_ranged_enum(local_data->report_data, "vkCreateGraphicsPipelines", ParameterName("pCreateInfos[%i].pInputAssemblyState->topology", ParameterName::IndexVector{ createInfoIndex }), "VkPrimitiveTopology", AllVkPrimitiveTopologyEnums, pCreateInfos[createInfoIndex].pInputAssemblyState->topology, VALIDATION_ERROR_0fc30001);`

Are you running with the parameter_validation layer?

That check should be hit down a vkCreateGraphicsPipelines() call for any VkGraphicsPipelineCreateInfo that has a non-null pInputAssemblyState with topology set to an invalid value.

**Comment by meup** [comment]
Sorry, I thought we were, but it turns out we're only using the core validation layer.

**Comment by tobine** [comment]
np, refer to layers [README](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/README.md#standard-validation) for how to use standard_validation meta-layer on desktop, or for the exact sequence of layers to use on Android.
