### ISSUE TITLE
CoreValidation: vkResetDescriptorPool does not reset availableSets

### ISSUE THREAD

**Issue by TiemoJung** [KhronosGroup/Vulkan-LoaderAndValidationLayers#218]
Hi,

when calling vkResetDescriptorPool, DESCRIPTOR_POOL_NODE::availableSets will not be reset.

This will lead to a spam of validation errors about empty descriptor sets even if they are reset.

**Comment by tobine** [comment]
Submitted #220 to fix this

**Comment by tobine** [comment]
fix merged to master
