### ISSUE TITLE
Add validation for sample rate shading

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2180]
There doesn't seem to be any validation for enabling sample rate shading. As per spec the validation should check the value of the ```VkPipelineMultisampleStateCreateInfo``` ```sampleShadingEnable``` member against the ```sampleRateShading``` device feature.

**Comment by tobine** [comment]
FYI this is VALIDATION_ERROR_10000620 in DB.

**Comment by jzulauf-lunarg** [comment]
Fix merged in #2220
