### ISSUE TITLE
vkCreateInstance takes 2 seconds

### ISSUE THREAD

**Issue by Jasper-Bekkers** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2191]
On my machine it appears that vkCreateInstance takes a full 2-2.5 seconds to get Vulkan up and running (two GPU machine, one NV and one AMD GPU). This is a non-parallelizable cost that we take every time we start our application so 2 seconds is a bit absurd.

This is with no explicit layers enabled and two extensions enabled (VK_KHR_surface and VK_KHR_win32_surface).

**Comment by chrisforbes** [comment]
@Jasper-Bekkers are you able to isolate this to one ICD or the other, or is the time being spent in the loader itself? (`VK_ICD_FILENAMES` in env should help)

**Comment by krOoze** [comment]
It takes ~0.5 s for me. Still, sounds unnecessarily long for a modern PC.

**Comment by krOoze** [comment]
AMD seem to have cut the creation times in half in the latest drivers (at least for me).

**Comment by mark-lunarg** [comment]
Evidence is pointing to this particular issue being driver-related, and not due to the loader or layers.  Please reopen if this assumption is incorrect.
