### ISSUE TITLE
vkGetInstanceProcAddr code in the loader does not match specifiction description

### ISSUE THREAD

**Issue by ashleysmithgpu** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2199]
The vulkan spec says:

Table 1. vkGetInstanceProcAddr behaviour

instance | pName | return value
-- | -- | --
.* | NULL | undefined
invalid instance | * | undefined
NULL | vkEnumerateInstanceExtensionProperties | fp
NULL | vkEnumerateInstanceLayerProperties | fp
NULL | vkCreateInstance | fp
NULL | * (any pName not covered above) | NULL
instance | core Vulkan command | fp1
instance | enabled instance extension commands for instance | fp1
instance | available device extension2 commands for instance | fp1
instance | * (any pName not covered above) | NULL

However when passing in a valid instance and "vkCreateInstance" [the code](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/loader/trampoline.c#L55) will return NULL, whereas row 7 states it should return the function pointer. This also applies for the other two mentioned entry points.

The code should be changed to:

```
if (instance == VK_NULL_HANDLE) {
	// Get entrypoint addresses that are global (no dispatchable object)

	return addr;
}
```

**Comment by lenny-lunarg** [comment]
I just pushed a fix for this to master with commit 8f9d7ca19ea3ec0b45de929de561e5e4b3e79183. Thanks for the bug report.
