### ISSUE TITLE
DrawState: crash on vkUpdateDescriptorSets

### ISSUE THREAD

**Issue by TiemoJung** [KhronosGroup/Vulkan-LoaderAndValidationLayers#22]
Hi,

we encounter a crash while calling vkUpdateDescriptorSets when the draw_state layer is active.

In draw_state.cpp:validateSampler:
line:2588: `auto sampIt = my_data->sampleMap.find(*pSampler);`

Reason:
pSampler is an invalid pointer.

pSampler is inavlid because in line 2968:
`if ((skipCall = validateUpdateContents(my_data, &pWDS[i], &pLayout->createInfo.pBindings[binding])) == VK_FALSE)` using *binding* as index for *pBindings* is invalid for sparsely defined descriptor sets.

This is also a regression to previous versions of the sdk.

**Comment by tobine** [comment]
This is already fixed in master. Below is the latest version of the call referenced above:

    skipCall = validateUpdateContents(
                             my_data, &pWDS[i],
                             &pLayout->createInfo.pBindings[bindingToIndex->second])

Note that binding is now correctly mapped to a valid index, handling sparsely defined descriptor sets.
