### ISSUE TITLE
Core validation does not check push constant ranges to determine set compatibility between pipeline layouts

### ISSUE THREAD

**Issue by mark-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2214]
This is from [LunarXchange, #648](https://vulkan.lunarg.com/issue/view/588c4e776631512b4c4b1f50):

The Vulkan specification states:

> Two pipeline layouts are defined to be “compatible for set N” if they were created with matching (the same, or identically defined) descriptor set layouts for sets zero through N, and if they were created with identical push constant ranges.

The core validation layers however do not seem to check the push constant ranges when determining pipeline layout compatibility regarding descriptor sets. In my project I use two different pipeline layouts. The first one only defines a descriptor set with one uniform buffer (meant to contain view and projection matrices); no push constants. The second one defines two descriptor sets, the first with one uniform buffer (in order to be compatible with the first layout) and the second with additional resources like a sampler and sampled images. The second set also defines a push constant range (used to set the model matrix). When rendering I first bind the first descriptor set with the first layout and then the second descriptor set with the second layout. Why? Because it happens in two different objects.

According to the quoted paragraph above this should not work because the push constant ranges of both layouts are different. The core validation layer however does not report anything (no error, warn, perf, info). Is there a reason for this lack of errors/warnings?

**Comment by stroyan** [comment]
That link went to github issue 648 instead of LunarXchange [#648](https://vulkan.lunarg.com/issue/view/588c4e776631512b4c4b1f50)

**Comment by mark-lunarg** [comment]
Thanks Mike!
