### ISSUE TITLE
Performance issue: large arrays of texture descriptors (bindless) is very slow

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2221]
We've just hooked up using a large unflattened array of textures in our shader, for example like this in HLSL:

Texture2D g_tTextureArray[ 4096 ] : layout( set = 1, binding = 3 ) ;

This array is dynamically uniform indexed in the shader.  The descriptor set associated with this array is updated very infrequently (not every frame).  

Turning this rendering path on has caused a massive drop in performance with validation (< 1FPS) in DOTA.  The costs look spread out from profiling, but it basically is from iterating over the entire array in the cases where it validates descriptors.  

I can't quite share a test case yet, but I'm wondering if we could disable validation somehow for large arrays of textures?  Another option might be detecting that the descriptor set is unchanged since previous use and skipping redundant validation?

**Comment by jzulauf-lunarg** [comment]
Fixes merges in 2301.
