### ISSUE TITLE
No warning for VkViewport.minDepth > maxDepth

### ISSUE THREAD

**Issue by hrydgard** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2224]
Calling vkCmdSetViewport with a minDepth with a greater value than the maxDepth appears to fail silently on at least AMD boards, resulting in wrong rendering output. It's unclear to me whether it's valid or not, the spec doesn't seem to say more on the subject than:

    minDepth must be between 0.0 and 1.0, inclusive
    maxDepth must be between 0.0 and 1.0, inclusive

So either this should be an error, maybe a warning, or I should try to report a driver bug to AMD. The latter I guess since the spec doesn't actually say that it has to be smaller? AMD has long had the same behaviour in D3D11 and D3D9, although in OpenGL it does work to reverse them.

**Comment by krOoze** [comment]
Implemented by PR #2222

**Comment by krOoze** [comment]
Yes, indeed the specification does say:

> It is valid for `minDepth` to be greater than or equal to maxDepth.

**Comment by hrydgard** [comment]
Oh right, I missed that. Then, I'd guess that this case is missing in the Vulkan conformance tests, because both AMD and older Mali drivers misbehave badly with minDepth > maxDepth. What's the best place to report or contribute missing conformance test cases? 

I'll try to get around to reporting this to AMD in the near future. Feel free to close.

**Comment by krOoze** [comment]
I would assume the [Vulkan CTS repo](https://github.com/KhronosGroup/VK-GL-CTS).
AMD Issues probably through Radeon Settings->Preferrences->Report Issues Online. Or [AMD Dev forum](https://community.amd.com/community/devgurus/).
I don't know Mali, but knowing Android it won't get fixed for a year or if ever.

BTW, you can self-close on GitHub.

**Comment by hrydgard** [comment]
Turns out it's actually already tested - but the test was added quite recently, which would explain the failures: https://github.com/KhronosGroup/VK-GL-CTS/issues/44

It's fixed in newer Mali driver versions - S8 has the fix, Xiaomi doesn't. 

Yeah I know I can close, project policies for who closes tend to differ though :)
