### ISSUE TITLE
VL seems to not check maxBoundDescriptorSets

### ISSUE THREAD

**Issue by Brotcrunsher** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2230]
**Overview**: When calling `vkCreatePipelineLayout` with an invalid (too high) `setLayoutCount` inside `VkPipelineLayoutCreateInfo`, no message is printed. Instead the program crashes with an illegal write operation (varying locations).

**Details**: The spec says: 
> setLayoutCount must be less than or equal to VkPhysicalDeviceLimits::maxBoundDescriptorSets
[link](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VkPipelineLayoutCreateInfo)

Vulkan Version: 1.0.65.0
Tested under Visual Studio 2017 15.4.1
Device: GeForce GTX 1080 Ti
Allowed setLayoutCount: 8
Used setLayoutCount: 9

**Comment by krOoze** [comment]
Probably also reported in #2063.

**Comment by daveh-lunarg** [comment]
This should be resolved with PR #2255.  Closing.

**Comment by daveh-lunarg** [comment]
Re-opened as I've temporarily reverted #2255.  Will be PR #2262 when re-submitted.

**Comment by daveh-lunarg** [comment]
Resolved in PR #2262.
