### ISSUE TITLE
Validation bug in vkCmdCopyImage between compressed and uncompressed image formats

### ISSUE THREAD

**Issue by strandborg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2239]
The spec says this on vkCmdCopyImage:

```When copying between compressed and uncompressed formats the extent members represent the texel dimensions of the source image and not the destination. When copying from a compressed image to an uncompressed image the image texel dimensions written to the uncompressed image will be source extent divided by the compressed texel block dimensions. When copying from an uncompressed image to a compressed image the image texel dimensions written to the compressed image will be the source extent multiplied by the compressed texel block dimensions. In both cases the number of bytes read and the number of bytes written will be identical.```

However, trying to copy from 512x512 BCH6 image into 128x128 A32R32G32B32 image raises this validation error:

 ```VULKAN DEBUG: ERROR:  [IMAGE, 419430646]: vkCmdCopyImage: Dest pRegion[0] with mipLevel [ 0 ], offset [ 0, 0, 0 ], extent [ 512, 512, 1 ] exceeds the destination image dimensions. The spec valid usage text states 'The destination region specified by a given element of pRegions must be a region that is contained within dstImage' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkCmdCopyImage-pRegions-00123)```

**Comment by daveh-lunarg** [comment]
Resolved with PR #2274. Closed.

Thanks @strandborg for the bug report!
