### ISSUE TITLE
CoreValidation: validate_and_update_drawtime_descriptor_state crash on not set descriptors

### ISSUE THREAD

**Issue by TiemoJung** [KhronosGroup/Vulkan-LoaderAndValidationLayers#226]
Hi,

validate_and_update_drawtime_descriptor_state will deference a null pointer if the pipeline uses a slot of a descriptor set that was never been set/updated.
The first use is at line 2851 eg `switch (set_node->pDescriptorUpdates[i]->sType)` where `pDescriptorUpdates[i]` can be null.

**Comment by tobine** [comment]
Just submitted #236 to fix this. We had a check in place if the set had not been updated, but there was still a hole if individual slots within a set weren't updated.

**Comment by tobine** [comment]
Fix merged to master
