### ISSUE TITLE
DevSim does not support extensions?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2265]
Are extensions supported in DevSim.

It does seem to report supported extensions and allow to enable them, but the profile files (e.g. format features in them) seem to only be collected for core Vulkan.

**Comment by mikew-lunarg** [comment]
Hi krOoze,

You are correct that control of extensions is not yet implemented by the DevSim layer.  The implementation in active development.

Do you have a particular extension of interest, that I could prioritize?  I'll include you on the PR reviewers when the time comes.

**Comment by krOoze** [comment]
@mikew-lunarg It is bit of a problem, because the tests seem to use it. I would perhaps recommend to not return extensions as supported from the DevSim, unless they fully are.

I encountered this problem with Maintenance1 extension.

**Comment by mikew-lunarg** [comment]
@krOoze  there are actually two separate layers for controlling Vulkan implementations, with different audiences and use models:
1. the "Device Simulation" (DevSim) layer, for use by App developers, statically configured with JSON before App startup.
2. a "device profile" layer, specifically for internal use only by Vulkan layer tests, which provides an API to modify the implementation during test execution.

For the most part, tests should be using the device profile layer, rather than DevSim.

Could you create an issue with specific details about the failure you're seeing, so we can determine how best to address?

**Comment by krOoze** [comment]
@mikew-lunarg It is in PR #2264 where I needed to make workaround [here](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/2264/files#diff-bc93061e85db14990b70883fc4964c3eR830), otherwise the tests fail an assertion and fail in CI. Even with the workaround there would of course be "Unexpected" messages from the validation layers (those still count as SUCCESS though).

**Comment by mikew-lunarg** [comment]
@krOoze I see the comment:
> // WORKAROUND: for DevSim not reporting extended enums, and possibly some drivers too

Without my digging deeply into the test logic, could you explain the specific behavior expected that necessitates the workaround?  

I'm trying to understand if the issue is in DevSim, DevPro, the binary of DevSim checked into the repo, or the config being specified by the test.

FWIW @tobine has approved #2264 in its current form, but I still want to understand the issue.

**Comment by krOoze** [comment]
@mikew-lunarg I explained a bit in the previous post. Also https://github.com/KhronosGroup/Vulkan-Docs/issues/639 is relevant.

The issue is that in core Vulkan the `TRANSFER` feature is implicit if any other flags are reported.

But in Maintenance1 the `TRANSFER` feature flags are explicit.

So what happens if I run a Test depending on Maintenance1 is that those explicit flags are missing, if the Devsim was recorded in the core mode, despite transfer actually being supported for that format. And so the test fails to create an image it needs.

**Comment by mikew-lunarg** [comment]
@krOoze @tobine Thanks for using and wringing out use-models for DevSim!  We're still learning how this tool fits into the bigger picture, but I think there's a path forward in this case (assuming DevSim v1.2.0 or later)...

I believe the tests are using a prebuilt binary of DevSim v1.2.0 (@tobine is that correct?)

DevSim does exactly what is specified in its configuration files.  It does not automatically adjust anything if extensions are enabled.  If a format flag should be enabled, it must be specified as such in the JSON config file.

In this case, the desired format (with the expected flags) needs to be added/modified in the ArrayOfVkFormatProperties section of the config file.

Perhaps the config files at LVL/tests/device_profiles/*.json should have additional copies for "+maintenance1" configurations?

A new feature of DevSim v1.2.1 is it can consume multiple JSON config files.  That permits configs to be split into modular sections.  Perhaps that could help with structuring common ArrayOfVkFormatProperties files that could be shared across different simulated devices?

**Comment by tobine** [comment]
Yes, LVL is using a prebuild DevSim v1.2.0 binary.

It's not clear to me that there is any issue with DevSim here, it's simply reporting the capabilities in the config file.
If we need to adjust the checked-in LVL config files, manually modifying them to include desired extensions is one possibility. Replacing current config files with more recent/similar ones that actually support maintenance1 is another possibility.

The long-term solution, though, is for LVL tests to migrate to device profile layer and to use that to set whatever extensions and features each individual test intends to exercise.

**Comment by krOoze** [comment]
@tobine Recording the flags with all extensions enabled should work for most purposes.
I mean it would not be 100 % same as the device could behave. Then again there's not even a guarantee the flags won't change between two calls to `vkCreateInstance`, so it does not matter that much.

The VHCV app seems to report the extended flags, but the http://vulkan.gpuinfo.org web does not seem to list them.

**Comment by krOoze** [comment]
PS: Actually the json profiles seem to have extended flags if my bit-fu is correct.
Hmm, I should re-test it. Perhaps it is a problem only of one of the profiles...

**Comment by tobine** [comment]
mali-t760.json & powervr_rogue_ge8300.json are the only 2 profiles that don't report VK_KHR_maintenance1.

**Comment by krOoze** [comment]
PS2: I was only using the CI. But I had problem setting it up locally on Windows. Could someone help me set it up? I pretty much copied what is in the `.travis.yml`, but it did not quite work.

**Comment by mikew-lunarg** [comment]
@krOoze I believe this issue is resolved.  Please close if you agree.

**Comment by krOoze** [comment]
@mikew-lunarg I suppose it is (at least the way I formed it, which turned out to be a X-Y problem). At worst, we seem to have list of tests that do not play well with devsim + mock ICD, so this does not necessarily need be an Issue.
