### ISSUE TITLE
Invalid validation layer error message when using VK_EXT_shader_viewport_index_layer 

### ISSUE THREAD

**Issue by marco-we** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2288]
The sample I am looking at is using the VK_EXT_shader_viewport_index_layer device extension to render to two viewports using the instance id.

The following stripped down vertex shader

```glsl
#version 450
#extension GL_ARB_shader_viewport_layer_array : enable

void main() 
{
	gl_ViewportIndex = viewportIndex;
}
```

generates the SPIR-V below:

```
// Module Version 10000
// Generated by (magic number): 80002
// Id's are bound by 12

                              Capability Shader
                              Capability MultiViewport
                              Capability ShaderViewportIndexLayerNV
                              Extension  "SPV_EXT_shader_viewport_index_layer"
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Vertex 4  "main" 8 10
                              Source GLSL 450
                              SourceExtension  "GL_ARB_shader_viewport_layer_array"
                              Name 4  "main"
                              Name 8  "gl_ViewportIndex"
                              Name 10  "gl_InstanceIndex"
                              Decorate 8(gl_ViewportIndex) BuiltIn ViewportIndex
                              Decorate 10(gl_InstanceIndex) BuiltIn InstanceIndex
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeInt 32 1
               7:             TypePointer Output 6(int)
8(gl_ViewportIndex):      7(ptr) Variable Output
               9:             TypePointer Input 6(int)
10(gl_InstanceIndex):      9(ptr) Variable Input
         4(main):           2 Function None 3
               5:             Label
              11:      6(int) Load 10(gl_InstanceIndex)
                              Store 8(gl_ViewportIndex) 11
                              Return
                              FunctionEnd
```

At run-time the validation layer is complaining that the shader requires the extension `VK_NV_viewport_array2` and that it is not enabled on this device.
The extension is not available here and the sample runs correctly, outputting to both viewports in the full example. 

I had a quick look and the SPIR-V spec lists both tokens under the same ID (see https://www.khronos.org/registry/spir-v/specs/1.2/SPIRV.html#_a_id_capability_a_capability):

5254 | ShaderViewportIndexLayerEXT | MultiViewport | SPV_EXT_shader_viewport_index_layer
-- | -- | -- | --
5254 | ShaderViewportIndexLayerNV | MultiViewport | SPV_NV_viewport_array2

Not sure if this might be related to this issue at all though.

**Comment by daveh-lunarg** [comment]
Looks like a validation bug.  We expect a unique mapping from a Capability->Extension, but the duplicated token here violates that assumption.

**Comment by daveh-lunarg** [comment]
Pushed PR #2297 which resolves this issue.  Closing.

@marco-we, Thanks for the bug report!
