### ISSUE TITLE
Missing validation: Transitioning an image before binding memory to it is illegal

### ISSUE THREAD

**Issue by hrydgard** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2289]
As described in the title.

When initializing a texture image, I use vkCmdPipelineBarrier to transition it to from UNDEFINED to TRANSFER_DST_OPTIMAL before vkCmdCopyBufferToImage, which should be a normal way to go about things. However, I accidentally did this *before* binding memory to the image. Turns out most implementations don't care, as presumably any transition from UNDEFINED is generally a no-op apart from possibly updating a bit of metadata. Intel's ANV Linux driver did care though, and promptly crashed.

The validation layers didn't catch this, but probably should - seems like an easy case to detect.

**Comment by jzulauf-lunarg** [comment]
Agree this should be validated.

There doesn't appear to be a VUID asserting that memory must be bound, but in the spec there is text 

> Image layout transitions may perform read and write accesses on all memory bound to the image subresource range

And 

> VkBuffer and VkImage resources in Vulkan must be bound completely and contiguously to a single VkDeviceMemory object. This binding must be done before the resource is used, and the binding is immutable for the lifetime of the resource.

So there appears to be an assumption of memory being bound to the Image at command record time (for non-sparse images), and at execution time (for sparse images).

**Comment by chrisforbes** [comment]
Clear rule for non-sparse cases in the 1.0.68 spec:

11.6:

> Non-sparse resources must be bound completely and contiguously to a single VkDeviceMemory object before the resource is passed as a parameter to any of the following operations:
> 
> - creating image or buffer views
> - updating descriptor sets
> - recording commands in a command buffer

**Comment by jzulauf-lunarg** [comment]
This needs a Valid Usage statement, no?

**Comment by jzulauf-lunarg** [comment]
@hrydgard -- the merge above should address your concern.

**Comment by hrydgard** [comment]
@jzulauf-lunarg Great, thanks!
