### ISSUE TITLE
external_revision_generator.py broken on Windows

### ISSUE THREAD

**Issue by leizleiz** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2294]
https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/b699ba8cfbb6c97dbc590bf15a84fcb4b41d35a6/scripts/external_revision_generator.py#L37

The line tries to do Windows compatibility by calling git.bat, but it has a conditional that will never evaluate to True because os is a Python module. Shouldn't it be:

`sys.platform == "win32"` or `platform.platform() == "Windows" ?`

**Comment by tobine** [comment]
I believe intention was:

os.name == "nt"

I'll make a PR

**Comment by tobine** [comment]
#2299 fixed this
