### ISSUE TITLE
vkCmdDispatch doesn't validate groupCount parameters against maxComputeWorkGroupCount limits

### ISSUE THREAD

**Issue by critsec** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2296]
These VU statements on vkCmdDispatch don't appear to be implemented:

* `groupCountX` must be less than or equal to `VkPhysicalDeviceLimits::maxComputeWorkGroupCount[0]`
* `groupCountY` must be less than or equal to `VkPhysicalDeviceLimits::maxComputeWorkGroupCount[1]`
* `groupCountZ` must be less than or equal to `VkPhysicalDeviceLimits::maxComputeWorkGroupCount[2]`

See [this StackOverflow question](https://stackoverflow.com/questions/47927866/vulkan-buffer-workgroupid-not-returning-actual-value-when-large-number-of-elemen). A quick grep through the validation code didn't find anything that looked like an implementation of this check.

**Comment by tobine** [comment]
Thanks @critsec , yes, these checks are not yet implemented. Note that [vk_validation_error_database.txt](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/vk_validation_error_database.txt) contains implementation status for VUIDs and *should* be easier to check than grepping code.

Implementer note, here are the VUIDs:
VALIDATION_ERROR_19c00304
VALIDATION_ERROR_19c00306
VALIDATION_ERROR_19c00308

Similar checks for these VUIDs on extension function vkCmdDispatchBaseKHX:
VALIDATION_ERROR_19e00350
VALIDATION_ERROR_19e00352
VALIDATION_ERROR_19e00354

**Comment by daveh-lunarg** [comment]
These checks are implemented in PR #2349.  Thanks @critsec for the bug report!
