### ISSUE TITLE
False positive loader warning

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2309]
This is really minor, but the loader issues a warning like this in [`terminator_CreateDevice`](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/loader/loader.c#L5169):

> vkCreateDevice extension VK_EXT_foobar not available for devices associated with ICD [...]

When it sees a device extension enabled that the ICD doesn't support, and then it filters the extension out before passing the list to the ICD.

This is fine, but it doesn't take into account that layers can add support for extensions that ICDs don't expose. In that case it should check if the extension was supported by one of the layers, then still filter it out before passing to the ICD but skip the warning.

FYI it was added way back in 8b0f75529901e0dfc7a5d70a19ed95c41d8035af but I rarely set up the debug report callback at device creation time so I hadn't noticed until now.

**Comment by lenny-lunarg** [comment]
I'm inclined to agree that this shouldn't be a warning. I'm going to switch this message to a debug message, which should clearly mark that there is nothing wrong with this behavior, while still leaving the message around for debugging. I'm testing the (admittedly tiny) change on our internal test farm now and I'll push it up shortly, as long as I don't get any unexpected failures.

**Comment by lenny-lunarg** [comment]
Resolved with commit a5ced43963485640c99d9a50f57c538a2c1a6b5f.
