### ISSUE TITLE
external_revision_generator.py should not depend on Git

### ISSUE THREAD

**Issue by cdwfs** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2346]
The `external_revision_generator.py` script is used to generate a unique ID for a particular state of the validation code, to determine whether a blob of serialized validation cache data is compatible with the version of the validation code currently in use by an application. The script currently uses the repository's Git commit ID as the unique ID, but this creates an implicit build requirement that the layers code is being hosted in a Git repository. A different, more portable method for UUID generation should be used instead.

**Comment by cnorthrop** [comment]
Hey Cort,

Pinging @chrisforbes too.

Any update on this?  Could we just use a random number instead of something tied to git?  This is affecting the Android NDK downstream.

-C

**Comment by cdwfs** [comment]
No concrete progress yet; just ideas.

- The ideal ID would correspond to a particular state of the spirv-tools shader validation code.

- The next best thing would be a build number from the spirv-tools library; I see a build-version.inc in the spirv-tools build directory, but its contents also seems to be derived from the Git commit ID.

- Worst-case, any old random number for a given build of the core_validation layer would _probably_ be an acceptable ID; it would limit the ability to share validation cache data between different builds of the exact same layers code, but that's unlikely to a significant problem in practice.

- Another approach would be to add an optional flag to `external_revision_generator.py` that lets users override the default Git-derived ID with any arbitrary value of their choosing (ideally, something semantically equivalent to a spirv-tools commit ID or build number). That would be the most flexible solution, but it's really just passing the problem on to developers who build layers in non-Git environments.

**Comment by cnorthrop** [comment]
A couple more ideas:

- Use a timestamp.  This is akin to the random number, but trackable.

- It looks like `build-version.inc` is created by `update_build_version.py`, which can use the `git rev-parse`, but doesn't require it.  So you could get a string out to identify the approximate SPIR-V version, which would hopefully be compatible between hashes until `CHANGES` were updated? i.e.:
  - `"v2017.1-dev", "SPIRV-Tools v2017.1-dev unknown hash, 2018-02-01"`
  vs
  - `"v2017.1-dev", "SPIRV-Tools v2017.1-dev spirv-1.1-rev1-463-g7e2d26c"`

**Comment by cdwfs** [comment]
If the spirv-tools build-version.inc works with or without Git, that's suddenly a much more compelling solution! I wish the timestamp it included in that case were a bit higher-resolution; would it be reasonable to add a HH:MM:SS suffix?
