### ISSUE TITLE
Accidental force-push to LVL master; may need to reset branches.

### ISSUE THREAD

**Issue by mikew-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2347]
Due to an accidental forced-push to LVL master, 11 recent commits (from Jan 5 - 15) had their history rewritten, so their hashes have changed.  The push did not remove any commits, so nothing was lost.  Erroneous commits have been reverted, so code-wise, the content of the master branch is as before; just the hashes have changed. 

If your repo does not reference any of those rewritten commits, you will not be affected.

If you have a branch that references the old hash of one of those rewritten commits, you will probably need to create a new branch, and cherry-pick your commits from the old.  

The rewritten commits are:
> 33a39f5 build: Fix linux 32-bit assembly config
> cb19c6c build: Use DevSim from a VulkanTools build in CI
> 0d034c4 layers: Fix Android build
> fdbf6f3 layers: Fix typos in ValidateUpdateDescriptorSets
> 47bc78a layers: Make bind more robust to invalid memory
> 7bc436c tests: Add buffer creation zero size test
> b8a2c8f tests: Add mipLevels and arrayLayers zero tests
> 02369dd tests: Update CreateImageLimitsViolationMinWidth
> bac7331 layers: Make ValidateGreaterThan report vuid etc.
> 88e4bad tests: add tests for descriptor limit VUs
> 44bf63f layers: add remaining descriptor limit VUs

Apologies in advance.

**Comment by krOoze** [comment]
I believe there is a setting in the GitHub to prevent rewriting history on specific branches.

**Comment by mikew-lunarg** [comment]
Indeed.  LVL is protected against this recurring.
