### ISSUE TITLE
Vulkan loader crash

### ISSUE THREAD

**Issue by shinchiro** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2355]
Hello, I've compiled vulkan loader statically. It always works fine before until this commit, a2be059 where it will crash any application calling function like `vkCreateInstance`

**Comment by lenny-lunarg** [comment]
That commit fixed up some memory leaks when using the loader as a dll, but I forgot that we still needed the old method in case this is a static library. I'll get it added back in shortly.
