### ISSUE TITLE
Validate descriptor operations for VK_DESCRIPTOR_SET_LAYOUT_CREATE_PUSH_DESCRIPTOR_BIT_KHR

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2361]
The spec says that

> VK_DESCRIPTOR_SET_LAYOUT_CREATE_PUSH_DESCRIPTOR_BIT_KHR specifies that descriptor sets must not be allocated using this layout, and descriptors are instead pushed by vkCmdPushDescriptorSetKHR

Validation layers currently allow allocating descriptors with layouts created with this flag, this most likely needs to be an error.

**Comment by jzulauf-lunarg** [comment]
VUID-VkDescriptorSetAllocateInfo-pSetLayouts-00308

**Comment by jzulauf-lunarg** [comment]
Addressed in above commit.
