### ISSUE TITLE
Validate descriptor types for vkCmdPushDescriptorSetKHR

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2362]
I'm not sure whether it makes sense to handle it in `vkCmdPushDescriptorSetKHR`, or when creating descriptors with `VK_DESCRIPTOR_SET_LAYOUT_CREATE_PUSH_DESCRIPTOR_BIT_KHR` (which requires #2361...), but the spec says that push descriptor sets can not work with dynamic descriptor types, and validation layers don't check this at creation or `vkCmdPushDescriptorSetKHR` time.

**Comment by jzulauf-lunarg** [comment]
This should be added to DescriptorSetLayout::ValidateCreateInfo
VUID-VkDescriptorSetLayoutCreateInfo-flags-00280

**Comment by jzulauf-lunarg** [comment]
fixed in validation of vkCreateDescriptorSetLayout
