### ISSUE TITLE
Binding memory using vkBindImageMemory after getting its requirements via vkGetImageMemoryRequirements2KHR results in a warning

### ISSUE THREAD

**Issue by atomnuker** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2364]
Seems like vkBindImageMemory isn't checking if image has had its requirements gotten through vkGetImageMemoryRequirements2KHR.
This is common if an API user doesn't need non-disjoint multiplanar images (and in fact one of the examples in 1.0.68 version of the specs does exactly that).

> vkBindImageMemory(): Binding memory to image 0x1 but vkGetImageMemoryRequirements() has not been called on that image

Also the inverse is maybe true as well, using vkGetImageMemoryRequirements to get an image's requirements and binding it via the new vkBindImageMemory2KHR would maybe result in a warning as well.

**Comment by daveh-lunarg** [comment]
It seems fairly easy to fix up all the permutations of KHR/non-KHR entry points, but it begs the question of whether this warning should even exist. A user can plausibly know the memory requirements of an image without calling any flavor vkGetImageMemoryRequirements on it, e.g. when creating (n > 1) identical images and only calling vkGIMR() on the first.

Unless I'm missing something, this warning seems as likely to produce a false positive as a useful heads-up.  I'm inclined to just remove the warning altogether. Anyone disagree?

**Comment by tobine** [comment]
My initial thought is not to remove the warning unless users are requesting that. The spec does not guarantee that identical images will have identical memory requirements returned by the driver. That's up to the implementation. I believe this warning originated from some bad assumptions apps were making about similar or identical images that were causing errors.

**Comment by atomnuker** [comment]
I think this is one of those warnings that should be gone. API users can just set the memory requirements directly in case they know them. Which is what happens when importing Unix FDs, where you can lseek to know its size, its flags are going to be the flags of the heap of the queue the memory is in and the alignment is the page size.

**Comment by tobine** [comment]
Remember that warnings can often be helpful to novice API users. The use case referenced by @atomnuker is very specific and in such a case the warning can easily be ignored. There are many more use cases and possibilities for novice users to hit tricky bugs due to making incorrect mem requirement assumptions when failing to get mem requirements from the implementation. As the spec says: 

> In general if you see a warning but you know that the behavior is intended/desired, then simply ignore the warning.

**Comment by mark-lunarg** [comment]
Alternatively, this entire class of warnings (not covered in the spec) could be moved to the assistant layer.

**Comment by daveh-lunarg** [comment]
Users managing their own memory pools will be re-using memory for a given image all the time, and my guess is the potential annoyance of being warned "you didn't ask how much memory is needed *this* time" is higher than the potential benefit of this warning. But, I don't know the history of how this warning got added in the first place, and if my guesses were 100% reliable I be sitting on a pile of Facebook stock right now.

So, I'll fix KHR permutations in the short term, and flag this with a TODO to move into the assistant layer long term.
