### ISSUE TITLE
Device can be created with VK_KHR_push_descriptor and without VK_KHR_get_physical_device_properties2 

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2366]
It looks like dependent extensions are not checked when creating the device - creation of device with VK_KHR_push_descriptors but without VK_KHR_get_physical_device_properties2 that it depends on succeeds without warnings/errors.

When trying to use vkCmdPushDescriptorSetKHR, the validation does error if VK_KHR_get_physical_device_properties2 isn't specified but this check seems like it should be performed earlier.

**Comment by mark-lunarg** [comment]
@zeux, I believe this check was intentionally deferred until use.  Is it worth an error/warning if an application enables an extension without its dependent extensions, and never uses the extension?

**Comment by zeux** [comment]
My understanding is that in some cases what constitutes "use" of an extension is not 100% clear (for example, VK_KHR_maintenance1 subtly changes the behavior of vkAllocateDescriptors removing the VU for pool having sufficient # of descriptors). It seems that if the application enables an extension but doesn't use it, this is a lingering bug and I'd much rather get notified about this early - if the application doesn't use it, it's easy to remove the extension - since it's effectively redundant.

Since there's no VU for this in the spec yet (although it mentions that one might appear at some point), would it make sense to emit a warning for now?

**Comment by mark-lunarg** [comment]
We have learned through long experience that users hate to get warnings for things they be doing intentionally, and in general we tend towards being conservative with warnings in the Validation layers.  I'll talk to the folks here to see what the consensus is, but I'm guessing that this, and possibly other issues in this grey area would be better located in the Assistant Layer (in VulkanTools).

**Comment by krOoze** [comment]
> Since there's no VU for this in the spec yet (although it mentions that one might appear at some point), would it make sense to emit a warning for now?

??
VUID-vkCreateDevice-ppEnabledExtensionNames-01387:

> All required extensions for each extension in the `VkDeviceCreateInfo::ppEnabledExtensionNames` list **must** also be present in that list.

**Comment by zeux** [comment]
Interesting. Does this conflict with what is written here?

https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#extended-functionality-extensions-dependencies

**Comment by mark-lunarg** [comment]
So for now, I'll mark this as an INCOMPLETE pointing to VU 0x1a700422 (VUID-vkCreateDevice-ppEnabledExtensionNames-01387), and we'll leave sorting out the spec for another issue.  Thanks @zeux and @krOoze.

**Comment by krOoze** [comment]
> Does this conflict with what is written here?

Not really IMO. The VU even links to that section.

As analytic philosophy teaches us, english sentence can be interpreted in million different ways. I would imagine that is the reason VU sections were introduced in the first place.
I have similar problems with the free-form text in the specification all the time...

**Comment by hrydgard** [comment]
This actually seems to crash hard inside the validation layers now during vkCreateDevice (enabling VK_KHR_push_descriptor without VK_KHR_get_physical_device_properties2), which isn't really better :)

**Comment by jzulauf-lunarg** [comment]
PR [2586](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/2586) fixes this.
