### ISSUE TITLE
Non consecutive vertex buffer bindings causes layer to report a warning

### ISSUE THREAD

**Issue by nikitablack** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2371]
Create multiple vertex buffers with non-consecutive binding indices:
```
VkVertexInputBindingDescription binding1{0, stride1, VK_VERTEX_INPUT_RATE_VERTEX};
VkVertexInputBindingDescription binding2{2, stride2, VK_VERTEX_INPUT_RATE_VERTEX};
```
Bind vertex buffers to specified indices:
```
vkCmdBindVertexBuffers(commandBuffer, 0, 1, &buffer1, &offset);
vkCmdBindVertexBuffers(commandBuffer, 2, 1, &buffer2, &offset);
```
Model renders as expected but validation layer emits
`validation layer: Cannot submit cmd buffer using deleted buffer 0x0.`

**Comment by critsec** [comment]
Just to link things in both directions, this came from a [StackOverflow question](https://stackoverflow.com/questions/48420392/why-multiple-vertex-buffer-bindings-should-be-consecutive).

**Comment by daveh-lunarg** [comment]
Assigning this to @chrisforbes, as he already has a PR up to fix it.
