### ISSUE TITLE
vulkaninfo doesn't give anything useful when DISPLAY is not set

### ISSUE THREAD

**Issue by jekstrand** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2379]
On Linux, if there is no DISPLAY environment variable (so it can't find X11), vulkaninfo doesn't give anything useful.  However, running a Vulkan driver headless is a perfectly reasonable thing to do so it should be able to print out everything other than the WSI information.

**Comment by krOoze** [comment]
I distinctly remember fixing that. Let's see... PR #2272.

**Comment by shannon-lunarg** [comment]
@jekstrand How are you producing this output?
I was able to break vulkaninfo as you described by setting the DISPLAY environment variable to nothing (`export DISPLAY=`) and two double quotes (`export DISPLAY=""`). Is this similar to how you achieved this effect?

**Comment by krOoze** [comment]
@shannon-lunarg That might be a good enhancement. It currently only considers if the `DISPLAY` is undefined.

PS `export DISPLAY=` is equivalent to `export DISPLAY=""`, right?

**Comment by jekstrand** [comment]
@shannon-lunarg I frequently run on machines with no X or Wayland server running.  In this case, neither DISPLAY nor WAYLAND_DISPLAY is even set.  Another way to reproduce this is to run `unset DISPLAY`.  Another is to SSH into a machine that can run Vulkan so you get a command-line environment only.

**Comment by krOoze** [comment]
@jekstrand Alright, try the new master, though `unset DISPLAY` should have worked even before...

**Comment by karl-lunarg** [comment]
`vulkaninfo` worked fine for me with no `DISPLAY` set in the environment before #2398 was merged.  

It is possible the @jekstrand was using `vulkaninfo` from an SDK that didn't have #2272 in it.

And #2398 does fix the crash when `DISPLAY=""`.

**Comment by jekstrand** [comment]
That's quite possible.  I've got 1.0.65 on my laptop.

**Comment by jekstrand** [comment]
I just pulled the latest and everything seems to work now.  Here's hoping Fedora pulls a new loader and demos in soon...
