### ISSUE TITLE
Buffer validation: Invalid check for VkBufferImageCopy::bufferOffset field.

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2382]
https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/6d71c6473925e03deab5b3396112cf31e95f1249/layers/buffer_validation.cpp#L1396

This check does not make much sense. I'm guessing this was supposed to validate following language:

``
bufferOffset must be a multiple of 4
``

meaning _granularity.width_ should have been 4 here.

**Comment by mark-lunarg** [comment]
This was originally in the spec as validated, and was also a vuid (VUID-VkBufferImageCopy-bufferOffset-00210, or VALIDATION_ERROR_016001a4) which has been deleted.  Removing the checks.
