### ISSUE TITLE
CoreValidation: "Blend state attachment/subpass color attachment count mismatch" should be reported at draw call time, not for vkCmdNextSubpass().

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#240]
Consider a renderpass where:

* subpass 0 defines 1 color attachment and uses pipeline A
* subpass 1 defines 0 color attachments and uses pipeline B

Pipeline B is bound before a draw call in subpass 1 is issued, but after renderpasses moves to subpass 1 with a vkCmdNextSubpass() call. In effect, I'm seeing the following debug call-back, which is incorrect & misleading:

![image](https://cloud.githubusercontent.com/assets/17761066/14205886/1ab0e68c-f80f-11e5-8234-d4a069f202f2.png)

**Comment by MarkY-LunarG** [comment]
Merged with pull request #490, commit id eca2d52a6bfa3f9d63a86ca9fd30abc0adf775b7.
