### ISSUE TITLE
CoreValidation: Invalid error debug call-back is generated if an event is repeatedly set with vkSetEvent(), waited on & reset from a cmd buffer

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#241]
Consider the following chain of actions:

1. Event A is set with vkSetEvent()
2. From command buffer X:
2a. the event is waited on with a vkCmdWaitEvents() call, whose srcStageMask is set to VK_PIPELINE_STAGE_HOST_BIT.
2b. the event is reset with vkCmdResetEvent()

Let the above actions be repeated per frame.

Starting from the second frame, I'm seeing an invalid debug call-back, indicating an error, being generated by the Core Validation layer:

![image](https://cloud.githubusercontent.com/assets/17761066/14206533/f92dbbc0-f813-11e5-95d7-2de2f815c144.png)

**Comment by DominikWitczakAMD** [comment]
Here's a bit more insight into what's happening:

The first _vkSetEvent()_ call sets:

![image](https://cloud.githubusercontent.com/assets/17761066/14206714/4fb69e16-f815-11e5-81cb-a9dc4f3284a2.png)

In the validation routine for _vkCmdWaitEvents()_, the new event's descriptor is stored in _dev_data->eventMap_.

This information is later correctly checked by one of the validation functions:

 ![image](https://cloud.githubusercontent.com/assets/17761066/14206757/a8ccbd1e-f815-11e5-8d88-335d5991eea7.png)

However, the recorded _vkCmdResetEvent()_ invocation enqueues a deferred call to _setEventStageMask()_ with _stageMask_ arg set to 0. This, in turn, stores the stage mask of 0 in both _pCB->eventToStageMap_ and _queue_data->second.eventToStageMap_ for that event handle.

![image](https://cloud.githubusercontent.com/assets/17761066/14206803/fb83b940-f815-11e5-8234-3da7ec0550fb.png)

This feels wrong.

We now start rendering the second frame, and the application submits the same command buffer. We again end up in _VkLayer_core_validation.dll::vkSetEvent() _which assigns the _STAGE_HOST_BIT_ stage mask to the event in _dev_data->eventMap[event handle]_.

The problem is that now _validateEventStageMask()_ enters a different if() block and assumes an invalid stage mask value should be passed with the vkCmdWaitEvents() call:

![image](https://cloud.githubusercontent.com/assets/17761066/14206854/5c05630e-f816-11e5-84e8-424f46e6739f.png)

**Comment by tobine** [comment]
I believe the vkCmdResetEvent() call that leads to both the cmd buffer and queue stageMask getting set to 0 is ok. This issue is that on the second submission of the cmd buffer, the queue still sees the event stageMask as "0" even though vkSetEvent() was called again.

One way to fix this is to make vkSetEvent() affect the stageMask of any queues that know about the event as well as the stageMask in the device-global eventMap.

I posted a proposed fix in #293 but need consultation from @lentinem to get his opinion.

**Comment by tobine** [comment]
#293 was merged to master, please confirm it fixes this issue and close if so

**Comment by DominikWitczakAMD** [comment]
Issue fixed :-) Closing.
