### ISSUE TITLE
vkGetSwapchainImagesKHR called more than once, returns another handle (ID)s

### ISSUE THREAD

**Issue by techlabxe** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2410]
When enabled validation layer and 'vkGetSwapchainImagesKHR' is called twice, 
I think that invalid handle (ID) returned.

I tried to vkGetSwapchainImagesKHR without validation layer, so value was same.
I expect the values to be the same when enabled validation layer.

example:
```
int count = 0; 
vkGetSwapchainImagesKHR(device, swapchain, &count, nullptr); // (e.g.) return count = 3.

VkImage images[3];
vkGetSwapchainImagesKHR(device, swapchain, &count, images); // (e.g.) return ID = 4,5,6

// again
vkGetSwapchainImagesKHR(device, swapchain, &count, images); // (e.g.) return ID = 7,8,9 
```

thanks

**Comment by cforfang** [comment]
Hmm, this sounds kinda similar to #2386... Are you running MSI Afterburner by any chance?

**Comment by techlabxe** [comment]
I also confirmed the issue. and I not installed MSI Afterburner.
Other sample programs are working normally.

I studing programming of vulkan, it was called twice (vkGetSwapchainImagesKHR) by chance.
Is it prohibited calling vkGetSwapchainImagesKHR twice ?

**Comment by krOoze** [comment]
> Is it prohibited calling vkGetSwapchainImagesKHR twice ?

No.
I can reproduce the issue too. Probably an `unique_objects` layer bug.

**Comment by techlabxe** [comment]
> it should be correctly translated back when handed out to the driver.

however, using VkImage (stored unique_object's ID, second call), 
GetImageState function is returend nullptr in PostCallRecordCreateImageView.

**Comment by mark-lunarg** [comment]
@techlabxe, the purpose of the unique-objects layer is to NEVER return the same handle for any object.  Vulkan does not disallow this, so this utility layer remaps the handles so that they are unique (even if as far as the driver is concerned it's the same object).  

As far as the image objects returned by GetSwapchainImagesKHR, even if they are the same driver objects, I believe it is unsafe for an application to assume this is so.  Are you running into bad validation errors or errors in your application?

**Comment by krOoze** [comment]
> [...], even if they are the same driver objects, I believe it is unsafe for an application to assume this is so.

Is it so? It was clarified some time ago that unless otherwisely specified, queries return constant values for the lifetime of queried object. It is further strongly implied the `vkCreateSwapchainKHR` creates those image objects, not `vkGetSwapchainImagesKHR`.

**Comment by techlabxe** [comment]
thanks for tell me that purpose of the unique-objects layer.


> Are you running into bad validation errors or errors in your application?

no bad validation warning or error reported.
Simply calling vkCreateImageView with images of the second call crashed with the validation layer.

**Comment by mark-lunarg** [comment]
@techlabxe & @krOoze, I am able to repro this here, lemme drag in some swapchain experts and I'll get back to you shortly!

**Comment by mark-lunarg** [comment]
Hey guys, you're right, looks like the handle wrapping is too aggressive here.  I'll get it fixed.  Thanks!

Unrelated, but while calling GetSwapchainImagesKHR repeatedly is perfectly valid, it is unnecessary.  Once for the size query and once to get the images is plenty.

**Comment by kikijiki** [comment]
So the problem in #2386 was just that Afterburner calls `vkGetSwapchainImagesKHR` a second time to initialize the OSD... makes sense.
