### ISSUE TITLE
VK_DYNAMIC_STATE_LINE_WIDTH and Geometry Shader

### ISSUE THREAD

**Issue by AaronHaganAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2429]
Can a check be added that if VK_DYNAMIC_STATE_LINE_WIDTH is set for the pipeline and there is a GS shader that outputs lines to verify that vkCmdSetLineWidth has been called before the draw.. 

According to the spec: 
VK_DYNAMIC_STATE_LINE_WIDTH specifies that the lineWidth state in
VkPipelineRasterizationStateCreateInfo will be ignored and must be set dynamically with
vkCmdSetLineWidth before any draw commands that generate line primitives for the
rasterizer.

**Comment by polarina** [comment]
Would such a validation not be required to check if the geometry shader actually outputs any line primitives? My understanding of the spec tells me that one may skip a call to vkCmdSetLineWidth as long as the geometry shader does not emit any line segments.

**Comment by AaronHaganAMD** [comment]
Yes. it only needs to be called before draw commands that generate line prims... 

• VK_DYNAMIC_STATE_LINE_WIDTH specifies that the lineWidth state in
VkPipelineRasterizationStateCreateInfo will be ignored and **mus**t be set dynamically with
vkCmdSetLineWidth before any draw commands that generate line primitives for the
rasterizer.

**Comment by chrisforbes** [comment]
@mark-lunarg this will require some work in shader_validation -- do you want me to pick that up?

**Comment by chrisforbes** [comment]
Fixed in #2508
