### ISSUE TITLE
VK_IMAGE_LAYOUT_UNDEFINED to VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL transition

### ISSUE THREAD

**Issue by Tulon** [KhronosGroup/Vulkan-LoaderAndValidationLayers#243]
In the spec (version 1.0.7), the section on vkDestroySemaphore() has a side note describing how to setup an image barrier for transitioning from VK_IMAGE_LAYOUT_PRESENT_SRC_KHR to VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL. In particular, it recommends:
> * srcStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT
* srcAccessMask = VK_ACCESS_MEMORY_READ_BIT
* dstStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT
* dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_READ_BIT | VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT.
* oldLayout = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR
* newLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL 

It also mentions the following:
> Alternately, oldLayout can be VK_IMAGE_LAYOUT_UNDEFINED, if the image’s contents need not be preserved.

Since I clear my color attachment during rendering anyway, I thought I could always do VK_IMAGE_LAYOUT_UNDEFINED to VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL transition as a rendering preparation step. This way I no longer need an initial transition away from VK_IMAGE_LAYOUT_UNDEFINED.
Unfortunately, when I tried this strategy, a validation layer complained about having srcAccessMask == VK_ACCESS_MEMORY_READ_BIT with oldLayout == VK_IMAGE_LAYOUT_UNDEFINED. Yet, the spec section on vkAcquireNextImageKHR() makes it clear VK_ACCESS_MEMORY_READ_BIT is required in srcAccessMask:
> The vkCmdWaitEvents or vkCmdPipelineBarrier used to transition the image away from VK_IMAGE_LAYOUT_PRESENT_SRC_KHR layout must have dstStageMask and dstAccessMask parameters set based on the next use of the image. The srcAccessMask must include VK_ACCESS_MEMORY_READ_BIT to ensure that all prior reads by the presentation engine are complete before the image layout transition occurs. 

So, it looks like using VK_IMAGE_LAYOUT_UNDEFINED in place of VK_IMAGE_LAYOUT_PRESENT_SRC_KHR is a no-go after all, despite the spec suggesting that as an option. Is my understanding correct?

**Comment by lentinem** [comment]
In this case, you are not transitioning away from PRESENT_SRC_KHR but instead transitioning from UNDEFINED so the later part of the spec is still correct but doesn't apply. If you do use UNDEFINED you shouldn't be using MEMORY_READ_BIT.

**Comment by Tulon** [comment]
I was under the impression you can use UNDEFINED as oldLayout in a barrier instead of the actual current layout, as long as you don't care about image contents being preserved.

From "Image Memory Barriers" section of the spec:
> oldLayout must be VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_PREINITIALIZED or the current layout of the image region affected by the barrier.

And this one from the section on vkDestroySemaphore():
> Alternately, oldLayout can be VK_IMAGE_LAYOUT_UNDEFINED, if the image’s contents need not be preserved.

Ideally I would like to always use oldLayout == UNDEFINED instead of PRESENT_SRC_KHR, since I don't need image contents preserved.

The spec seems to suggest I can do that, though in practice I can't, as oldLayout == UNDEFINED prevents me from setting srcAccessMask = VK_ACCESS_MEMORY_READ_BIT, which I have to, according to the spec.

I hope I was more clear this time.

**Comment by lentinem** [comment]
I looked into this a bit. This should just be a warning which you can ignore if you are taking advantage of this case. Are you getting an error?

**Comment by Tulon** [comment]
It's indeed a warning:
> Additional bits in Source accessMask 32768 [VK_ACCESS_MEMORY_READ_BIT]
 are specified when layout is VK_IMAGE_LAYOUT_UNDEFINED.

So, it looks like what I am trying to do is valid after all. Should this warning be removed then?

**Comment by lentinem** [comment]
We would like the keep the warning. Warnings indicate that you need to completely understand what you are doing but if you do (as is true in this case) then you can ignore it. This is a very specific case that is valid but in many cases if you are transitioning from undefined then those bits should not be set.
