### ISSUE TITLE
Invalid calculation of number of descriptors for maxDescriptorSetUniformBuffersDynamic limit

### ISSUE THREAD

**Issue by adam-sawicki-amd** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2437]
Latest version of the validation layer incorrectly reports following message:

> sum of dynamic uniform buffer bindings among all stages (16) exceeds device maxDescriptorSetUniformBuffersDynamic limit (8).

in case when I create a pipeline layout that uses 2 descriptor set layouts:
 
- First descriptor set layout uses 1 descriptor binding of “dynamic uniform buffer” type with 1 descriptor, with stageFlags = ALL = 0x7fffffff.
- Second descriptor set layout uses 2 descriptor bindings of “dynamic uniform buffer” type, 1 descriptor each, with stageFlags = 31 = 0b11111.

These are just 3 dynamic uniform buffers. But it seems that validation layer counts each buffer accessible to each shader stage as a separate buffer, hence the sum 16. This logic is probably in function `GetDescriptorSumAcrossStages`.

I believe this is a bug in validation layer, because Vulkan specification says:

> The total number of descriptors of the type VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC accessible across all shader stages and across all elements of pSetLayouts must be less than or equal to VkPhysicalDeviceLimits::maxDescriptorSetUniformBuffersDynamic

For me it means we are talking about the number of “buffers”, regardless of the number of shaders stages that they are available for.

**Comment by chrisforbes** [comment]
Fixed by #2432.

**Comment by adam-sawicki-amd** [comment]
OK, it's duplicate then.
