### ISSUE TITLE
build issues on gentoo

### ISSUE THREAD

**Issue by shaohme** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2440]
on my gentoo i've justed:
pulled the repository
checked out: "sdk-1.0.68.0"

and ran:

update_external_sources.sh
cmake -H. -Bdbuild -DCMAKE_BUILD_TYPE=Debug -DBUILD_WSI_WAYLAND_SUPPORT=OFF
cd dbuild
make

and ends up with:

[ 49%] Building CXX object tests/CMakeFiles/vk_layer_validation_tests.dir/layer_validation_tests.cpp.o
/home/mkj/dev/Vulkan-LoaderAndValidationLayers/tests/layer_validation_tests.cpp: In function ‘T NextAfter(T, T) [with T = float]’:
/home/mkj/dev/Vulkan-LoaderAndValidationLayers/tests/layer_validation_tests.cpp:173:12: error: ‘nextafterf’ was not declared in this scope
     return nextafterf(from, to);
            ^~~~~~~~~~
/home/mkj/dev/Vulkan-LoaderAndValidationLayers/tests/layer_validation_tests.cpp:173:12: note: suggested alternative: ‘NextAfter’
     return nextafterf(from, to);
            ^~~~~~~~~~
            NextAfter
/home/mkj/dev/Vulkan-LoaderAndValidationLayers/tests/layer_validation_tests.cpp: In member function ‘virtual void VkLayerTest_PSOLineWidthInvalid_Test::TestBody()’:
/home/mkj/dev/Vulkan-LoaderAndValidationLayers/tests/layer_validation_tests.cpp:10356:57: error: ‘nextafterf’ was not declared in this scope
     const std::vector<float> test_cases = {-1.0f, 0.0f, nextafterf(1.0f, 0.0f), nextafterf(1.0f, 2.0f), NAN};
                                                         ^~~~~~~~~~
/home/mkj/dev/Vulkan-LoaderAndValidationLayers/tests/layer_validation_tests.cpp:10356:57: note: suggested alternative: ‘NextAfter’
     const std::vector<float> test_cases = {-1.0f, 0.0f, nextafterf(1.0f, 0.0f), nextafterf(1.0f, 2.0f), NAN};
                                                         ^~~~~~~~~~
                                                         NextAfter
/home/mkj/dev/Vulkan-LoaderAndValidationLayers/tests/layer_validation_tests.cpp:10356:105: error: ‘NAN’ was not declared in this scope
     const std::vector<float> test_cases = {-1.0f, 0.0f, nextafterf(1.0f, 0.0f), nextafterf(1.0f, 2.0f), NAN};
                                                                                                         ^~~
/home/mkj/dev/Vulkan-LoaderAndValidationLayers/tests/layer_validation_tests.cpp:10356:108: error: could not convert ‘{-1.0e+0f, 0.0f, <expression error>, <expression error>, <expression error>}’ from ‘<brace-enclosed initializer list>’ to ‘const std::vector<float>’
     const std::vector<float> test_cases = {-1.0f, 0.0f, nextafterf(1.0f, 0.0f), nextafterf(1.0f, 2.0f), NAN};
                                                                                                            ^
/home/mkj/dev/Vulkan-LoaderAndValidationLayers/tests/layer_validation_tests.cpp: In member function ‘virtual void VkLayerTest_ImageFormatLimits_Test::TestBody()’:
/home/mkj/dev/Vulkan-LoaderAndValidationLayers/tests/layer_validation_tests.cpp:19135:50: error: ‘log2’ was not declared in this scope
     if ((imgFmtProps.maxMipLevels + 1) <= (floor(log2(maxDim)) + 1)) {
                                                  ^~~~
/home/mkj/dev/Vulkan-LoaderAndValidationLayers/tests/layer_validation_tests.cpp:19135:50: note: suggested alternative: ‘long’
     if ((imgFmtProps.maxMipLevels + 1) <= (floor(log2(maxDim)) + 1)) {
                                                  ^~~~
                                                  long
/home/mkj/dev/Vulkan-LoaderAndValidationLayers/tests/layer_validation_tests.cpp:19135:44: error: ‘floor’ was not declared in this scope
     if ((imgFmtProps.maxMipLevels + 1) <= (floor(log2(maxDim)) + 1)) {
                                            ^~~~~
/home/mkj/dev/Vulkan-LoaderAndValidationLayers/tests/layer_validation_tests.cpp:19135:44: note: suggested alternative: ‘float’
     if ((imgFmtProps.maxMipLevels + 1) <= (floor(log2(maxDim)) + 1)) {
                                            ^~~~~
                                            float
make[2]: *** [tests/CMakeFiles/vk_layer_validation_tests.dir/build.make:63: tests/CMakeFiles/vk_layer_validation_tests.dir/layer_validation_tests.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:367: tests/CMakeFiles/vk_layer_validation_tests.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

any ideas :-| ?

**Comment by krOoze** [comment]
> cmake -H. -Bdbuild -DCMAKE_BUILD_TYPE=Debug -DBUILD_WSI_WAYLAND_SUPPORT=OFF
> cd build

You cmake into `dbuild` but then use `build` instead.

> error: ‘nextafterf’ was not declared in this scope

`layer_validation_tests.cpp` is only missing `#include <math.h>, and probably is indirectly included on other platforms.
Try to add it, to fix your build.

**Comment by shaohme** [comment]
> You cmake into dbuild but then use build instead.
Sorry, that was a typo :-|

> Try to add it, to fix your build.
I will try later today

**Comment by shaohme** [comment]
> Try to add it, to fix your build.

adding `#include <math.h>` fixed the build issue :+1:

**Comment by mark-lunarg** [comment]
Will push @krOoze's change when CI is clear!
