### ISSUE TITLE
Missing indexed draw call validation

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2448]
Consider the following scenario:

1. Index buffer is assigned a memory range that fits X elements, each index taking N bytes.
2. Application records an indexed draw command which uses the index buffer and wants to draw Y elements using start index Z, where Y+Z > X

Use case 2:

1. Index buffer is assigned a memory range that fits X elements, each index taking N bytes.
2. Application records a bind index buffer command which uses a non-zero start offset.
3. Application records an indexed draw command which uses the index buffer and wants to draw Y elements using start index Z, where Y+Z <= X *but* the memory range the specified index range maps to exceeds available buffer memory

Core validation layer does not inform the draw call may try to use out-of-bound indices, even though there is a corresponding VU defined for the function:

``
indexSize * (firstIndex + indexCount) + offset) must be less than or equal to the size of the currently bound index buffer, with indexSize being based on the type specified by indexType, where the index buffer, indexType, and offset are specified via vkCmdBindIndexBuffer
``

**Comment by karl-lunarg** [comment]
I have a new validation layer test written for this.  Working on the validation layer checks now.

@DominikWitczakAMD, the layers don't currently analyze the Indirect flavors of Draw and DrawIndexed.  Are you concerned at all about these Indirect versions?

**Comment by DominikWitczakAMD** [comment]
@karl-lunarg: I'm not exactly concerned about the indirect variants at this point *but* if we have a gap here, it wound be useful to have it patched up as well :)

**Comment by DominikWitczakAMD** [comment]
Frankly, it's going to be a nightmare. :-( Even if the buffers used to host dispatch/draw call args used host-coherent mappable memory, the layers would still have a hard time with cases where a single cmd buffer does the following:

1. Stash cmd buffer args into a buffer using a dispatch/draw call.
2. Issue an indirect dispatch/draw call that consumes data generated in step 1.

The layer would need to transparently split the cmd buffer to two, inject an intermediary cmd buffer that fires a buffer barrier which lets you HOST_READ and verify the generated data on CPU. This can quickly get out of hand, especially if the submission chain gets complex (eg. the submission sets semaphores or fences)

Ugh.
