### ISSUE TITLE
Validation database Vs Issues tracker

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2449]
The Issue tracker is filled with [Incomplete] Issues which are mostly redundant to the `N` entries in the [VUID database](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/vk_validation_error_database.txt).
One Issue per-VU is unsustainable, and Issue should probably be open only if someone thinks the particular VU validation is extra important. So,

I suggest this [v. 2]:
- Make one meta-Issue for all of this
   - perhaps more; e.g. one for core commands, more for extensions (so it has more definite target for close)
   - it should contain info such as link to the db, what relevant Issues should contain, which labels to use, and link to filtered and sorted by `+1` Issue list
- Encourage people to make Incomplete Issues (iff they want to prioritize one VU validation), and `+1` vote on them
- Link to the meta-Issue heavily, notably from Known Issues section in the documentation

**Comment by mark-lunarg** [comment]
👍  Issues tagged **Incomplete** receive a higher priority than issues marked <N> in the database, but this effort would not change that priority.  See issue #1612 for an example of how this might look.

**Comment by mark-lunarg** [comment]
An **Enhancement** tracking issue would also help with issue clutter.

**Comment by krOoze** [comment]
Yes, except the curated list should not be needed, I think, if some discipline is maintained.

I.e.
- such Issues having proper Label
- people instructed to only open such Issues for voting purposes (emphasize that we already know all the holes in the layer impl)
- people encouraged to add `+1` to such issues
- such Issues being well searchable (e.g. contain all appropriate VEID codes, and perhaps VUID codes too, and all relevand cmd, struct and param names)

In that case it is possible to make GitHub do all the work, e.g.:
https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues?q=is%3Aopen+is%3Aissue+label%3Aincomplete+sort%3Areactions-%2B1-desc

**Comment by mark-lunarg** [comment]
@krOoze, maybe we're already where you want to go.  We rarely open issues (at least internally) against outstanding incomplete VU checks.  The issues that ARE opened, by Google, LunarG, or anybody else, are the highest priority behind bugs.  We could fold this information into the database, but it is captured here and we have medium-term plans to obsolete the database and replace it with a dynamic tool to give the same information.  I do like the idea of folding all of the INCOMPLETE issues into a single tracking issue, but maybe at the cost of some priority, age, etc. Enhancements I might tackle this way though.  Would you be comfortable closing this issue, knowing that we do not create tracking issues for all outstanding VUIDs?

**Comment by krOoze** [comment]
> Would you be comfortable closing this issue, knowing that we do not create tracking issues for all outstanding VUIDs?

"we"? What about the general public.

Anyway, it was just an idea. I am always comfortable with it closing as long as you are not interested in implementing it.

It is mostly about esthetics (or OCD?) than anything. The Issue is that there are Issues that practically serve no purpose (and also just contain unnecessary info, where usually just VUID would suffice). And they are bit of a bait; to get rid of one (for the Achievement you know), you would have to fix it -- but then again there might be checks in the DB that probably have better `benefit / cost`.

**Comment by mark-lunarg** [comment]
@krOoze, I'm totally with you on the OCD -- it is more than a little frustrating to constantly work this list and to have the issue count inexorably inch upwards.  Our stance on the general public creating missing VUID issues is that they must have encountered them In Real Life, making them perhaps more useful than purely technical checks.  Less than a handful of issues are from folks just pointing out the obvious (thank goodness).  And we value all of your ideas -- keep them coming.
