### ISSUE TITLE
Clean up stale branches

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2450]
Please consider cleaning up stale branches in this repo.

- It is cumbersome to switch to the relevant branches (master, sdk-1.0.X, ...).
- Or discover potentially useful branches.
- Cmdline tools would give more useful output (`git branch -r`)
- ?

**Comment by mikew-lunarg** [comment]
+1

**Comment by mark-lunarg** [comment]
@krOoze, I deleted about a hundred or so.  Planning to leave this open for about a week or so.  Feel free to gently call out offenders directly.

**Comment by krOoze** [comment]
Eyeing it, most branches seem to be @tobine , @lenny-lunarg and @cnorthrop . Gentlement, would you kindly start chipping those branches?

**Comment by cnorthrop** [comment]
I deleted a bunch of them through the Github interface earlier, I think they are gone now.

**Comment by lenny-lunarg** [comment]
I just deleted most of my branches. I left a couple that I still want, but that's only three. It looks we're down to 95 branches at this point.

**Comment by mark-lunarg** [comment]
Wow, @krOoze, this worked like a champ and I was surprised at the results.  Don't see any egregious offenders any more, but will keep cleaning.  Closing for now -- thanks!

**Comment by krOoze** [comment]
@mark-lunarg Great!

Let's see... master + sdk is 20 branches, open PR is ~16 branches. So still ~60 branches that are who-knows-what.

~14 are merged PR (+ 2 are closed as merged by other means), which usually are no-brainer for delete.

And there are two pages of years old branches that apparently didn't go through the PR interface. But nobody probably knows anymore what these are...

Anyway,
is there a reason to use the mainstream repo branches for the mundane patches? Could be done in the private repos (as any of the non-members do).

**Comment by cnorthrop** [comment]
Our internal CI requires the branches to be on the main repo, not downstream repos.  That's why you often see us pushing branches to test PRs.  We can be better at cleaning them up afterwards.
