### ISSUE TITLE
update_external_sources deletes files outside its own directory tree

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-LoaderAndValidationLayers#246]
I had a bunch of Vulkan-related projects in locations like:

    c:\vulkan\Vulkan-Docs
    c:\vulkan\Vulkan-LoaderAndValidationLayers
    c:\vulkan\glslang
    ...

with some local branches and modifications etc.

I wanted to build LoaderAndValidationLayers, so I followed the instructions and ran `update_external_sources.bat --all`.

That script automatically deleted my `..\glslang` directory (it intentionally calls `rd /S /Q %GLSLANG_DIR%`), which is quite surprising and dangerous.

I did have some local modifications in that directory, but (if I remember correctly) they weren't important so it didn't cause much real harm, but other people might be less lucky.

In general I think the contents of a git project should never affect any files outside of that repository's directory, to avoid surprises like this. I believe git is happy with nested git repositories, so the script could simply clone the dependencies into subdirectories of the `Vulkan-LoaderAndValidationLayers` directory (and add them to `Vulkan-LoaderAndValidationLayers\.gitignore` so they don't show up in `git status` in the outer repository), which would keep everything sensibly contained.

**Comment by jon-lunarg** [comment]
Phillip:
The LoaderAndValidationLayers  updates glslang outside of it's directory tree (eg ..) in part since other repos  VulkanTools  and samples have similiar dependencies on glslang.  We had issue with the update not happening correctly unless the entire glslang directory was deleted. Consider this an enhancement request for a better method.

**Comment by cnorthrop** [comment]
Moving the offending directories to a unique, date-based name instead of deleting would work.

**Comment by jon-lunarg** [comment]
Also reported that if one runs the script twice it fails the second time.

**Comment by jon-lunarg** [comment]
This has been fixed by syncing the glslang and spirv-tools  directories inside of the repository directory tree  in a directory called "external".  Thus, the update_external_sources script no longer updates directories outside of the source tree.
