### ISSUE TITLE
trampoline.c is missing core entrypoints

### ISSUE THREAD

**Issue by mchock-nv** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2476]
Specifically, 

vkCreateDescriptorUpdateTemplate
vkDestroyDescriptorUpdateTemplate
vkUpdateDescriptorSetWithTemplate

**Comment by lenny-lunarg** [comment]
Resolved via 27157624a7efc98de08c563f5b2c4f2732a68a46 and 8984ee77864cc9f4d8b235262a97d0622a5c9883. See the linked PR for more details.
