### ISSUE TITLE
Handle secondary cmd buffer clear attachment requests

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2480]
Extent checks for vkCmdClearAttachments() need to handle secondary command buffer cases.

There's a TODO in the code for this: https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/buffer_validation.cpp#L2201

Filing issue to track and bump priority as ANGLE team just got bit by this.

**Comment by mark-lunarg** [comment]
@tobine, hopefully this'll cover #1501 as well.
