### ISSUE TITLE
Compatibility class checks are failing for multiplane formats

### ISSUE THREAD

**Issue by atomnuker** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2482]
For example, creating an image view with format VK_FORMAT_R8_UNORM from an image with format VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM and the VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT yields the following error:

> vkCreateImageView(): ImageView format VK_FORMAT_R8_UNORM is not in the same format compatibility class as image (5)  format VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM.  Images created with the VK_IMAGE_CREATE_MUTABLE_FORMAT BIT can support ImageViews with differing formats but they must be in the same compatibility class. The spec valid usage text states 'If image was created with the VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT flag, format must be compatible with the format used to create image, as defined in Format Compatibility Classes' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkImageViewCreateInfo-image-01018)  

However, the spec says in "Compatible formats of planes of multi-planar formats" that they're fully compatible.
The same issue occurs with other non-planar formats too, like a view with format VK_FORMAT_R8G8_UNORM from VK_FORMAT_G8_B8R8_2PLANE_420_UNORM (NV12).

**Comment by atomnuker** [comment]
ping?

**Comment by daveh-lunarg** [comment]
Queued.
