### ISSUE TITLE
sort pieces of vulkaninfo output where sorting makes sense

### ISSUE THREAD

**Issue by jjulianoatnv** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2483]
I've been diffing output of vulkaninfo across different driver versions and across different GPUs.

There is a block of text near the top of the output that enumerates one instance extension per line. The order of lines in this block appears to be random. Maybe it is the iteration order through the keys of a hash map, or something like that.

The text itself is amenable to alphanumeric sort. The purpose of this issue is to propose that text blocks in vulkaninfo output be alphanumerically sorted in cases where doing so makes sense, and where the text is otherwise non-deterministically sorted.

Candidates for alphanumeric soft include:
- List of instance extensions
- List of device extensions

Things that need not be sorted alphanumerically include:
- Dump of the values of fields of a struct. Printing them in the order in which they appear in the struct definition is both sensible and deterministic.
- Dump of the bits that are set in a bitfield. Printing them in bit-position order is both sensible and deterministic.

For instance extensions, the order is up to the loader because the loader constructs a union-or-intersection of extensions from each physical device, and physical devices can themselves use different orders.

For device extensions, even when comparing from a single vendor, the order appears to be non-deterministic. This suggests that either the loader or the vulkaninfo app is already changing the order from that which is returned by the ICD. Even so, a vendor's ICD is not required to use a canonical sort order. It makes sense for vulkaninfo to ignore the ICD's own sort order and to output the extension list in a canonical sort order. Alphanumeric sort is probably the most sensible canonical sort order.

**Comment by jjulianoatnv** [comment]
Oh, for device extensions vulkaninfo might be using the ICD's order. When I look at my dGPU output it seems to have a stable order, but my iGPU's output does not. That could just mean that the iGPU driver does have itself have a stable ordering.

Still, when I have only a dGPU, the instance extension order is not stable, implying that the loader is probably itself using a random order. (That's still a guess.) And IMO it still makes sense to ignore the ICD's order or the loader's order, and for vulkaninfo to use a stable order regardless for instance and device extension lists.

**Comment by shannon-lunarg** [comment]
Fixed with PR #2617.
