### ISSUE TITLE
Dangling sampler references are not reported

### ISSUE THREAD

**Issue by FallenShard** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2485]
Greetings, I hope I'm posting this in the right place. There's a small issue I encountered in validation layers.
The setup is the following:
1) Create a VkSampler
2) Update some descriptor set's binding (e.g. COMBINED_IMAGE_AND_SAMPLER in my case) using the created sampler
3) Mistakenly delete the VkSampler from 1)
4) Draw stuff using the descriptor set from 2)

Nothing is crashing, though I think such errors could/should be reported by the validation layers at either descriptor bind or draw call. Discovered the issue through RenderDoc.
System: win10 x64 - SDK Version 1.1.70.0 - Nvidia 1080ti - driver version 391.01

**Comment by chrisforbes** [comment]
We should definitely pick this up if the descriptor in question is used by the draw.

**Comment by tobine** [comment]
Yeah I'll check this out and fix any hole here.

**Comment by tobine** [comment]
I think this is a hole. We should verify that sampler if valid in [this](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/descriptor_sets.cpp#L551) block where we're making sure the the components of descriptor are valid at draw time. We verify that the image hasn't been destroyed, but not the sampler. I've got a test that verifies this and will add the additional check.
