### ISSUE TITLE
Objects listed twice in validation error messages

### ISSUE THREAD

**Issue by Tony-LunarG** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2504]
Recent changes to layer logging have resulted in the object handle being listed twice:

DS(ERROR): **object: 0x191e90f0** type: 6 location: 7822 msg_code: 461375810: **Object: 0x191e90f0** | vkCmdPipelineBarrier(): pImageMemBarriers[0].dstAccessMask (0x1000) is not supported by dstStageMask (0x1). The spec valid usage text states 'Each element of pMemoryBarriers, pBufferMemoryBarriers and pImageMemoryBarriers must not have any access flag included in its dstAccessMask member if that bit is not supported by any of the pipeline stages in dstStageMask, as specified in the table of supported access types.'

**Comment by MarkY-LunarG** [comment]
Pull Request #2505 resolves this.
