### ISSUE TITLE
Incorrect case 

### ISSUE THREAD

**Issue by jherico** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2511]
https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/8d0233f2c8d0f56d092cb2d68a1c48939fe802ac/layers/core_validation.cpp#L4621

Should be `vkDestroyFramebuffer` not `vkDestroyFrameBuffer`

**Comment by mark-lunarg** [comment]
Fixed pushed to Master -- Thanks!
