### ISSUE TITLE
ABA issue with freeing and allocation of command buffers and destruction of command pools in core validation layer

### ISSUE THREAD

**Issue by fduranleau-gl** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2517]
We have stumbled recently on a bug in core validation layer. The bug lies in the layer's DestroyCommandPool API entry function. Here is the function:

```
VKAPI_ATTR void VKAPI_CALL DestroyCommandPool(VkDevice device, VkCommandPool commandPool, const VkAllocationCallbacks *pAllocator) {
    layer_data *dev_data = GetLayerDataPtr(get_dispatch_key(device), layer_data_map);
    unique_lock_t lock(global_lock);
    bool skip = PreCallValidateDestroyCommandPool(dev_data, commandPool);
    if (!skip) {
        lock.unlock();
        dev_data->dispatch_table.DestroyCommandPool(device, commandPool, pAllocator);
        lock.lock();
        if (commandPool != VK_NULL_HANDLE) {
            PostCallRecordDestroyCommandPool(dev_data, commandPool);
        }
    }
}
```

The problem is that the command pool's state is erased after destroying the command pool in the next layer while unlocked. After this line executed
```
        dev_data->dispatch_table.DestroyCommandPool(device, commandPool, pAllocator);
```
any other thread can allocate any number of command buffers, and it might (and will, we did get it) happen that memory freed by the above line is reused, and thus it's state will reuse the existing entry in the layer's command buffer map . So when we get to
```
            PostCallRecordDestroyCommandPool(dev_data, commandPool, cp_state);
```
it will destroy the command buffer's state, leaving the created command buffer with no state, and later on, we hit an assert (or a crash) about the command buffer's state being null.

I do not know why clearing the layer's command pool data must be done after calling the next layer's function. Looking in what PostCallRecordDestroyCommandPool does, it does not seem to require that order. Then again I might miss something. On our end, I replaced the code inside `if (!skip)` for
```
    //...
    if (!skip) {
        if (commandPool != VK_NULL_HANDLE) {
            PostCallRecordDestroyCommandPool(dev_data, commandPool, cp_state);
        }
        lock.unlock();
        dev_data->dispatch_table.DestroyCommandPool(device, commandPool, pAllocator);
    }
    //...
```
and aside from the fact that the function now does not bare the right name (rename it as `PreCallRecordDestroyCommandPool`?), it solved our problem. It also follows a normal reverse-order destruction sequence.

P.S.: The unlock/lock pattern around the next layer's API call and doing the core validation's associated work (other than validating) after that call is common in the code. I did not spend time to see if any other similar ABA issue exist.

**Comment by tobine** [comment]
Thanks, @fduranleau-gl I agree with your assessment and proposed fix. I'll create a formal PR and credit you.

**Comment by mark-lunarg** [comment]
@tobine, he has an existing PR, which we've added to.

**Comment by tobine** [comment]
@mark-lunarg cool, yeah, I see it now #2518. Thanks, @fduranleau-gl

**Comment by jzulauf-lunarg** [comment]
@fduranleau-gl  I'd like clarification on the usage pattern exposing the bug.

If you are saying that during the destruction of a command pool, that command buffers are being allocated from that same pool, that's a spec violation and an incomplete detection our the validation layers part to not report it.

Or... are you saying that when destroying *one* command pool, another is created and command buffers allocated from *that* pool are corrupted.  I'm trying to see the mechanism for failure and (absent unique objects) I could see a race where while deleting command pool with handle "A", another is created, given the same handle "A", meanwhile the destroy function is cleaning up the data from the destroyed version of "A".  (your fix, would be exactly correct for this failure mechanism)

**Comment by fduranleau-gl** [comment]
@jzulauf-lunarg It's exactly the second case you mention that we hit.

**Comment by jzulauf-lunarg** [comment]
@fduranleau-gl -- the case starting "Or..." or the case starting "I could also see" ?  (I should have numbered them :) ) 

Also, was the unique objects layer enabled?

**Comment by mark-lunarg** [comment]
Pushed changes to Master.  Thanks a bunch @fduranleau-gl.  I'll close the issue, but you guys can continue with the investigation in this issue.

**Comment by fduranleau-gl** [comment]
@jzulauf-lunarg It would be the "Or...", or a situation like this:

1. Thread 1 destroys a command pool, from which a command buffer with handle value A has been created.
2. Thread 1 unlocks and executes the down-chain call.
3. Thread 2, before thread 1 regains the lock, creates a command buffer from another pool. That command buffer gets handle value A.
4. Thread 1 regains the lock, and removes layer state data for command buffer with handle value A from the map.
5. Thread 2 executes a command with its newly allocated command buffer, but it's layer state has been destroyed.

The enabled layer was VK_LAYER_LUNARG_standard_validation, so yes, but it is higher up in the call chain.

**Comment by mark-lunarg** [comment]
@jzulauf-lunarg, Vulkan command buffer objects are dispatchable.  Unique objects wraps only non-dispatchable objects.  So all is right in the world again.
