### ISSUE TITLE
Core Validation layer crashes when different render pass is used for drawing than the one provided during pipeline creation

### ISSUE THREAD

**Issue by Ekzuzy** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2528]
Specification allows graphics pipelines to be used with various render passes that are compatible with the render pass provided during pipeline creation. Unfortunately, when the original render pass is destroyed after pipeline creation and then another render pass is created (even with exactly the same parameters!!), then crash occurs in VkLayer_core_validation.dll when trying to record a drawing command with such setup.

**Comment by Ekzuzy** [comment]
Problem was seen on 1.0.61.1 of Validation Layers but with the latest version it does not occur.

**Comment by mark-lunarg** [comment]
@Ekzuzy -- thanks very much for running this down!
