### ISSUE TITLE
Repo Closed.  See README.md [was: Closing this Repository To Write Access [was: Splitting this Repository]]

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2533]
The issue is meant to announce the upcoming split of this repository as well as a place to discuss the split and post news about the split.

For more information about the split, please see this wiki [page](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/wiki/Repository-Split).

Comments and questions should be made to the discussion section of this issue.

**Comment by karl-lunarg** [comment]
We were having a hard time finding homes for the less obvious components like vulkaninfo, cube, and the mock ICD.
One draft proposal had them all in a new repo KhronosGroup/Vulkan-Utils.
But we changed the draft to try to avoid creating this Vulkan-Utils repo and we had to put vulkaninfo someplace as a result.
We felt that vulkaninfo is a basic, simple, "canonical" app that is a companion to typical Vulkan installations and is good for testing for proper installation on desktop and for fetching basic information about the system, sort of like glxinfo.

I'll also add that the Vulkan-Loader repo can be configured with CMake variables like BUILD_LOADER and BUILD_VULKANINFO so that you could get the repo and avoid building the loader.

KhronosGroup/Vulkan-Tools is a good suggestion for a place to put vulkaninfo and the mock ICD.  It does have the problem of being confused with LunarG/VulkanTools, but we already have the same problem today with LunarG/VulkanSamples and KhronosGroup/Vulkan-Samples.

We'll give this some more thought.

**Comment by cnorthrop** [comment]
Thanks, Karl.  I do feel if you are going to go through all this effort, let's get it right.  I was okay with the Vulkan-Utils proposal.  Vulkan-Tools seems like a good idea too.  You're right, the mockICD is a tool as well.

**Comment by tobine** [comment]
I support the idea of KhronosGroup/Vulkan-Tools repo for vulkaninfo and mockICD

**Comment by karl-lunarg** [comment]
Thanks for the feedback.  I've updated the wiki to show the return to using Vulkan-Tools.

**Comment by mark-lunarg** [comment]
**UPDATE:**
This repository is slated to **close for write access** on **Sunday, 5/13/2018**.

- Existing **Issues** will be migrated to the appropriate follow-on repositories (Vulkan-Tools, Vulkan-Loader, or Vulkan-ValidationLayers).
- Any open **pull requests** will need to be manually moved after Sunday Morning.  Each PR owner will also be notified separately.

**Comment by mark-lunarg** [comment]
UPDATE: 
This repository is now read-only.  Issues have been migrated to the follow-on repositories listed below.  Pull Requests in this repository will need to be resubmitted in the new repositories.

- Vulkan-Headers
- Vulkan-Loader
- Vulkan-ValidationLayers
- Vulkan-Tools

**Comment by mark-lunarg** [comment]
Closing this issue and opening a new one so that it'll be on the top of the list.
