### ISSUE TITLE
Validate getter's structure count

### ISSUE THREAD

**Issue by iostrowsINTEL** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2535]
Getter functions like vkGetPhysicalDeviceSparseImageFormatProperties that require querying number of output structures before use should validate requested structure count.

`
If pProperties is NULL, then the number of sparse format properties available is returned in pPropertyCount. Otherwise, pPropertyCount must point to a variable set by the user to the number of elements in the pProperties array, and on return the variable is overwritten with the number of structures actually written to pProperties. If pPropertyCount is less than the number of sparse format properties available, at most pPropertyCount structures will be written.
`

It is not forbidden by spec to use pPropertyCount greater than available structure count, but it is rather unintentional, so warning should be reported.

There was a cts test issue where uninitialized pPropertyCount was used along with single pProperties structure, and function returned more than a single structure corrupting stack memory. Such check could spot it.

**Comment by mark-lunarg** [comment]
Great suggestion.  Added to the Assistant Layer tracking issue, #1612.
