### ISSUE TITLE
ParameterValidation layer + VK_KHR_descriptor_update_template: Invalid error reported for vkCreateDescriptorUpdateTemplateKHR()

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2537]
Spec says the following about VkDescriptorUpdateTemplateCreateInfoKHR::pipelineBindPoint:

```
pipelineBindPoint is a VkPipelineBindPoint indicating whether the descriptors will be
used by graphics pipelines or compute pipelines. This parameter is ignored if templateType
is not VK_DESCRIPTOR_UPDATE_TEMPLATE_TYPE_PUSH_DESCRIPTORS_KHR
```

However, for a templateType value of VK_DESCRIPTOR_UPDATE_TEMPLATE_TYPE_DESCRIPTOR_SET_KHR, I'm getting the following error reported at vkCreateDescriptorUpdateTemplateKHR() call time:

```
vkCreateDescriptorUpdateTemplateKHR: value of pCreateInfo->pipelineBindPoint (2147483647)
does not fall within the begin..end range of the core VkPipelineBindPoint enumeration tokens
and is not an extension added token. (null)
```

which is plainly wrong.

**Comment by jzulauf-lunarg** [comment]
This check no longer appears to be present in the parameter_validation_layer (though it is present as of SDK 1.0.68)

**Comment by DominikWitczakAMD** [comment]
Excellent, that works for me. Thanks!
