### ISSUE TITLE
Two image validation issues

### ISSUE THREAD

**Issue by pppessi** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2547]
> ERROR: Object: 0x0 | vkCmdCopyBufferToImage(): pRegion[0] exceeds image bounds. The spec valid usage text states 'The image region specified by each element of pRegions must be a region that is contained within srcImage' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkCmdCopyImageToBuffer-pRegions-00182). (code 0x1920016c from IMAGE at CommandBuffer:3921)

It should probably say `vkCmdCopyImageToBuffer` instead of `vkCmdCopyBufferToImage`.

https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/buffer_validation.cpp#L3933

Another one:

In `vk_format_utils.cpp` there is a map of different formats with byte size, number of channels and format compatibility class. In this map `VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK` has an element size of 8 bytes, but I believe it should be 16 bytes.

https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/vk_format_utils.cpp#L192

**Comment by daveh-lunarg** [comment]
Good catch (x2), @pppessi!

Love these quick & easy issues - wish they all were :)

Fix is incoming.
