### ISSUE TITLE
Threading layer: vkResetCommandBuffer() is incorrectly required to have exclusive access to the command pool

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2548]
The latest version of the Threading layer, checked out from Git repo earlier today reports the following error if >1 threads call vkResetCommandBuffer() for cmd buffers which have been allocated from the same command pool:

```
0x4c3ebb0 (Type = 25) | THREADING ERROR : object of type VkCommandPool is simultaneously used i
n thread 0x21a4 and thread 0x2af8
```

The only external sync requirement for the vkResetCommandBuffer() entrypoint listed in the spec for the entrypoint in question is:

```
Host access to commandBuffer must be externally synchronized
```

**Comment by chrisforbes** [comment]
5.2 says:

Command pools are externally synchronized, meaning that a command pool
*must* not be used concurrently in multiple threads. That includes use via
recording commands on any command buffers allocated from the pool, as well
as operations that allocate, free, and reset command buffers or the pool
itself.

**Comment by DominikWitczakAMD** [comment]
Ah ha! Would you agree this one is a spec issue then? It seems like the requirement should also be listed in the external synchronization requirements for the entrypoint.

**Comment by jzulauf-lunarg** [comment]
Or potentially is 5.2 overly broad?  If the intent is that CommandPools function as an SBA for command buffer objects that would then alloc/free as needed from some thread local arena (as they are recorded. reset, etc), then the language of 5.2 would be overly broad.  If instead the intent is that CommandPools function no only as the SBA for command buffers, but *also* act as the allocation arena for command buffers allocated from them,  then any vk operation that could alter the size/allocation of a command buffer would need the command pool synchronized, and have it's valid use updated.

**Comment by chrisforbes** [comment]
@jzulauf-lunarg I recall discussions about VkCommandPool from very early on where the intent was that you wouldn't share them between threads. I don't think there's any overreach here.

I disagree with shoehorning every piece of spec text into per-entrypoint VUs -- it's a cross-cutting requirement, and 5.2 specifies it fairly precisely. If you wanted to attach a VU tag to 5.2 itself that might be OK.

Closing this bug as there's nothing wrong on the LVL side.
