### ISSUE TITLE
Colorblend attachment count must match subpass colorAttachmentCount

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-LoaderAndValidationLayers#256]
Spec says that attachmentCount from pipeline's ColorBlendStateCreateInfo must match the colorAttachmentCount of "subpass" meaning the single subpass referenced in ColorBlendStateCreateInfo, but core_validation currently checks against each active subpass of the active renderpass.

The check should only apply to the single subpass at index "subpass", and not each subpass as they become active.

Relevant spec sections are concerning "VkGraphicsPipelineCreateInfo":

    If pColorBlendState is not NULL, The attachmentCount member of pColorBlendState must be equal to the value of colorAttachmentCount used to create subpass

And concerning "VkPipelineColorBlendStateCreateInfo":

    attachmentCount is the number of VkPipelineColorBlendAttachmentState elements inpAttachments. This value must equal the colorAttachmentCount for the subpass in which this pipeline is used.

**Comment by Tony-LunarG** [comment]
I think VulkanSamples issue 63 addresses at least part of this in that if the are no color attachments in the subpass, you shouldn't pass pColorBlendState at all.  I'm not sure what the answer is for 2 different subpasses with differing numbers of color attachments - that still needs to be addressed

**Comment by MarkY-LunarG** [comment]
This has been corrected with the changes in pull request #350 [https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/350]
