### ISSUE TITLE
Missing checks for VALIDATION_ERROR_32a00272

### ISSUE THREAD

**Issue by eskilsund** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2563]
Resetting descriptor pools with in-flight cmdbuffers seems to lack validation and I couldn't find any open issues on this. So here's my attempt at addressing this. (Feel free to reject if this is already tracked somewhere else.)

As seen in layers/core_validation.cpp
```
VKAPI_ATTR VkResult VKAPI_CALL ResetDescriptorPool(VkDevice device, VkDescriptorPool descriptorPool,
                                                    VkDescriptorPoolResetFlags flags) {
    // TODO : Add checks for VALIDATION_ERROR_32a00272
```
Failing to fence properly before resetting a pool seems like a common application issue so it would be good to get into the core validation layer.

I've already forked master and made a suggested fix here https://github.com/eskilsund/Vulkan-LoaderAndValidationLayers/commit/9fea1df674f9fa4f373dd1db6817510997e0b374

I can create a pull request and link to this issue if wanted.

**Comment by mark-lunarg** [comment]
@daveh-lunarg, can you take a look at the fix @eskilsund has pointed to?  It looks like it's ready for a PR to me, but you're the expert!

**Comment by chrisforbes** [comment]
I'd say go ahead with creating the pull request, and have the discussion of the details there.

**Comment by daveh-lunarg** [comment]
PR #2566 is merged so I guess this issue should be closed.
