### ISSUE TITLE
ImmutableSampler sample getting unwarranted validation error

### ISSUE THREAD

**Issue by Tony-LunarG** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2569]
The sample creates a sampler, and uses it as an immutable sampler in a COMBINED_IMAGE_SAMPLER descriptor set layout.  CV correctly puts it into the descriptors_  vector.  Later UpdateDescriptorSets is called, and the write to the descriptor has a VkDescriptorImageInfo.sampler value of 0 that is not ignored and overwrites the good pointer in descriptors_.  At draw time, CV validates the sampler and the 0 from the descriptor write is discovered and an error message to the effect that a descriptor is using a sampler that has been destroyed is printed.

The spec says:
```
typedef struct VkDescriptorImageInfo {
    VkSampler        sampler;
    VkImageView      imageView;
    VkImageLayout    imageLayout;
} VkDescriptorImageInfo;

sampler is a sampler handle, and is used in descriptor updates for types VK_DESCRIPTOR_TYPE_SAMPLER and 
VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER if the binding being updated does not use immutable samplers.
```
So sampler should not be used in descriptor updates if immutable samplers are being used.

**Comment by jzulauf-lunarg** [comment]
@chrisforbes  -- thanks for jumping on this! :1st_place_medal:
