### ISSUE TITLE
Parameter Validation: vkCreateRenderPass indexes NULL pResolveAttachments

### ISSUE THREAD

**Issue by TiemoJung** [KhronosGroup/Vulkan-LoaderAndValidationLayers#257]
Hi,

the Parameter Validation layer indexes into a NULL pointer.

pResolveAttachments of the sub pass description of a vkCreateRenderPass will always be indexed, even if it is NULL and will lead to a crash, the called function to validate an entry checks for NULL but if the index is not 0 then the pointer will not be NULL.
Even worse, all arrays of the sub pass description will be accessed w/o any null pointer checks and will lead to crashes instead of diagnostics.

The function in question is `parameter_validation_VkSubpassDescription` (auto generated i assume?)

**Comment by dustin-lunarg** [comment]
This should be fixed with commit 16ee6bb
