### ISSUE TITLE
Resource destruction that is referenced by pending command buffer

### ISSUE THREAD

**Issue by kennyalive** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2571]
Hello,

in the specification for resource destruction we have the following statement (I'll use VkImage as an example):

_All submitted commands that refer to image, either directly or via a VkImageView, must have completed execution_

a) From this follows it is not required that entire command buffer finished execution before deleting resource, it's enough to ensure that the commands of interest have finished execution. Is it correct?

In case a) is true:

b) I record some command that access an image and after it I record vkCmdSetEvent. After the command buffer is submitted I check event status using vkGetEventStatus and if event is set I delete the image using vkDestroyImage. According to a) this should be valid sequence of actions. Does validation layers handle this and **do not** report '_Cannot call vkDestroyImage on Image 0xdf77 that is currently in use by a command buffer_'?

**Comment by polarina** [comment]
A call to `vkCmdSetEvent` defines an execution dependency on commands that were submitted before it, but it does not define a memory dependency. The device may thus still be using the image after an event signal.

**Comment by kennyalive** [comment]
@polarina, that's a good point. 

Does the wording '_must have completed execution_' assumes only execution dependency?

**Comment by kennyalive** [comment]
In section 2.3.1 Object Lifetime we have more clear statement:

_The following Vulkan objects must not be destroyed while any command buffers using the object are in the pending state:
 ...
VkImage
..._

From it follows that we can not use event status as an indicator that resource can be destroyed - we should wait for entire command buffer. 

With everything said above I find this statement from documentation for vkDestroyImage correct but a bit misleading :

_All submitted commands that refer to image, either directly or via a VkImageView, must have completed execution_

since this formulation alone allows to write code that is forbidden by section 2.3.1.
