### ISSUE TITLE
Missing validation for vkInvalidateMappedMemoryRanges

### ISSUE THREAD

**Issue by cforfang** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2584]
Hi, commit 2fabc52a disabled some of the validation for ``vkInvalidateMappedMemoryRanges`` pending discussion in Khronos, but this was never enabled again after the discussion closed.

Could this be re-enabled again? I've some apps struggle with this VU in particular:
```
If size is not equal to VK_WHOLE_SIZE, size must either be a multiple of VkPhysicalDeviceLimits::nonCoherentAtomSize, or offset plus size must equal the size of memory.
```

**Comment by Tony-LunarG** [comment]
Fixed with PR #2595
