### ISSUE TITLE
update_external_sources has invalid glslang SHA1

### ISSUE THREAD

**Issue by jekstrand** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2592]
Running update_external_sources.sh fails with the following

    fatal: reference is not a tree: 3bb4c48cd95892a5cfcd63df20fcc47fd51c97a0

**Comment by greg-lunarg** [comment]
This is working on Linux for me and passes Travis. What environment are you running this in?

**Comment by jekstrand** [comment]
I just cloned into a different directory and now it works. I don't know why it wasn't working before.
