### ISSUE TITLE
Should "actual + rdur" be "desired + rdur" in cube.c ActualTimeLate()?

### ISSUE THREAD

**Issue by bradgrantham** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2602]
https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/826d9699aa66007e729c0649b283038a676d61d1/demos/cube.c#L572

**Comment by mark-lunarg** [comment]
@mikes-lunarg, this related to your cube glitches maybe?

**Comment by mikes-lunarg** [comment]
@mark-lunarg I don't think it is related.  ActualTimeLate() is part of the VK_GOOGLE_display_timing demo embedded within cube, which my desktop system does not support.

**Comment by ianelliottus** [comment]
@bradgrantham , @mark-lunarg , and @mikes-lunarg , I'll take a look at this (sounds like code that I wrote).

My understanding is that Keith Packard wrote VK_GOOGLE_display_timing support for at least one Mesa Vulkan driver (paid for by Valve).  I think it's for AMD hardware on Linux, but I'm not certain.

**Comment by ianelliottus** [comment]
@bradgrantham you are correct that there is a bug.  As @karl-lunarg described, #2637 is a fix that we should take.
