### ISSUE TITLE
core_validation::PostCallRecordFreeMemory() crashes at vkFreeMemory() call time

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2608]
This is only seen happening when multiple (4 in this case) threads (each using its own device created using the same shared Vulkan instance) do Vulkan stuff:

![image](https://user-images.githubusercontent.com/17761066/39183853-b1ee9ad6-47c1-11e8-9f87-730734d867b7.png)

![image](https://user-images.githubusercontent.com/17761066/39183917-ebe51ab2-47c1-11e8-82fe-3f0f8ddecdee.png)

No validation errors are reported prior to the crash.

This is seen happening with the latest version of the layers, checked out from this repo earlier today.

**Comment by jzulauf-lunarg** [comment]
I can see a race for two threads freeing the same memory on the same device, where one thread would end up with a pointer to a DEVICE_MEM_INFO erased by another thread -- though that would violate the "Host Synchronization" for vkFreeMemory.  I'll patch that a push that for review and test.  I don't see anyway two threads accessing two different devices could do the same thing however.

**Comment by DominikWitczakAMD** [comment]
Exactly, I'd assume that such condition would be prepended with a validation error, telling the same mem block is about to be released for the second time. I'm not getting any such error. In fact, I'm not getting any errors at all, apart from the crash.

Please ping me when the patch lands so I can give it a go. If the crashes are still there afterward, I can provide you with a repro so you can have something to work with.

**Comment by jzulauf-lunarg** [comment]
Created WIP branch with two commits.  One adds defensive/logging code for detect races and not dying, and the other plugs a potential hole in the threading layers logging (at some performance cost for singly threaded applications).

https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/tree/zulauf_free_mem_crash_2608

**Comment by DominikWitczakAMD** [comment]
Excellent. I'll get back to you later today with further feed-back.

**Comment by DominikWitczakAMD** [comment]
OK, I think I know what's cracking here. This issue appears to be directly related to the other one I also reported yesterday (https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2607).

I've modified my framework to:

1) Printf TID + mem handle at mem alloc time
2) Printf TID + mem handle at mem free time

Here's what I'm getting right before the new checks you added yesterday kick in:

![image](https://user-images.githubusercontent.com/17761066/39237215-22fdbe96-487b-11e8-979d-b7ac839c8201.png)

Thread A appears to be releasing a mem block. At a similar time, thread B tries to alloc a mem block and ends up being returned exactly the same handle. If my understanding is correct, vkAllocateMemory / vkFreeMemory do not need to be serialized even if they are used against the same VK device, so the only way I imagine this error to be reported is because of the additional validation overhead which I described in the other ticket.

Looks like we need to get #2607 out of the way before we can investigate this one. Chances are they have the same root cause.

**Comment by jzulauf-lunarg** [comment]
It's the same class of issue as #2607. I've updated the branch s.t. the free/allocation race is removed.

The other cause here is that "unique_objects" isn't enabled, and there are likely an even larger set of elements in this class for races that can occur when unique objects is disabled. (essentially any free/alloc, destroy/create pair where the driver is reusing handles)

I'll put together a PR that address this and 2607, and use that to drive a conversation about the broader set.

**Comment by mark-lunarg** [comment]
@DominikWitczakAMD, I'd suggest we try one more thing, perhaps removing everything from your layer list *except* for standard validation.  Don't have it handy, but the loader may process requested layers and 'standard_validation' in some non-obvious order.  Your optimal order is _either_ standard_validation, OR, {"VK_LAYER_GOOGLE_threading", "VK_LAYER_LUNARG_parameter_validation",
"VK_LAYER_LUNARG_object_tracker", "VK_LAYER_LUNARG_core_validation",
"VK_LAYER_GOOGLE_unique_objects"};

**Comment by DominikWitczakAMD** [comment]
Requesting only standard_validation does not appear to cause the loader to load any layers into process space.

On the other hand, if I use the list @mark-lunarg  suggested, the errors are gone. A question that arises at this point is how can a Vulkan application determine the right order, in which validation layers installed on the platform should be requested at instance creation time?

Until now, I had assumed that traversing the list reported by vkEnumerateInstanceLayerProperties() and caching any layer whose description includes "Validation" is what should be done, but it appears I was wrong ..

**Comment by DominikWitczakAMD** [comment]
I'll have a look at this tomorrow, thanks.
