### ISSUE TITLE
Creating multiplanar image views with multiplanar formats prints incorrect errors

### ISSUE THREAD

**Issue by atomnuker** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2619]
Attempting to create image views with multiplanar VkFormats (to use in converting samplers, for example NV12 to RGBA) prints the following error messages:

>vkCreateImageView(): ImageView format VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM is not compatible with plane 3 of underlying image format VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM, must be VK_FORMAT_UNDEFINED. The spec valid usage text states 'If image was created with the VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT flag, if the format of the image is a multi-planar format, and if subresourceRange.aspectMask is one of VK_IMAGE_ASPECT_PLANE_0_BIT, VK_IMAGE_ASPECT_PLANE_1_BIT, or VK_IMAGE_ASPECT_PLANE_2_BIT, then format must be compatible with the VkFormat for the plane of the image format indicated by subresourceRange.aspectMask, as defined in features-formats-compatible-planes' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VUID-VkImageViewCreateInfo-image-01586)                                                                                                                     

The spec says that to create multiplanar VkImageViews you need to OR all aspect flags applicable to the format you're trying to create an imageview for and use the original image format.

>vkCreateImageView() pCreateInfo->format VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM cannot be used with an image having the VK_IMAGE_TILING_OPTIMAL and VK_IMAGE_USAGE_STORAGE_BIT flags set. The spec valid usage text states 'If image was created with VK_IMAGE_TILING_OPTIMAL and usage contains VK_IMAGE_USAGE_STORAGE_BIT, format must be supported for storage images, as specified by the VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT flag in VkFormatProperties::optimalTilingFeatures returned by vkGetPhysicalDeviceFormatProperties with the same value of format' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkImageViewCreateInfo-image-01014)

This should be addressed by the image being created with an EXTENDED USE flag (which it is). So it shouldn't be printed unless the EXTENDED USE flag isn't set when creating the image.

**Comment by daveh-lunarg** [comment]
Yep, I just added that error message.  The multi-plane Hydra bites me again...

**Comment by atomnuker** [comment]
Thanks for dealing with all the issues I report, and sorry for bothering you.

**Comment by daveh-lunarg** [comment]
Found the invalid logic that assumed that if MUTABLE was set at image creation then the imageview would be of a different format, which isn't necessarily true. @atomnuker, it's no bother. Inserting the multiplane validation is proving to be complicated and (demonstrably) error-prone, so I appreciate having the real-world implementation feedback!

BTW, as I understand EXTENDED_USAGE it's only inspected at image creation time rather than imageview creation time (Or would be if those VUs were implemented, which isn't true as I type :( ).
