### ISSUE TITLE
Cannot coexist with glslang in the same Cmake project.

### ISSUE THREAD

**Issue by lawrencem99** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2622]
I'm testing the waters for an idea to allow the loader/validation library to coexist side-by side as sub directories in the same CMake project.

Currently I don't believe this is possible because this library re-defines the glslang libraries (please feel free to correct me on this).

It's a nice model for me because then I can work with the loader and glslang as first class citizens in CLion and not have to change workspace when I work on either library.

**Comment by mark-lunarg** [comment]
@lawrencem99, is this the information you needed?  In any case, the ability to use your own copy of glslang will be improved in the near future.

**Comment by lawrencem99** [comment]
Basically I think this is a special case where the LVL and glslang/spirv tools are subdirectories in the same cmake project, I'll just make a PR to illustrate better if I get the time.
