### ISSUE TITLE
CMake errors building LVL

### ISSUE THREAD

**Issue by Tony-LunarG** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2667]
There are CMake errors that result from CMake looking for pthread_create and secure_getenv in build/CMakeFiles/CMakeError.log.  While these don't prevent anything from building, when things do go wrong they are sometimes a distraction from the real issue.  We have had them reported in multiple issues, most recently in VulkanSamples, as the cause of compile failures, when the real cause was something else.

**Comment by Tony-LunarG** [comment]
Logfile from building today's master.
[CMakeError.log](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/files/1992458/CMakeError.log)

**Comment by TonyBarbour** [comment]
Closed as Vulkan-Loader #10
