### ISSUE TITLE
Texture buffer with R32G32B32_* not supported even when exposed by driver ?

### ISSUE THREAD

**Issue by vlj** [KhronosGroup/Vulkan-LoaderAndValidationLayers#267]
Hi,

I use a samplerBuffer in my vertex shader to load vertex with texelFetch(mySamplerBuffer, gl_VertexId);
However if I use R32G32B32_FLOAT format (48 bits) for the underlying bufferView on my radeon card (with drivers 16.3.2) there's no geometry appearing. If I use R32G32B32A32_FLOAT it works as expected. My vertex attributes are packed (ie stride is 48 bits in the former case and 64 bits in the latter).

According to the vulkan hardware database (http://vulkan.gpuinfo.org/listreports.php?bufferformat=R32G32B32_SFLOAT) the radeon card supports 3 x 4 bytes format for buffer.
Is there a driver bug or am I doing something not compliant with the spec ?

For reference it works correctly with R32G32B32 on a Geforce and the debug layer doesn't report anything.

**Comment by DominikWitczakAMD** [comment]
If you don't mind sharing the application's source code, I would definitely like to have a look.

**Comment by vlj** [comment]
It's rpcs3 : https://github.com/RPCS3/rpcs3 
You can use it with the primitive test in https://github.com/RPCS3/ps3autotests  - tests/rsx/primitives/primitives.ppu.elf.

Currently the app uses RGBA32 instead of RGB32 when requested as a workaround but I would rather use less component if possible.
DX12 codepath (rpcs3 supports both dx12 and Vulkan) uses DXGI_RGB32_FLOAT without issue on every IHV (the vertex buffer is wrapped inside a Buffer<float4>) so it hints me that GCN is able to read data with 12 bytes stride.

**Comment by DominikWitczakAMD** [comment]
I've started working on a repro for this issue, so I should be able to tell something more tomorrow. 

One way or another, probably best if we take this off-line, since this does not sound like a validation layer problem to.

vlj: Can you drop me an e-mail, please? It's dominik.witczak@amd.com. Thanks.

**Comment by jon-lunarg** [comment]
Dominik:
Thanks for jumping in here! Since this is probably not a loader or validation issue closing this issue.
