### ISSUE TITLE
Spacing in Paths

### ISSUE THREAD

**Issue by computerquip** [KhronosGroup/Vulkan-LoaderAndValidationLayers#27]
A path with a space in it, whether it be on Linux (update_external_sources.sh) or Windows( update_external_sources.bat), appears to be a nightmare. I did get the batch script to work on Windows with some simple quotes here and there, but then CMake gives me trouble with spacing as well. 

This was a little rough since MSYS2 has somewhat of a weird scheme where my full name with a space was used but you can force a home directory name thankfully with a bit of trouble. 

Would it be considered a bug to not have the scripts work with spaces in the current directory path?

**Comment by jon-lunarg** [comment]
I would consider it a feature request to be able to support a local directory path with spaces in it.  It sounds like you were able to get your local directory path to not have spaces in it?

**Comment by computerquip** [comment]
Yes, it's a minor request.

**Comment by karl-lunarg** [comment]
Fixed with cb788b361028f98b1928f68e0478ccc6c3582b2d
