### ISSUE TITLE
Resizing cube causes validation errors

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#275]
cube --validate emits 2 validation errors due to new validation checks.  May need to rework resize code along the lines of the resize code in Hologram.
(Note: Karl didn't see the validation errors on linux/nvidia)

**Comment by Tony-LunarG** [comment]
I don't think this is necessarily a problem with cube.  See Lunar Exchange #501  ‐  ERROR: [DS] Code 12: ...  In debugging this, I see  Cube has just recreated the swapchain images, all of which are (verified in the debugger) B8G8R8A8_UNORM and core-validation is complaining that ASPECT_DEPTH and ASPECT_STENCIL need to be set. Note that I've only seen this on Windows, never on Linux, so it could be something uninitialized

**Comment by Tony-LunarG** [comment]
Addressed by PR 503 - pushed to master
