### ISSUE TITLE
layer_validation_test failures

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#282]
AMD fails ResetUnsignalledFence, InvalidImageViewAspect, PSOViewportCountWithoutDataAndDynScissorMismatch and PSOScissorCountWithoutDataAndDynViewportMismatch as of 1.0.11 SDK

 VPG Fails ResolveHighSampleCount and ResolveImageTypeMismatch, 
Both Intel Linux drivers crash on many tests

**Comment by Tony-LunarG** [comment]
Fixed with 3291be9  at least for now
