### ISSUE TITLE
Validate imageExtent for copying to/from images and buffers

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-LoaderAndValidationLayers#284]
See spec section 18.4.

Copying to or from block-compressed images is typically done in multiples of the block. For this reason the imageExtent must be a multiple of the block dimension. There is one exception to this rule which is required to handle compressed images created with dimensions that are not a multiple of the block dimensions. If imageExtent.width is not a multiple of the block width then (imageExtent.width + imageOffset.x) must equal the subresource width, if imageExtent.height is not a multiple of the block height then (imageExtent.height + imageOffset.y) must equal the subresource height and if imageExtent.depth is not a multiple of the block depth then (imageExtent.depth + imageOffset.z) must equal the subresource depth.

Similar to the extent in copy image this needs to be validated with a set of if statements in both vkCmdCopyImageToBuffer and vkCmdCopyBufferToImage.

**Comment by daveh-lunarg** [comment]
This requirement is contained within valid usage statement no. 01270. ( VALIDATION_ERROR_01270 )

**Comment by daveh-lunarg** [comment]
Completed as part of adding valid use checks for vkCmdCopyImageToBuffer() and vkCmdCopyBufferToImage(), PR #1485.
