### ISSUE TITLE
Verify extent for copy image

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-LoaderAndValidationLayers#285]
See Spec section 18.3:

Copying to or from block-compressed images is typically done in multiples of the block. For this reason the extent must be a multiple of the block dimension. There is one exception to this rule which is required to handle compressed images created with dimensions that are not a multiple of the block dimensions. If the srcImage is compressed and if extent.width is not a multiple of the block width then (extent.width + srcOffset.x) must equal the subresource width, if extent.height is not a multiple of the block height then (extent.height + srcOffset.y) must equal the subresource height and if extent.depth is not a multiple of the block depth then (extent.depth + srcOffset.z) must equal the subresource depth. Similarily if the dstImage is compressed and if extent.width is not a multiple of the block width then (extent.width + dstOffset.x) must equal the subresource width, if extent.height is not a multiple of the block height then (extent.height + dstOffset.y) must equal the subresource height and if extent.depth is not a multiple of the block depth then (extent.depth + dstOffset.z) must equal the subresource depth.

When copy image is called, param checker should validate that the above is true which is a fairly straightforward set of if statements.

**Comment by yavn** [comment]
I'd like to request a further enhancement to verification of ranges, e.g. in `VkBufferImageCopy`.

It would be great to keep track of image size and mip levels and catch an invalid extent, for example:

```
const uint32_t          mipLevel = 1;
const VkBufferImageCopy region   =
{
    0ull,                                                                     // VkDeviceSize                bufferOffset;
    0u,                                                                       // uint32_t                    bufferRowLength;
    0u,                                                                       // uint32_t                    bufferImageHeight;
    makeImageSubresourceLayers(VK_IMAGE_ASPECT_COLOR_BIT, mipLevel, 0u, 1u),  // VkImageSubresourceLayers    imageSubresource;
    makeOffset3D(0, 0, 0),                                                    // VkOffset3D                  imageOffset;
    makeExtent3D(width, height, 1),                                           // VkExtent3D                  imageExtent;
};               ↑
                 oops, width is for level 0, so we're out of bounds now!
```

**Comment by daveh-lunarg** [comment]
These checks are in validation with PR #1796, and are mip-level aware.
