### ISSUE TITLE
Re-enable Xlib (and Xcb) by default for Linux builds

### ISSUE THREAD

**Issue by jon-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#295]
Xlib default was disabled since generated layers don't handle multiple platform surface extensions being enabled. Need to fix this.  Default loader and layers should at least have Xlib and Xcb WSI surface extensions built together (both enabled).

**Comment by Tony-LunarG** [comment]
Done and committed to master.  I also updated VTools to accommodate the LVL changes
