### ISSUE TITLE
Specifying #version 400 in glsl shaders triggers "shaderClipDistance" requirement error

### ISSUE THREAD

**Issue by hrydgard** [KhronosGroup/Vulkan-LoaderAndValidationLayers#298]
Not sure if the bug is in the validator or in glslang, but when compiling a GLSL vertex shader with #version 400 and then creating a pipeline from it with the validator enabled, I get the following:

ERROR: [SC]  Code 15 : Shader requires VkPhysicalDeviceFeatures::shaderClipDistance but is not enabled on the device

The shader code is as follows:

    #version 400
    #extension GL_ARB_separate_shader_objects : enable
    #extension GL_ARB_shading_language_420pack : enable
    layout (location = 0) in vec3 a_position;
    layout (location = 1) in vec2 a_texcoord0;
    layout (location = 0) out vec2 v_texcoord0;
    void main() {
      v_texcoord0 = a_texcoord0;
      gl_Position = vec4(a_position, 1.0);
    }

As you can see, gl_ClipDistance[]; is nowhere to be found. Or does 400 imply that requirement even if the feature isn't used?

The error goes away if I instead specify #version 140.

**Comment by lentinem** [comment]
Chris, can you take a look to see which one it is? I'm guessing this is not validation but it would be good to know for certain.

**Comment by hrydgard** [comment]
Oh yeah, this appeared in 1.0.8 - no such error in 1.0.5. If validation of this was just added, it's probably a glslang bug that the 1.0.5 validator didn't care about.

**Comment by greg-lunarg** [comment]
glslangValidator does appear to generate a ClipDistance capability for this
shader (at least it did a week ago when I last pulled it).

A reading of the GLSL spec seems to suggest that gl_ClipDistance is
implicitly declared when gl_PerVertex is not declared explicitly. This
could potentially justify the capability being enabled.

FWIW, the ClipDistance capability is not enabled in the SPIR-V when this is
added to your shader above main:

out gl_PerVertex {
    vec4 gl_Position;    // will use gl_Position
};

Greg


Greg Fischer

Project Manager and Senior Engineer

LunarG, Inc. - 3D Driver Innovations

greg@lunarg.com <alan@lunarg.com>

**Comment by chrisforbes** [comment]
Redeclaration of gl_PerVertex is required in order to subset it. This is
not a validation issue.

**Comment by greg-lunarg** [comment]
Not quite sure why this came to me, but since this does not appear to be a validation issue, this should be closed.

If you believe that glslang should not be generating the ClipDistance capability for this shader, I suggest opening an issue at https://github.com/KhronosGroup/glslang
