### ISSUE TITLE
[draw_state] Handle descriptors dynamically skipped in shader

### ISSUE THREAD

**Issue by mark-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#30]
From LunarXchange #325 from Baldur:

At the moment I have a 'render a texture' shader in renderdoc that has each different type of sampler - 2D array (which could have just 1 slice for just a 'normal' 2D image), 1D array similarly, 3D and 2DMS. Each of these is also duplicated for regular float, uint and int types.
The shader itself only ever samples from one of these 12 images, which one is determined by a uniform uploaded. I only set the corresponding descriptor and update it, the others I leave undefined (either unset, or set from previous use).

This currently crashes in the draw state validation layer, in this loop:
static VkBool32 validate_dynamic_offsets(layer_data* my_data, const GLOBAL_CB_NODE* pCB, const vector<SET_NODE*> activeSetNodes)
{
    VkBool32 result = VK_FALSE;

    VkWriteDescriptorSet* pWDS = NULL;
    uint32_t dynOffsetIndex = 0;
    VkDeviceSize bufferSize = 0;
    for (auto set_node : activeSetNodes) {
        for (uint32_t i=0; i < set_node->descriptorCount; ++i) {
            switch (set_node->ppDescriptors[i]->sType) {
                case VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET:

because that set_node->ppDescriptors could have some elements be NULL if they haven't been set. This crash should probably be fixed but I'm not clear if this is invalid or not.
I believe that descriptors which aren't used by the shader are allowed to be undefined - either unset, set to deleted objects, or something else. I'm not sure if that applies to descriptors which are used by the shader (in theory) but are then skipped by shader execution. I assume these probably have to be set to something valid, but does that also mean they have to be set to a valid texture of the write type? ie. 1D for 1D, 2D for 2D, etc.

Michael Lentine:
My understanding is that descriptors can have null elements (I would also assume this applies to those that are skipped by shader execution - seems weird to me to have different answers depending on if its used).

Tobin Ehlis:
Seeing NULL ppDescriptors during dynamic offset validation makes me think there's a bug in draw_state. Guarding against this case with the check as you have is certainly a reasonable workaround for the time being.
I suspect a bug b/c those should be active sets, meaning that the shaders are using them and they've been updated so we should have updated data.
Can you put a "TODO" comment in the code at the NULL check and file a GitHub issue against me to investigate and fix this case?
With the workaround I don't consider it high priority but would definitely like to get to it and the solution may involve replacing ppDescriptors with something better as that struct is kind of a vestige of the old, original C-based data structs.

**Comment by chrisforbes** [comment]
This sounds like invalid usage. Spec bug 103 has some discussion -- but the short version is that if the shader /statically/ uses a descriptor-backed resource, the descriptor must be valid.

**Comment by tobine** [comment]
#236 fixes this issue and was merged a while ago
