### ISSUE TITLE
race on globalLockInitialized: it is reset after releasing the mutex lock

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/Vulkan-LoaderAndValidationLayers#306]
In the device_limits layer, the reset of globalLockInitialized in vkDestroyInstance occurs *after* the mutex is released:

https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/device_limits.cpp#L185

It should occur before the release of the mutex.  The mutex should be guarding all transitions of the value of that variable.

**Comment by karl-lunarg** [comment]
No longer applies due to changes in the implementation.
