### ISSUE TITLE
vkCmdCopyQueryPoolResults executed from different command buffers

### ISSUE THREAD

**Issue by ArkadiuszSarwa** [KhronosGroup/Vulkan-LoaderAndValidationLayers#319]
When function vkCmdCopyQueryPoolResults is executed from diffrent command buffer (VkCommandBuffer) layers generate the error:

> DS(ERROR): object: 0 type: 0 location: 8634 msgCode: 14: Requesting a copy from query to buffer with invalid query: queryPool 80491216, index 0
> DS(ERROR): object: 0 type: 0 location: 8634 msgCode: 14: Requesting a copy from query to buffer with invalid query: queryPool 80491216, index 1
> DS(ERROR): object: 0 type: 0 location: 8634 msgCode: 14: Requesting a copy from query to buffer with invalid query: queryPool 80491216, index 2

Below the example of code, which should reproduce this situation.

```
....
	const vk::VkQueryPoolCreateInfo queryPoolCreateInfo	=
	{
		vk::VK_STRUCTURE_TYPE_QUERY_POOL_CREATE_INFO,
		NULL,
		0u,
		vk::VK_QUERY_TYPE_OCCLUSION,
		3,
		0
	};

	VK_CHECK(vk.createQueryPool(device, &queryPoolCreateInfo, /*pAllocator*/ DE_NULL, &m_queryPool));
...
//CommandBuffer 1
	vk.cmdBeginQuery(*cmdBuffer_1, m_queryPool, 0, 0);
	...
	vk.cmdEndQuery(*cmdBuffer_1, m_queryPool,	0);
	
	vk.cmdBeginQuery(*cmdBuffer_1, m_queryPool, 1, 0);
	...
	vk.cmdEndQuery(*cmdBuffer_1, m_queryPool, 1);
	
	vk.cmdBeginQuery(*cmdBuffer_1, m_queryPool, 1, 0);
	...
	vk.cmdEndQuery(*cmdBuffer_1, m_queryPool, 1);
...
//CommandBuffer 2
	vk.beginCommandBuffer(cmdBuffer_2, &beginInfo);
	vk.cmdCopyQueryPoolResults(cmdBuffer_2, m_queryPool, 0, 3, object, /*dstOffset*/ 0, ResultsStride, 0);
	vk.endCommandBuffer(cmdBuffer_2);
```
	
This error should not be displayed because in the specification there is no restriction about using two different CommandBuffer, layers should keep track of Query status between two different command buffers.

**Comment by DominikWitczakAMD** [comment]
Came across this issue as well.

**Comment by lentinem** [comment]
Is there a repro case for this?

**Comment by DominikWitczakAMD** [comment]
@ArkadiuszSarwa: do you have a repro for the discussed issue?

If not, I guess we could share an application with the team which does reproduce this problem.

**Comment by ArkadiuszSarwa** [comment]
@DominikWitczakAMD No I only created this issue. In my description is some example source which can reproduce it. If you have prepared the whole application which reproduce this problem, you can added it to this issue...

**Comment by lentinem** [comment]
Should be fixed. Please let me know if it's not.

**Comment by mark-lunarg** [comment]
Please reopen if the issue still manifests, closing for now.

**Comment by DominikWitczakAMD** [comment]
A "tad" late, but yeah, I can confirm the fix does exactly what was needed. Thanks!
