### ISSUE TITLE
Test WSI KHR_xlib_surface extension on Linux

### ISSUE THREAD

**Issue by jon-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#323]
Now that Xlib  is defaulted on. Update and existing test or write a new test to test the usage of this extension.  Could add a command line option to use xcb or xlib on tri for example.

**Comment by Tony-LunarG** [comment]
I updated cube to take a --xlib option that will use xlib instead of xcb on Linux (if the driver advertises the extension)
