### ISSUE TITLE
Validation layer should catch unbound descriptors in vkCreateDescriptorSetLayout

### ISSUE THREAD

**Issue by kayru** [KhronosGroup/Vulkan-LoaderAndValidationLayers#326]
If a shader contains gaps in descriptor bindings, like in the following example:

	#version 400
	#extension GL_ARB_separate_shader_objects : enable
	#extension GL_ARB_shading_language_420pack : enable
	layout (binding = 1) uniform sampler2D tex; // Slot 0 is intentionally left unused here
	layout (location = 0) in vec2 texcoord;
	layout (location = 0) out vec4 uFragColor;
	void main() {
	   uFragColor = texture(tex, texcoord);
	}

... the descriptor set layout must have declarations for the unused binding slots with `descriptorCount = 0`. Failure to declare bindings like that results in a crash later inside `vkCreateGraphicsPipelines` when using certain IHV drivers.

If possible, validation layer should catch unbound descriptors during `vkCreateGraphicsPipelines` and report a sensible error.

Full diff for a repro: [unbound_descriptors_diff.txt](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/files/217960/unbound_descriptors_diff.txt)

**Comment by kayru** [comment]
I think it may be necessary to validate the bindings in both `vkCreateDescriptorSetLayout` and `vkCreateGraphicsPipelines`.

**Comment by chrisforbes** [comment]
This should be resolved with newer drivers which handle sparse bindings correctly.

**Comment by chrisforbes** [comment]
Closing as a driver issue

**Comment by DominikWitczakAMD** [comment]
Chris, under what basis do you believe this to be a driver issue? Please point me to relevant spec language or WG discussion.

We have encountered this scenario a number of times and it is our belief it is apps' duty to define a dummy" slot in the DS in such cases.

**Comment by baldurk** [comment]
Maybe I'm misunderstanding the problem but I thought the purpose of the `VkDescriptorSetLayoutBinding::binding` index was to allow you to specify a descriptor set layout with sparse bindings, without needing dummies? If you have to specify each binding with dummies, the binding index be redundant as it'd be equal to the index in the `VkDescriptorSetLayoutCreateInfo::pBindings` array.

In the spec under `VkDescriptorSetLayoutBinding` there is the following text which seems to back this up:

> The above layout definition allows the descriptor bindings to be specified sparsely such that not all binding numbers between 0 and the maximum binding number need to be specified in the `pBindings` array. However, all binding numbers between 0 and the maximum binding number may consume memory in the descriptor set layout even if not all descriptor bindings are used, though it should not consume additional memory from the descriptor pool.

**Comment by DominikWitczakAMD** [comment]
Without an intention of playing a trading card game :), here's our counter:

* Section 13.2.2, valid usage block for VkPipelineLayoutCreateInfo:

> If setLayoutCount is not 0, pSetLayouts must be a pointer to an array of setLayoutCount valid VkDescriptorSetLayout handles

..where "valid" means non-VK_NULL_HANDLE.
