### ISSUE TITLE
Validation layer reports error if barrier has access mask that doesn't match with image layout

### ISSUE THREAD

**Issue by misojarv** [KhronosGroup/Vulkan-LoaderAndValidationLayers#327]
The spec doesn't require access mask and layout to match. At most this should be warning or performance warning.

CTS tests in  dEQP-VK.memory.pipeline_barrier.* trigger this.

There might be actually usecase for srcLayout = UNDEFINED and srcAccessMask other than 0. The application has to depend on previous write operation to make sure caches are flushed/invalidated, but it might not care about the image contents.

**Comment by lentinem** [comment]
This is already a warning.

**Comment by misojarv** [comment]
The error  that I get is: "ERROR: Dest AccessMask 0 [None] must have required access bit 2048 [VK_ACCESS_TRANSFER_READ_BIT]  when layout is VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, unless the app has previously added a barrier for this transition. (code 0x0000000c at Unknown:8208)".

The destination access mask is allowed to be 0 or anything else as long as there is dependency chain between pipeline barrier doing the layout transition and the memory access, and the dependency chain includes barrier where destination mask is correct.

**Comment by lentinem** [comment]
Weird; the message says that this only has to be true when the app doesn't have such a chain but for some reason this one in contrast to the others is an error. Will fix.

**Comment by lentinem** [comment]
Fixed.
