### ISSUE TITLE
Validation layer reports errors if memory object alias same memory

### ISSUE THREAD

**Issue by misojarv** [KhronosGroup/Vulkan-LoaderAndValidationLayers#328]
Memory objects are allowed to alias. See "11.8 Memory Aliasing" in the spec.

Triggered by CTS tests:
dEQP-VK.memory.pipeline_barrier.*

**Comment by lentinem** [comment]
Please post the error you found.

**Comment by misojarv** [comment]
The error messages are: 
"ERROR: Buffer 33d7f30 is alised with image 33f2fc0 (code 0x00000003 at Buffer:0)"
"ERROR: Image 3426160 is alised with buffer 33d7f30 (code 0x00000003 at Image:0)"

The test case does make sure that they are never used at the same time and that correct pipeline barriers are used.

**Comment by mark-lunarg** [comment]
Aliasing memory objects will no longer result in validation errors. #1264 has taken care of this for the most part.
