### ISSUE TITLE
Validation layer should check that vk(Invalidate|Flush)MappedRange() rounds ranges to VkPhysicalDeviceLimits::nonCoherentAtomSize

### ISSUE THREAD

**Issue by misojarv** [KhronosGroup/Vulkan-LoaderAndValidationLayers#329]
The spec section "10.2.1. Host Access to Device Memory Objects" has error condition for VkMappedMemoryRange arguments:
"offset must be a multiple of VkPhysicalDeviceLimits::nonCoherentAtomSize" and
"If size is not equal to VK_WHOLE_SIZE, size must be a multiple of VkPhysicalDeviceLimits::nonCoherentAtomSize"

The CTS tests in dEQP-VK.memory.mapping.\* currently don't check this and there are probably other tests too.

**Comment by lentinem** [comment]
This is a bug with CTS? Are you saying validation doesn't check this?

**Comment by misojarv** [comment]
This is a feature request.

The CTS does have some known issues with this, but the validation layer doesn't seem to be catching them.

**Comment by mark-lunarg** [comment]
Addressed by PR #1157 .

**Comment by mikew-lunarg** [comment]
There is a discussion about this at GitLab issue 611.
Meanwhile, PR #1157 has been disabled by commits 2fabc52a37efad97b70642932652a7129dcce79e and 82dbf60aef6769c5556deae2f8482ea9ce72c7c3

**Comment by mark-lunarg** [comment]
Gitlab issue #611 has been closed, the PR was accepted, and LVL was updated.
