### ISSUE TITLE
Missing formats in layers/core_validation.cpp get_format_type()

### ISSUE THREAD

**Issue by misojarv** [KhronosGroup/Vulkan-LoaderAndValidationLayers#330]
At least formats VK_FORMAT_A8B8G8R8_SINT_PACK32 and VK_FORMAT_A8B8G8R8_UINT_PACK32 are missing. This means that they are incorrectly mapped to FORMAT_TYPE_FLOAT.

**Comment by lentinem** [comment]
What does missing mean? Is there more info here?

**Comment by misojarv** [comment]
The CTS tests in dEQP-VK.renderpass.formats.a8b8g8r8_uint_pack32.* and dEQP-VK.renderpass.formats.a8b8g8r8_sint_pack32.* trigger the issues.

The error is:
"ERROR: Attachment 0 of type `VK_FORMAT_A8B8G8R8_SINT_PACK32` does not match FS output type of `ptr to output vec4 of sint32` (code 0x00000001 at Unknown:1776)"

If I map VK_FORMAT_A8B8G8R8_SINT_PACK32 to FORMAT_TYPE_SINT and VK_FORMAT_A8B8G8R8_UINT_PACK32  to FORMAT_TYPE_UINT, the tests start passing.

**Comment by chrisforbes** [comment]
@misojarv thanks for pointing these out. Fixed with #390.
