### ISSUE TITLE
Validation layer doesn't understand dependency chains between subpasses.

### ISSUE THREAD

**Issue by misojarv** [KhronosGroup/Vulkan-LoaderAndValidationLayers#334]
Validation layer seems to report errors unless there is direct dependency from subpass to all previous subpasses using the same attachment. It should be enough if there is dependency chain from source subpass to destination subpass.

The CTS tests in dEQP-VK.renderpass.attachment_allocation.* trigger this issue. The error logs are pretty spammy and include following message many times with different src and dst subpasses:
"ERROR: A dependency between subpasses 0 and 2 must exist but only an implicit one is specified. (code 0x0000002d at Unknown:8777)"

The subpass dependency chains are defined in the spec:
"A subpass dependency chain is a sequence of subpass dependencies in a render pass, where the source subpass of each subpass dependency (after the first) equals the destination subpass of the previous dependency."

The memory synchronisation language that defines execution and memory dependencies for subpasses is mostly in the "6.4. Execution And Memory Dependencies" -section.

**Comment by lentinem** [comment]
Yea. Spec has changed since that was written.

**Comment by lentinem** [comment]
Fixed.
