### ISSUE TITLE
Undefined memory tracking is not fine grained enough

### ISSUE THREAD

**Issue by misojarv** [KhronosGroup/Vulkan-LoaderAndValidationLayers#335]
Using render pass storeOp VK_ATTACHMENT_STORE_OP_DONT_CARE marks the whole image as undefined even if the render area doesn't cover the whole image.

Reading or using memory that has not been defined before isn't error by the spec, but the results are undefined. I think it would be better to report warning when accessing undefined memory.

Following CTS tests trigger the issue.
dEQP-VK.renderpass.attachment.*
dEQP-VK.renderpass.attachment_allocation.*

The message is:
"ERROR: vkCmdCopyImageToBuffer(): Cannot read invalid memory 22d0b40, please fill the memory before using. (code 0x00000010 at DeviceMemory:431)"

**Comment by mark-lunarg** [comment]
This has been changed to a Warning.
