### ISSUE TITLE
vkCmdExecuteCommands marks the buffer "in flight" right away

### ISSUE THREAD

**Issue by yavn** [KhronosGroup/Vulkan-LoaderAndValidationLayers#339]
I'm recording a primary command buffer that executes a secondary command buffer (in pseudocode):

```
vkBeginCommandBuffer(secondaryBuf, &secondaryBeginInfo)
vkEndCommandBuffer(secondaryBuf)

vkBeginCommandBuffer(primaryBuf, &primaryBeginInfo)
vkCmdExecuteCommands(primaryBuf, 1u, &secondaryBuf)
vkEndCommandBuffer(primaryBuf)

// primary buffer is NOT submitted for execution

vkDestroyCommandPool(device, cmdPool, NULL)
```

However, the command buffer is never submitted to a queue. Therefore, neither primary nor secondary buffer is actually executed. Regardless, I'm getting this message when I free the command buffers:

> DS(ERROR): object: 0x601f560 type: 6 location: 5904 msgCode: 54: Attempt to free command buffer (0x601f560) which is in use.

I think the problem is in `vkCmdExecuteCommands()` in `core_validation.cpp`, where the secondary buffer is being added to `globalInFlightCmdBuffers` right away. Instead, I would expect this to happen only after the primary buffer was submitted to a queue.

**EDIT**

I'm also getting this:

> DS(ERROR): object: 0x5f99f40 type: 6 location: 10119 msgCode: 53: Attempt to simultaneously execute CB 0x5f99f40 w/o VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT set!

even though the secondary command buffer is used only once. Note though, that this is intermittent and happens only when running without debugger attached.

**Comment by tobine** [comment]
Submitted #345 to fix this issue

**Comment by tobine** [comment]
Fix was cherry-picked and pushed to master
