### ISSUE TITLE
Error in compiling

### ISSUE THREAD

**Issue by Joilnen** [KhronosGroup/Vulkan-LoaderAndValidationLayers#358]
I have this 
-- Glslang --
Glslang Version: SPIRV99.947 15-Feb-2016
ESSL Version: OpenGL ES GLSL 3.00 glslang LunarG Khronos.SPIRV99.947 15-Feb-2016
GLSL Version: 4.20 glslang LunarG Khronos.SPIRV99.947 15-Feb-2016
SPIR-V Version 0x00010000, Revision 3
GLSL.std.450 Version 100, Revision 1
Khronos Tool ID 8

-- Vulkan-LoaderAndValidationLayers --

[ 96%] Building CXX object tests/CMakeFiles/vk_layer_validation_tests.dir/test_nvironment.cpp.o
[ 97%] Linking CXX executable vk_layer_validation_tests
/usr/lib64/gcc/x86_64-slackware-linux/5.3.0/../../../../lib64/libglslang.a(ShadrLang.cpp.o): In function `bool (anonymous namespace)::ProcessDeferred<(anonymos namespace)::DoPreprocessing>(TCompiler*, char const* const*, int, int const*,char const* const*, char const*, EShOptimizationLevel, TBuiltInResource const*,int, EProfile, bool, bool, EShMessages, glslang::TIntermediate&, (anonymous namspace)::DoPreprocessing&, bool, glslang::TShader::Includer&)':
ShaderLang.cpp:(.text+0x4cb1): undefined reference to `glslang::HlslParseContex::HlslParseContext(glslang::TSymbolTable&, glslang::TIntermediate&, bool, int, Profile, int, int, EShLanguage, TInfoSink&, bool, EShMessages)'
/usr/lib64/gcc/x86_64-slackware-linux/5.3.0/../../../../lib64/libglslang.a(ShadrLang.cpp.o): In function `bool (anonymous namespace)::ProcessDeferred<(anonymos namespace)::DoFullParse>(TCompiler*, char const* const*, int, int const*, cha const* const*, char const*, EShOptimizationLevel, TBuiltInResource const*, int EProfile, bool, bool, EShMessages, glslang::TIntermediate&, (anonymous namespae)::DoFullParse&, bool, glslang::TShader::Includer&)':
ShaderLang.cpp:(.text+0x58e3): undefined reference to `glslang::HlslParseContex::HlslParseContext(glslang::TSymbolTable&, glslang::TIntermediate&, bool, int, Profile, int, int, EShLanguage, TInfoSink&, bool, EShMessages)'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/vk_layer_validation_tests] Error 1
make[1]: *** [tests/CMakeFiles/vk_layer_validation_tests.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 98%] Linking CXX shared library libVkLayer_core_validation.so
[100%] Built target VkLayer_core_validation
make: *** [all] Error 2

**Comment by tobine** [comment]
Did you run update_external_sources.sh from the root of your "Vulkan-LoaderAndValidationLayers" workspace?

**Comment by jon-lunarg** [comment]
We weren't able to reproduce this issue.  Reopen if it is still a problem.
