### ISSUE TITLE
ParamValidation(?): vkCmdBindDescriptorSets does not catch a corner case

### ISSUE THREAD

**Issue by TiemoJung** [KhronosGroup/Vulkan-LoaderAndValidationLayers#359]
Hi,

a corner case of the inputs to vkCmdBindDescriptorSets is not cached:
1) create descriptor pool
2) allocate descriptor set
3) reset descriptor pool
4) submit vkCmdBindDescriptorSets with the set allocated in 2)
5) no error is reported

Checked with 88f2e92a842cb325b7f17b56ca5aaf2c6f1f1617
And VK_LAYER_LUNARG_standard_validation was turned on

**Comment by tobine** [comment]
Yep, this is a hole, thanks.
Submitted #360 to fix this.

**Comment by tobine** [comment]
Fix was cherry-picked and pushed to master
