### ISSUE TITLE
loader: pointer cast build warnings

### ISSUE THREAD

**Issue by garyjsweet** [KhronosGroup/Vulkan-LoaderAndValidationLayers#36]
When cross-compiling for our 32-bit Linux embedded platform we see warnings regarding pointer casts due to non-dispatchable object handles being uint64_t on these platforms.

Here are the 3 warnings in question. They can all be trivially fixed by adding an intermediate cast to (uintptr_t) between the object and the final type.

[ 14%] Building C object loader/CMakeFiles/vulkan.dir/loader.c.o
.../Vulkan-LoaderAndValidationLayers/loader/loader.c: In function ‘loader_log’:
.../Vulkan-LoaderAndValidationLayers/loader/loader.c:238:33: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
                                 (uint64_t)inst, 0, msg_code, "loader", msg);

[ 28%] Building C object loader/CMakeFiles/vulkan.dir/trampoline.c.o
.../Vulkan-LoaderAndValidationLayers/loader/trampoline.c: In function ‘vkCreateInstance’:
.../Vulkan-LoaderAndValidationLayers/loader/trampoline.c:86:33: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
             instance_callback = (VkDebugReportCallbackEXT)ptr_instance;

[ 42%] Building C object loader/CMakeFiles/vulkan.dir/wsi.c.o
.../Vulkan-LoaderAndValidationLayers/loader/wsi.c: In function ‘loader_DestroySurfaceKHR’:
.../Vulkan-LoaderAndValidationLayers/loader/wsi.c:212:36: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     loader_heap_free(ptr_instance, (void *)surface);

**Comment by MarkY-LunarG** [comment]
Can you give us more info like:
 - Which embedded target (ARM, PowerPC, ...)
 - Are you building on Windows and cross-compiling for that target, or are you building on Linux?
 - What compiler are your using?
Personally, I don't like adding an intermediate cast if we can fix it properly some other way.

**Comment by MarkY-LunarG** [comment]
Things for you to try:
1) Try uintptr_t instead of uint64_t for loader.c:238
2) I think this is gone, so you shouldn't have this any more
3) Can you look into what type surface is using?  It should easily convert to a void* (which it does on other 64-bit or 32-bit targets).

**Comment by MarkY-LunarG** [comment]
Closing as I've heard nothing back, and this issue can't be fixed without more info.
