### ISSUE TITLE
backslash in JSON loader files not properly escaped by cJSON library

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#362]
Moved from gitlab 31

"One thing I did notice that doesn’t work is having a path with a backslash in it. There’s a bug in the JSON parser that prevents this. Basically, when the JSON string values are parsed, backslashes are escapes, which means that single backslashes are merged with the next character as an escape code and are therefore eaten. However, if you escape the backslash (put a double backslash) in the string, it properly unescapes it, but then before returning the string, it re-escapes everything, turning the (now escaped) double backslash into four backslashes. Therefore, it’s physically impossible to have a string with a single backslash in it with the JSON parser you’re using. It just happens to work for paths on Windows because the filesystem folds consecutive backslashes together. But really, that’s just luck. You might want to fix that too."

**Comment by MarkY-LunarG** [comment]
Return strings now fixed with commit 31dbc350191fc2f5d86e48b00fa9c4eeb4e842ce
