### ISSUE TITLE
The mem tracker validation layer reports a memory leak when calling vkDestroyDebugReportCallbackEXT after vkDestroyDevice.

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#365]
Moved from gitlab 93

The mem tracker validation layer reports a memory leak when calling vkDestroyDebugReportCallbackEXT after vkDestroyDevice, but before vkDestroyInstance, even though VkDebugReportCallbackEXT is an instance object.

`Mem Object 148617029248 has not been freed. You should clean up this memory by calling vkFreeMemory(148617029248) prior to vkDestroyDevice().`

**Comment by mre4ce** [comment]
With latest master I am unable to reproduce this problem.

**Comment by mark-lunarg** [comment]
Thanks for the quick feedback Johannes.
