### ISSUE TITLE
Validate that VkSwapchainCreateInfoKHR::imageSharingMode = VK_SHARING_MODE_CONCURRENT when using separate present queue family.

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#366]
Moved from gitlab 94

Would it be possible to add validation that VkSwapchainCreateInfoKHR::imageSharingMode = VK_SHARING_MODE_CONCURRENT when presentation happens on a different queue family than updating the swapchain images?

**Comment by mark-lunarg** [comment]
This check is present in the core_validation layer.
