### ISSUE TITLE
[SDK 1.0.1.1] Validation layers do not verify correctness of VkPipelineColorBlendAttachmentState fields

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#368]
Moved from gitlab 101

The fields do not appear to be checked if blending has been disabled for a given CB attachment. However, recently the spec has been updated to include the following "valid usage" conditions:
srcColorBlendFactor must be a valid VkBlendFactor value dstColorBlendFactor must be a valid VkBlendFactor value colorBlendOp must be a valid VkBlendOp value srcAlphaBlendFactor must be a valid VkBlendFactor value dstAlphaBlendFactor must be a valid VkBlendFactor value alphaBlendOp must be a valid VkBlendOp value colorWriteMask must be a valid combination of VkColorComponentFlagBits values

Tobin Ehlis @tobine  2 months ago
I believe this request can be covered in param_checker. When graphics pipelines are created, this check should verify that any non-null VkPipelineColorBlendStateCreateInfo structs have valid enum and flag bit values in the fields of the embedded VkPipelineColorBlendAttachmentState structs.

**Comment by dustin-lunarg** [comment]
The code generation process for parameter validation produces code that unconditionally checks the VkBlendFactor and VkBlendOp enumeration values, but the old hand written code with the conditional checks was still present.  It has been removed with [d59852](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/commit/d59852fc4166e674833898daa5037270f5c75ea6).
