### ISSUE TITLE
all validation layers need to use app provided memory allocators

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#371]
Moved from gitlab 112

Many object creation calls provide memory allocation callbacks. Validation layers should be using these callbacks when provided.

**Comment by chrisforbes** [comment]
This is pretty nasty with all the STL use...

**Comment by tobine** [comment]
This is not required. See [LoaderAndLayerInterface.md](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/loader/LoaderAndLayerInterface.md#layer-conventions-and-rules)

When a layer requires host memory, it is free to scope the allocations to itself, bypassing the provided allocators entirely.

**Comment by tobine** [comment]
Keeping this open amid ongoing discussion about whether or not this should be a requirement. Current priority is low regardless so leaving un-assigned for time being.

**Comment by jon-lunarg** [comment]
Resolution is that layers can choose to ignore the allocators or not. Recommendation is that layers intended to be run in production environments should use the allocators if they are provided.  Thus validation layers can ignore the allocators if they wish to.
