### ISSUE TITLE
Improve device limits checking to use a "device profile" to check against, instead of the actual device limits.

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#372]
Moved from gitlab 116

For each limit that can be returned by the api we need to validate that the app doesn't exceed those limits. For example, the number of viewports cannot exceed VkPhysicalDeviceLimits::maxViewports. Ideally we will create a set of limits that should not be violated across all android apps and will generate a warning if it exceeds this set but doesn't exceed those returned by the driver being run on (this is covered in another bug).

**Comment by karl-lunarg** [comment]
This effort is really represented by the creation of a "device profile" or "spoofing" layer.  LunarG is currently working on this new feature.

**Comment by Tony-LunarG** [comment]
I believe that with the addition of the device_profile_api layer and an example of its use in ExceedMemoryAllocationCount, that this issue is complete and the layer is available for any future tests that can use it.
