### ISSUE TITLE
The object tracker validation layer crashes when it is not enabled as an instance layer, but is as a device layer.

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#374]
Moved from gitlab 131

initObjectTracker is only called from vkCreateInstance.

Jon Ashburn @jashburn  about a month ago
What if the loader error checked that"global" layers were enabled at both CreateInstance and CreateDevice and logged error if it didn't or simply failed the CreateDevice.

**Comment by jon-lunarg** [comment]
Now that device layers are deprecated it should be impossible for the enable to enable object_tracker only at device time and not at instance time.

Closing this issue since it is no longer an issue.
