### ISSUE TITLE
Validate that image/buffer memory is bound before creating views

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-LoaderAndValidationLayers#376]
Currently on master there doesn't seem to be any validation that memory is bound to a buffer or image before trying to create views - but the spec requires that this in section 11.6.

I haven't checked if the other requirements are validated (memory bound before use in command buffers is maybe already validated, but not sure if memory bind before use in descriptor sets is checked).

**Comment by DominikWitczakAMD** [comment]
+1. I can recall at least one application in the wild where this problem took us several hours to hunt down.
