### ISSUE TITLE
DS: Immutable sampler binding not recognized

### ISSUE THREAD

**Issue by yavn** [KhronosGroup/Vulkan-LoaderAndValidationLayers#384]
I'm using a descriptor set layout with two bindings:

```
t{0} vkCreateDescriptorSetLayout(device = 00000000050F94A0, pCreateInfo = 000000000015EB38, pAllocator = 0000000000000000, pSetLayout = 000000000015E9B8) = VK_SUCCESS
   pCreateInfo (000000000015EB38)
    sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO
    pNext = 0000000000000000
    flags = 0
    bindingCount = 2
    pBindings = 00000000062D9170
     pBindings[0] (00000000062D9170)
      binding = 0
      descriptorType = VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE
      descriptorCount = 1
      stageFlags = 1
      pImmutableSamplers = 0000000000000000
     pBindings[1] (00000000062D9188)
      binding = 1
      descriptorType = VK_DESCRIPTOR_TYPE_SAMPLER
      descriptorCount = 1
      stageFlags = 1
      pImmutableSamplers = 0000000006300520
       pImmutableSamplers[0].handle = 00000000062CADC0
```

The second one uses immutable samplers. The first one is updated as normal:

```
t{0} vkUpdateDescriptorSets(device = 00000000050F94A0, descriptorWriteCount = 1, pDescriptorWrites = 00000000062CB0F0, descriptorCopyCount = 0, pDescriptorCopies = 0000000000000000)
   pDescriptorWrites[0] (00000000062CB0F0)
    sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET
    pNext = 0000000000000000
    dstSet = 00000000062CF800
    dstBinding = 0
    dstArrayElement = 0
    descriptorCount = 1
    descriptorType = VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE
    pImageInfo = 00000000062EF730
    pBufferInfo = 0000000000000000
    pTexelBufferView = 0000000000000000
     pImageInfo[0] (00000000062EF730)
      sampler = 0000000000000000
      imageView = 00000000002AEBA0
      imageLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL
```

When `vkCmdDraw()` is called, the layer complains:

> DS(ERROR): object: 0x12 type: 23 location: 2730 msgCode: 48: DS 0x12 bound and active but it never had binding 1 updated. It is now being used to draw so this will result in undefined behavior.

It seems this usage scenario is not taken into account.

BTW, I can't seem to find `api_dump` layer in the sources. Was it removed? Can I enable it somehow when working with the sources, or do I have to use binary SDK for that?

**Comment by tobine** [comment]
Submitted #385 to fix this.
api_dump is in LunarG [VulkanTools](https://github.com/LunarG/VulkanTools) repo

**Comment by tobine** [comment]
Fix was cherry-picked and pushed to master

**Comment by yavn** [comment]
Hi, there's an error in #385 and consequently I'm still getting a failure.

See [these lines](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/4e41b22a0367c219e178282157f9e7a9c01f6038/layers/core_validation.cpp#L2673-L2680).

The problem is we're iterating with `i` which spans all descriptors in the set, rather than bindings. So indexing `pBindings` with `i` results in an access outside the bounds (`i = endIdx = 2`). See my particular case:

```
VkDescriptorSetLayoutCreateInfo =
{
	sType: VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO (32)
	pNext: NULL
	flags: 0
	bindingCount: 2
	pBindings: 0x00000000066c01c0
}

pBindings[0] =
{
	binding: 0
    descriptorType: VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE (2)
    descriptorCount: 1
    stageFlags: 1
    pImmutableSamplers: NULL
}

pBindings[1] =
{
    binding: 1
    descriptorType: VK_DESCRIPTOR_TYPE_SAMPLER (0)
    descriptorCount: 2
    stageFlags: 1
    pImmutableSamplers: 0x00000000066c0360
}
```

**Comment by tobine** [comment]
Yep, totally my bad. Sorry about that. See #408 for correct fix. Give that a try if you can as I'm unable to test today.
In better news, I'm in the process of overhauling descriptor validation code which will make things clearer and help prevent bugs like this. See #405 for initial changes down this path.

**Comment by tobine** [comment]
Fix was cherry-picked and pushed to master
