### ISSUE TITLE
SC validation layer incorrect report?

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#388]
Description

I was trying to do a multipass for a shadowmap subpass and a render subpass. At the end i was able to make it work but i was getting this warning right when i was creating the render pipeline:

flags = 2

type = 0

obj = 0

location = 1804

err_code = 2

layer_prefix = SC

"FS writes to output location 0 with no matching attachment."

So i decided to check the warning and here is what I found: the first subpass of the renderpass had only a depth reference and the pipeline had a fragment shader that writes to the color attachment 0. After adding a color reference to the first subpass this warning vanished, but I never intended to use this pipeline on the first subpass. Don't know if this is intended or not but anyway, hope it helps.

windows 10

geforce 780gtx

364.72

1.0.8
(Moved from LunarXchange #486)

**Comment by chrisforbes** [comment]
Can we confirm that the app was setting
VkGraphicsPipelineCreateInfo::subpass correctly?

**Comment by fusion32** [comment]
Oh... I totally forgot you need to set the subpass when creating the pipeline! Yeah, the VkGraphicsPipelineCreateInfo::subpass was indeed 0 when it should have been 1. But still it could give another message -> "FS writes to output location 0 with no matching attachment. Did you set the pipeline subpass correctly?" or something like that.

Anyway, I'm sorry i completely forgot about that as this was the first time I was trying something with more than 1 subpass. As it was working and it was just a warning I thought maybe this could be something. Thanks for your patience.
