### ISSUE TITLE
draw_state.cpp::find_entrypoint crashes if name is 0

### ISSUE THREAD

**Issue by mathiasschott** [KhronosGroup/Vulkan-LoaderAndValidationLayers#39]
I don't know whether this is covered by the param_checkers_layer, but ideally find_entrypoint would early out if name is null

**Comment by chrisforbes** [comment]
It should be protected by param_checker, yes. There's a lot of cases like this...

**Comment by mathiasschott** [comment]
I am running without param_checker since it fails building on Windows (something about a lxml python lib missing).

**Comment by cnorthrop** [comment]
There's documentation for setting up the lxml stuff in the spec generation README:

https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/src/spec/README

**Comment by jon-lunarg** [comment]
Mathias:
If the meta layer (VK_LAYER_LUNARG_standard_validation) is available, I suggest using it. It will put param_checker ahead (closer to the app) of draw_state in the layer chain allowing param_checker to catch the error.

I updated the BUILD.md document to include directions on installing python lxml.  I believe this issue can be closed.
