### ISSUE TITLE
Input Attachments requiring a sampler ?

### ISSUE THREAD

**Issue by vlj** [KhronosGroup/Vulkan-LoaderAndValidationLayers#394]
I'm trying to use input attachments to read data from a small gbuffer.
My renderpass has 2 subpasses, the first one fills 2 color attachments with normal and diffuse data and the second one reads the result using subpassLoad().

Both pipeline layout have a (non immutable) sampler declared. It's required for the first subpass (the pipeline samples from a texture using vertex texcoord) however it's unused in the second subpass.
However if I remove the sampler from the pipeline layout declaration the device is lost using a GeForce card with 364.96 drivers (and vulkan sdk 1.0.8). Same if I leave the sampler in the declaration but don't write a descriptor set.

Is it a bug or does the spec mandates a sampler for subpassLoad ? As far as I know non tiled architecture uses an image load operation to support subpassLoad call and maybe drivers need the app to allocate a sampler for this usage.
The validation layer don't emit anything related to a missing sampler.

**Comment by DominikWitczakAMD** [comment]
vlj: Sounds like a driver bug to me. Our driver definitely does not require a sampler for subpass input uniform support.

**Comment by vlj** [comment]
It works correctly on my radeon card indeed.
