### ISSUE TITLE
Validation: vkCreateFramebuffer should check attachments are within spec

### ISSUE THREAD

**Issue by pdaniell-nv** [KhronosGroup/Vulkan-LoaderAndValidationLayers#397]
The Vulkan spec for vkCreateFramebuffer says, amongst other things:
* Any given element of pAttachments must have dimensions at least as large as the corresponding framebuffer dimension

Looking at the code in https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/parameter_validation.cpp#L2807 and parameter_validation_VkFramebufferCreateInfo() there doesn't appear to be a check for this or most other validation requirements listed here:
https://www.khronos.org/members/login/sandbox/vulkan/wsi/xhtml/vkspec.html#vkCreateFramebuffer

**Comment by mathiasschott** [comment]
FWIW we had a couple more applications since the issue was filed that got this wrong, which could have been prevented by implementing this.

Seems like a common app mistake so would it be feasible to bump the priority?

**Comment by mark-lunarg** [comment]
Yeah, we'll move it up to an A on our list.  Thanks.

**Comment by dustin-lunarg** [comment]
This issue was resolved by @tobine with commit aac6fea2aeb81a0d354d80a9226bdc5de2aef5e2
