### ISSUE TITLE
MEM: Stencil attachment memory not marked as valid in render pass

### ISSUE THREAD

**Issue by yavn** [KhronosGroup/Vulkan-LoaderAndValidationLayers#401]
I'm using a render pass with a single stencil attachment (no depth, color, etc.):

```
VkAttachmentDescription
{
    flags:          0
    format:         VK_FORMAT_S8_UINT (127)
    samples:        VK_SAMPLE_COUNT_1_BIT (1)
    loadOp:         VK_ATTACHMENT_LOAD_OP_DONT_CARE (2)
    storeOp:        VK_ATTACHMENT_STORE_OP_DONT_CARE (1)
    stencilLoadOp:  VK_ATTACHMENT_LOAD_OP_CLEAR (1)
    stencilStoreOp: VK_ATTACHMENT_STORE_OP_STORE (0)
    initialLayout:  VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL (3)
    finalLayout:    VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL (3)
}
```

I'm also passing in a `VkClearValue` when starting a render pass, so it's expected that contents of attachment memory are well-defined at the begining (CLEAR) as well as at the end (STORE) of the render pass.

However, layer reports this error:

> MEM(ERROR): object: 0x4 type: 8 location: 421 msgCode: 16: vkCmdCopyImageToBuffer(): Cannot read invalid memory 4, please fill the memory before using.

I think the root cause of this is in `vkCreateRenderPass()` in `core_validation.cpp`, where attachment description is copied. Only `loadOp` and `storeOp` fields are handled but in this case layer should use `stencilLoadOp` and `stencilStoreOp`.

In this case, attachment gets assigned DONT_CARE which later results in marking the memory as not valid.

**Comment by mark-lunarg** [comment]
Hi Maciej, I'm working on a fix but it'd be great if you could share an app that reproduces the failure OR can either add a case to the layer_validation_tests.cpp or modify one of the vulkansamples to make it show the behavior.  Debugging will go a lot quicker.   Thanks!

**Comment by mark-lunarg** [comment]
Bump.

**Comment by mark-lunarg** [comment]
Pushed to Master:

commit 1a65650f856376768d7b03ea2d080aaff87cacfd
Author: Mark Lobodzinski <mark@lunarg.com>
Date:   Fri Jun 10 15:28:17 2016 -0600

    layers: GH401, Break out stencil load/storeOp check

    Stencil attachment load/storeOp settings were being ignored. Added
    format appropriate checks for these flags.

    Change-Id: I6a917fc8a28cbb0d0441152e8d6630defb1b81e3

**Comment by yavn** [comment]
Hi, looks good, thanks!
