### ISSUE TITLE
Calls to vkGetImageSubresourceLayout don't verify the image is linear tiled

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-LoaderAndValidationLayers#402]
As it says, the spec requires that images passed to `vkGetImageSubresourceLayout` must be in linear tiling, but there's no validation error/warning when passing an image with optimal tiling.

**Comment by mikew-lunarg** [comment]
This check corresponds to Valid Usage VALIDATION_ERROR_00732

**Comment by mikew-lunarg** [comment]
See PR #1494

**Comment by mikew-lunarg** [comment]
#1494 pushed to master
