### ISSUE TITLE
 [CTS] Object tracker maps need to be per device

### ISSUE THREAD

**Issue by Tony-LunarG** [KhronosGroup/Vulkan-LoaderAndValidationLayers#403]
Running CTS dEQP-VK.api.object_management.multithreaded_per_thread_device.device_memory_small (and many other multithread tests), Object tracker is confusing memory allocations and frees on one device with those on another due to VkDeviceMemoryMap being layer global rather than per device. This is probably true for the other global maps as well.  Although this has been the case for some time, we think that changing unique_objects' handle allocation scheme has exacerbated the problem.

**Comment by mark-lunarg** [comment]
This has been addressed through a change to the unique_objects layer.  In the near future, object_tracker will undergo changes to move data into per-device and per-instance incarnations to be consistent with other layers.

**Comment by karl-lunarg** [comment]
This has been implemented.
