### ISSUE TITLE
Error should be reported if the app attempts to sample an image without VK_IMAGE_USAGE_SAMPLED_BIT bit specified at creation time

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#407]
That's an issue I'm seeing frequently in ISV apps. Still, it doesn't seem to excite the validation layers at all.

Recommend to add support for this case asap.

**Comment by jeremy-lunarg** [comment]
Hi Dominik,
Are you still encountering this issue? I took a look at the validation layers and it appears we now have the necessary checks in place to catch this type of error during descriptor set binding.

**Comment by tobine** [comment]
Yes, I believe this was added [here](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/descriptor_sets.cpp#L867) quite a while ago, must have spaced this issue.

**Comment by DominikWitczakAMD** [comment]
No idea, to be honest, but from the commit that @tobine referred us to, it seems like it's indeed safe to close this ticket.
