### ISSUE TITLE
DS: vkQueueSubmit checks Event state too early when vkSetEvent is used

### ISSUE THREAD

**Issue by yavn** [KhronosGroup/Vulkan-LoaderAndValidationLayers#410]
I originally submitted this as part of #378, but this part of the problem wasn't fixed yet, so I'm opening a new issue.

Consider the following situation:

```
// recording a CB
vkCmdWaitEvents(cb, 1u, &event, VK_PIPELINE_STAGE_HOST_BIT, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT, 0u, NULL, 0u, NULL, 0u, NULL);

// some time later
vkQueueSubmit(queue, 1u, &submitInfo, NULL);

vkSetEvent(device, event);
```

Inside a command buffer I'm waiting for an event that is signaled on the host. Note that source flags are specified correctly, i.e. have `VK_PIPELINE_STAGE_HOST_BIT`. Still, I'm getting this error:

> DS(ERROR): object: 0 type: 0 location: 8532 msgCode: 17: Submitting cmdbuffer with call to VkCmdWaitEvents using srcStageMask 0x4000 which must be the bitwise OR of the stageMask parameters used in calls to vkCmdSetEvent and VK_PIPELINE_STAGE_HOST_BIT if used with vkSetEvent.

If I use `vkSetEvent` before `vkQueueSubmit`, all is good and no errors appear. If I use wrong flags, I'm getting an error as expected. So I think internal state that is being updated in `vkSetEvent` is fine, but the checks are done upfront in `vkQueueSubmit` before it happens.

Also, if `vkCmdWaitEvents` is part of a secondary CB executing indirectly through a primary CB, then `srcStageMask` is not checked at all.

**Comment by lentinem** [comment]
Should be fixed. Let me know if it continues to be an issue.

**Comment by yavn** [comment]
Hi, no I don't think this is working yet. I'm observing two problems:

[1] If `vkQueueSubmit` comes before `vkSetEvent` (in API call order), then `stageMask` observed by `validateEventStageMask` in core_validation.cpp is 0.

  If this order is reversed, then a correct mask will be used.

E.g.:

```
vkBeginCommandBuffer()
vkCmdWaitEvents()
vkEndCommandBuffer()

vkQueueSubmit()       // error here

vkSetEvent()
```

But this will work fine:


```
vkBeginCommandBuffer()
vkCmdWaitEvents()
vkEndCommandBuffer()

vkSetEvent()

vkQueueSubmit()       // OK
```

[2] The condition to check flags seems too strict to me. It expects an exact mask, rather than presence of some bits:

```
if (sourceStageMask != stageMask && sourceStageMask != (stageMask | VK_PIPELINE_STAGE_HOST_BIT)) {
```

If we wait for two events with different flags, then this can't work by definition. E.g. imagine `srcStageMask = VK_PIPELINE_STAGE_HOST_BIT | VK_PIPELINE_STAGE_VERTEX_SHADER_BIT` and signal from `vkSetEvent`. I don't think this use is prohibited by the spec, so it shouldn't be an error.

**Comment by lentinem** [comment]
For [1], we have a test case called WaitEventThenSet which does what you are describing. If your case still fails can you please describe what the differences between that case and yours are or provide a repro case? For [2] it expects an exact mask where the mask is the bitwise or of each event that is being waited on which should be correct according the the spec. This means that in your case both flags would be logged in stageMask. Also, the spec says:

"srcStageMask must be the bitwise OR of the stageMask parameter used in previous calls to vkCmdSetEvent with any of the members of pEvents"

which doesn't seem to allow for a only a subset being checked.

**Comment by yavn** [comment]
Hi, I've reconsidered this definition and I think you're right. Given this the problematic test used the stage masks incorrectly.

I've corrected the arguments and I'm no longer getting any errors. The original issue you speak in [1] is fixed. Thanks!
