### ISSUE TITLE
Add tests for descriptor set validation

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-LoaderAndValidationLayers#421]
This is a top-level issue to capture adding validation tests for descriptor set validation cases. The comprehensive list of validation layer checks is contained in [vk_validation_layer_details.md](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/vk_validation_layer_details.md). Checks that don't currently have tests identified are below. Tests should be added where missing and the document should be updated.

INVALID_SET
INVALID_LAYOUT
DESCRIPTOR_STAGEFLAGS_MISMATCH
DESCRIPTOR_UPDATE_OUT_OF_BOUNDS
INCONSISTENT_IMMUTABLE_SAMPLER_UPDATE
BUFFERINFO_DESCRIPTOR_ERROR
MISSING_ATTACHMENT_REFERENCE

Descriptor sets also need a test where descriptors are updated with consecutive bindings both correctly and incorrectly based on [descriptorsets-updates-consecutive](https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#descriptorsets-updates-consecutive) of specification

**Comment by MarkMLunarG** [comment]
Completed via SHA-1: 9d2e7a3

* tests: GH421 vkUpdateDescriptorSets tests

A) Adding the WriteDescriptorSetIntegrityCheck test, which verifies
some requirements of chapter 13.2.3 of the Vulkan Spec
 1) A uniform buffer update must have a valid buffer index.
 2) When using an array of descriptors in a single WriteDescriptor,
      the descriptor types and stageflags must all be the same.
 3) Immutable Sampler state must match across descriptors
The above tests also exercise cases where descriptors are updated with
consecutive bindings both correctly and incorrectly

B) adding a MissingClearAttachment test that points to a wrong
colorAttachment index in a VkClearAttachment structure passed to
vkCmdClearAttachments

C) update vk_validation_layer_details.md to reflect above changes.

Change-Id: I3f4f2233371b68caf23b5a4111d63a94765121c3
