### ISSUE TITLE
Add tests for buffer validation

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-LoaderAndValidationLayers#422]
This is a top-level issue to capture adding validation tests for buffer-related validation cases. The comprehensive list of validation layer checks is contained in [vk_validation_layer_details.md](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/vk_validation_layer_details.md). Checks that don't currently have tests identified are below. Tests should be added where missing and the document should be updated.

INVALID_BUFFER
DOUBLE_DESTROY
INVALID_BUFFER_MEMORY_OFFSET
INVALID_TEXEL_BUFFER_OFFSET
INVALID_STORAGE_BUFFER_OFFSET
INVALID_UNIFORM_BUFFER_OFFSET
INVALID_MEM_OBJ

**Comment by MarkMLunarG** [comment]
PR #734 was accepted to close this issue.

SHA-1: c996428a1156dad8461ea86d905708b732897640

* test: GH422 - Buffer Validation Tests

Add classes to support vertex buffer creation and binding
to the pipe and command buffer. Create VertexBufferInvalid
Test to verify:
1) INVALID_BUFFER
2) DOUBLE_DELETE
3) INVALID_BUFFER_MEMORY_OFFSET
4) INVALID_TEXEL_BUFFER_OFFSET
5) INVALID_STORAGE_BUFFER_OFFSET
6) INVALID_UNIFORM_BUFFER_OFFSET
7) INVALID_MEM_OBJ
