### ISSUE TITLE
Add tests for device_limits validation layer

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-LoaderAndValidationLayers#424]
This is a top-level issue to capture adding validation tests for device_limits validation cases. The comprehensive list of validation layer checks is contained in [vk_validation_layer_details.md](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/vk_validation_layer_details.md). Checks that don't currently have tests identified are below. Tests should be added where missing and the document should be updated.

INVALID_QUEUE_INDEX
INVALID_INSTANCE
INVALID_PHYSICAL_DEVICE
INVALID_INHERITED_QUERY
INVALID_ATTACHMENT_COUNT
MUST_QUERY_COUNT
COUNT_MISMATCH
INVALID_QUEUE_CREATE_REQUEST
INVALID_CALL_SEQUENCE
INVALID_FEATURE_REQUESTED
INVALID_STORAGE_BUFFER_OFFSET
INVALID_UNIFORM_BUFFER_OFFSET

Long-term a single test group could be created that queries the underlying device VkPhysicalDeviceLimits struct and then proceeds to perform operations outside of those limits and verifies that all such operations are caught as errors.

**Comment by MarkMLunarG** [comment]
Looking at the code, there is no means to trigger the INVALID_INSTANCE test case. In core_validation's EnumeratePhysicalDevices function the only way to trigger the error is for the vulkan instance to be invalid, but the only way to get to the EnumeratePhysicalDevices function is to have a valid instance. Therefore, INVALID_INSTANCE in EnumeratePhysicalDevices is dead code.

**Comment by MarkMLunarG** [comment]
Testing INVALID_PHYSICAL_DEVICE is not possible within the existing VkLayerTest and derivatives gtest infrastructure and it's hard to justify creating a new infrastructure for a single test. This should probably be handled by a simple stand alone test, which is beyond the scope of GH424.

**Comment by MarkMLunarG** [comment]
There is no instance of INVALID_INHERITED_QUERY, but there is an INVALID_QUERY that is marked as TODO, is that what meant here?

**Comment by MarkMLunarG** [comment]
INVALID_ATTACHMENT_COUNT appears to no longer apply

**Comment by MarkMLunarG** [comment]
MISSING_QUERY_COUNT should be on this list. I've added it to the GH issue.

**Comment by MarkMLunarG** [comment]
INVALID_STORAGE_BUFFER_OFFSET and INVALID_UNIFORM_BUFFER_OFFSET have been expertly covered in #422 .
