### ISSUE TITLE
Add tests for image validation layer

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-LoaderAndValidationLayers#425]
This is a top-level issue to capture adding validation tests for image layer validation cases. The comprehensive list of validation layer checks is contained in [vk_validation_layer_details.md](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/vk_validation_layer_details.md). Checks that don't currently have tests identified are below. Tests should be added where missing and the document should be updated.

FORMAT_UNSUPPORTED
VIEW_CREATE_ERROR
MISMATCHED_IMAGE_ASPECT
INVALID_FORMAT
INVALID_FILTER
INVALID_IMAGE_RESOURCE
INVALID_FORMAT_LIMITS_VIOLATION
INVALID_LAYOUT

For format support, test(s) could be written that query underlying hardware for supported formats, and then proceeds to use all unsupported formats in simple image calls to verify that FORMAT_UNSUPPORTED error is correctly triggered in each case.

**Comment by Tony-LunarG** [comment]
Addressed with PR 492
