### ISSUE TITLE
Add tests for render pass validation

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-LoaderAndValidationLayers#427]
This is a top-level issue to capture adding validation tests for render pass validation cases. The comprehensive list of validation layer checks is contained in [vk_validation_layer_details.md](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/vk_validation_layer_details.md). Checks that don't currently have tests identified are below. Tests should be added where missing and the document should be updated.

INVALID_RENDER_AREA
RENDERPASS_INCOMPATIBLE
FRAMEBUFFER_INCOMPATIBLE
INDEPENDENT_BLEND
RENDERPASS_INVALID_ATTACHMENT
RENDERPASS_INVALID_DS_ATTACHMENT

**Comment by Tony-LunarG** [comment]
Completed with pull request #839
