### ISSUE TITLE
Add tests for various synchronization validation cases

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-LoaderAndValidationLayers#428]
This is a top-level issue to capture adding validation tests for synchronization validation cases. The comprehensive list of validation layer checks is contained in [vk_validation_layer_details.md](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/vk_validation_layer_details.md). Checks that don't currently have tests identified are below. Tests should be added where missing and the document should be updated.

INVALID_CB_SIMULTANEOUS_USE
OBJECT_INUSE
INVALID_FENCE
INVALID_SEMAPHORE
INVALID_EVENT
QUEUE_FORWARD_PROGRESS
INVALID_FENCE_STATE

**Comment by MarkMLunarG** [comment]
INVALID_SEMAPHORE appears to no longer be applicable. It is probably covered in OBJECT_INUSE

**Comment by MarkMLunarG** [comment]
Testing OBJECT_INUSE for vkFreeDescriptorSets in core_validation does not appear to be possible after PR #791 so this test case was skipped. Adding the test to the existing code, when support is available, will be easy
