### ISSUE TITLE
Add tests for shader_checker validation cases

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-LoaderAndValidationLayers#429]
This is a top-level issue to capture adding validation tests for shader_checker validation cases. The comprehensive list of validation layer checks is contained in [vk_validation_layer_details.md](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/vk_validation_layer_details.md). Checks that don't currently have tests identified are below. Tests should be added where missing and the document should be updated.

INCONSISTENT_SPIRV
NON_SPIRV_SHADER
UNKNOWN_STAGE
BAD_SPECIALIZATION
MISSING_ENTRYPOINT
PUSH_CONSTANT_NOT_ACCESSIBLE_FROM_STAGE
DESCRIPTOR_NOT_ACCESSIBLE_FROM_STAGE
DESCRIPTOR_TYPE_MISMATCH
FEATURE_NOT_ENABLED
BAD_CAPABILITY

**Comment by MarkMLunarG** [comment]
SHADER_CHECKER_NON_SPIRV_SHADER, SHADER_CHECKER_UNKNOWN_STAGE are not implemented in core_validation

**Comment by tobine** [comment]
The issue has out-lived those checks.
Like Confucious says "if you wait long enough you won't have to write any tests."
Or something like that...

**Comment by mark-lunarg** [comment]
+1 for Confucious.

**Comment by MarkMLunarG** [comment]
MISSING_ENTRYPOINT isn't viable to test because once the condition is created, core_validation crashes in mark_accessible_ids because the entrypoint argument is invalid and the     worklist.insert(entrypoint.word(2)); statement leads to much grief in our uncertain world.

**Comment by MarkMLunarG** [comment]
INCONSISTENT_SPIRV is already handled in InvalidSPIRVCodeSize

**Comment by mark-lunarg** [comment]
Covered in PR #941.
