### ISSUE TITLE
Add tests for image/memory usage bit validation

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-LoaderAndValidationLayers#434]
Currently a single test is identified for INVALID_USAGE_FLAG case in [vk_validation_layer_details.md](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/vk_validation_layer_details.md).

This case should be examined according to the existing validation code and the Vulkan specification and additional test(s) should be added as appropriate.

**Comment by Tony-LunarG** [comment]
Addressed with PR 468
