### ISSUE TITLE
Add tests for object_tracker layer

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-LoaderAndValidationLayers#435]
The currest list of validation errors as well as any associated tests for the object_tracker validation layer are documented in [vk_validation_layer_details.md](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/vk_validation_layer_details.md).

This documentation should be examined according to the existing validation code and the Vulkan specification and additional test(s) should be added as appropriate.

**Comment by mark-lunarg** [comment]
Addressed by pull request #488, pushed to Master.
