### ISSUE TITLE
Add tests for swapchain validation layer

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-LoaderAndValidationLayers#437]
The currest list of validation errors as well as any associated tests for the swapchain validation layer are documented in [vk_validation_layer_details.md](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/vk_validation_layer_details.md).

This documentation should be examined according to the existing validation code and the Vulkan specification and additional test(s) should be added as appropriate.

**Comment by ianelliottus** [comment]
Just noticed this tracking issue.  I dealt with this a while back, but didn't close this issue.  There are some time-consuming tests that should be added sometime (I left TODO statements for what was needed).

Jon Ashburn also added some incomplete support for the VK_KHR_display extension.  It would be good for somebody to finish that support sometime.
