### ISSUE TITLE
Add tests for threading validation layer

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-LoaderAndValidationLayers#438]
The current list of validation errors as well as any associated tests for the threading validation layer are documented in [vk_validation_layer_details.md](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/vk_validation_layer_details.md).

This documentation should be examined according to the existing validation code and the Vulkan specification and additional test(s) should be added as appropriate.

**Comment by mark-lunarg** [comment]
This document has been superseded and no longer exists.  Closing for now.
