### ISSUE TITLE
Image layer: Check return value of vkGetPhysicalDeviceImageFormatProperties in image.cpp

### ISSUE THREAD

**Issue by ewerness** [KhronosGroup/Vulkan-LoaderAndValidationLayers#441]
https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/43b53e83705f02245da6ae61e31273866a35b833/layers/image.cpp#L279

Should check for VK_ERROR_FORMAT_NOT_SUPPORTED and report explicitly.

**Comment by mark-lunarg** [comment]
This particular issue is validated by the parameter_validation layer, which should typically be in the layer chain before the image layer.
