### ISSUE TITLE
Please update the "clang-format" instructions in "CONTRIBUTING.md"

### ISSUE THREAD

**Issue by ianelliottus** [KhronosGroup/Vulkan-LoaderAndValidationLayers#444]
I just followed the instructions on lines 38 through 42 in the "CONTRIBUTING.md" file, and ran into problems:

- Line 39: by running "git add .", all of the non-tracked (e.g. auto-generated) files were staged for commit.

- Line 40: by running the "clang-format" command directly, parts of the files that I didn't touch were also changed, including reordering of the #include files.

I suggest a slightly-different set of commands:

>        # Make changes to the source.
>        $ git add -u .
>        $ git clang-format --style=file
>        # Check to see if clang-format made any changes and if they are OK.
>        $ git add -u .
>        $ git commit

This worked well, and "git clang-format" only touched the lines that I changed.

**Comment by karl-lunarg** [comment]
Fixed as described.  Thanks!
