### ISSUE TITLE
loader: rework locking for thread safety

### ISSUE THREAD

**Issue by jon-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#446]
The original locking was done a long time ago when the threading rules were not yet finalized in the Vulkan spec.  Right now the locking is overly consevative including holding locks while calling down the instance chain.  This all needs to be reworked.  Lock only for protecting global data access and any Vulkan object accesses after object creation which are not externally synchronized.

**Comment by MarkY-LunarG** [comment]
After some discussion offline, we've determine there's no real issue here at this time.  Applications seem to be using multithreading properly and the loader has yet to rise as an issue in any of the performance areas.  We'll close this for now, and re-open if an issue appears.
