### ISSUE TITLE
False DrawState positive - CB 0x24bda40 was submitted with secondary buffer 0x24ca270 but that buffer has subsequently been bound to primary cmd buffer 0x24c4400

### ISSUE THREAD

**Issue by mark-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#449]
Running CTS dEQP-VK.api.command_buffers.secondary_execute_twice. The test creates and records a secondary command buffer, then executes it in recording primary command buffer 1, and also executes it in recording command buffer 2. Then, when it QueueSubmits command buffer 1, it gets the validation error in the title

**Comment by tobine** [comment]
Were all the cmd buffers recorded w/ VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT? Note that I have an [open issue](https://github.com/KhronosGroup/Vulkan-Docs/issues/182) in Vulkan-Docs on this behavior. If all of the CBs in question are recorded w/ VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT then I agree that it's probably a false positive but spec can be clarified on this point. I'll file a PR for my proposed spec change and if there are no issues with it I'll update this behavior.

**Comment by tobine** [comment]
Just submitted [MR1305](https://gitlab.khronos.org/vulkan/vulkan/merge_requests/1305) for Vulkan spec update.

**Comment by Tony-LunarG** [comment]
The secondary command buffer was recorded with USAGE_SIMULTANEOUS_USE, but neither of the primary command buffers specified it.

**Comment by tobine** [comment]
Spec change was approved for inclusion today so just submitted #511 to address this issue.

**Comment by tobine** [comment]
Fix was cherry-picked and pushed to master
