### ISSUE TITLE
7 layer validation tests failing on latest master

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-LoaderAndValidationLayers#452]
Hi Dustin,
I think your latest commits on master are causing the following layer validation tests to fail:

[  FAILED  ] VkLayerTest.CreatePipelineAttribMatrixType
[  FAILED  ] VkLayerTest.CreatePipelineAttribArrayType
[  FAILED  ] VkLayerTest.CreatePipelineSimplePositive
[  FAILED  ] VkLayerTest.CreatePipelineRelaxedTypeMatch
[  FAILED  ] VkLayerTest.CreatePipelineTessPerVertex
[  FAILED  ] VkLayerTest.CreatePipelineGeometryInputBlockPositive
[  FAILED  ] VkLayerTest.CreatePipeline64BitAttributesPositive

The tests are expected to succeed but not have errors. The errors may be valid, but please fix up the tests to correct the errors. We need to keep these passing for all commits.

**Comment by dustin-lunarg** [comment]
I have submitted PR #454 to fix this.
