### ISSUE TITLE
Remapper bug causes ShaderChecker layer crash (assert) using remapped spirv shaders

### ISSUE THREAD

**Issue by mark-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#455]
Running Dota2 using remapped spirv shaders triggers asserts in shader_checker validation.  

Running release build of layers or disabling shader remapping works fine.  Assert is in collect_interface_by_location:

![image](https://cloud.githubusercontent.com/assets/7252958/14924728/2ff1fbaa-0e01-11e6-87d6-ea9b7d48a295.png)

here:
![image](https://cloud.githubusercontent.com/assets/7252958/14924771/4f998a68-0e01-11e6-8944-42c8a34a65c8.png)

entrypoint.word(5) = 0x1240, insn = 0x0004003b
entrypoint.word(6) = 0x14BC, insn = 0x0004003b
entrypoint.word(7) = 0x0F00, insn = not found

**Comment by chrisforbes** [comment]
Looks like this was bad behavior in the remapper. A definition must exist for everything named in `OpEntryPoint`. Reopen if you think there's some residual bad behavior in validation after that is fixed.

**Comment by mark-lunarg** [comment]
Reopening just to track the issue and bad remapper interaction from our side.

**Comment by mark-lunarg** [comment]
Chris added some additional asserts to prevent an infinite loop on debug builds.  The spirv-validator should have spit out a message beforehand anyhow.
