### ISSUE TITLE
Validation for pCreateInfo structures does not report actual index (attachments, vertex input state)

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-LoaderAndValidationLayers#462]
Attachment description flags are now validated, but the validation message doesn't contain the attachment index but instead always says "attachment[i]" :

`value of pCreateInfo->pAttachments[i].flags contains flag bits that are not recognized members of VkAttachmentDescriptionFlagBits`

The [i] seems to be hard coded right now, having the real index of the attachment in the message would be better.

**Comment by SaschaWillems** [comment]
It seems that this is also the case for several other validations like the vertex input state :

`vkCreateGraphicsPipelines: parameter pCreateInfos[i].pVertexInputState->flags must be 0`

**Comment by dustin-lunarg** [comment]
This is the case for all arrays of structures.  Fixing it is on my list of things to do, but it has been a lower priority.  I'll try to get to it soon.

**Comment by mark-lunarg** [comment]
@SaschaWillems, we believe these issues have been addressed.  I'm going to close this for now, if you find any more that we have missed please reopen this issue.
