### ISSUE TITLE
No debug call-back reported if vkCmdDispatch() is recorded without a pipeline being bound to the compute bind point

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#465]
I've just encountered an application which tried to dispatch compute invocations without having bound a compute pipeline first. This should have resulted in a debug call-back, but apparently existing validation layers do not capture such cases.

We need this fixed asap. It's very easy to fall for this trap.

**Comment by tobine** [comment]
Submitted #467 to add this check

**Comment by tobine** [comment]
Fix was cherry-picked and pushed to master
