### ISSUE TITLE
VkLayerTest.EnableWsiBeforeUse triggering SEH exception on Windows

### ISSUE THREAD

**Issue by dustin-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#470]
The EnableWsiBeforeUse test is crashing on Windows due to a combination of an incomplete test and a bug in the swapchain layer.  

* Commit 832f5c4 contains some WSI surface creation code that is #ifdef'd off for some platforms, including Windows, until it can be tested.  The problem is that the other WSI calls are being made with a VK_NULL_HANDLE surface handle, which triggers a crash in the swapchain layer.  The entire test needs to be disabled for the untested platforms.
* See #471 for a description of the swapchain layer bug that produces the crash.

**Comment by ianelliottus** [comment]
Sorry about that!

I have a Windows laptop now, and brought it into work, but I haven't been able to figure out how to run the tests on Windows.  There's a run_all_tests.ps1 file that doesn't run from my Cygwin-bash shell.  I did Start->Run "powershell", and tried to run the script, but I get an error about scripts being turned off.  How can I run the tests on Windows?

**Comment by dustin-lunarg** [comment]
For the PowerShell scripts, you probably need to use Set-ExecutionPolicy to allow scripts to be run: https://technet.microsoft.com/en-us/library/ee176961.aspx

You can also just run vk_layer_validation_tests.exe directly.  I either run the _run_all_tests.ps1 from the build/test directory, or run vk_layer_validation_tests.exe from the VIsualStudio debugger.

**Comment by ianelliottus** [comment]
Hmm.  I don't see any *.exe files under my dbuilt/tests directory.

**Comment by ianelliottus** [comment]
@dustin-lunarg, please try the pull request I just pushed (https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/476) and tell me if that solves the problem for now.

**Comment by dustin-lunarg** [comment]
PR #470 shifts the issue to vkDestroySwapChainKHR.  Similar problem: 
1. vkCreateswapChainKHR skips swap chain creation due to validation error
2. vkGetSwapchainImagesKHR is called with VK_NULL_HANDLE, which adds an invalid entry to the map.
3.  vkDestroySwapChainKHR tries to dereference a pointer obtained from the invalid map entry.

**Comment by ianelliottus** [comment]
Hmm.  It looks like this test will NOT be able to run on Windows in Debug mode.  The whole point of this test is to call functions without the extension being enabled (to verify that an error is thrown).  Therefore, the create functions will never succeed.

Is the problem on Windows-Debug what you describe in bug #471?

**Comment by dustin-lunarg** [comment]
Yes, this is the result of the issue described in #471.  If that bug is fixed, these tests should work with Windows Debug builds.

**Comment by ianelliottus** [comment]
> Yes, this is the result of the issue described in #471. If that bug is fixed, these tests should work with Windows Debug builds.

Okay.  I'm guessing that other layers have (or had) this problem too, since this offending code has been around for several months:-).


> For the PowerShell scripts, you probably need to use Set-ExecutionPolicy to allow scripts to be run: https://technet.microsoft.com/en-us/library/ee176961.aspx

I see, this is a command.  I ran it, and my system is wide open to security attacks.  I can run all tests, and lots fail.  I'd like to debug ...

> You can also just run vk_layer_validation_tests.exe directly. I either run the _run_all_tests.ps1 from the build/test directory, or run vk_layer_validation_tests.exe from the VIsualStudio debugger.

What project do you use?  What command-line options do you give (e.g. to point to the validation layers)?  Thanks!

**Comment by dustin-lunarg** [comment]
>I see, this is a command. I ran it, and my system is wide open to security attacks. I can run all tests, and lots fail. I'd like to debug ...

If you have set the execution policy to Unrestricted, you can use RemoteSigned instead.

>What project do you use? What command-line options do you give (e.g. to point to the validation layers)? Thanks!

With VisualStudio, use the vk_layer_validation_tests project to debug.  To point to the validation layers, and the gtest DLLs, I set the Configuration Properties|Debugging|Environment property to  >VK_LAYER_PATH=..\layers\Release
>PATH=%PATH%;.\gtest-1.7.0\Release
in the vk_layer_validation_tests Property Pages

**Comment by ianelliottus** [comment]
Okay, I'm into the debugger.  Thanks to @dustin-lunarg, @stroyan and @cnorthrop for your help!

**Comment by ianelliottus** [comment]
I just created pull request #482 (see: https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/482).  It addresses this and other issues.

**Comment by jon-lunarg** [comment]
This issue has been resolved AFAIK, closing.
