### ISSUE TITLE
The draw state validation layer incorrectly reports that an image layout is VK_IMAGE_LAYOUT_TRANSFER_SRC_LAYOUT.

### ISSUE THREAD

**Issue by mre4ce** [KhronosGroup/Vulkan-LoaderAndValidationLayers#48]
Using latest code, I get the following error every once in a while when mapping an image that has just been created with VK_IMAGE_LAYOUT_PREINITIALIZED.

    "Cannot map an image with layout VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL. Only GENERAL or PREINITIALIZED are supported."

**Comment by lentinem** [comment]
This should be assigned to me but I can't do so - can someone else do that?

**Comment by lentinem** [comment]
A repro with this one would also be helpful as somehow the layers things you have submitted a barrier transitioning to TRANSFER_SRC_OPTIMAL before calling map.

**Comment by karl-lunarg** [comment]
I cannot recreate a failure scenario for this either.  And I don't see any obvious flaw in the layer code.  Johannes, could you please provide more info, or better, a repro case?

**Comment by mre4ce** [comment]
I don't have a good repro case. It happens very rarely. This makes me believe it is either a threading or uninitialized memory issue. While I'm rendering from multiple threads, I'm not actually allocating resources from multiple threads simultaneously (too many issues and not critical for this sample). Hopefully this isn't user error, but this is the code that triggered the validation error:

		VkImageCreateInfo imageCreateInfo;
		imageCreateInfo.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
		imageCreateInfo.pNext = NULL;
		imageCreateInfo.flags = 0;
		imageCreateInfo.imageType = ( depth > 1 ) ? VK_IMAGE_TYPE_3D : VK_IMAGE_TYPE_2D;
		imageCreateInfo.format = format;
		imageCreateInfo.extent.width = width;
		imageCreateInfo.extent.height = height;
		imageCreateInfo.extent.depth = depth;
		imageCreateInfo.mipLevels = 1;
		imageCreateInfo.arrayLayers = arraySize;
		imageCreateInfo.samples = VK_SAMPLE_COUNT_1_BIT;
		imageCreateInfo.tiling = VK_IMAGE_TILING_LINEAR;
		imageCreateInfo.usage = VK_IMAGE_USAGE_TRANSFER_SRC_BIT;
		imageCreateInfo.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
		imageCreateInfo.queueFamilyIndexCount = 0;
		imageCreateInfo.pQueueFamilyIndices = NULL;
		imageCreateInfo.initialLayout = VK_IMAGE_LAYOUT_PREINITIALIZED;

		VK( context->device->vkCreateImage( context->device->device, &imageCreateInfo, VK_ALLOCATOR, &linearImage ) );

		VkMemoryRequirements memoryRequirements;
		VC( context->device->vkGetImageMemoryRequirements( context->device->device, linearImage, &memoryRequirements ) );

		VkMemoryAllocateInfo memoryAllocateInfo;
		memoryAllocateInfo.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
		memoryAllocateInfo.pNext = NULL;
		memoryAllocateInfo.allocationSize = memoryRequirements.size;
		memoryAllocateInfo.memoryTypeIndex = GpuDevice_GetMemoryTypeIndex( context->device, memoryRequirements.memoryTypeBits, VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT );

		VK( context->device->vkAllocateMemory( context->device->device, &memoryAllocateInfo, VK_ALLOCATOR, &linearMemory ) );
		VK( context->device->vkBindImageMemory( context->device->device, linearImage, linearMemory, 0 ) );

		void * mapped;
		VK( context->device->vkMapMemory( context->device->device, linearMemory, 0, memoryRequirements.size, 0, &mapped ) );

**Comment by dustin-lunarg** [comment]
This issue should have been resolved by pull request [#131](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/131).
