### ISSUE TITLE
Check for unsupported image format being used as color attachment

### ISSUE THREAD

**Issue by Tulon** [KhronosGroup/Vulkan-LoaderAndValidationLayers#485]
I spent several days debugging an issue with color / input attachment not working in my code. It turned out I was using VK_FORMAT_R32G32B32_SFLOAT, which can't be used as a color attachment (on nVidia 760M) according to vkGetPhysicalDeviceFormatProperties(). That was unexpected, as this format does work for render-to-texture in OpenGL. Switching to VK_FORMAT_R32G32B32A32_SFLOAT fixed the issue.

It would be nice if such an situation gets caught by a validation layer. At the moment, it's not (LunarG Vulkan SDK 1.0.11.0).

**Comment by mark-lunarg** [comment]
Addressed by PR #551.  Pushed to master.
