### ISSUE TITLE
"No active render pass found at draw-time in Pipeline" reported wrong for secondary buffers

### ISSUE THREAD

**Issue by McNopper** [KhronosGroup/Vulkan-LoaderAndValidationLayers#498]
Using secondary command buffers, the vaildation report is wrong. Can be reproduced with my example 7:

https://github.com/McNopper/Vulkan/tree/master/VKTS_Example07

Seems that VkCommandBufferInheritanceInfo is not taken into account.

**Comment by tobine** [comment]
Fix was cherry-picked and pushed to master
