### ISSUE TITLE
Become the most popular graphics API

### ISSUE THREAD

**Issue by TheJJ** [KhronosGroup/Vulkan-LoaderAndValidationLayers#5]
Vulkan has the potential to become the most popular graphics API, but:

- [ ] I hope, in order to minimize the complexity, boilerplate libraries will emerge and provide abstraction layers fitting for different applications. Some of those should probably be officially supported/listed.

  Only then, those small hobby projects will have a chance to use Vulkan and developers get familiar with it. Just targetting AAA engines will lead to having very few developers that use and understand the API which makes it popular.

- [ ] In order to prevent totally outdated guides and scattering the community, a **central wiki** should be in place from the beginning. There, howtos, examples, tutorials and tipps & tricks should be placed and maintained.

- [ ] After programs have been written, they will most likely not be updated for new Vulkan versions. Although that was never the problem with e.g. OpenGL, I can only hope Vulkan won't do things like the Python2->3 breakage, qt3->4->5, gtk2->3, gnome2->3, kde4->5, etc.
Instead, following the Linux kernel way will guarantee ABI stability for a minimalistic interface that provides space for internal improvements and reliably sane behavior.

If the interface remains stable and the community is actively integrated and supported into further evolvement of Vulkan and not only industry giants, the success is probably guaranteed.

Thanks for making all this possible :smile:

(and please, use a better repo name...)

**Comment by jon-lunarg** [comment]
The JJ:
This issue list is for issues specific to the code in this repository. Your comments would be more appropriate in Vulkan-Docs  repository:
https://github.com/KhronosGroup/Vulkan-Docs/issues
