### ISSUE TITLE
VkPipelineColorBlendStateCreateInfo must have matching number of VkPipelineColorBlendAttachmentState

### ISSUE THREAD

**Issue by httpdigest** [KhronosGroup/Vulkan-LoaderAndValidationLayers#50]
I was recently debugging an issue with a Vulkan application which works perfectly well on Nvidia but does not draw anything on AMD.
Both of them had the very latest Vulkan Beta Nvidia and Radeon drivers installed.
- Nvidia 356.43 on Windows 7 x64 with a Quadro K2000M
- AMD Radeon 16.15.1009 Beta 5 on Windows 7 x64 with a Radeon HD 8790M

The problem in the end was that VkGraphicsPipelineCreateInfo had a valid pColorBlendState of type VkPipelineColorBlendStateCreateInfo, but that VkPipelineColorBlendStateCreateInfo did not have any VkPipelineColorBlendAttachmentState attachments in its pAttachments.

The rationale behind that was that blending was not used, BUT the bad thing was that this blend state also contains the color write mask, which Nvidia apparently interpreted as 0xF (all of RGBA written) and AMD as 0x0 (none written) when no VkPipelineColorBlendAttachmentState is present.
So Nvidia's driver behaved - let's say - "more lenient."

The validation layers had nothing to say on this.

The spec says the following: 

> VkPipelineColorBlendStateCreateInfo* pColorBlendState;
"pColorBlendState is a pointer to an instance of the VkPipelineColorBlendStateCreateInfo structure,
or NULL if the pipeline has rasterization disabled or if the subpass of the render pass the pipeline is created against does not use any color attachments."

It says that the pColorBlendState is only to be NULL if rasterization is to be disabled or no color attachments should be used, BUT it does not say what happens when pColorBlendState is _not null_ but at the same time there is no contained pAttachments within that VkPipelineColorBlendStateCreateInfo.

It would be nice if the validation layers catches this. This essentially means that on render pass being, it should be checked whether (page 466 of the Vulkan spec PDF):
> attachmentCount is the number of VkPipelineColorBlendAttachmentState elements in
pAttachments. This value must equal the colorAttachmentCount for the subpass in which this pipeline is used.

**Comment by httpdigest** [comment]
I somewhat hastily also posted on the Nvidia Developer Submission Form about the different behaviour of Nvidia's and AMD's drivers, and got a response from Mathias Schott, and we quickly concluded that the issue is with the application incorrectly specifying a mismatching number of VkPipelineColorBlendAttachmentState attachments which do not match the actual number of framebuffer color attachments used in the render subpass, as stated on page 466 of the Vulkan spec PDF.

So, the drivers behave correctly and it is an issue with the application code, which the validation layers should report.

**Comment by mark-lunarg** [comment]
We believe this has been addressed by a change Mark Young made to Master (below).  Please reopen the issue if it still occurs.  Thanks!

commit eca2d52a6bfa3f9d63a86ca9fd30abc0adf775b7
Author: Mark Young <marky@lunarg.com>
Date:   Wed May 4 14:38:51 2016 -0600

    layers: Fix core_validation issues GH103 and GH240

    Perform pipeline sample and attachment count validation at draw
    time instead of vkCmdNextSubpass() time.  Also validate that
    an active renderpass exists.
