### ISSUE TITLE
demo Smoke missing -lrt under GCC 4.9

### ISSUE THREAD

**Issue by Delwin9999** [KhronosGroup/Vulkan-LoaderAndValidationLayers#500]
The demo Smoke fails to link on CentOS 6.8 with GCC 4.9 due to clock_gettime being an undefined reference.

Adding -lrt to line 63 of demos/smoke/CMakeLists.txt fixes this.  My apologies that I cannot make a pull request at this time.

**Comment by Tony-LunarG** [comment]
Fix committed to master - thanks!
