### ISSUE TITLE
How to handle perf warn case for GENERAL layout of renderpass attachments

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-LoaderAndValidationLayers#508]
Validation currently issues a perf warning on renderpass creation if layout for input/color/ds attachments is GENERAL instead of the corresponding READ_*/COLOR_*/DEPTH_STENCIL_* OPTIMAL layout.
Chris points out in #493 that there are certain cases, just as an attachment being used as both input and color, where GENERAL is the only correct layout. Validation doesn't recognize such cases.
So, should we:

1. Just stop issuing the perf warnings
2. Continue issues in the perf warnings but make them smarter to recognize valid GENERAL cases
3. Do nothing. Issue the warnings as they are and trust users to figure out when/if they need to care about the warnings

I'd favor 1 or 3 as 2 seems like a fair amount of extra code for limited return at this point. Wanted to gather some other opinions, though.

**Comment by lentinem** [comment]
It is a warning because of this exact reason. I would vote for 3 which was the original intent. 2 would be better but is difficult to implement. We can leave this open if we want to do that later.

**Comment by tobine** [comment]
Yeah I lean towards 3 as well with possible 2 in the future. Assigning to Chris for his input.

**Comment by chrisforbes** [comment]
Agree for now, but I think everyone who does a full deferred pipeline in a single renderpass will hit this case? Let's deal with it when an app doing that shows up?

**Comment by lentinem** [comment]
It shouldn't. If thy are using a single renderpass it gets broken into multiple subpasses and the layouts are transitioned between them. It's theoretically possible to do everything in a single subpass but I wouldn't expect that to happen in practice.

**Comment by chrisforbes** [comment]
OK, that sounds better. So the only real cases where this happens are when you're doing feedback in the same subpass - shader-based blend, etc.

**Comment by tobine** [comment]
Closing this as we have a current consensus on keeping behavior as-is. If external issues come in complaining about the warning we can address further at that time.
