### ISSUE TITLE
Validation layer reports wrong MEM(ERROR) calling vkCmdCopyImage()

### ISSUE THREAD

**Issue by McNopper** [KhronosGroup/Vulkan-LoaderAndValidationLayers#509]
With a computer shader, content is rendered into an image.
As soon as this is done, the content of the image is gathered and written to disk.

The current validation layer reports an invalid error, as soon as vkCmdCopyImage is called.

Somehow, the written memory is not tracked.

Problem can be reproduced with this example:
https://github.com/McNopper/Vulkan/tree/master/VKTS_Example08

Wrong output:
MEM(ERROR): object: 0x5 type: 8 location: 356 msgCode: 16: vkCmdCopyImage(): Cannot read invalid memory 5, please fill the memory before using.

**Comment by lentinem** [comment]
There is no easy well to tell if the memory is written to via compute. For now I'll mark every output for a compute call as written.

**Comment by lentinem** [comment]
Actually looks like it should already be doing that. I'll try to repro.

**Comment by McNopper** [comment]
With master branch, my example 8 (see link above), reproduces this.

**Comment by lentinem** [comment]
Thanks; I tried to get that up and running but haven't had too much luck so far. I'm using android as I don't have access to a windows machine but have had to made some modifications to the build and install process. I'm currently getting a crash on pipeline creation though which is probably from a bug in the shader. I'll look more tomorrow but was wondering if you might know. Thanks!

**Comment by McNopper** [comment]
Hmm, I am normally testing under Windows, Linux (AMD and NVIDIA) and Android (NVIDIA Shield K1).

On all devices I do get the correct output. On which exact device do you work on?

**Comment by lentinem** [comment]
I'm on a Nexus 6P using android but built off of linux. It originally looked like the set of shaders copied were missing a bunch of them so I created a new build_install.sh which copied the missing ones. I'm currently building example 9 for the other issue. I ran into the example name being wrong in the Android.mk (was listed as example06) and the copy script was missing all the _shadow and _write_shadow shader files. After I copied those over I was able to load and run but it fails on create pipeline. The most likely cause of these errors is typically shader errors so I was guessing that the shaders are not compatible with mobile but if you are running them then maybe something else is going on?

**Comment by McNopper** [comment]
Okay, fixed the naming problem.
Also, please make sure to download the assets and shaders from here:
http://nopper.tv/Vulkan/VKTS_Binaries.zip
They are no longer in the repo, as it did grow to fast.

I will move - sooner or later - the copy scripts to python, so I do not have the double work for Windows and Linux anymore.

**Comment by McNopper** [comment]
Example 1 - 7, using master branch, are now validation layer error free.

Example 8 reports this:
MEM(ERROR): object: 0x5 type: 8 location: 356 msgCode: 16: vkCmdCopyImage(): Cannot read invalid memory 5, please fill the memory before using.

Example 9 reports this:
MEM(ERROR): object: 0xffffffffffffffff type: 8 location: 348 msgCode: 16: vkQueuePresentKHR(): Cannot read invalid swapchain image 14, please fill the memory before using.
MEM(ERROR): object: 0x297 type: 7 location: 4542 msgCode: 14: Fence 0x297 submitted in SIGNALED state.  Fences must be reset before being submitted

**Comment by McNopper** [comment]
Also I do have a Google Nexus Player to test. I will wait for the next image update and test on this device as well.

**Comment by lentinem** [comment]
I think I got this mostly running now but I'm getting no errors reported. Did the errors listed here get addressed or do you still get there?

**Comment by lentinem** [comment]
Ok, I got one of the errors to show up. I'll address that and see if anything else reports.

**Comment by lentinem** [comment]
I had a number of issues running 08 but I'm not seeing this error atm. Can you verify that this still exists?

**Comment by McNopper** [comment]
Yes, it still exists.
You need to build VKTS with -DVKTS_WSI=VKTS_NO_VISUAL, that no windowing is enabled.
But I will dig into it again,if there is a similar problem line in example 9.

**Comment by McNopper** [comment]
Yes, it still occurs and the problem is, that the offscreen image is not set as valid, as the validation layer does skip it setting it valid.

**Comment by McNopper** [comment]
A virtual method is missing. This fixes it:
https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/546

**Comment by tobine** [comment]
Fix was cherry-picked and pushed to master
