### ISSUE TITLE
PV: VkDescriptorSetLayoutBinding stageFlags validation

### ISSUE THREAD

**Issue by yavn** [KhronosGroup/Vulkan-LoaderAndValidationLayers#515]
Parameter validation is too strict about `stageFlags` checking:

> ParameterValidation(ERROR): object: 0 type: 0 location: 613 msgCode: 4: vkCreateDescriptorSetLayout: value of pCreateInfo->pBindings[i].stageFlags must not be 0

It should be allowed to pass 0 flags, which means that no shader stage is allowed to access the descriptor. See here the original discussion regarding this: [bugzilla](https://cvs.khronos.org/bugzilla/show_bug.cgi?id=15022)

I think this message should be changed from ERROR to WARN.

**Comment by dustin-lunarg** [comment]
It looks like this check needs to be conditional on descriptorCount not being 0, which it currently is not:
>If descriptorCount is not 0, stageFlags must be a valid combination of VkShaderStageFlagBits values

The code generator needs to be adjusted to ignore VkFlags values tagged as 'noautovalidity', and then I can add a manual check that includes 'descriptorCount != 0'.

**Comment by yavn** [comment]
Yeah, that wouldn't hurt of course, but I'm not sure if this is sufficient.

Based on discussion so far, I think either of these cases should be treated as dummy descriptor case:

- descriptorCount = 0, or
- stageFlags = 0

I have a test that creates descriptors with descriptorCount > 0 and stageFlags = 0, and simply never uses the descriptors in any shader stage. This is done for implementation convenience I suppose.

I think we can still emit an error if flags are completely off (neither 0 nor combination of enum values), and a performance warning if descriptorCount or stageFlags are 0 (to discourage use of dummy descriptors, as advised in the spec).

**Comment by dustin-lunarg** [comment]
This has been addressed in a larger change that disables code generation for parameters in vk.xml that have the noautovalidity attribute set to true: Pull Request #552 

  A message is now only generated for the stageFlags value if descriptorCount != 0, stageFlags != 0, and stage flags contains an unrecognized VkShaderStageFlagsBits value.  The new validation for stageFlags starts at line [3125 in parameter_validation.cpp](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/552/files#diff-5e9a3bb1ecda42704945cbcb83c3647dR3125).

**Comment by dustin-lunarg** [comment]
The fix for this should be included in SDK 1.0.13

**Comment by yavn** [comment]
Fixed, thanks!
