### ISSUE TITLE
THREADING ERROR : object of type VkFence is simultaneously used in thread X and thread Y

### ISSUE THREAD

**Issue by TiemoJung** [KhronosGroup/Vulkan-LoaderAndValidationLayers#519]
Hi,

the threading layer reports a usage error of a fence.

The scenario is:
Thread Y waits for the fence in question
Thread X calls vkQueueSubmit with the fence as parameter.

It should be valid to wait for a fence and then later signal it in a other thread?!

**Comment by stroyan** [comment]
The specification indicates that vkQueueSubmit cannot use a fence that is already being used by vkWaitForFences.   From the section on threading behavior-
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#fundamentals-threadingbehavior
"If two commands operate on the same object and **at least one of the commands declares the object to be externally synchronized**, then the caller must guarantee not only that the commands do not execute simultaneously, but also that the two commands are separated by an appropriate memory barrier (if needed)."
And the fence parameter to vkQueueSubmit is externally synchronized.

**Comment by TiemoJung** [comment]
vkWaitForFences is entirely read only, so it should not count against this. It is even not listed in the list that needs sync of the objects.

**Comment by lentinem** [comment]
While wait is read only the submit is not. In other words, the submit is the at least one of the commands" from the quoted spec. This does not mean that you cannot use multiple threads but you have to ensure that these two commands are not executed simultaneously.

**Comment by TiemoJung** [comment]
So i have to add a mutex to make sure that i do not wait for a fence before it was submited?
This makes zero sense.

**Comment by stroyan** [comment]
An implementation of vulkan could depend this synchronization.  Calling vkQueueSubmit could allocate some device specific fence ID and record that as part of the vulkan VkFence object.  Then vkWaitForFences would read that device specific fence ID and start to wait on it.  Calling vkQueueSubmit while vkWaitForFences is already using the VkFence object would leave the wait with bad data about what fence ID to wait on.
Just adding your own mutex would not be a sufficient fix for your blocking call to vkWaitForFences.  You would need some condition variable to signal when a vkQueueSubmit was completed before you can wait on a VkFence from that call.
