### ISSUE TITLE
Ability to install to a prefix using make/cmake

### ISSUE THREAD

**Issue by salamanderrake** [KhronosGroup/Vulkan-LoaderAndValidationLayers#52]
Could you set it up to where we could install the libraries(layers and etc...) and headers under a prefix defaulting to /usr/local so we could install a local copy of the files where we could point all the tools and other sdk stuff to, it would make it so much simpler for us. Also it would help with packaging systems that don't use CPack or deb files. As it is now CMAKE_INSTALL_PREFIX and make install are ignored.

**Comment by karl-lunarg** [comment]
Committed with #1003.
