### ISSUE TITLE
Validation doesn't check image format matches vkCmdClear*Image command

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-LoaderAndValidationLayers#535]
None of the layers (not sure if this would go in layer_image or layer_core_validation) validate that `vkCmdClearColorImage` is only called with a non-compressed non-depthstencil image, or that `vkCmdClearDepthStencilImage` is only called with a depthstencil image.

**Comment by tobine** [comment]
Created #566 to add these checks

**Comment by tobine** [comment]
Fix was cherry-picked and pushed to master
