### ISSUE TITLE
ParameterValidation: "size not a mul of 4" error reported if VK_WHOLE_SIZE is passed to vkCmdFillBuffer()

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#536]
Current implementation does not recognize the VK_WHOLE_SIZE enum and treats it literally as a number of bytes to be filled with the user-specified int32 value.

It needs to be reworked, so that for cases, where the user passes the VK_WHOLE_SIZE enum, it actually verifies that ((size of the memory attached to the BO - start offset) % sizeof(int32_t) ) == 0.

![image](https://cloud.githubusercontent.com/assets/17761066/15213089/417b1c96-1845-11e6-8446-2bf987139e05.png)

![image](https://cloud.githubusercontent.com/assets/17761066/15213104/5217a952-1845-11e6-82d0-ec2f43ce5d83.png)

**Comment by mark-lunarg** [comment]
Fixed in PR #635.
