### ISSUE TITLE
CoreValidation: Fence X submitted in SIGNALED state. Emited randomly on freshly reseted fences

### ISSUE THREAD

**Issue by TiemoJung** [KhronosGroup/Vulkan-LoaderAndValidationLayers#537]
Hi,

the error message "Fence X submitted in SIGNALED state.  Fences must be reset before being submitted" is randomly generated on reseted fences.

Setup 2 threads:
1. Thread A -> reset fence X
2. Thread A -> pushes commands and fence X to Thread B for pending execution
3. Thread B -> submits commands with fence X. -> Randomly generating error message.
4. Thread A -> wait for fence (after checking that fence X has been submitted)
5. Go Back To 1.

The call log looks like this (format: thread_id, function, fence):
0xFF0 core_validation::ResetFences(VkDevice_T *, unsigned int, VkFence_T * const *) 0x000000000000000b
0xC04 core_validation::QueueSubmit(VkQueue_T *, unsigned int, const VkSubmitInfo *, VkFence_T *) 0x000000000000000b

**Comment by lentinem** [comment]
Does this happen with one thread?

**Comment by TiemoJung** [comment]
No, only with two (and probably more) threads.

**Comment by lentinem** [comment]
Thanks; can you elaborate a bit on what you are doing in 2.? It's a bit unclear to me how the thread synchronization is happening. Alternatively is there a repro that we could use for this issue?

**Comment by TiemoJung** [comment]
Thread B's only purpose is to submit command buffers to queues to move the cost for submits out of all other threads. 
Thread B has a queue where other threads push their commands with and without fences, as needed.
Thread B takes those pushes from the queue and submits them to the vulkan queue.

It is also tracked the state of the fence to ensure not to wait on fences that are not submited yet and that fences that are signaled are reseted before reuse for submits.

**Comment by TiemoJung** [comment]
Also the fence in question is responsible to ensure that resource that are in use are not destroyed while in use. So if the fence was in signaled state, it would trigger other errors to or even crash the driver. But this does not happen.

**Comment by ShaneYCG** [comment]
This setup is the same that lead me to issue #458, but I have not had a chance to test PR #520 against it.

**Comment by TiemoJung** [comment]
Oh yes, i forgot the fence(s) in question are create with signaled bit set.

**Comment by tobine** [comment]
Hi @TiemoJung. The fix for @ShaneYCG #458 just hit master two days ago and it does seem like the same issue. Have you run with the lastest master as of yesterday or today?

**Comment by TiemoJung** [comment]
Have the problem with 8b408b074df08df317a047e913e5ccf7257bf859

**Comment by tobine** [comment]
@TiemoJung I'm going to need a repro case I can run to see this is in order to debug.

**Comment by TiemoJung** [comment]
@tobine Ok, but i don't known when i have the time for it. So it could take a while

**Comment by ShaneYCG** [comment]
Closed my other issue, but I am still occasionally seeing this. Might be a race condition in the validation layer. I do have cpu-side sync mechanisms to ensure the second thread has reset the fence before the first resubmits it.

**Comment by tobine** [comment]
@TiemoJung a related fix was pushed to master today. Can you give this another try and see if you're still seeing the issue?

**Comment by TiemoJung** [comment]
Hi,
seems that the last changes to the fence handling did indeed fix the problem
