### ISSUE TITLE
Incorrect CB_INVALID leading to confusing 'You must call vkBeginCommandBuffer() before this call to ...' messages

### ISSUE THREAD

**Issue by ShaneYCG** [KhronosGroup/Vulkan-LoaderAndValidationLayers#544]
I'm still trying to track down the precise cause, so this initial post is mostly to see if anyone else is running into this issue, and also to bring attention to the misleading warning message.

GLOBAL_CB_NODE::state is sometimes incorrectly being set to CB_INVALID, which causes subequent calls to nearly everything to emit the "You must call vkBeginCommandBuffer()" message.

As best I can tell so far, sometimes resetCB() is not always calling RemoveBoundCommandBuffer (uniqueBoundSets is sometimes incorrectly empty), causing vkUpdateDescriptorSets to call invalidateBoundCmdBuffers, setting the command buffer to the INVALID state.

**Comment by ShaneYCG** [comment]
It seems related to my reuse of VkDescriptorSet. I have a pool of them and I reset to the head when it is safe, if I simply let my pool regrow infinitely the error disappears. Otherwise, the error seems to appear on the first frame that re-use occurs. Unfortunately I have not yet been able to reproduce this in a minimal sample, it may be timing sensitive.

**Comment by ShaneYCG** [comment]
This appears to a problem with ping-ponging command buffers: https://gist.github.com/ShaneYCG/b2b7361f1ddcab0313da31eaf52d726c

**Comment by tobine** [comment]
Debugging this now. Have the repro working. Thanks, Shane.

**Comment by tobine** [comment]
Just submitted #549 to address this issue. That commit message explains the fix, but in general there was a hole where a CB that was placed into INVALID state due to having a bound descriptor set updated was not being implicitly reset when vkBeginCommandBuffer() was called on it.

**Comment by ShaneYCG** [comment]
Will verify as soon as the PR is accepted (I am admittedly new to git and not sure how to grab it before! :)

**Comment by tobine** [comment]
Fix was cherry-picked and pushed to master

**Comment by ShaneYCG** [comment]
Did the trick, thanks!

**Comment by cippyboy** [comment]
I'm using the 1.0.17 validation and I get this and have no idea what it might be related to as I am 1000% sure I'm calling Begin/EndCommandBuffer properly. Is this fix in the 1.0.17 release ?

**Comment by tobine** [comment]
@cippyboy I'm pretty sure this fix should have been included in 1.0.17 SDK as the fix was in on May 18th and that SDK came out in late June.

You have a few options:

1. Try with the lastest master branch of validation and see if the error still occurs, if so and you believe it's invalid, file a new bug, preferably with a repro case
2. If running with master is too much of a hassle, wait for next SDK. I believe there may be one soon.
3. File a new bug on the 1.0.17 SDK, preferably with a repro case

**Comment by cippyboy** [comment]
Just tried with 1.0.21 and I get the same error. I must note that my rendering doesn't produce the expected results so it's probably my fault but I have no idea what could be wrong.

**Comment by cippyboy** [comment]
I tried to check out this git but it gives me an error about my python installation not being version 3. It's a pain to keep reinstalling Python because one app wants 2 and another version 3...
