### ISSUE TITLE
android-generate.bat out of date

### ISSUE THREAD

**Issue by mre4ce** [KhronosGroup/Vulkan-LoaderAndValidationLayers#545]
Looks like the android-generate.bat is not up to date. core_validation needs descriptor_sets.cpp and various other layers need vk_safe_struct.cpp

copy /Y ..\layers\descriptor_sets.cpp   generated\common\
move generated\include\vk_safe_struct.cpp generated\common\

**Comment by cnorthrop** [comment]
Fixed in 4c863b97

Thanks for the report!

-C
