### ISSUE TITLE
validate_pipeline_shaders doesn't catch invalid VkPipelineShaderStageCreateInfo name

### ISSUE THREAD

**Issue by phire** [KhronosGroup/Vulkan-LoaderAndValidationLayers#55]
The spec states:

> • pName must be the name of an OpEntryPoint in module with an execution model that matches stage

But the current validation layers don't check this and both AMD and Nvidia drivers blow up and return weird errors on VkGraphicsPipelineCreate if pName doesn't match your shader's entry point. Should be easy enough to check.

**Comment by chrisforbes** [comment]
Done in master. Just missed the window for lunarg-sdk-1.0.3.1.

**Comment by chrisforbes** [comment]
Should be in next SDK, closing.
