### ISSUE TITLE
[CTS] QueueBindSparse incorrectly reporting fence in use by another submission

### ISSUE THREAD

**Issue by Tony-LunarG** [KhronosGroup/Vulkan-LoaderAndValidationLayers#550]
Running the sparse CTS tests, for instance api.buffer.createBuffer_1_1, calls to QueueBindSparse get the message "Fence 0x4 is already in use by another submission"  even though fence 4 was just created and reset, and never used anywhere prior to the QueueBindSparse call.  Repro case pushed as tony-queuebindsparse-repo - LVT "TonyTestcase".

**Comment by lentinem** [comment]
Uploaded #577 to fix this. The test case you added should also be committed to make sure this doesn't break in the future.

**Comment by lentinem** [comment]
Fix has been committed. Assigning to Tony to check in his test.

**Comment by Tony-LunarG** [comment]
Verified fixed running api.buffer.createBuffer_1_1
