### ISSUE TITLE
Crash when running on system with two graphics cards

### ISSUE THREAD

**Issue by courtney-g** [KhronosGroup/Vulkan-LoaderAndValidationLayers#569]
This is a new issue seen while working on #487

Thanks to Piers Daniell from NVIDIA I found the cause of this crash and why not everyone is able to reproduce this :

I mainly develop on an NVIDIA GPU but I sometimes switch it for an AMD GPU (for e.g. testing image layout transitions). As Windows is fine with this and loads up the drivers for the different GPUs just fine I don't remove drivers when switching from one vendor to another.

As such I have entries for the NVIDIA and AMD drivers in the registry :

image

And the crash I'm getting seems to be related to this.

Testing with NVIDIA I removed the AMD driver entry from the registry and the crash no longer happens.

Putting the AMD entry back in the crash occurs again.

If I switch to AMD while still having the NVIDIA driver entry in the registry I don't see the crash, so this may be tied to an alphabetical loading order?

So this seems to be a very specific issue not related to a special IHV at all, but rather only related to systems with multiple driver entries of which at least one is for a GPU currently not present.

I'm not sure how this should be handled, but (if it's possible to fix) it would be great if this won't would crash inside a validation layers. I can image that this may happen to more people in the future that switch to a different vendor without uninstalling drivers.

Should I open up a new issue for this or is it okay to continue here?

**Comment by SaschaWillems** [comment]
In case you need an application to reproduce, here is my triangle example that I can reproduce the problem with. It includes windows binaries as well as sources : [vulkan_validation_crash_repo.zip](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/files/275058/vulkan_validation_crash_repo.zip)

**Comment by jon-lunarg** [comment]
Hi Sascha:

I currently don't have a computer setup handy to repo this case.  There was a fixed that got checked in on May 5 to master branch that might fix the issue. Did you see the issue with this fix in the code?

commit 999878744bdf08a860b9ee96ede44687eac636ab
Author: Mark Young <marky@lunarg.com>
Date:   Wed May 4 16:44:10 2016 -0600

    loader: Fix issue when ICD DestroyDebugReportCallbackEXT not found.


This fix should also be in the SDK 1.0.13 we released recently.

**Comment by MarkY-LunarG** [comment]
The issue Courtney references above is the one fixed by the commit you pointed out, Jon.  I was able to repro the issue seen by that by simply renaming the Intel JSON file in my System32 folder so it failed to find the driver.  But the same change is not reproducing this issue for me.  I'll have to find a desktop system to try to repro.

**Comment by SaschaWillems** [comment]
Sorry for the late reply, I haven't been able to test this yet, but I'll give it a shot this weekend.

**Comment by SaschaWillems** [comment]
Just checked, and I can confirm that this is no longer crashing with multiple ICDs registered! Thx!
