### ISSUE TITLE
Make sure framebuffer attachments have the correct usage flag.

### ISSUE THREAD

**Issue by mre4ce** [KhronosGroup/Vulkan-LoaderAndValidationLayers#576]
Currently no validation layer appears to catch using an image without the correct usage flags as a framebuffer attachment. For instance, you can use an image without VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT as a color attachment. This also appears to just work with most drivers. I only started noticing problems when using an 2D array image as a framebuffer color attachment where the 2D array image didn't have VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT set.

**Comment by mark-lunarg** [comment]
Addressed by PR #653.  

commit 6600a7662f6dac6a8c8622a8305f02625439bf30
Author: Mark Lobodzinski <mark@lunarg.com>
Date:   Thu Jun 16 13:23:02 2016 -0600

    layers: GH576, Validate attachment image usage

    Framebuffer attachment images are created with IMAGE_USAGE flags. These
    flags are now validated against their attachment location in subpass
    description structures. Also added a check for a preserve attachment
    being set to UNUSED and fixed a few typos in the attachment index
    checking stuff.

    Change-Id: Id62d3539c490ce8f381d7ae606402980f11946fa
