### ISSUE TITLE
ParameterValidation: crash on vkUpdateDescriptorSets

### ISSUE THREAD

**Issue by TiemoJung** [KhronosGroup/Vulkan-LoaderAndValidationLayers#593]
Hi,

the parameter validation layer crashes with the following setup:
```
VkWriteDescriptorSet update;
update.sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
update.pNext = NULL;
update.dstSet = valid_descriptor_set_handle;
update.dstBinding = valind_binding_index_of_the_descriptor_set;
update.dstArrayElement = 0;
update.descriptorCount = 1;
update.descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
VkDescriptorImageInfo img_update;
update.pImageInfo = &img_update;
imgUpdate.imageLayout = valid_image_layout_for_sampling;
imgUpdate.imageView = valid_view_of_a_valid_image;
imgUpdate.sampler = valid_sampler_handle;
vkUpdateDescriptorSets(device, 1, &update, 0, NULL);
```

This code will crash because some pointers are not set and the checker ignores `VkWriteDescriptorSet::descriptorType` and deferenses these invalid pointers.
The function in question is **parameter_validation_vkUpdateDescriptorSets** in file **parameter_validation.h**.

**Comment by tobine** [comment]
Hi @TiemoJung. I know I had talked to @dustin-lunarg about this previously and I believe it may already be fixed. Assigning to him to confirm.

**Comment by TiemoJung** [comment]
Hi, just updated to 8dc6deec07567c276e52475a6d71faf979463765 but still crashes because of the described behavior.

**Comment by dustin-lunarg** [comment]
I have submitted PR #596 to address this.  There was an issue with the autogenerated code in parameter_validation.h always checking pBufferInfo[i].buffer when pBufferInfo was not NULL.  An uninitialized pBufferInfo value would lead to a crash.

**Comment by dustin-lunarg** [comment]
The fix for this should now be on master.
