### ISSUE TITLE
Validate correct VkDescriptorSetLayoutBinding::stageFlags was used

### ISSUE THREAD

**Issue by sheredom** [KhronosGroup/Vulkan-LoaderAndValidationLayers#594]
While writing a [compute sample for Vulkan](http://www.duskborn.com/a-simple-vulkan-compute-example/) I had an annoying bug that it took me a while to find - and I think its something the validator could/should be able to help with!

TL;DR I had accidentally set VkDescriptorSetLayoutBinding::stageFlags to 0 when creating my descriptor set layout, and then tried to bind and use this descriptor set with a compute shader in a command buffer. Of course nothing happened and I spent a while ensuring buffers were aligned correctly, and all manner of other things.

It seems like the validator could at least verify that when using a descriptor set is used with a compute pipeline bound, that the descriptor set layout had VK_SHADER_STAGE_COMPUTE_BIT set - and for graphics it could at least check that some graphics stage was set (even if it couldn't do a deeper inspection).

**Comment by chrisforbes** [comment]
We currently validate this for graphics pipelines -- it's not wired up for compute pipelines yet. Expect that to happen fairly soon...

**Comment by chrisforbes** [comment]
Addressed by #599.

**Comment by sheredom** [comment]
Awesome, thanks!

**Comment by chrisforbes** [comment]
@sheredom the fix for this has now landed in master. Please try it out, and open new issues for areas where you think we're still missing something useful.
