### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [KhronosGroup/Vulkan-LoaderAndValidationLayers#6]
[An extra null pointer check is not needed in functions](http://dietmar-kuehl.de/mirror/c++-faq/freestore-mgmt.html#faq-16.8 "Do I need to check for NULL before delete p?") like the following.
* [VkRenderFramework::ShutdownFramework](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/1affe90f0ec7f9bccb6841a56a2a5b66861efe6a/tests/vkrenderframework.cpp#L163 "VkRenderFramework::ShutdownFramework function")
* [_DESCRIPTOR_POOL_NODE](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/1affe90f0ec7f9bccb6841a56a2a5b66861efe6a/layers/draw_state.h#L448 "Destructor for _DESCRIPTOR_POOL_NODE")

**Comment by tobine** [comment]
These fixes have been merged to master

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/commit/00a897325251de38bacc017bcacf17bc5b018072 "Deletion of a few unnecessary checks").
