### ISSUE TITLE
Enabling Wayland disables XCB?

### ISSUE THREAD

**Issue by Jajcus** [KhronosGroup/Vulkan-LoaderAndValidationLayers#60]
I wanted to play with Wayland surfaces, was disappointed finding out that loader from sdk-1.0.3 won't handle that (failing in a very non-obvious way, I spent few hours with gdb before it occurred to me, that the support is just not there) and then happy seeing this implemented on the master branch (through #17).

I rushed to apply those changes, but it failed to build due to `${DisplayServer}` not being set it `make`. I could fix that, but it seems it can be set to either `Xcb` or `Wayland`. Does this mean that Vulkan-LoaderAndValidationLayers can be built to support Xcb or Wayland, but not both?

It seems the difference is only in the generated code of the layers, but still, is this limitation necessary? On Linux Wayland and X11 are supposed to be used, by different applications, at the same time, on the same system, at least for some undefined transition period.

**Comment by mark-lunarg** [comment]
You are absolutely correct -- unfortunately the current framework allows only a single display server to be specified at build-time.  In our current stage of development the available resources to broaden support in this area are limited, and our development and testing is focused on Xcb, Win32, and Android (through Google).  The majority of support for the other display servers has come in through community contributions for which everyone is grateful.  We do plan to broaden support in the future.
