### ISSUE TITLE
CoreValidation: Valdiation of Shaders

### ISSUE THREAD

**Issue by TiemoJung** [KhronosGroup/Vulkan-LoaderAndValidationLayers#600]
Hi,

the core validation may be to pedantic about the validation of spir-v shaders. when variables are declared that require some cap flags to be set but they are never used we get a validation error.
We generate our shader with glslang and already reported the problem here https://github.com/KhronosGroup/glslang/issues/315 and the answer to it was that the validation layer is probably to strict about it.

**Comment by lentinem** [comment]
This has come up a few times with different solutions proposed. Assigning to Chris to figure out what is most ideal for this case.

**Comment by chrisforbes** [comment]
The shader should be declaring the subset of the builtin block it actually wants.
