### ISSUE TITLE
Missing validation check: vkCmdBeginRenderPass clearValueCount check

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#601]
It does not appear to me that validation is checking the following valid usage of clearValueCount for VkRenderPassBeginInfo:

"clearValueCount must be greater than or equal to the number of attachments in renderPass that specify a loadOp of VK_ATTACHMENT_LOAD_OP_CLEAR" (Vulkan spec 1.0.15 section 7.4)

One of the IHVs has reported that we are violating this requirement.  I'm still working to track it down, but wanted to report this as a missing validation check because this is something validation should be able to catch.

**Comment by tobine** [comment]
Submitted #603 to fill this hole.

**Comment by danginsburg** [comment]
I reviewed the change and it looks good to me.  Thanks.

**Comment by tobine** [comment]
Fix was cherry-picked and pushed to master

**Comment by mre4ce** [comment]
I have three attachments (VkFramebufferCreateInfo::attachmentCount = 3):

1. MSAA color buffer with VK_ATTACHMENT_LOAD_OP_CLEAR
2. resolve color buffer with VK_ATTACHMENT_LOAD_OP_DONT_CARE
3. MSAA depth buffer with VK_ATTACHMENT_LOAD_OP_CLEAR

If I set the VkRenderPassBeginInfo::clearValueCount to 2 I do not get a validation error.

**Comment by tobine** [comment]
From spec:

`clearValueCount must be greater than or equal to the number of attachments in renderPass that specify a loadOp of VK_ATTACHMENT_LOAD_OP_CLEAR`

What do you expect the error to be?

**Comment by mre4ce** [comment]
With a VkRenderPassBeginInfo::clearValueCount of 2 things don't render correctly on all drivers/hardware I've tried.

**Comment by jeffbolznv** [comment]
The spec says:

  * pname:clearValueCount is the number of elements in pname:pClearValues.
  * pname:pClearValues is an array of slink:VkClearValue structures that
    contains clear values for each attachment, if the attachment uses a
    pname:loadOp value of ename:VK_ATTACHMENT_LOAD_OP_CLEAR. **The array is
    indexed by attachment number**. Only elements corresponding to cleared
    attachments are used. Other elements of pname:pClearValues are ignored.

The validity rule looks wrong, it should care about the attachment indices. I think it should be more like:

* pname:clearValueCount must: be greater than the largest attachment index in pname:renderPass that specifies a pname:loadOp (or pname:stencilLoadOp, if the attachment is a depth/stencil format) of ename:VK_ATTACHMENT_LOAD_OP_CLEAR.

(Bonus fix that the validity and the core spec should mention stencilLoadOp).

I'll fix this in the spec.

**Comment by tobine** [comment]
@jeffbolznv update makes sense. I'll change validation to match his proposed update of having clearValueCount be at least as large as the last attachment index that has LOAD_OP_CLEAR.

**Comment by tobine** [comment]
Updated behavior of this check in #769

**Comment by oddhack** [comment]
The internal MR for this has been accepted to the vulkan spec tree and will go out in this week's spec update.
