### ISSUE TITLE
unique_objects causes vkCreateSwapchain to fail

### ISSUE THREAD

**Issue by jon-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#602]
From LunarXchange #537.
I thought for a long time that even this driver (AMD) is wrong, as calling vkCreateSwapchainKHR returned VK_ERROR_INITIALIZATION_FAILED. The issue stems from VK_LAYER_GOOGLE_unique_objects. The implementation lists it as available layer, but using it leads to the mentioned VK_ERROR. Without the layer everything is fine.

**Comment by tobine** [comment]
I double-checked the unique_objects code around CreateSwapchain and related calls. No clear issues based on inspection so need further replication info.

Note that the absence of unique_objects allowing the vkCreateSwapchain to fail is not a definite indication of a bug in unique_objects. If a driver makes invalid assumptions about the value of an object handle then it's possible that unique_objects could reveal such bugs in the driver. Have you tried any devices other than AMD? I have not seen this issue on other devices which causes me to lean towards a driver bug.

**Comment by ParticlePeter** [comment]
I posted this issue in the first place and was about to explain my setup in detail here when new web search for `VK_LAYER_GOOGLE_unique_objects` pointed to [this NVidia forum thread](https://devtalk.nvidia.com/default/topic/917733/vulkan/what-is-vkresult-1000013000-/). There I read for the first time that `VK_LAYER_GOOGLE_unique_objects` must be installed as instance layer extension as well as device layer extension. Till now I used it only as instance layer, but adding it as device layer fixes the problem.
Please consider putting this information in this [Vulkan-LoaderAndValidationLayers README.md](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/tree/master/layers) as all other layers in the super set layer `VK_LAYER_LUNARG_standard_validation` do not need to be installed as device layers.

**Comment by jon-lunarg** [comment]
Thanks for the additional info!  There has been some recent changes in this area of enabling layers at vkCreateInstance versus vkCreateDevice.  Currently on master branch in this repo  and also with SDK-1.0.13,  device layers are deprecated.  In one sentence to describe device layer deprecation, all layers must be enabled at vkCreateInstance, and either none at vkCreateDevice or the same list that was enabled at vkCreateInstance. For more details see the Vulkan specification, the SDK-1.0.13 release notes, the loader documentation (loader/LoaderAndLayerInterface.md), the SDK-1.0.13 layers document.  These SDK documents and specifications can all be found on lunarXchange.

If you are using Vulkan loader from an SDK prior to 1.0.13 all the validation layers must be enabled at BOTH vkCreateInstance and vkCreateDevice.  Some of the layers might have partially worked if only enabled at vkCreateInstance or only at vkCreateDevice but that would just be happenstance. The validation layers need to be enabled very early on (at vkCreateInstance) and left enabled during all the subsequent  vkCreateDevice calls.  After device layer deprecation now all the layers enabled at vkCreateInstance are also enabled automatically at vkCreateDevice by the loader, the app no longer needs to ensure this.

**Comment by DominikWitczakAMD** [comment]
jon-lunarg: Just as a side note, please consider pinging me directly whenever you suspect there's a bug in our Vulkan driver. I'm here to help :-)

**Comment by tobine** [comment]
Closing this as the issue seems to be understood presently and going forward.
