### ISSUE TITLE
vkCmdResolveImage generates invalid "Cannot read invalid memory..., please fill..." message

### ISSUE THREAD

**Issue by cmaaser** [KhronosGroup/Vulkan-LoaderAndValidationLayers#605]
I'm converting a multisample image into a single sample one using vkCmdResolveImage, and getting an invalid validation layer error:

> vkCmdResolveImage(): Cannot read invalid memory 0x9, please fill the memory before using. (code: 12)

The previous render pass has two attachments, a multisample image (view) a multisample depth image (view):

```
  std::array<VkAttachmentDescription, 2> attachment_descriptions;
  // color image:
  attachment_descriptions[0].flags = 0;
  attachment_descriptions[0].format = /* some surface format */;
  attachment_descriptions[0].samples = VK_SAMPLE_COUNT_4_BIT;
  attachment_descriptions[0].loadOp = VK_ATTACHMENT_LOAD_OP_LOAD;
  attachment_descriptions[0].storeOp = VK_ATTACHMENT_STORE_OP_STORE;
  attachment_descriptions[0].stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
  attachment_descriptions[0].stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
  attachment_descriptions[0].initialLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
  attachment_descriptions[0].finalLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;

  // depth image:
  attachment_descriptions[1].flags = 0;
  attachment_descriptions[1].format = /* some depth format */;
  attachment_descriptions[1].samples = VK_SAMPLE_COUNT_4_BIT;
  attachment_descriptions[1].loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
  attachment_descriptions[1].storeOp = VK_ATTACHMENT_STORE_OP_DONT_CARE; // <-- CAUSING ERROR
  attachment_descriptions[1].stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
  attachment_descriptions[1].stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
  attachment_descriptions[1].initialLayout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL;
  attachment_descriptions[1].finalLayout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL;
```

Both views are later attached to a framebuffer and used in a render pass to draw something as usual, filling the whole image. The important part is, that I don't care for the depth image's content once the render pass is finished, so I set the storeOp of attachment 2 (index 1) to VK_ATTACHMENT_STORE_OP_DONT_CARE, while setting the color image's storeOp to VK_ATTACHMENT_STORE_OP_STORE. Once the render pass is done, I call vkCmdResolveImage (ignoring a few barriers in between). This generates the validation layer error from above.

When setting both storeOps to VK_ATTACHMENT_STORE_OP_STORE, the error is gone, even though the depth image's content isn't needed for resolving the multisample color image.

Both the color and the depth image are using the same memory object (0x9), but non-overlapping and well aligned regions within the memory object, respecting size and alignment of what vkGetImageMemoryRequirements says.

**Comment by lentinem** [comment]
To give an update on this. Yes, the fact that it uses the same memory exposes a bug in the memory tracking aspect of the validation layer. Right now a memory block is valid or not instead of a range. Assigning to chris for now to see if he can get to it at some point but if I can do so earlier I'll take it back.

**Comment by lentinem** [comment]
Moving to unassigned to see who can tackle this first.
