### ISSUE TITLE
Multiple layers in a library and duplicated "layer" names

### ISSUE THREAD

**Issue by olvaffe** [KhronosGroup/Vulkan-LoaderAndValidationLayers#607]
`LoaderAndLayerInterface.md` does not really define `"layer"`.  But in `VkLayer_multi.json`, each layer is started by a `"layer"`.  According to RFC 7159,

    The names within an object SHOULD be unique.

Should the manifest file format be fixed?

**Comment by MarkY-LunarG** [comment]
I can't seem to find any ```VkLayer_multi.json``` file, where is it located?

Are you specifically referring to the ```"name"``` element, or do you mean multiple ```"layer"``` defines within a single JSON file?

If you're referring to the ```"name"``` element, is there already a standard in Vulkan for layer naming (i.e. something like any layers should be called VkLayer_<company/product/developer>_<layername>)?

**Comment by olvaffe** [comment]
VkLayer_multi.json is in VulkanTools, but the manifest file format is documented in LoaderAndLayerInterface.md here.

```json
{
    "file_format_version" : "1.0.0",
    "layer" : {
        "name": "VK_LAYER_LUNARG_multi1",
        ...
    },
    "layer" : {
        "name": "VK_LAYER_LUNARG_multi2",
        ...
    }
}
```

There are duplicated `"layer"` in the root object.

**Comment by MarkY-LunarG** [comment]
Got it.  Good point.

**Comment by MarkY-LunarG** [comment]
I'm preparing the change now (it's in internal review).  I've bumped the patch number for the version, and will warn if the version is 1.0.1 and multiple "layer" objects are defined.  I also warn if "layers" is being used with a version < 1.0.1.  After the change, when it gets propagated to VT, the multi.json file should look like:

```
{
    "file_format_version" : "1.0.1",
    "layers" : [
        {
            "name": "VK_LAYER_LUNARG_multi1",
            ...
        },
        {
            "name": "VK_LAYER_LUNARG_multi2",
            ...
        }
    ]
}
```

**Comment by MarkY-LunarG** [comment]
Changes pushed up in commit 887a28de61ddbbcea112a15f5d3cefba6d729c1c.  Changes to VKLayer_Multi will have to wait until these changes are propogated into VulkanTools.
