### ISSUE TITLE
Improve error reporting for failed CreateDevice requests

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#610]
For example, if a CreateDevice request is made with an extension that cannot be found, vkCreateDevice correctly returns VK_ERROR_EXTENSION_NOT_PRESENT.  However, it logs no other additional information about the failure.

The CreateDevice path in the loader probably needs to have additional logging and/or calls to callbacks added at failure points where only a non-success result code is returned.

See https://github.com/LunarG/VulkanTools/issues/43 for more discussion.

**Comment by MarkY-LunarG** [comment]
I've added a lot of more logging to the loader to improve failure paths.  Most failures should have detailed information now with commit e8f1cb0d4c9713a9354d563a86b7da6bbb60ab55.
