### ISSUE TITLE
Dynamic offsets incorrectly bound with dynamic descriptors

### ISSUE THREAD

**Issue by iostrowsINTEL** [KhronosGroup/Vulkan-LoaderAndValidationLayers#611]
In `descriptor_sets.cpp`, `ValidateDrawState()` function has `dyn_offset_index` set to 0 for each binding, while it should not.

**Comment by mark-lunarg** [comment]
RE: PR #612.

**Comment by tobine** [comment]
Fix was cherry-picked and pushed to master
