### ISSUE TITLE
Validation doesn't fire when setting dynamic state with non-dynamic pipeline bound

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-LoaderAndValidationLayers#614]
This is basically just the validation not catching the case I mentioned in KhronosGroup/Vulkan-Docs#235.

When calling `vkCmdSetViewport` etc, a pipeline must already be bound that uses them as dynamic. It's undefined to call these functions when the currently bound pipeline is non-dynamic.

**Comment by chrisforbes** [comment]
The spec still seems pretty vague about this area. There's the new VU block, but what happens to previously bound dynamic state when binding a new pipeline? Are the intersection of the old and new pipelines' dynamic states still valid after the second CmdBindPipeline?

**Comment by baldurk** [comment]
I think that will need clarification from inside Khronos. My understanding would be that yes as you suggest the intersection would be valid. The text from chapter 9 is:

> A pipeline object is bound to the device state in command buffers. Any pipeline object state that is marked as dynamic is not applied to the device state when the pipeline is bound. Dynamic state not set by binding the pipeline object can be modified at any time and persists for the lifetime of the command buffer, or until modified by another dynamic state command or another pipeline bind. No state, including dynamic state, is inherited from one command buffer to another. Only dynamic state that is required for the operations performed in the command buffer needs to be set. For example, if blending is disabled by the pipeline state then the dynamic color blend constants do not need to be specified in the command buffer, even if this state is marked as dynamic in the pipeline state object. If a new pipeline object is bound with state not marked as dynamic after a previous pipeline object with that same state as dynamic, the new pipeline object state will override the dynamic state. Modifying dynamic state that is not set as dynamic by the pipeline state object will lead to undefined results.

That seems to suggest that binding a pipeline inherits any dynamic state that was previously bound, sets any non-dynamic state it contains, and any subsequent dynamic state sets calls are only valid for whatever the current pipeline has as dynamic.

The spec in this section though only specifically calls out what happens for binding a non-dynamic pipeline after a dynamic one. Not explicitly mentioning dynamic-to-dynamic or static-to-dynamic.

**Comment by chrisforbes** [comment]
Fixed by various changes around 15 August.
