### ISSUE TITLE
unique_objects layer doesn't use the correct wsi extension enable flags

### ISSUE THREAD

**Issue by jon-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#615]
createInstanceRegisterExtensions()  appears to correctly sets the various wsi enable flags in the  instanceExtMap.  There is a different flag for the different surface related instance extensions: KHR_surface, KHR_win32_surface, KLHR_xcb_surface, etc. However, the intercept_wsi_enabled_command(const char *name, VkInstance instance) function only tests the
wsi_enable  flag  and bail out early. It should treat each extension differently since they don't necessarily get enabled always at the same time.  In other words, for example on Windows, there should be a
intercept_wsi_enabled_command()  and a intercept_wsi_win32_enabled_command().  Each of these
would bail out if the appropriate extension is not enabled returning null. If the appropriate extension is enabled then the function would do strcmps on only the Vulkan commands that are defined by the extension.

**Comment by jon-lunarg** [comment]
Note this should be fixed by MR #656.

**Comment by tobine** [comment]
Stale issue already fixed
