### ISSUE TITLE
object_tracker doesn't use the correct wsi extension flags

### ISSUE THREAD

**Issue by jon-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#618]
object_tracker.h only has one wsi_enabled flag in struct instExts.  However, it actually intercepts 7 different WSI instance extensions. It needs a flag for all of them:
struct instExts {
    bool wsi_enabled;
    bool xlib_enabled;
    bool xcb_enabled;
    bool wayland_enabled;
    bool mir_enabled;
    bool android_enabled;
    bool win32_enabled;
};

Then in createInstanceRegisterExtensions() it needs to set all seven flags correctly to true or false based on the extension being enabled or  not.

Finally, in object_tracker.cpp intercept_wsi_enabled_command(const char *name, VkInstance instance)  it needs to properly test if the correct (one of the 7) extensions is enabled to decide weather or not to return the intercept function or NULL.

**Comment by mark-lunarg** [comment]
Fixed by PR #687.  

commit 61d505ea40b189b7ae63f311e2f13210eef219d2
Author: Mark Lobodzinski <mark@lunarg.com>
Date:   Fri Jun 24 09:57:32 2016 -0600

    layers: GH618, Correct WSI exension flag usage

    Object_tracker had no notion of individual WSI extension flags,
    and unique_objects was not checking them.
