### ISSUE TITLE
IMAGE: "unsupported format" error may be too strict

### ISSUE THREAD

**Issue by yavn** [KhronosGroup/Vulkan-LoaderAndValidationLayers#621]
I noticed that formats which advertise no linear nor optimal tiling features are treated as unsupported formats, and an error is being emitted:

> IMAGE(ERROR): object: 0x0 type: 0 location: 240 msgCode: 1: vkCreateImage format parameter (VK_FORMAT_R8_USCALED) is an unsupported format

I think this may be too strict a requirement, because implementation may still return VK_SUCCESS from `vkGetPhysicalDeviceImageFormatProperties` indicating that the format is supported for some limited operations. For example, a transfer operation (e.g. image copy) which doesn't have any special feature flag associated with it should work for such format.

On the other hand error makes sense for more complex usages (e.g. blit, or storage images), so perhaps this only needs a small tweak.

**Comment by jon-lunarg** [comment]
Based on the following spec statements for vkGetPhysicalDeviceImageFormatProperties, I am not sure how this issue can not be an error during CreateImage?

"If the combination of parameters to vkGetPhysicalDeviceImageFormatProperties is not supported by the implementation for use in vkCreateImage, then all members of VkImageFormatProperties will be filled with zero.

If format is not a supported image format, or if the combination of format, type, tiling, usage, and flags is not supported for images, then vkGetPhysicalDeviceImageFormatProperties returns VK_ERROR_FORMAT_NOT_SUPPORTED."

I don't see how a given VkFormat can be validly used  in vkCreateImage unless it has some non-zero linearTilingFeatures or optimalTilingFeatures as returned by GetPhysicalDeviceFormatProperties. Am I missing something?

**Comment by yavn** [comment]
Yes, I was puzzled at first too, but after a while I decided there might be a use case. Consider the following:

- I want to create an image and simply clear it (`vkCmdClearColorImage`). I don't want to do anything else with it.

I can accomplish that with only the following properties:

- type: VK_IMAGE_TYPE_2D
- tiling: VK_IMAGE_TILING_OPTIMAL
- usage: VK_IMAGE_USAGE_TRANSFER_DST_BIT

Note that there's no `VkFormatFeatureFlagBits` to describe TRANSFER_DST usage. (<--- this is the important point I think)

So theoretically there might be a format that can't be used for anything but transfer operations. It should be allowed to create such an image. And in fact I have an implementation that does exactly that, which gave rise to this issue in the first place.

Perhaps usages such as clear/transfer operations should also be referenced by some format feature flag. I can try posting a spec issue to clarify this.

**Comment by jon-lunarg** [comment]
Yes, please post a spec issue to clarify weather this usage is valid or not.  Sounds to me like the Vulkan API might need to be expand this sort of example.

**Comment by Tony-LunarG** [comment]
I had this same question about what format feature corresponds to USAGE_TRANSFER_DEST, thinking it was probably FEATURE_BLIT_DEST, but it's certainly not clear in the spec.

**Comment by yavn** [comment]
Please follow up [here](https://gitlab.khronos.org/vulkan/vulkan/issues/371) if you wish.

**Comment by mark-lunarg** [comment]
Fixed in the Warts extension -- VK_FORMAT_FEATURE_TRANSFER_[SRC|DST]_BIT_KHR were added.
