### ISSUE TITLE
Validation suggestion: Report an error if a uniform buffer binding is assigned a buffer memory region whose range size is not a mul of 16

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#623]
It would be super-useful if we could have one of the layers detect & highlight a problem if the following use case is detected:

1. A shader defines a uniform block. Actual members are irrelevant.
2. Report an error, if the application tries to specify a buffer binding for the block, whose range size is not a mul of sizeof(float) * 4.
3. If the application specifies VK_WHOLE_SIZE as the binding range's size the defined buffer MUST meet the requirement defined in the title of this ticket. If not, also report an error.

This requirement comes from GL realm's definition of std140:

> For uniform blocks laid out according to these rules, the minimum buffer object size returned by the UNIFORM_BLOCK_DATA_SIZE query is derived by taking the offset of the last basic machine unit consumed by the last uniform of the uniform block (including any end-of-array or end-of-structure padding), adding one, and rounding up to the next multiple of the base alignment required for a vec4.

We are seeing an excruciating number of applications, CTS test cases, and so on, ignoring this requirement, so I'd appreciate if we could get a special check added for this scenario  :(

**Comment by chrisforbes** [comment]
@DominikWitczakAMD finally had time to circle back to this one -- I see what you're getting at, but I don't see this actually required anywhere in the Vulkan spec. Can you get a spec change to clarify this?

**Comment by DominikWitczakAMD** [comment]
With the recent spec clarification, this one is no longer needed. Thanks for bringing this up though!
