### ISSUE TITLE
core_validation layer bug: SIMULTANEOUS_USE cmdbuffers wrongly trace semaphores

### ISSUE THREAD

**Issue by scyganINTEL** [KhronosGroup/Vulkan-LoaderAndValidationLayers#626]
There is a not handled (or wrongly implemented case) in core_validation layer, where waitSemaphores are wrongly traced, if command buffer is submitted simultaneously more then once. 

Consider  following scenario: 

- _C_  is a command buffer created with `VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT`
- _S0_, _S1_ are two unsignalled semaphores.
- _F_ is an unsignalled Fence

```
vkQueueSubmit(C, pWaitSemaphores = S0, fence = F)
vkQueueSubmit(C, pWaitSemaphores = S1)
vkWaitForFences(F, _forever_) = VK_SUCCESS
---> vkDestroySemaphore(S0); 
```
That gives following validation error:
```
Cannot delete semaphore S0 which is in use.
```
However it is _S1_, not _S0_ which is in use.

This is possibly because in following code in `core_validation.cpp QueueSubmit`: 
```
skipCall |= ValidateCmdBufImageLayouts(dev_data, pCBNode);
            if (pCBNode) {
                pCBNode->semaphores = semaphoreList;
                pCBNode->submitCount++; // increment submit count
                pCBNode->lastSubmittedFence = fence;
                pCBNode->lastSubmittedQueue = queue;
```
the `semaphores` field is wrongly overridden  - `GLOBAL_CB_NODE` should track all semaphores cmdbuffer is actually submitted with.

**Comment by chrisforbes** [comment]
I'll take this as @lentinem is unavailable. @scyganINTEL, I agree with your analysis here. We need to be tracking all the submissions of a CB, not just keeping the "most recent".

**Comment by chrisforbes** [comment]
@scyganINTEL can you verify that #634 fixes this for you?

**Comment by scyganINTEL** [comment]
@chrisforbes Thanks, it works correctly for me.

However my app is trivially simple and only submit _with_ fences, so this does not count as exhaustive test of #634 :)

**Comment by chrisforbes** [comment]
Corresponding changes have now landed, closing.
