### ISSUE TITLE
Remove warning for implicit subpass dependencies

### ISSUE THREAD

**Issue by janharaldfredriksen-arm** [KhronosGroup/Vulkan-LoaderAndValidationLayers#628]
The validation layer checks whether there's a dependency between sub passes using the same attachments. This is good, but it also issues a warning if there are "only" implicit dependencies between two sub passes (rather than a direct dependency). I don't think this should be a warning since the notion of a subpass dependency chain is well defined in the spec:

> A subpass dependency chain is a sequence of subpass dependencies in a render pass, where the source subpass of each subpass dependency (after the first) equals the destination subpass of the previous dependency."

and:
> Render passes must include subpass dependencies (either directly or via a subpass dependency chain) between any two subpasses that operate on the same attachment or aliasing attachments

**Comment by mark-lunarg** [comment]
Fixed by PR #629.

**Comment by lentinem** [comment]
Mark, this issue had been raised a number of times and each time it was decided that the warning should be left it. Warnings are always explicitly allowed by the spec - if they aren't they would be an error. What changed?

**Comment by mark-lunarg** [comment]
I didn't have that context, and we agreed with Jan-Harald about warning for something specifically allowed. Was the warning to let people know that an implicit dependency was present who might not have intended it?

**Comment by lentinem** [comment]
Yes. I'm ok with removing it; when it came up in our meetings there was a lot of indifference if I remember correctly but I want to make sure that is the intent and we are consistent as we certainly have other warnings that fall into this category as well.
