### ISSUE TITLE
assert in vk_layer_validation_test 

### ISSUE THREAD

**Issue by jon-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#63]
[ RUN      ] VkLayerTest.CreatePipelineAttribMatrixType
/home/jon/vk/vk/tests/vktestbinding.cpp:555: Failure
Failed
Assertion: `vkCreateImage(dev.handle(), &info, __null, &handle) == VK_SUCCESS'
Segmentation fault (core dumped)

**Comment by jeremy-lunarg** [comment]
Fix pushed to master.
