### ISSUE TITLE
Remove error of incorrect use of vkEnumeratePhysicalDevices

### ISSUE THREAD

**Issue by janharaldfredriksen-arm** [KhronosGroup/Vulkan-LoaderAndValidationLayers#630]
The validation layer throws an error if vkEnumeratePhysicalDevices is called w/non-NULL pPhysicalDevices if pPhysicalDeviceCount is not been previously retrieved by a previous call to the same function.

I don't think there's any justification for this in the spec. It may be good practice, but the spec allows you use vkEnumeratePhysicalDevices to retrieve a subset of the devices (and that VK_INCOMPLETE is returned if you didn't retrieve them all) so I don't think the validation layer should complain about this.
(See https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#devsandqueues-physical-device-enumeration)

**Comment by tobine** [comment]
Agree that it doesn't need to be an error. Main concern with that check was user requesting devices when non were available, but as spec indicates that case should be handled correctly by loader and  VK_INCOMPLETE returned.

My initial thought is to keep the message but demote it to WARNING, as inexperienced users may just enumerate 1 device without querying the count, and the warning is a good indicator that they may want to actually query the count and handle cases in their app with more (and less) than 1 device.

**Comment by janharaldfredriksen-arm** [comment]
OK. I'm fine with just demoting it to a warning. I can update the MR.

**Comment by mark-lunarg** [comment]
Fixed by PR #632.
