### ISSUE TITLE
Validation layers warn on vkGetFenceStatus of freshly constructed fence

### ISSUE THREAD

**Issue by Ralith** [KhronosGroup/Vulkan-LoaderAndValidationLayers#637]
I'm using a fence to determine whether a given command buffer is currently executing. I do this by constructing it as signaled, resetting it immediately prior to submitting the command buffer, and associating the fence with the submission so that its completion. The operation that initiates the submission checks whether the fence is signaled and throws an error if so. When the application first starts, the command buffer has never been submitted, so this check produces an instance of the warning `vkGetFenceStatus called for fence 0x8 which has not been submitted on a Queue or during acquire next image.`

**Comment by chrisforbes** [comment]
From further IRC discussion: WFF/GFS is being called more than once, which is permissible; unfortunately they have various side effects too early, including resetting `FENCE_NODE::firstTimeFlag` which causes later calls to produce spurious warnings.

**Comment by chrisforbes** [comment]
Should be fixed by #652.
