### ISSUE TITLE
vkWaitForFences falsely fails validation when fed a SIGNALED fence

### ISSUE THREAD

**Issue by iamgreaser** [KhronosGroup/Vulkan-LoaderAndValidationLayers#639]
This looks like an oversight - there are many places where fences need to be entered in unsignaled, but this is definitely not one of them.

    DBG: MEM: vkWaitForFences specified fence 0xa already in SIGNALED state.
    DBG: ParameterValidation: vkWaitForFences: returned VK_ERROR_VALIDATION_FAILED_EXT, indicating that API validation has detected an invalid use of the API

(If I were to "work around" this by calling `vkGetFenceStatus` before calling `vkWaitForFences` it would most likely result in a race condition.)

**Comment by jon-lunarg** [comment]
I think this is what is going on looking at the most recent code in master branch.
The first message (DBG: MEM: vkWaitForFences....)  is an INFO level message that is logged.  This indicates something might be wrong with your app but what you are doing is certainly allowable  within the scope of the Vulkan spec. I would suggest only using VK_DEBUG_REPORT_ERROR_BIT_EXT in your VkDebugReportCallbackCreateInfoEXT struct when calling vkCreateDebugReportCallbackEXT() if you wish to only see messages indicating a spec violation.

The second message is triggered by the first message and the debug_report callback that is registered (created) returning true (PFN_vkDebugReportCallbackEXT returns a VkBool32). This
indicates to the validation layer it should abort (not call into the driver) with the current Vulkan command. Typically returning false from your debug_report callback is the thing to do to let the call go to the driver as it normally would even when validation has detected an issue.

The second message

**Comment by iamgreaser** [comment]
I've since made the debug callback return false if the only bit set is the information bit, but thanks for the note about checking the error bit. Should I close this?

**Comment by jon-lunarg** [comment]
Closing is good by me.
