### ISSUE TITLE
validatelayerdoc is missing IMAGE_INVALID_LAYOUT

### ISSUE THREAD

**Issue by jon-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#64]
[ RUN      ] ./vkvalidatelayerdoc.sh
~/vk/vk ~/vk/vk/dbuild/tests
Error: Undefined DisplayServer
Doc is missing check: IMAGE_INVALID_LAYOUT
[  FAILED  ] Validation of vk_validation_layer_details.md failed
[  FAILED  ] 1 test
1 TEST FAILED

**Comment by jeremy-lunarg** [comment]
Fix pushed to master.
