### ISSUE TITLE
Adjust Validation Layer Checking if vkCmdCopyImage Restrictions are Lifted

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#640]
This issue tracks work that will be needed in the Validation Layers if https://github.com/KhronosGroup/Vulkan-Docs/issues/177 is resolved to remove the restrictions in vkCmdCopyImage.

At a minimum, if the current layer implementation is reporting errors if the baseArrayLayer and layerCount members in the subresource of a 2D array image are not 0 and 1, respectively, then the layers must stop reporting these errors.

In addition, it would be desirable for the layers to report a warning that using values other than 0 and 1 may not work on driver implementations prior to the Vulkan version where this change takes place.

**Comment by mark-lunarg** [comment]
@daveh-lunarg pushed changes, and along with the Maintenance1 extension changes this is now settled and handled correctly.
