### ISSUE TITLE
Validate DS image view aspectMask restriction

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-LoaderAndValidationLayers#644]
According to spec `When using an imageView of a depth/stencil image to populate a descriptor set (e.g. for sampling in the shader, or for use as an input attachment), the aspectMask must only include one bit and selects whether the imageView is used for depth reads (i.e. using a floating-point sampler or input attachment in the shader) or stencil reads (i.e. using an unsigned integer sampler or input attachment in the shader). When an imageView of a depth/stencil image is used as a depth/stencil framebuffer attachment, the aspectMask is ignored and both depth and stencil image subresources are used.`

Need to validate this. Should be simple to add for textures, which I'll do first, and then will add input attachment support second.

**Comment by DominikWitczakAMD** [comment]
Please note https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/650. On the surface, that ticket seems to be slightl related to what you're working on ATM.

**Comment by tobine** [comment]
Fix was cherry-picked and pushed to master
