### ISSUE TITLE
Core_validation: "Buffer Barrier X has offset Y and size Z whose sum is greater than total size W" error refers to the wrong size

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#648]
Say X is a buffer of size 4 which is going to be used as an uniform buffer. On our implementation, vkGetBufferMemoryRequirements() will tell the application to bind a memory block of 16b for that buffer. Let's assume a memory block of size 16 is bound to that buffer.

Later on, if I schedule execution of a command buffer, which issues a buffer barrier requesting a flush of all 16 bytes, I'm getting the following call-back from the core_validation layer:

![image](https://cloud.githubusercontent.com/assets/17761066/16113577/278837c2-33bd-11e6-8a81-a4e8614f5abb.png)

This is incorrect, since I'm absolutely fine flushing all 16 bytes there, as per the following spec language, describing arguments of the vkBindBufferMemory() function:

> memoryOffset is the start offset of the region of memory which is to be bound to the buffer. ***The number of bytes returned in the VkMemoryRequirements::size member in memory, starting from memoryOffset bytes, will be bound to the specified buffer.***

Edit: This is being reported for the latest version from master, checked out approximately half an hour ago.

**Comment by chrisforbes** [comment]
Pretty subtle, but I agree.

I think there's a little bit of spec breakage here too; in `vkBindBufferMemory`, it says:

> The size of /buffer/ must be less than or equal to the size of /memory/ minus /memoryOffset/

This should really be "the size of the backing memory required for /buffer/ as returned in `VkMemoryRequirements::size` ...", right?

**Comment by DominikWitczakAMD** [comment]
Oh, that's definitely a spec inconsistency there. Will you be able to file a relevant ticket to the Vulkan spec project?
