### ISSUE TITLE
Core_validation: "vkCmdPushConstants() stageFlags = X do not match the stageFlags in any of the ranges in pipeline layout Y" error is too strict

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#649]
Let pipeline layout define a push constant range for certain shader stages (expressed as bitfield X), i.e. VkPushConstantRange[0]::stageFlags is set to X at pipeline layout creation time. As per the following spec language:

> stageFlags is a set of stage flags describing the shader stages that will access a range of push constants. **If a particular stage is not included in the range, then accessing members of that range of push constants from the corresponding shader stage will result in undefined data being read.**

I'm asserting that, for the configuration as above, I can access the push constant range from any shader stage, whose corresponding bit is set in X.

Later on however, when I call vkCmdPushConstants() where I request the push constant range to be made available to compute shader stage, I'm getting the following error call-back:

> vkCmdPushConstants() stageFlags = Z do not match the stageFlags in any of the ranges in pipeline layout W.

The "match" wording above means in practice this:

![image](https://cloud.githubusercontent.com/assets/17761066/16114308/dd35d6c6-33c0-11e6-84cc-0f379c605f4c.png)

That check seems to be wrong. Shouldn't we be instead verifying here that all bits from stageFlags are set in iter.stageFlags?

**Comment by chrisforbes** [comment]
I'm not so sure;

Spec says, for `vkCmdPushConstants`:

> stageFlags must match /exactly/ the shader stages used in layout for the range specified by offset and size 

Elsewhere, when a subset of the bits are allowed, the spec is explicit about it.

**Comment by DominikWitczakAMD** [comment]
You're right. Thanks for the clarification :)
