### ISSUE TITLE
Inconsistant handle display in api_dump and validation layer messages.

### ISSUE THREAD

**Issue by jcoder58** [KhronosGroup/Vulkan-LoaderAndValidationLayers#658]
While debugging a problem, I received the error message from vkQueueSubmit:

`Cannot submit cmd buffer using image (0xc) [sub-resource: aspectMask 0x2 array layer 0, mip level 0], with layout VK_IMAGE_LAYOUT_UNDEFINED when first use is VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL.`

I looked through the API dump file and couldn't find image 0xc.  I looked back at where I was creating the depth stencil and found the image handle was shown as both 12 and 0x12, as is shown in bold in the dump below.  So the error is shown in hexadecimal, parameters are shown as decimal and the pCreateInfo->image is shown in hexadecimal with the wrong value.

Can the display of handles be made consistent between validation messages and API dumps?  Bonus points for making them easily searchable, ie: `"image{12}"`

  t{0} vkCreateImage(device = 06F6C650, pCreateInfo = 067BE4C0, pAllocator = 00000000, pImage = 067BE4B8) = VK_SUCCESS
   pCreateInfo (067BE4C0)
    sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO
    pNext = 0x00000000
    flags = 0x0
    imageType = VK_IMAGE_TYPE_2D
    format = VK_FORMAT_D32_SFLOAT_S8_UINT
    extent = 0x067BE4D4
    mipLevels = 1
    arrayLayers = 1
    samples = VK_SAMPLE_COUNT_1_BIT
    tiling = VK_IMAGE_TILING_OPTIMAL
    usage = 0x33
    sharingMode = VK_SHARING_MODE_EXCLUSIVE
    queueFamilyIndexCount = 0
    pQueueFamilyIndices = 0x00000000
    initialLayout = VK_IMAGE_LAYOUT_UNDEFINED
     extent (0x067BE4D4)
      width = 1272
      height = 689
      depth = 1

  t{0} vkGetImageMemoryRequirements(device = 06F6C650, **image = 12** , pMemoryRequirements = 067BE528)
   pMemoryRequirements (067BE528)
    size = 0x7815168
    alignment = 0x1024
    memoryTypeBits = 0x128

  t{0} vkAllocateMemory(device = 06F6C650, pAllocateInfo = 067BE520, pAllocator = 00000000, pMemory = 067BE518) = VK_SUCCESS
   pAllocateInfo (067BE520)
    sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO
    pNext = 0x00000000
    allocationSize = 0x7815168
    memoryTypeIndex = 7

  t{0} vkBindImageMemory(device = 06F6C650, **image = 12** memory = 13, memoryOffset = 00000000) = VK_SUCCESS
  t{0} vkCreateImageView(device = 06F6C650, pCreateInfo = 067BE4D0, pAllocator = 00000000, pView = 067BE4C8) = VK_SUCCESS
   pCreateInfo (067BE4D0)
    sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO
    pNext = 0x00000000
    flags = 0x0
    **image = 0x12**
    viewType = VK_IMAGE_VIEW_TYPE_2D
    format = VK_FORMAT_D32_SFLOAT_S8_UINT
    components = 0x067BE4F0
    subresourceRange = 0x067BE500
     subresourceRange (0x067BE500)
      aspectMask = 0x6
      baseMipLevel = 0
      levelCount = 1
      baseArrayLayer = 0
      layerCount = 1
     components (0x067BE4F0)
      r = VK_COMPONENT_SWIZZLE_R
      g = VK_COMPONENT_SWIZZLE_G
      b = VK_COMPONENT_SWIZZLE_B
      a = VK_COMPONENT_SWIZZLE_A

**Comment by MarkMLunarG** [comment]
This was fixed approximately mid may, which would have first appeared in version 17 of the sdk. Please try a newer code release and report back if there are still issues.
