### ISSUE TITLE
VS Input error when using push constants.

### ISSUE THREAD

**Issue by hypernewbie** [KhronosGroup/Vulkan-LoaderAndValidationLayers#660]
I'm getting the error:
"VS consumes input at location 1 but not provided."
when I enable a single pushconstant range in my pipeline creation  VkPipelineLayoutCreateInfo , when trying to create a pipeline state.

The VS does not read from the push constant at all.

Did I miss something? I couldn't find anything in the specs about some magic pipeline state object stuff I have to do when enabling push constants, other than vkCmdPushConstants to update it.

**Comment by chrisforbes** [comment]
The error you're getting is about the vertex input interface, not the push constants. Would you mind sharing your vertex shader?

**Comment by hypernewbie** [comment]
`layout(set = VE_PSET_PER_OBJECT, binding = 2, std140)
uniform wvpMatrix {
    mat4 matProj;
    mat4 matView;
    mat4 matWorld;
};

layout(set = VE_PSET_PER_OBJECT, binding = 3)
uniform sampler2D uiTexture;

layout (location = 0) in vec2 vertexPosition;
layout (location = 1) in vec4 vertexColour;
layout (location = 2) in vec3 vertexTexCoord0;

layout (location = 0) out vec2 voutput_pos;
layout (location = 1) out vec2 voutput_uv;
layout (location = 2) out vec4 voutput_col;

void main() {
    voutput_uv = vertexTexCoord0.xy;
    voutput_col = vec4(vertexColour.xyz * vertexColour.xyz, vertexColour.w);
    voutput_pos = vertexPosition;
    gl_Position = matProj * vec4(vertexPosition, 0.0, 1.0);
    gl_Position.y *= -1.0;
}
`

**Comment by chrisforbes** [comment]
@hypernewbie and you're sure the inputs there match the pipeline's vertex input setup? (Validation is clean before adding the push constant block to your pipeline layout?)

**Comment by hypernewbie** [comment]
yes, validation layer is squeaky clean before.

**Comment by chrisforbes** [comment]
OK, after poking around a bit, I'm still not seeing why this is happening. Can you share a repro case?

**Comment by chrisforbes** [comment]
Suspect something uninitialized on the app side, still need a repro case.

**Comment by mark-lunarg** [comment]
@hypernewbie, we're going to close this issue for now.  If you are still running into this and can provide a short test case that reproduces the issue please reopen and we'll address it then.  Thanks!
