### ISSUE TITLE
The loader does not enumerate extensions implemented by explicit layers.

### ISSUE THREAD

**Issue by mre4ce** [KhronosGroup/Vulkan-LoaderAndValidationLayers#661]
I assume this was done because when a layer implements an extension you cannot easily separate the two. In other words, an application would always have to opt in to both the extension and the layer or neither. I didn't see this documented here though: https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/loader/LoaderAndLayerInterface.md

**Comment by mre4ce** [comment]
Even though extensions from implicit layers are enumerated, vkCreateInstance fails with VK_ERROR_EXTENSION_NOT_PRESENT when you try to enable such extensions. Are extensions from implicit layers also supposed to be enabled automatically?

**Comment by courtney-g** [comment]
Do you have an example you can share?

An application will need to enable the layer and extension at CreateInstance time to be able to use them. Implicit layers are automatically enabled and thus the app just has to enable the desired extension. The Valid Usage and descriptions of CreateInstance and CreateDevice were recently updated to clarify that behavior.

**Comment by mre4ce** [comment]
I ran into issues while writing a sample that adds an instance extension with a new entry point. Should I put up the sample at LunarG?

**Comment by MarkY-LunarG** [comment]
Several of the layers LunarG releases with the SDK export at least one instance extension (usually EXT_DEBUG_Report).  Those appear to be working fine.  I believe you should be able to upload your files here as long as they're zipped.   Make sure to include the json file as well.

**Comment by mre4ce** [comment]
The debug extension works because the loader is aware of it (debug_report_instance_gpa). If the loader didn't know about the debug extension it probably would not work either.

Issue #553 on LunarXchange.

**Comment by MarkY-LunarG** [comment]
Ok, I'll look into it.

**Comment by courtney-g** [comment]
Layers that expose new Instance level functions generally require loader support. Because of their global nature, the extension call needs to talk with all the ICDs and so something to with their response on the system and the only one that knows how to do that is the loader. There was no obvious "default" behavior that made sense for the loader to provide if an application requests an instance extension it doesn't know about.

**Comment by mre4ce** [comment]
The sample in question adds a very simple instance extension that shouldn't require special knowledge of the loader. I'm sure I'm missing some details but in general it seems bad that the loader needs to be aware of any extensions at all.

**Comment by MarkY-LunarG** [comment]
Preliminary changes for the desktop side are in marky_loader_3 branch.  A few changes are likely necessary for the Android side, Courtney and I are working those out.

**Comment by MarkY-LunarG** [comment]
Changes to support "physical device" extensions were added simultaneously with the "KHR_get_physical_device_properties2" extension using the new "vk_icdGetPhysicalDeviceProcAddr" function as detailed in the LoaderAndLayerIf.md markdown file (found under the loader folder).
