### ISSUE TITLE
VkBuffer objects not bound to VkDeviceMemory objects are not detected on use

### ISSUE THREAD

**Issue by iamgreaser** [KhronosGroup/Vulkan-LoaderAndValidationLayers#663]
This was tested on the 1.0.13 release of the LunarG SDK, and a fresh Git checkout of the validation layer.

Vulkan spec 1.0.17, section 11.6 states:

> Non-sparse resources must be bound completely and contiguously to a single VkDeviceMemory object before the resource is passed as a parameter to any of the following operations:
> 
> *creating image or buffer views
> *updating descriptor sets
> *recording commands in a command buffer

It is currently possible for me to call `vkCmdUpdateBuffer` or `vkCmdFillBuffer` with no warning, and then an in-driver crash (I'm using Mesa-git anvil).

It is also currently possible for me to call `vkCmdBindVertexBuffers` with no warning, and then the call is ignored and the vertex data is read as all-zeroes.

**Comment by tobine** [comment]
Note that same restrictions apply to VkImage object. @mark-lunarg we may want to break this out into separate issues.
I believe @MarkY-LunarG fix from last week handles the first case, `creating image or buffer views`
Descriptor should be an easy fix-up for me to own if there are any bugs there.
There are a bunch of holes for the last case `recording commands in a command buffer`. However, there are some uniform calls that already take place on images and buffers so we can hopefully find a clean, unified solution for making sure that memory is correctly bound to those objects when they're used while recording cmd buffer cmds.

**Comment by tobine** [comment]
#758 will address `recording commands in command buffer` case.
This just leaves `updating descriptor sets` so assigning this to myself to make sure those cases are correctly handled.

**Comment by mark-lunarg** [comment]
#758 has been pushed and closed, that covers the `recording commands in command buffer` case.

**Comment by tobine** [comment]
Just looking at this issue and I see that I added checks for Buffer descriptor updates but not images. Just making a note here that only remaining work is to handle image descriptor updates that don't have memory bound to image as specified.
