### ISSUE TITLE
Buffer's size not tracked in vkUpdateDescriptorSets() function

### ISSUE THREAD

**Issue by Ekzuzy** [KhronosGroup/Vulkan-LoaderAndValidationLayers#664]
When buffer's memory size is exceeded in vkFlushMappedMemoryRanges() function, proper error is reported by validation layers. But validation layers don't report any problem when buffer's memory size is exceeded in **vkUpdateDescriptorSets()** function, through **VkDescriptorBufferInfo** structure.

**Comment by tobine** [comment]
Fix was cherry-picked and pushed to master
