### ISSUE TITLE
Core validation layer incorrectly reports that swapchain image memory has not been filled.

### ISSUE THREAD

**Issue by mre4ce** [KhronosGroup/Vulkan-LoaderAndValidationLayers#676]
When using compute only to update a swapchain image you get:

    vkQueuePresentKHR(): Cannot read invalid swapchain image 0x5, please fill the memory before using.

I thought this issue had been reported before but I can't find the issue.

**Comment by mark-lunarg** [comment]
Johannes -- Was the image updated using CmdDispatch[Indirect]?  It looks like the validation for this is wired up correctly including some fixes in the past month or so.  Are you on Master, or using one of the SDKs?

**Comment by mre4ce** [comment]
I was using latest master. The compute work is submitted with vkCmdDispatch.

I thought we fixed this issue already so I was surprised to see it show up again. The original issue was filed on GitLab issue #90.

**Comment by mark-lunarg** [comment]
There've been a lot of descriptor-set changes lately, is this a regression?  Is there any way we can get a repro case, or some straightforward instructions on creating one?

**Comment by mre4ce** [comment]
The https://github.com/KhronosGroup/Vulkan-Samples/blob/master/samples/apps/atw/atw_vulkan.c sample runs into this issue.

**Comment by mre4ce** [comment]
I've tried the latest 1.0.17.0 SDK and I've tried latest main as well and I can't reproduce the issue. Could there be a threading issue making this a rare occurrence?

**Comment by mark-lunarg** [comment]
Johannes --  though it is possible it seems unlikely.  I have fiddled with atw this morning and I can't get it to reproduce either.  If you see it again we can reopen this issue but for now I'm going to close it and move onto some other ones.  Thanks.

**Comment by mre4ce** [comment]
Agreed. I'll let you know if it happens again and I'll make sure I have a good repro case. Thanks!
