### ISSUE TITLE
Problem with vkWaitDeviceIdle() in Validation Layers

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#677]
(Moved from LunarXchange 551)
Environment

Win 8.1 x64

NV GTX 1080

368.39

1.0.13.0

Description

Guys, this could be me (of course:), but I think I've found another issue...

Looks like function vkWaitDeviceIdle() does not reset tracking of vulkan objects, while it should... at least I think so. Anyway, here's an example:

using N descriptor sets...

vkQueueSubmit()

....

vkQueueSubmit()

vkWaitDeviceIdle()

free N descriptor sets

bind new desc sets (definately new!)

vkQueueSubmit() - validation error (using deleted DSs!), or sometimes even crash inside VLs.

Looks like tracking of used DSs left in VLs, while vkWaitDeviceIdle() should remove those from "tracking list". Yes, w/o VL everything works fine accross lot of vendors and platforms. :)

Regards, DEN

**Comment by mark-lunarg** [comment]
@chrisforbes has completely reworked the fence tracking code recently, to great benefit.  It's likely that this is no longer an issue on Master or in the imminent SDK.

**Comment by tobine** [comment]
@karl-lunarg does this happen w/ latest SDK? Master? It looks like user was hitting one or maybe two previously fixed issues.

**Comment by karl-lunarg** [comment]
We've asked the LunarXchange submitter to try it on SDK 1.0.17.   If we don't hear back shortly, we'll have to construct a repro case.

**Comment by karl-lunarg** [comment]
LunarXchange user reports that this is fixed with 1.0.17.
