### ISSUE TITLE
Failure to detect layout transitions?

### ISSUE THREAD

**Issue by tambry** [KhronosGroup/Vulkan-LoaderAndValidationLayers#680]
When running a program, that obtains a swapchain image, draws to a buffer and then copies the buffer to the swapchain image, there are several validation layer errors about invalid layouts, that shouldn't happen, as the transition to the correct layouts were made with pipeline barriers.

Example code:
http://pastebin.com/raw/2HxbhkVY

Validation layer errors produced by the code:
```
E: [DS]: Cannot submit cmd buffer using image (0x6) [sub-resource: aspectMask 0x1 array layer 0, mip level 1], with layout VK_IMAGE_LAYOUT_UNDEFINED when first use is VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL.
E: [DS]: Images passed to present must be in layout PRESENT_SOURCE_KHR but is in VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL
E: [DS]: Cannot submit cmd buffer using image (0x7) [sub-resource: aspectMask 0x1 array layer 0, mip level 1], with layout VK_IMAGE_LAYOUT_UNDEFINED when first use is VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL.
```

The example crashes on the second frame that is rendered with GTX770 and Nvidia drivers 368.39 on Windows 10 x64.
Validation layers seem to produce no errors that would indicate any actual invalid usage.

I'm not sure if this is related to #46.
I'm using validations layers 1.0.13 from LunarG website (I was unable to compile and install the validation layers from the latest master).
If needed, I can provide full self-contained repro code.

**EDIT:**
The new 1.0.17 layers from LunarG website make no difference.

**Comment by lentinem** [comment]
This definitely looks like the pipeline barriers are not executed. Can you paste the code to your pipeline barrier function?

**Comment by tambry** [comment]
The pipeline barrier wrapper function is as follows: 
```
void pipeline_barrier(VkCommandBuffer command_buffer, VkPipelineStageFlags src_stage, VkPipelineStageFlags dst_stage, std::vector<VkMemoryBarrier> memory_barriers, std::vector<VkBufferMemoryBarrier> buffer_barriers, std::vector<VkImageMemoryBarrier> image_barriers)
{
	vkCmdPipelineBarrier(command_buffer, src_stage, dst_stage, 0, static_cast<u32>(memory_barriers.size()), memory_barriers.data(), static_cast<u32>(buffer_barriers.size()), buffer_barriers.data(), static_cast<u32>(image_barriers.size()), image_barriers.data());
}
```

**Comment by chrisforbes** [comment]
@tambry I've recently pushed a whole bunch of fixes to layout tracking -- can you try again with latest master?

**Comment by tambry** [comment]
I have put together a minimal example to demonstrate the problem. The sample code is available [here](https://github.com/tambry/VulkanPixelRendererTest/). Following the README should be enough to get it compiled and running to demonstrate the problem.

@chrisforbes Last time I tried compiling the validation layers from masters I wasn't able to get them working very well (had to edit the generate .json's and some registry entries). I'll try again.

**Comment by mark-lunarg** [comment]
@tambry, after learning more about wxwidgets than I ever wanted to know and doing some debugging in the layer, it looks like you are using two different subresources.  Transitions are tracked on a subresource basis so the transitions are effectively happening to separate subresources of the image.

The 'clear' barrier subresource is:
`	// The common subresource range
        VkImageSubresourceRange subresource_range = {};
	subresource_range.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
	subresource_range.baseMipLevel = 0;
	subresource_range.levelCount = 1;
	subresource_range.baseArrayLayer = 0;
	subresource_range.layerCount = 1;`

while the CopyBufferToImage call is set to operate on:

`	// Copy the contents of the buffer to the image
	VkImageSubresourceLayers subresource_layers = {};
	subresource_layers.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
	subresource_layers.mipLevel = 1;
	subresource_layers.baseArrayLayer = 0;
	subresource_layers.layerCount = 1;`

So, there is one transition from UNDEFINED to TRANSFER_DST_OPTIMAL on miplevel 0, and a transition from TRANSFER_DST_OPTIMAL to PRESENT_SRC_KHR on miplevel 1.  
Changing subresource_layers.mipLevel to zero makes things run with no validation errors.

**Comment by tambry** [comment]
@mark-lunarg Thank you very much for taking the time to debug and figure out what was wrong. Fixing that little mistake has fixed the crashing problem along with the validation errors. There's still now a crash after resizing, but that's likely due to some other unrelated problem (no validation layer output, though).

Closing this for now, as this was a bug on my side.
