### ISSUE TITLE
Should vk_dispatch_table_helper.h try to resolve extensions?

### ISSUE THREAD

**Issue by mre4ce** [KhronosGroup/Vulkan-LoaderAndValidationLayers#682]
Is there any harm in having vk_dispatch_table_helper.h try to resolve extensions so the layer code isn't littered with explicit calls to get the proc addresses of extensions?

Also shouldn't layer_init_instance_dispatch_table memset the table just like layer_init_device_dispatch_table to clear any proc addresses that are not initialized?

**Comment by jon-lunarg** [comment]
Seems like these helper functions in vk_dispathc_table_helper.h  could add WSI extensions as suggested.  Just be careful when adding them not to change the base dispatch tables defined in vk_layer.h. vk_layer.h file defines the loader<->layer interface and that shouldn't be changed unless we add version negotiation to layer's and loader.  The common WSI extension functions are already in the tables in vk_layer.h so I don't think this is an issue.

**Comment by MarkY-LunarG** [comment]
Completed with commit: 373469f006399d6b5204ee05db3b56beb168b36f

**Comment by mre4ce** [comment]
Currently the vk_displath_table_helper.h is generated for one specific platform. Could we instead generate the vk_dispatch_table_helper.h with conditional compilation to work with all platforms so the file does not have to be regenerated for every platform?

**Comment by mre4ce** [comment]
Pull request #793 implements this. If you specify "vk-generate.py AllPlatforms dispatch-table-ops layer > vk_dispatch_table_helper.h" it will generate one vk_dispatch_table_helper.h that works on all platforms.

**Comment by MarkY-LunarG** [comment]
Changes have been committed with id caeb0e1fd41fe854c9ceb2a65c75920fcae258fb.  Additionally, I enabled this as part of the build now with commit id 3245c959c527ccfa1bbf8cb64e20aecdab5eb473.  So, now all targets should always be present.
