### ISSUE TITLE
Need help with that error...

### ISSUE THREAD

**Issue by DotBlack** [KhronosGroup/Vulkan-LoaderAndValidationLayers#684]
Hey!

I'm learning Vulkan by my own and I would need help fixing a error.

Debugger throws:

VK Debug: ERROR: @[DS]: Cannot submit cmd buffer using image(2)
[sub-resource: array layer 0, mip level 0], with layout
VK_IMAGE_LAYOUT_UNDEFINED when first use is
VK_IMAGE_LAYOUT_PRESENT_SRC_KHR.

I don't understand, where to look exactly in my code...

I would be really happy fixing that..
A big thanks in advance! :D

**Comment by mre4ce** [comment]
This is not the right place for general Vulkan questions. You may want to try the Khronos forums at: https://forums.khronos.org/

With that said, it looks like you need to use a VkImageMemoryBarrier to change the image layout from VK_IMAGE_LAYOUT_UNDEFINED to VK_IMAGE_LAYOUT_PRESENT_SRC_KHR. The Vulkan spec has all the details on how to do this: https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html

**Comment by DotBlack** [comment]
Hey.

Thank's for that answer. It helped me out.
I didn't know that forum. Good to know that.

Have a nice day :+1:
