### ISSUE TITLE
DrawState false positive claiming deleted event

### ISSUE THREAD

**Issue by Tony-LunarG** [KhronosGroup/Vulkan-LoaderAndValidationLayers#69]
Running vk_blit_tests with validation enabled, when I get to VkCmdCopyBufferTest.RAWHazard, I get 2 DS validation errors: 

DS(ERROR): object: 0x277b420 type: 23 location: 3813 msgCode: 16: Cannot submit cmd buffer using deleted event 41399328.

Looking at the api_dump of the subtest, the event is created, then reset, then vkCmdSetEvent is put into a command buffer referencing it, then vkCmdWaitEvents is put into the command buffer referencing it.  Ending the command buffer causes the above DrawState error twice, supposedly once for each reference in the command buffer.  Nowhere in the call stream is the event destroyed.

**Comment by lentinem** [comment]
This is essentially hitting an assert that should never happen - somehow the hash of events is missing that one but it is added on creation and only removed on deletion. I'm guessing it gets accidentally removed somehow but will look into it.

**Comment by lentinem** [comment]
Can you or tobin check if #81 fixed this issue on that specific test?

**Comment by tobine** [comment]
Yes, #81 appears to have fixed this issue.
