### ISSUE TITLE
False positive when layer is checking pipeline compatibility against a deleted render pass

### ISSUE THREAD

**Issue by hrydgard** [KhronosGroup/Vulkan-LoaderAndValidationLayers#690]
Let's say I do the following:

* Create a renderpass object
* Create a pipeline, passing in that renderpass object
* Delete the renderpass object
* Create another render pass object, compatible with the first (identical)
* Draw using the pipeline

This currently triggers

    ERROR: [DS] Pipeline Code 43 : At Draw time the active render pass (0x52) is incompatible
    w/ gfx pipeline (0x23f733aebb0) that was created w/ render pass (0x10) due to:
    invalid VkRenderPass (0000000000000010)

Presumably the validation layer compat check wants to compare the current render pass against a no-longer-existing VkRenderPass object, while the driver will certainly not be doing such validation, there's no reason it should go back and try to read the renderpass the pipeline was created with, so it really should be safe.

As in my previous reports, this can be easily reproduced by building PPSSPP in debug mode and switching to the Vulkan backend, then debug from within VS.

Appears to be new in 17.

**Comment by chrisforbes** [comment]
Hey @tobine, another variation on what you just fixed for framebuffers.

**Comment by tobine** [comment]
Submitted #697 that should fix this issue

**Comment by tobine** [comment]
Update PR #717 fixes this and various related issues

**Comment by tobine** [comment]
Fix was cherry-picked and pushed to master
