### ISSUE TITLE
command repeated twice in update_external_sources.sh

### ISSUE THREAD

**Issue by sl1pkn07** [KhronosGroup/Vulkan-LoaderAndValidationLayers#691]
https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/update_external_sources.sh#L63
https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/update_external_sources.sh#L64

**Comment by karl-lunarg** [comment]
Fixed.  Thanks.
