### ISSUE TITLE
Core Validation mishandling of pipeline layout objects

### ISSUE THREAD

**Issue by chrisforbes** [KhronosGroup/Vulkan-LoaderAndValidationLayers#695]
Vulkan spec 2.3.1 says:

>The following object types are consumed when they are passed into a Vulkan command and not further accessed by the objects they are used to create. They can be destroyed at any time they are not in use by an API command:
>
>VkShaderModule
>VkPipelineCache
>VkPipelineLayout

However, core validation retains the pipeline layout handle and uses it in descriptor set compatibility checks at bind & draw time etc.

**Comment by tobine** [comment]
Fix was cherry-picked and pushed to master
