### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [KhronosGroup/Vulkan-LoaderAndValidationLayers#7]
I would like to point out that identifiers like "[`_CALL_STATE`](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/1affe90f0ec7f9bccb6841a56a2a5b66861efe6a/layers/device_limits.h#L59)" and "[`_CMD_TYPE`](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/1affe90f0ec7f9bccb6841a56a2a5b66861efe6a/layers/draw_state.h#L458)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by karl-lunarg** [comment]
Thanks for your input.  We'll schedule this work for the near future.

**Comment by mark-lunarg** [comment]
Fixed and pushed to Master.

**Comment by elfring** [comment]
Thanks for [your improvement of affected identifiers](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/570 "Deletion of some underscores").
