### ISSUE TITLE
Core Validation: Should renderpass-level & first used subpass' initialLayout values really be required to match?

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#704]
Let image X stand for a swapchain image. These, by spec language, must not be transitioned to any specific layout until actually acquired.

Now, let A stand for a renderpass whose one of the attachments is an image view, created from image X. To use the auto-transition mechanism, we set _VkRenderPassCreateInfo::pAttachments[RP attachment index]::initialLayout_ to _VK_IMAGE_LAYOUT_UNDEFINED_ and _VkSubpassDescription::pColorAttachments[SP attachment index]::layout_ to, say, _VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL_. This request is deemed invalid by core validation layer which now complains that:

![image](https://cloud.githubusercontent.com/assets/17761066/16413829/b73965e6-3d34-11e6-9607-5c01e153745f.png)

However, I am unaware of any restriction in the spec which would require renderpass' initial layout to always match the first used subpass' initial layout. In specific, the following language would indicate exactly the opposite:

![image](https://cloud.githubusercontent.com/assets/17761066/16413861/e1c57958-3d34-11e6-9677-6a298a6d0b57.png)

**Comment by DominikWitczakAMD** [comment]
This "Valid Usage" bullet can also come in handy here:

![image](https://cloud.githubusercontent.com/assets/17761066/16414362/7cd7d6a0-3d37-11e6-90ce-4cb3fe81b90a.png)

**Comment by chrisforbes** [comment]
@DominikWitczakAMD I agree, this is broken.

**Comment by chrisforbes** [comment]
Interacts with #655.

**Comment by chrisforbes** [comment]
@DominikWitczakAMD this check isn't doing what you think it does -- it's between the previous layout of that image (within the command buffer) if known, and the render pass's initial layout for that attachment. The subpass layouts are not in play.

**Comment by DominikWitczakAMD** [comment]
@chrisforbes: Possibly, yeah. I never claimed I went an extra mile to trace down the root cause of this problem. :-)

**Comment by chrisforbes** [comment]
@mark-lunarg do you actually want this ticket? I understand it enough to fix it quickly now.

**Comment by mark-lunarg** [comment]
No!  Have fun!

**Comment by chrisforbes** [comment]
Fixed by #715.
