### ISSUE TITLE
Shader Validation and VK_NV_glsl_shader extension

### ISSUE THREAD

**Issue by mark-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#706]
When using the NVidia driver and enabling the VK_NV_glsl_shader extension, the shader validation appears to assume the shader must be SPIRV and throws this error:

`SC: SPIR-V module not valid: Invalid SPIR-V magic number. Exception thrown at 0x00007FF8F9DD51E4 (VkLayer_core_validation.dll) in Viewer.exe: 0xC0000005: Access violation reading location 0x000001A629FE1574.`

The extension allows GLSL shaders to be passed in instead of SPIR-V. The debug layer does not allow for non-SPIRV shaders when this extension is present.  If the exension is _enabled_ and the shader signature is not SPIRV, we should probably skip continuing with the validator.

**Comment by THofstee** [comment]
Any updates on this?

**Comment by Loftilus** [comment]
I suggest also adding a way to provide SPIR-V in addition to the GLSL shader code.

**Comment by THofstee** [comment]
@Loftilus Sorry what do you mean by that? I believe you can pass in SPIR-V even while the nv_glsl_shader extension is active.

**Comment by Loftilus** [comment]
So i would like to provide GLSL for VK_NV_glsl_shader, but have the validation layers use the additionally provided SPIR-V for validation.

**Comment by mark-lunarg** [comment]
Fixed by PR #1452.

**Comment by sergeyreznik** [comment]
@mark-lunarg is it included in 1.0.42.0 ?
