### ISSUE TITLE
Draw state layer tries to traverse VkSwapchainCreateInfoKHR::pQueueFamilyIndices array even if imageSharingMode is set to VK_SHARING_MODE_EXCLUSIVE

### ISSUE THREAD

**Issue by KarenGhavam** [KhronosGroup/Vulkan-LoaderAndValidationLayers#71]
Originally posted on gitlab by Dominick Witczak. Moved to this public github.

As per spec, this behavior is invalid: VkSwapchainCreateInfoKHR::pQueueFamilyIndices is an array of queue family indices having access to the images of the swapchain in case imageSharingMode is VK_SHARING_MODE_CONCURRENT.

**Comment by lentinem** [comment]
Tobin is going to merge Dominick's fix for this.

**Comment by tobine** [comment]
Merged Dominik's fix from GitLab onto GitHub master.
