### ISSUE TITLE
Publish .pdb for VulkanRT installer and VulkanRT uninstaller

### ISSUE THREAD

**Issue by KarenGhavam** [KhronosGroup/Vulkan-LoaderAndValidationLayers#72]
Originally posted on private gitlab by Jeff Juliano. Moved to this public github.

A security audit of the VulkanRT installer and uninstaller has generated a request for a pair of .pdb files that match the two .exe files. They are wanted in order to support running a Binscope scan on the .exe files.
I'm not certain, but passing a Binscope scan might be a requirement for including these files in a driver package that gets posted to Windows Update. (I'll try o verify this claim.)
Publishing the .pdb files privately would be sufficient. They need not be published to the public.

**Comment by hlandau** [comment]
The installer is NSIS based, so I guess the question is whether NSIS can provide such files.

**Comment by jjulianoatnv** [comment]
> but passing a Binscope scan might be a requirement for including these files in a driver package that gets posted to Windows Update. (I'll try o verify this claim.)

I was told it is not a requirement. However that does not obsolete the request.

**Comment by jjulianoatnv** [comment]
pdb is desired for both VulkanRT installer and VulkanRT uninstaller. Both are executed within the elevated security context of an IHV driver or ISV app install.

**Comment by davidlunarg** [comment]
I have pdb files for the Runtime Installer/Uninstaller. The attached zip file contains an experimental Runtime Installer and Uninstaller (ignore the version number), and a couple of pdb files. A command such as:
`dumpbin /PDBPATH:VERBOSE UninstallVulkanRT.exe`
indicates that the stub_zlib.pdb file is the pdb file for that executable. Also, a command such as:
`symchk VulkanRT-1.0.1.0.pre.1-Installer.exe  /s .`
indicates that a pdb file for that executable was found.

The installers include other executables/dll's, so I'm not sure if providing these two pdb files is sufficient for nVidia's Binscope scan, or if additional pdb files are needed. Let me know.

Don't plan on using these pdb files for production RT installers - I can provide the pdb files corresponding to the RT installer/uninstaller when we do the next release. 

[rtpdbfiles.zip](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/files/188273/rtpdbfiles.zip)

**Comment by davidlunarg** [comment]
pdb files for the Runtime Installer and Uninstaller have been delivered to the requester. If anyone else would like a copy of those files, please submit a new issue.
