### ISSUE TITLE
Enable MIR WSI support

### ISSUE THREAD

**Issue by MarkY-LunarG** [KhronosGroup/Vulkan-LoaderAndValidationLayers#725]
Complete and validate necessary WSI extensions on a MIR enabled Linux system.  The necessary extensions include at the very least VK_KHR_mir_surface.  The majority of functionality appears to be in place, but we need to verify that it is complete and fully exposed for all appropriate targets.  Right now, this is only exposed via compile time only support in the loader.

**Comment by mark-lunarg** [comment]
This should be complete.
