### ISSUE TITLE
Performance warning: when instanceCount = 0 (or drawCount = 0)

### ISSUE THREAD

**Issue by RCalocaO** [KhronosGroup/Vulkan-LoaderAndValidationLayers#727]
From this spec issue:
https://github.com/KhronosGroup/Vulkan-Docs/issues/275

"instanceCount in VkCmdDraw\* does not specify 0 or 1 as minimum: Some implementations treat 0 and 1 differently, it would be nice if the spec stated what happens and if it's valid when passing 0 as instanceCount (either not valid, treated as 1 or the draw called is ignored)"

Maybe the validation layer can warn if instanceCount=0 for a potential perf issue, and/or even when drawCount=0? Maybe not for the indirect draw case as 0 primitives there is more expected.

**Comment by karl-lunarg** [comment]
Related to #1155

**Comment by mark-lunarg** [comment]
This issue is now tracked via issue #1612.
