### ISSUE TITLE
UninstallVulkanRT.exe is not digitally signed

### ISSUE THREAD

**Issue by KarenGhavam** [KhronosGroup/Vulkan-LoaderAndValidationLayers#73]
Originally posted on private gitlab by Jeff Juliano. Moved to this public github.

The VulkankRT uninstaller, UninstallVulkanRT.exe, is not digitally signed.
It should be signed, probably with the same key that is used to sign the VulkanRT installer.
It's against policy for my display driver uninstaller to invoke a .exe that is not signed.

**Comment by davidlunarg** [comment]
The next SDK release will have a Runtime uninstaller that is signed.
