### ISSUE TITLE
add install libvulkan.so.*, json files and demos through cmake instead of by hand

### ISSUE THREAD

**Issue by sl1pkn07** [KhronosGroup/Vulkan-LoaderAndValidationLayers#740]
when run `make install`, only install the headers and libvklayers_*. 

libvulkan.so\* and json files should be installed by hand

please add support to cmake for install the demos, the json layers and libvulkan.so\* with `make install`

greetings

**Comment by karl-lunarg** [comment]
Looks like there was a weak attempt to add install support for layers.  But I didn't see anything there for include.  We were planning to do some cleanup of the CMakefiles anyway, and this is a good thing to include in that effort.

**Comment by karl-lunarg** [comment]
the CMake files were recently modified to do much more on a `make install`.  Please see the [BUILD.md](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/BUILD.md) file in the section "Linux Install to System Directories".
