### ISSUE TITLE
Tests: VkLayerTest.StencilLoadOp crash with Windows Debug build

### ISSUE THREAD

**Issue by dustin-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#741]
For Debug Windows builds, VkLayerTest.StencilLoadOp is triggering an SEH exception in vkDestroyImage.  

This issue started with change 99df1a43113407af9ddb0aa2322fb99d9f59e5c2.  The crash is happening in core_validation when DestroyImage calls:
>invalidateCommandBuffers(img_node->cb_bindings, {reinterpret_cast<uint64_t &>(img_node->image), VK_DEBUG_REPORT_OBJECT_TYPE_IMAGE_EXT});

Where img_node->cb_bindings contains one entry having multiple fields populated with the 0xdddddddd pattern, which should indicate a freed memory block.

**Comment by tobine** [comment]
Yeah, I need to make sure that all appropriate cb_bindings are cleared when cmd buffer is reset/freed.
