### ISSUE TITLE
core_validation may fail due to reuse of dispatchable handles in threads

### ISSUE THREAD

**Issue by stroyan** [KhronosGroup/Vulkan-LoaderAndValidationLayers#750]
If a dispatchable handle is reused after free or destroy, core_validation may lose track of it.
FreeCommandBuffers calls the down the dispatch table to free before updating its data structures.
Another thread may reuse those command buffer handles before the call returns and the data is updated.
All calls releasing dispatchable handles should update data structures before calling down the the next layer or icd.  This problem may effect other functions beyond FreeCommandBuffers.

**Comment by tobine** [comment]
Fix was cherry-picked and pushed to master
