### ISSUE TITLE
Ensure that depth/stencil state is specified during pipeline creation when a depth attachment is used

### ISSUE THREAD

**Issue by Overv** [KhronosGroup/Vulkan-LoaderAndValidationLayers#759]
The validation layers currently do not ensure that `VkGraphicsPipelineCreateInfo.pDepthStencilState` is not a `nullptr`  if the renderpass contains a depth/stencil attachment.

**Comment by chrisforbes** [comment]
Addressed by #924

**Comment by karl-lunarg** [comment]
Appears to have been addressed.
