### ISSUE TITLE
Report an error on invalid image layout transitions

### ISSUE THREAD

**Issue by yavn** [KhronosGroup/Vulkan-LoaderAndValidationLayers#760]
(this is an enhancement request)

Would it be possible to add a check for the following scenario?
- an image is created **without** a `VK_IMAGE_USAGE_SAMPLED_BIT` and `VK_IMAGE_USAGE_
  INPUT_ATTACHMENT_BIT` flags
- a layout transition to `VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL` is executed

Specification says this is not allowed. This mistake can happen e.g. for a storage image which we intend to only read and set the aforementioned layout instead of the correct GENERAL.

Not sure if other similar usage/layout combinations are being tested, but it may be a good idea to include them to avoid this class of problems.

**Comment by scyganINTEL** [comment]
This is from internal vulkanCTS issue, I may have looked from the other perspective and identified another problem: 

- Layers does not warn, when vkUpdateDescriptorSets try to update descriptor of type VK_DESCRIPTOR_TYPE_STORAGE_IMAGE with layout VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL. (only GENERIC is allowed for image load store).

**Comment by mikew-lunarg** [comment]
The first comment appear to be specified by Valid Usage 00306 for vkCmdPipelineBarrier().
The VUs 00303 thru 00308 are of similar structure; i.e.: "If either oldLayout or newLayout is VK_IMAGE_LAYOUT_* then image must have been created with VK_IMAGE_USAGE_*_BIT set"

**Comment by mikew-lunarg** [comment]
For the second comment, I'm having trouble identifying the specifying Valid Usage.

The closest seems to be VU 00943: "If descriptorType is ... VK_DESCRIPTOR_TYPE_STORAGE_IMAGE ..., the imageView and imageLayout members of any given element of pImageInfo must be a valid VkImageView and VkImageLayout, respectively." which does not put restrictions on the VK_IMAGE_LAYOUT_* values.

@scyganINTEL If this problem still exists, could you create a separate GitHub issue pointing to the place in the spec that calls out the VK_IMAGE_LAYOUT_GENERAL requirement?

Thanks

**Comment by scyganINTEL** [comment]
Submitted as separate issue #1526

**Comment by mikew-lunarg** [comment]
Please see PR #1542

**Comment by mikew-lunarg** [comment]
PR has merged.
@yavn Let me know how this works for you.
