### ISSUE TITLE
Validation suggestion: textureSamples() should not be called for single-sampled image bindings

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#762]
We've just discovered a problem with one of the recently introduced CTS tests, where they first bind a single-sample MS image and then try to query the number of samples exposed by the image with a textureSamples() call. This would work in GLSL, but is illegal after being converted to SPIR-V due to the following restriction in the SPIR-V spec:

```
OpImageQuerySamples
Query the number of samples available per texel fetch in a multisample image.
Result Type must be a scalar integer type. The result is the number of samples.
Image must be an object whose type is OpTypeImage. Its Dim operand must be one
of 2D and MS of 1(multisampled)
```

SPIRV-Validation does not have shadow enough state information to determine this condition, so validation layers seem like a more suitable candidate.

**Comment by chrisforbes** [comment]
@DominikWitczakAMD I might be being blind here, but what additional state do you think is needed? The restriction you've quoted is just between a type and an operation consuming it, at the SPIRV level.

**Comment by DominikWitczakAMD** [comment]
Sorry if I was unclear. When they configure the "sampled image" descriptor, they specify an image view. whose parent is a single-sample image. The case which would be useful to have validated is the mismatch which can occur if you try to bind a multisample image to a non-MS image variable (and vice versa).

**Comment by chrisforbes** [comment]
Alright, we can definitely produce a draw-time error for a multisampled image being consumed through a non-MS image variable. I'm not seeing a clear rule for singlesampled images being consumed through a MS image variable, though -- the spec merely says (15.3):

> If the image’s samples is not equal to VK_SAMPLE_COUNT_1_BIT, the instruction must have MS = 1.

Do you have a spec quote to back disallowing singlesampled images through MS=1? [This was possible (but not wildly useful) in GL]

**Comment by DominikWitczakAMD** [comment]
Good question. I don't have an answerr off the cuff. Let's drop the other case then.

**Comment by chrisforbes** [comment]
OK, I'll get to this shortly.

**Comment by chrisforbes** [comment]
@DominikWitczakAMD going to change my position on this -- per table 11.1 in the Vulkan spec, I believe both cases should be errors as you previously suggested.

**Comment by chrisforbes** [comment]
@DominikWitczakAMD can you verify that #799 does what you want?

**Comment by DominikWitczakAMD** [comment]
Sorry, I was away on a paternity leave. Yeah, this works just fine, thanks Chris :-)
