### ISSUE TITLE
Validation suggestion: Check bufferRowLength in BufferToImage copies.

### ISSUE THREAD

**Issue by Themaister** [KhronosGroup/Vulkan-LoaderAndValidationLayers#763]
Just debugged an issue where bufferRowLength was set to an undefined value, non-zero but smaller than image width. Validation layer did not catch this bug.

**Comment by mark-lunarg** [comment]
Re: PR #876 .

**Comment by mark-lunarg** [comment]
Fixed by #876.  

commit 810d14c89ff9bf32ff07ae8cd757b17ccb7f2c7d
Author: Mark Lobodzinski <mark@lunarg.com>
Date:   Fri Aug 19 08:50:15 2016 -0600

    layers: GH763, Add validation for VkBufferImageCopy

    Added valid usage checks for members of this structure used in
    vkCmdCopyImageToBuffer and vkCmdCopyBufferToImage.

    Change-Id: I62ec7b04504e91fa33c86d1a5b606ba8fb7a294a
