### ISSUE TITLE
Update unique_objects FreeDescriptorSets() to erase map entries

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-LoaderAndValidationLayers#770]
Currently the handles aren't released from the map

**Comment by tobine** [comment]
@mark-lunarg I was a slacker and never addressed this bug. I see it's still there in your current rework. Can you add custom code to this function to erase the descriptor handles from unique_id_mapping?

**Comment by mark-lunarg** [comment]
Happy to.

**Comment by mark-lunarg** [comment]
Addressed as part of #1018 .
