### ISSUE TITLE
Validation suggestion: Check framebuffer layer dimension against attachment layer count

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-LoaderAndValidationLayers#772]
It's currently possible to create a frambuffer with VkFramebufferCreateInfo.layers being less than the layerCount of an attachment attached to that framebuffer.

Creating such a framebuffer should at least generate a warning that it has an attachment assigned that has more layers than the actual framebuffer.

During my tests (using a geometry shader to output to different layers of a depth attachment), having the framebuffer's layer count below that of the attachment behaves differently across the implementations, (worked on one IHV, for another one all GS outputs ended up on the first layer of the FB), so I think there should be at least a warning.

I'm not 100% sure, but I can imagine situations where you may want to have an attachment with more layers than the FB attached to it, hence a warning should suffice?

**Comment by chrisforbes** [comment]
@SaschaWillems that sounds like a broken driver...

**Comment by lentinem** [comment]
This does sound like a candidate for CTS. If the drivers are behaving correctly it's hard to see how this could be misused by the developer which is what warnings are really for. Let me know if anyone thinks otherwise.

**Comment by lentinem** [comment]
This has been inactive for a while so I'm going to close it and suggest Sascha file against CTS. If you disagree please re-open.
