### ISSUE TITLE
Add validation for null pColorBlendState at pipeline creation (with rasterizer discard disabled)

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-LoaderAndValidationLayers#777]
The current spec states that you must pass a valid pointer to pColorBlendState for the pipeline if you have subpasses using color attachments and rasterizer discard is not enabled:

> If the rasterizerDiscardEnable member of pRasterizationState is VK_FALSE, and subpass uses
> color attachments, pColorBlendState must be a pointer to a valid
> VkPipelineColorBlendStateCreateInfo structure

Having a renderpass with a color (and) depth attachment in a single subpass and setting pColorBlendState to NULL with rasterizerDiscardEnable = VK_FALSE for a pipeline that uses this renderpass does not trigger any validation errors or warnings.

There is a validation for the attachmentCount of the colorBlendState, but nothing if the colorBlendState is set to null.

**Comment by mikew-lunarg** [comment]
This check corresponds to Valid Usage VALIDATION_ERROR_02116

**Comment by mikew-lunarg** [comment]
Candidate check code is implemented on branch mikew_gh777.
Pull request is awaiting test code to exercise the check.

**Comment by mikew-lunarg** [comment]
Pull request #1457

**Comment by mikew-lunarg** [comment]
Merged to master at commit b502f14620de42454ef8906b6d76e9a176c52067
