### ISSUE TITLE
Identifying layer debug report messages reliably is currently impossible

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-LoaderAndValidationLayers#780]
At the moment there's no sane reliable way to identify a specific message or a narrow category of similar messages, for muting in the application's debug report callback if they are spammy and useless.

Calls to `log_msg` from the layers all use `__LINE__` as the `location` field, which makes it useless for identifying messages outside of a particular build of the layers. You could use it in a debugger session for conditional breakpoints, or add a temporary if, but it's not something you could commit.

I was using the `messageCode` field which is predefined with e.g. `DRAWSTATE_INVALID_BARRIER` or `DRAWSTATE_INVALID_BUFFER` in [core_validation_error_enums.h](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/core_validation_error_enums.h) and other headers. Note that these aren't immediately convenient to use, since core_validation_error_enums.h isn't shipped with the SDK, and other layers use enums defined within their layer headers which come with a number of other `#include` dependencies so they can't just be dropped into a project.

I found today though that items are removed and/or added in the middle of the list - changing all of the values and meaning that `messageCode` is not any more portable between layer versions than `location` is.

I'd recommend that `messageCode` should be treated the same as any ABI guarantee and those enum values should *never* change.

I've also recommended in the past eliminating use of `__LINE__` and replacing it with a immutable globally unique ID across all layers. This would be very simple to implement in any external scripting language, and since python is already required to build many of the layers it would be trivial to add as a pre-build step. An outline:

1. Create a file `layers/log_msg_id.txt` which contains a number that always increments.
2. Add `#define LAYER_LOG_MSG_ID(id) id` to `vk_layer_utils.h`
3. When a new log_msg is added, for the location field use `NEXT_LAYER_LOG_MSG_ID`.
4. Add a python script that runs pre-build step. It will look at every instance of `LAYER_LOG_MSG_ID(id)` to make sure they are unique (this will prevent merge conflicts creating duplicate IDs, just needs to be manually replaced with `NEXT_LAYER_LOG_MSG_ID` and re-run). Then for each instance of `NEXT_LAYER_LOG_MSG_ID` it replaces it with `LAYER_LOG_MSG_ID(contents of log_msg_id.txt)` and increments the txt file value.

You then immediately have unique IDs that never change no matter what, and conflicts are automatically detected if multiple people use the same ID allocation. This is much more useful than `__LINE__` because it's equally usable in a debugger or localised use, but it can also be committed or used in perpetuity.

**Comment by tobine** [comment]
FYI: I'm starting to look at a solution to this and some additional issues. Very simple/early prototype for feedback posted to #856

**Comment by tobine** [comment]
@baldurk Just pushed #1019 to master which creates unique error enums for every validation valid usage case in the spec. @karl-lunarg and I will start focused effort to make use of all these enums in existing checks, welcoming help from anyone else, of course.
There's a semi-automated flow that I will manage going forward to update enums and make sure that the same error always keeps the same enum value.
