### ISSUE TITLE
polygonMode can not be VK_POLYGON_MODE_POINT or VK_POLYGON_MODE_LINE if fillModeNonSolid is not supported.

### ISSUE THREAD

**Issue by cdwfs** [KhronosGroup/Vulkan-LoaderAndValidationLayers#785]
When creating a graphics pipeline, the `parameter_validation` layer should ensure that the `VkPipelineRasterizationStateCreateInfo.polygonMode` does not specify an unsupported polygon mode, based on the value of `VkPhysicalDeviceFeatures.fillModeNonSolid`.

(I've written the new check, and will add a negative test & submit the pull request tomorrow if all goes well)

**Comment by mark-lunarg** [comment]
Resolved by pr #843 .  Thanks all.
