### ISSUE TITLE
loader: instance WSI extensions that can be compiled out of loader falsely reported

### ISSUE THREAD

**Issue by jon-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#79]
The WSI surface extensions on Linux  are not always built into the loader. This is problematic since
if a driver reports  an extension supported you really need the loader to also support the instance
extension for it to work. 

A couple solutions:
1) On linux always compile in all four WSI surface extensions
2) Add code to loader filter out any reported instance extensoins  by ICD that also require loader support that is not built in.

I favor 2) since this is a general problem of new extensions that a ICD supports but the loader doesn't support yet (or not in the loader version one i suing.)

**Comment by ianelliottus** [comment]
I've not seen ICDs that support all of the WSI extensions that can be supported on Linux.  That means that we can't fully test them.  Other than that, is there harm in always compiling them on Linux?

**Comment by jon-lunarg** [comment]
There may be an install/packaging issue with option 1) in building an SDK with them all compiled in.

**Comment by ianelliottus** [comment]
Potentially I'm showing some ignorance.  I think that install/packaging issues need to be solved, so that ISVs can compile and link an application that will work on a variety of Linux distros and/or their favorite API.  In particular, I believe Canonical has various flavors of Ubuntu that come with X11 (i.e. XCB/Xlib) and Mir (not sure about Wayland).  I'm not sure on the priority of this, but I guess it will get in the way of ISVs sometime.

**Comment by jon-lunarg** [comment]
Also the CMake has variables for enabling or disabling the inclision of these extensions (xlib, xcb, wayland, mir) in the build of this repo. Are you suggesting we remove these CMake variables and always build all of these four extensions?  This would negatively  impact developers building this repo, as they would need to be able to install packages for getting the Mir, Wayland, etc headers.  I am not sure that these development  packages are all readily available (especially for Mir) on all Linux distros. I couldn't find Mir development packages on Fedora for example.

There is more flexibility in leaving the CMake as is so developers and Linux distro packagers can choose which of the extensions  (Xlib, Xcb, Mir, Wayland) they want to enable in their builds of the loader  and layers.  Then loader and layers should function correctly  with a given sub set of the four extensions built.

**Comment by jon-lunarg** [comment]
fixed on master branch.
