### ISSUE TITLE
Remove LunarGLASS from update_external_sources.sh?

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#8]
Without the LunarG driver in this repo, I wonder if LunarGLASS is still a necessary dependency for this repo?  It would greatly shorten build time for new users to not build LunarGLASS if it is not necessary.

**Comment by karl-lunarg** [comment]
Agreed.  See https://github.com/LunarG/VulkanTools/issues/4

**Comment by greg-lunarg** [comment]
This has now been done on both sdk-1.0.3 and master. An update_external_sources.sh has been added to VulkanTools which can be use to build LunarGLASS.
