### ISSUE TITLE
Core validation mishandles invalidation of dynamic state when a new pipeline is bound

### ISSUE THREAD

**Issue by chrisforbes** [KhronosGroup/Vulkan-LoaderAndValidationLayers#802]
Broken in various subtle ways

**Comment by chrisforbes** [comment]
Guts of this is that set_cb_pso_status only ever sets more bits.

**Comment by mark-lunarg** [comment]
@chrisforbes, was this by chance covered by PR #2004 or maybe a related change?

**Comment by chrisforbes** [comment]
This is done, closing.

**Comment by mark-lunarg** [comment]
Sweet!  Thanks.
