### ISSUE TITLE
Add ability to disable implicit layers via the application

### ISSUE THREAD

**Issue by MarkY-LunarG** [KhronosGroup/Vulkan-LoaderAndValidationLayers#806]
If a malicious or undesired implicit layer were to exist and be enabled by default, we should have some mechanism to disable that layer via the loader.

**Comment by lentinem** [comment]
Can you expand on when you expect this to be possible? It's difficult to set a priority without more info but I'm going to park it P3 for now.

**Comment by MarkY-LunarG** [comment]
I don't have a time on this just yet, so I think P3 is fine for now.  I want to take care of a few more important items first, then I'll likely get to this.

**Comment by MarkY-LunarG** [comment]
This is not what is wanted.  So killing this issue.  An external tools is what's desired.
