### ISSUE TITLE
DS: wrong 2D array view descriptor requirements

### ISSUE THREAD

**Issue by yavn** [KhronosGroup/Vulkan-LoaderAndValidationLayers#808]
I'm getting this error message:

> DS(ERROR): object: 0x2f type: 23 location: 2836 msgCode: 49: DS 0x2f encountered the following validation error at draw time: Descriptor in binding #0 at global descriptor index 0 requires an image view of type VK_IMAGE_VIEW_TYPE_3D but got VK_IMAGE_VIEW_TYPE_2D_ARRAY.

But the descriptor is set up like this:

```
// layout(set = 0, binding = 0, rgba8) uniform image2DMSArray u_msImage;

OpName %34 "u_msImage"
OpDecorate %34 DescriptorSet 0
OpDecorate %34 Binding 0
%28 = OpTypeFloat 32
%29 = OpTypeVector %28 4
%30 = OpTypePointer Function %29
%32 = OpTypeImage %28 2D 0 1 1 2 Rgba8
%33 = OpTypePointer UniformConstant %32
%34 = OpVariable %33 UniformConstant
```

I think the code in `descriptor_type_to_reqs` (core_validation.cpp) isn't correct. 2D image arrays should have an image type of 2D, not 3D (table 11.1 in Vulkan spec).

**EDIT**

Actually, this code is probably fine. The problem is with the enum.
Somehow `DESCRIPTOR_REQ_VIEW_TYPE_2D << 1` yields `DESCRIPTOR_REQ_VIEW_TYPE_3D` instead of `DESCRIPTOR_REQ_VIEW_TYPE_2D_ARRAY`.

Need to investigate this.

**Comment by yavn** [comment]
OK, got it. I think the enum is laid out in an misleading way, which lead to this bug:

```
enum descriptor_req {
    DESCRIPTOR_REQ_VIEW_TYPE_1D = 1 << VK_IMAGE_VIEW_TYPE_1D,
    DESCRIPTOR_REQ_VIEW_TYPE_1D_ARRAY = 1 << VK_IMAGE_VIEW_TYPE_1D_ARRAY,
    DESCRIPTOR_REQ_VIEW_TYPE_2D = 1 << VK_IMAGE_VIEW_TYPE_2D,
    DESCRIPTOR_REQ_VIEW_TYPE_2D_ARRAY = 1 << VK_IMAGE_VIEW_TYPE_2D_ARRAY,
    DESCRIPTOR_REQ_VIEW_TYPE_3D = 1 << VK_IMAGE_VIEW_TYPE_3D,
    DESCRIPTOR_REQ_VIEW_TYPE_CUBE = 1 << VK_IMAGE_VIEW_TYPE_CUBE,
    DESCRIPTOR_REQ_VIEW_TYPE_CUBE_ARRAY = 1 << VK_IMAGE_VIEW_TYPE_CUBE_ARRAY,

    DESCRIPTOR_REQ_SINGLE_SAMPLE = 2 << VK_IMAGE_VIEW_TYPE_END_RANGE,
    DESCRIPTOR_REQ_MULTI_SAMPLE = DESCRIPTOR_REQ_SINGLE_SAMPLE << 1,
};
```

If we fill in values from vulkan.h and reorder the bits, we get:

```
enum descriptor_req {
    DESCRIPTOR_REQ_VIEW_TYPE_1D = 1 << 0,
    DESCRIPTOR_REQ_VIEW_TYPE_2D = 1 << 1,
    DESCRIPTOR_REQ_VIEW_TYPE_3D = 1 << 2,
    DESCRIPTOR_REQ_VIEW_TYPE_CUBE = 1 << 3,
    DESCRIPTOR_REQ_VIEW_TYPE_1D_ARRAY = 1 << 4,
    DESCRIPTOR_REQ_VIEW_TYPE_2D_ARRAY = 1 << 5,
    DESCRIPTOR_REQ_VIEW_TYPE_CUBE_ARRAY = 1 << 6,

    DESCRIPTOR_REQ_SINGLE_SAMPLE = 2 << 6,
    DESCRIPTOR_REQ_MULTI_SAMPLE = DESCRIPTOR_REQ_SINGLE_SAMPLE << 1,
};
```

Take note of how 3D follows 2D. So the code in `descriptor_type_to_reqs` is incorrect after all. We should shift 4 places instead of 1. For the sake of simplicity, I'd change it to:

```
case spv::Dim2D:
    return (msaa ? DESCRIPTOR_REQ_MULTI_SAMPLE : DESCRIPTOR_REQ_SINGLE_SAMPLE) |
           (arrayed ? DESCRIPTOR_REQ_VIEW_TYPE_2D_ARRAY : DESCRIPTOR_REQ_VIEW_TYPE_2D);
```

Btw, there's a same bug here:

```
            case spv::DimCube:
                return DESCRIPTOR_REQ_VIEW_TYPE_CUBE << arrayed;
```

I can prepare a MR if you wish, but it's a small fix so you'll probably get it done faster yourself with less overhead.

**Comment by chrisforbes** [comment]
Ugh, you're right, that's bogus. I'll fix it.
