### ISSUE TITLE
No message from VK_LAYER_LUNARG_standard_validation when submitting an invalid command buffer to VkQueueSubmit

### ISSUE THREAD

**Issue by NTimmons** [KhronosGroup/Vulkan-LoaderAndValidationLayers#812]
When submitting a 'VKCommandBuffer' that has been created from a VkCommandPool with the mismatching queueFamilyIndex, VkQueueSubmit will return an invalid error code (_VK_ERROR_INITIALIZATION_FAILED on the implementation I am using_) but will not output a validation message.

**Comment by lentinem** [comment]
Duplicate of #790

**Comment by NTimmons** [comment]
Apologies for the duplicate, didnt spot the other. 

Thanks
