### ISSUE TITLE
It is too strict to mark "lack of checking something" as an error

### ISSUE THREAD

**Issue by tim37021** [KhronosGroup/Vulkan-LoaderAndValidationLayers#818]
Around here. I am using LunarG version 1.0.8 
https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/swapchain.cpp#L1684

I temporarily hard-coded queue family index.
In release mode without validation layers enabled, my program works just fine.
However, with swapchain layer enabled, I will get an error message "vkCreateSwapchainKHR() called with pCreateInfo->surface that was not returned by vkGetPhysicalDeviceSurfaceSupportKHR() for the device".
It is a unclear error message. After I checked out the source code of the layer. I finally realized it was just asking me to check if the queue family support presentation before creating swapchain.
It is not supposed to be an error if the program can run without the layers. It should be warning instead in my opinion.

**Comment by tobine** [comment]
@tim37021 this was changed to a warning a while ago. Please update to latest LunarG SDK when possible.
Also, "It is not supposed to be an error if the program can run without the layers" is an incorrect statement. The layers are enforcing the specification. There are plenty of Vulkan programs that may run on one device yet still be in violation of the specification and crash on other, untested devices.

**Comment by tim37021** [comment]
I see, yet I think the error message can be better. I could not understand when I first saw it. Because I was thinking "vkGetPhysicalDeviceSurfaceSupportKHR() won't return surface to me. there would be some mistake on the error message." Maybe I am not good at English, which led to misunderstanding, how do you think about this message?

**Comment by tobine** [comment]
Sorry @tim37021, I mistakenly thought this was referencing another message. This error message is still the same and I agree that it could perhaps be updated. Assigning to swapchain owner.
@ianelliottus please take a look at Tim's request.

**Comment by tim37021** [comment]
@tobine will it be a warning or remain an error?

In the parameter description,
"surface must be a surface that is supported by the device as determined using vkGetPhysicalDeviceSurfaceSupportKHR".
I thought the spec was not enforcing us to call vkGetPhysicalDeviceSurfaceSupportKHR() before initialize VkSwapchainCreateInfoKHR. That's why I stuck for a while. I was pretty surprised after I found what's going on, actually.

**Comment by ianelliottus** [comment]
Let me try a new version of the error message:

> The surface in pCreateInfo->surface, that was given to vkCreateSwapchainKHR(), must be a surface that is supported by the device as determined by vkGetPhysicalDeviceSurfaceSupportKHR().  However, vkGetPhysicalDeviceSurfaceSupportKHR() was never called with this surface.

Is this error message better?  Is it good enough?

**Comment by ianelliottus** [comment]
See https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/825

**Comment by ianelliottus** [comment]
Sorry if I am going to quick.  Assuming the new error is good enough (already pushed), I'm going to close this issue.  Please re-open if you want different wording.
