### ISSUE TITLE
Core validation broken when using non-coherent memory

### ISSUE THREAD

**Issue by gary-sweet** [KhronosGroup/Vulkan-LoaderAndValidationLayers#819]
The core validation layer uses a shadow copy of memory during MapMemory and FlushMappedMemoryRanges. It adds guard regions to the front and end so that it can detect buffer overwrites.

Unfortunately, it doesn't copy data back again during InvalidateMappedMemoryRanges. This means that any memory you read back does not reflect the current state of device memory.

**Comment by tobine** [comment]
@karl-lunarg Assigning these memory issues to you. Re-assign as appropriate.

**Comment by mark-lunarg** [comment]
Gary, can you try #852 ?  Also for issues #820 and #822.

**Comment by mark-lunarg** [comment]
Fix pushed to Master.

commit 9e21e56fc23ade48efd3752d2e2729895eb90349
Author: Mark Lobodzinski <mark@lunarg.com>
Date:   Tue Aug 16 09:06:15 2016 -0600

    layers: GH819, Fix non-coherent memory shadow copy

    InvalidateMappedMemoryRanges was not updating core validation's
    shadow copy of non-coherent memory.

    Change-Id: I7b5e05791405871489014d6b08595c9bae941185
