### ISSUE TITLE
validation layer not checking pWaitDstStageMask in VkSubmitInfo

### ISSUE THREAD

**Issue by Ashalah** [KhronosGroup/Vulkan-LoaderAndValidationLayers#82]
According to the spec, if waitSemaphoreCount is not 0, then pWaitDstStageMask must be a valid pointer to an array, but my current prebuilt LunarG SDK (1.0.3.1) does not report anything in the case that pWaitDstStageMask is null and waitSemaphoreCount > 0.

**Comment by dustin-lunarg** [comment]
The param_checker validation layer included with the 1.0.3 SDK did not perform NULL checks on struct members.  I have submitted change [af0d6dc](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/commit/af0d6dc3237346933fb9da9cb13d414bf46cf664) to address this issue.  I tested this case and now see the following validation message:
    PARAMCHECK: vkQueueSubmit: required parameter pSubmits->pWaitDstStageMask specified as NULL

This change will be included in the next LunarG SDK release.
