### ISSUE TITLE
Core validation needs to respect alignment constraints for MapMemory shadow copy

### ISSUE THREAD

**Issue by gary-sweet** [KhronosGroup/Vulkan-LoaderAndValidationLayers#820]
The core validation layer has a shadow copy of non-coherent mapped memory regions. When it mallocs the shadow region (in initializeAndTrackMemory) it does not respect the alignment constraints that exist for the real device memory (e.g. minMemoryMapAlignment, nonCoherentAtomSize) so the CPU pointer that is returned does not match the alignment constraints that are expected.

This is causing some of our tests (which validate the alignment of the returned pointer) to fail.

**Comment by mark-lunarg** [comment]
Can you give us a summary of what platform/hardware you are on, and what the available memory types are for your setup?  The systems we have at-hand only appear to support HOST_VISIBLE AND COHERENT.

**Comment by mark-lunarg** [comment]
Gary, I have a potential fix for this issue and believe that this memory type should be supported on our shield TV.  I need to work up a test case for it before we continue, but the fix should be coming along shortly.

**Comment by gary-sweet** [comment]
This is our own internal driver development for our set-top-box platforms.

We have memory types which include (HOST_VISIBLE | HOST_COHERENT) but also (HOST_VISIBLE | HOST_CACHED).

Thanks
Gary

**Comment by mark-lunarg** [comment]
See PR #852.

**Comment by gary-sweet** [comment]
This fix doesn't quite work yet. See my comments in PR #852.

**Comment by mark-lunarg** [comment]
Fixed by #852 .  Thanks!
