### ISSUE TITLE
Core validation FlushMappedMemoryRanges and InvalidateMappedMemoryRanges don't handle mapped memory where size was VK_WHOLE_SIZE

### ISSUE THREAD

**Issue by gary-sweet** [KhronosGroup/Vulkan-LoaderAndValidationLayers#822]
If you map memory with a range size of VK_WHOLE_SIZE, subsequent calls to vkFlushMappedMemoryRanges and vkInvalidateMappedMemoryRanges also with VK_WHOLE_SIZE will overflow the shadow buffer and/or crash.

**Comment by mark-lunarg** [comment]
As for #820 , we have a potential fix for this issue and believe that this memory type should be supported on our shield TV.  After we have a repro case on that HW we'll make sure it works.

**Comment by mark-lunarg** [comment]
See PR #852.

**Comment by mark-lunarg** [comment]
Fix pushed to Master.

commit eefe1df8a93c1cbfb1815488501c61d9e57515ea
Author: Mark Lobodzinski <mark@lunarg.com>
Date:   Mon Aug 15 15:00:12 2016 -0600

    layers: GH822, handle WHOLE_SIZE for mapped memory

    A support routine for FlushMappedMemoryRanges and InvalidateMapped-
    MemoryRanges ignored VK_WHOLE_SIZE, causing invalid memory accesses.

    Change-Id: I28616faa1339a394a3462e72780efd1b852ac489
