### ISSUE TITLE
Binding a copy of a descriptor set issues warning/error about it not beeing updated.

### ISSUE THREAD

**Issue by marius-luca-87** [KhronosGroup/Vulkan-LoaderAndValidationLayers#83]
When binding a descriptor set that was creating using copied elements from other descriptor sets the validation layer output warningss/error:

[DS] Code 44 : DS 0x2a7ab888a60 bound but it was never updated. You may want to either update it or not bind it.
[DS] Code 44 : DS 0x2a7ab888a60 bound but it was never updated. It is now being used to draw so this will result in undefined behavior.

By looking at https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/draw_state.cpp it looks like validation is done by checking if "pSet->pUpdateStructs != nullptr". 
pUpdateStructs never gets created when doing a copy from another descriptor set.

**Comment by tobine** [comment]
I know there are a few holes in validation of copied descriptor sets.

Mark, if you haven't looked at this, feel free to assign it to me.

**Comment by mark-lunarg** [comment]
All yours!

**Comment by tobine** [comment]
Just pushed a fix for this to master.
There's still some issues with how copy descriptor updates are handled in draw_state, but current fix handles this specific issue by copying descriptor update state from src descriptor set to dst set.
