### ISSUE TITLE
Core Validation: False error on use of VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL for depth target on render pass create

### ISSUE THREAD

**Issue by TiemoJung** [KhronosGroup/Vulkan-LoaderAndValidationLayers#832]
Hi,

while creating a render pass that uses one color attachment and on depth target, where the depth attachment is set to the VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL layout the core validation layer reports: "Layout for depth attachment is VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL but can only be DEPTH_STENCIL_ATTACHMENT_OPTIMAL or GENERAL". 

As it seems the checks in ValidateLayouts does not check for VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL for depth stencil attachments, only for input attachments.

Tested with a63ca9584235113103a10fd33b5d3abbb41431d1

**Comment by chrisforbes** [comment]
Fixed by #833.
