### ISSUE TITLE
Validation Layer does not catch when non-aligned MappedMemoryRange passed through vkFlushMappedMemoryRanges

### ISSUE THREAD

**Issue by ardaLunarG** [KhronosGroup/Vulkan-LoaderAndValidationLayers#836]
By Spec VkMappedMemoryRange Valid Usage: 
If size is not equal to VK_WHOLE_SIZE, size must be a multiple of VkPhysicalDeviceLimits::nonCoherentAtomSize

When non-aligned MappedMemoryRange passed through vkFlushMappedMemoryRanges, validation layer does not catch.

Issue is reproducible in Hologram application in LunarG/VulkanSamples by reverting the following patch which does the alignment for flush:
https://github.com/LunarG/VulkanSamples/commit/8a8094637cab67b619de3d3ed50a8501d783f60c

I don't have reproduction case but same might apply to vkInvalidateMappedMemoryRanges.

**Comment by mikew-lunarg** [comment]
This corresponds to Valid Usage VALIDATION_ERROR_00645, which is currently marked as check_implemented=Y.
Will investigate and close if already complete.

**Comment by mikew-lunarg** [comment]
Appears to have been addressed in Nov 2016 by PR #1157
