### ISSUE TITLE
demos/tri.c: VkAllocationCallbacks is broken

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-LoaderAndValidationLayers#84]
demos/tri.c implements VkAllocationCallbacks with aligned_alloc/_aligned_malloc, free/_aligned_free, and realloc.

I belive that is broken in many ways:

* realloc does not return a pointer with the necessary alignment.
* realloc(_aligned_malloc(...)) crashes.
* _aligned_free(realloc(...)) crashes.
* aligned_alloc requires that size must be a multiple of alignment, while Vulkan provides no such guarantee to these callbacks.
* On POSIX-based implementations, aligned_alloc requires that alignment must be a multiple of sizeof(void *) as well as a power of two, while Vulkan merely requires it to be a power of two.
* aligned_alloc(0), realloc(p, 0) might return non-NULL, while I think Vulkan requires NULL.
* _aligned_malloc(0, a) is documented to invoke the invalid parameter handler (although I'm not sure it actually does in practice).

Implementing a valid allocator is quite non-trivial, so it may be best to just delete the allocator entirely from the demo.

(See also https://github.com/KhronosGroup/Vulkan-Docs/issues/21 and https://github.com/KhronosGroup/Vulkan-Docs/issues/103 for related discussions.)

**Comment by Tony-LunarG** [comment]
I've removed the allocation callbacks from the tri demo.  Thanks.
