### ISSUE TITLE
Running build from msys shell breaks python scripts

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-LoaderAndValidationLayers#850]
In `vulkan.py` the code checks for `sys.platform` to start with `win32` to identify windows, but if the shell used to invoke cmake originally is an msys shell, any python binary from msys will be picked up first so when python is invoked in cmake rules like for generating vulkan-1.def then `sys.platform` will equal `msys`.

**Comment by MarkY-LunarG** [comment]
Are you suggesting we change to this?

@@ -1276,7 +1276,7 @@ if sys.argv[1] == 'AllPlatforms':

 else :
     if len(sys.argv) > 3:
-        if sys.platform.startswith('win32') and sys.argv[1] != 'Android':
+        if (sys.platform.startswith('win32') or sys.platform.startswith('msys')) and sys.argv[1] != 'Android':
             extensions = [core, ext_khr_surface, ext_khr_device_swapchain, ext_khr_win32_surface, ext_khr_display]
             extensions_all = [core, ext_khr_surface, ext_khr_device_swapchain, ext_khr_win32_surface, ext_khr_display, lunarg_debug_report]
         elif sys.platform.startswith('linux') and sys.argv[1] != 'Android':
@@ -1286,7 +1286,7 @@ else :
             extensions = [core, ext_khr_surface, ext_khr_device_swapchain, ext_khr_android_surface]
             extensions_all = [core, ext_khr_surface, ext_khr_device_swapchain, ext_khr_android_surface, lunarg_debug_report]
     else :
-        if sys.argv[1] == 'Win32':
+        if sys.argv[1] == 'Win32' or sys.argv[1] == 'msys':
             extensions = [core, ext_khr_surface, ext_khr_device_swapchain, ext_khr_win32_surface, ext_khr_display]
             extensions_all = [core, ext_khr_surface, ext_khr_device_swapchain, ext_khr_win32_surface, ext_khr_display, lunarg_debug_report]
         elif sys.argv[1] == 'Android':

**Comment by baldurk** [comment]
Yes I think something like that would work for my case. It's up to you whether you actually want to support it or not, but the compile errors you get are quite strange to diagnose so I think at least trying to detect it and bail out would be nice.

**Comment by MarkY-LunarG** [comment]
If you want, I just pushed a commit into the marky_working branch ( cce5624fa1e28ac44ad24993f566f9a52f595e21).  If you get a chance, can you try that?

**Comment by baldurk** [comment]
I presume you mean 544c06833f44ed051809bc5c9356439c59696ba3 rather, but yes this works for me now. Thank you very much!

**Comment by MarkY-LunarG** [comment]
<Sigh> That's what happens when you've got 4 tasks running simultaneously.  I'll commit that.  Thanks for verifying.
