### ISSUE TITLE
Loader doesn't handle wrapping debug report callbacks

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-LoaderAndValidationLayers#851]
The dispatch chain for `CreateDebugReportCallback` goes from `application` &rarr; `debug_report_CreateDebugReportCallback` &rarr; `layers...` &rarr; `terminator_CreateDebugReportCallback` which calls into the ICD.

Inside `debug_report_CreateDebugReportCallback` on successful return, the callback is inserted into a linked list of live callbacks, with the function from the matching `VkDebugReportCallbackCreateInfoEXT` as the function to call. This is used for internal messages the loader sends off, as well as anything that calls `vkDebugReportMessageEXT` (which is implemented by the loader).

The problem is that this doesn't account for layers potentially changing and wrapping debug report callbacks. E.g. If a layer wants to add some annotation to all messages before passing them back to the application, or in my case my layer will suppress and discard all messages to prevent them from reaching the application.

So what happens is my layer and anything downstream (including ICD, if such messages exist) will go through the right callback function, but the loader will go directly to the unwrapped application's callback. This is an inconsistency - a minor one for the loader, but a more significant one for messages inserted by `vkDebugReportMessageEXT`.

I'm not sure exactly what the fix would be - you need to have the `VkDebugReportCallbackCreateInfoEXT` that is specified in the terminator to get the 'fully wrapped' callback function. But the resulting `VkDebugReportCallbackEXT` and `VkResult` needs to come from `debug_report_CreateDebugReportCallback`. Perhaps the new node could be created temporarily in the terminator, and upon successful return it could be filled out with the resulting callback object and enqueued - otherwise if there's a failure, it's deleted. Or maybe just a temporary member of the `struct loader_instance` so there's no need for allocation.

**Comment by MarkY-LunarG** [comment]
Can you try the code I put in marky_gh851_debugreport?  I believe I've made the changes you desire.

**Comment by baldurk** [comment]
That branch seems to do the trick from my quick testing :+1:.

**Comment by MarkY-LunarG** [comment]
Pushed up in commit 4b0c7df3980851c6e872437860ac88a98b34c8c5
