### ISSUE TITLE
Error message for VK_DYNAMIC_STATE_SCISSOR when isn't set

### ISSUE THREAD

**Issue by dankbaker** [KhronosGroup/Vulkan-LoaderAndValidationLayers#859]
I'm getting this message even though I _didn't_ set state VK_DYNAMIC_STATE_SCISSOR.

```
ParameterValidation (ERROR): object: 0x0 type: 0 location: 2868 msgCode: 4: vkCreateGraphicsPipelines: if pCreateInfos[0].pDynamicState->pDynamicStates contains VK_DYNAMIC_STATE_SCISSOR, pCreateInfos[0].pViewportState->scissorCount must be greater than 0
ParameterValidation (ERROR): object: 0x0 type: 0 location: 2880 msgCode: 4: vkCreateGraphicsPipelines: if pCreateInfos[0].pDynamicState->pDynamicStates contains VK_DYNAMIC_STATE_SCISSOR, pCreateInfos[0].pViewportState->pScissors must not be NULL
```

This is the code I used 
```     
    VkDynamicState DynamicStateEnables[VK_DYNAMIC_STATE_RANGE_SIZE];
    DynamicStateEnables[0] = VK_DYNAMIC_STATE_VIEWPORT;
    VkPipelineDynamicStateCreateInfo dynamicState;
    memset(&dynamicState, 0, sizeof dynamicState);
    dynamicState.sType = VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO;
    dynamicState.pDynamicStates = DynamicStateEnables;
    dynamicState.dynamicStateCount = 1;
```

and validated in debugger that enum isn't in the pipeline create structure during shader creation.

**Comment by tobine** [comment]
The error message is incorrectly worded, but the errors are correct. The first part of the error statement is backwards and should actually state:

`if pCreateInfos[0].pDynamicState->pDynamicStates does not contains VK_DYNAMIC_STATE_SCISSOR`

See spec section "9.2 Graphics Pipelines" valid usage for VkGraphicsPipelineCreateInfo struct:

`If no element of the pDynamicStates member of pDynamicState is VK_DYNAMIC_STATE_SCISSOR, the pScissors member of pViewportState must be a pointer to an array of pViewportState→scissorCount VkRect2D structures`

I will update the error messages.

**Comment by tobine** [comment]
Fix was cherry-picked and pushed to master
