### ISSUE TITLE
Improve parameter checking for vkQueueSubmit

### ISSUE THREAD

**Issue by tim37021** [KhronosGroup/Vulkan-LoaderAndValidationLayers#861]
```cpp
vkQueueSubmit(device, queue, 1, &submit, VK_NULL_HANDLE);
vkQueueWaitIdle(queue);
```
If the queue does not belong to the device or it does not support some of the operations in the sent command buffers. Validator will report error at vkQueueWaitIdle "returned VK_ERROR_DEVICE_LOST, indicating that the logical device has been lost". which is actually resulted from incorrect parameter of vkQueueSubmit.

**Comment by lentinem** [comment]
What branch is being used? PR #840 addressed a similar issue and it would be good to know if that also addresses yours.

**Comment by stroyan** [comment]
Did you have VK_LAYER_LUNARG_object_tracker active?
I would expect it to report "Invalid Queue" because
 ```vkQueueSubmit(device, queue, 1, &submit, VK_NULL_HANDLE);```
was given a device parameter that it doesn't take.  It should be 
``` C
VkResult vkQueueSubmit(
    VkQueue                                     queue,
    uint32_t                                    submitCount,
    const VkSubmitInfo*                         pSubmits,
    VkFence                                     fence);
```

**Comment by tim37021** [comment]
@lentinem 
I am using the lastest version 1.0.21.1 SDK downloaded from LunarG offical website.
@stroyan 
I've enabled standard validation layer, so VK_LAYER_LUNARG_object_tracker should be included.
Yeah, just a mistake on in the post.
In my code it is correctly called can be compiled.

**Comment by lentinem** [comment]
If you sync to master this problem should be resolved but the fix would not have been in the SDK version. It should be included in the next release so I'm going to close but if you feel that is not sufficient feel free to re-open.
