### ISSUE TITLE
Wrong vk_format_table sizes for ETC2/EAC RGBA8888 formats?

### ISSUE THREAD

**Issue by sg-brcm** [KhronosGroup/Vulkan-LoaderAndValidationLayers#873]
The format table entries in vk_layer_utils.cpp set the size for the two ETC2/EAC RGBA8888 formats to 8 bytes (64bits). However the khronos dataformat specification states they are 128bit blocks (to accommodate the full alpha), so I was expecting this table to say 16 bytes as for ASTC.

This is causing a validation failure when doing an image copy to an uncompressed 128bit class color format, which I expected to be compatible with these compressed formats. Have I misunderstood or is the table wrong?

Specifically the two entries in question are:
    {8, 4, VK_FORMAT_COMPATIBILITY_CLASS_ETC2_EAC_RGBA_BIT}, //  [VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK]
    {8, 4, VK_FORMAT_COMPATIBILITY_CLASS_ETC2_EAC_RGBA_BIT}, // [VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK]

**Comment by mark-lunarg** [comment]
See PR #875 .

**Comment by mark-lunarg** [comment]
Pushed to Master.  Thanks!

**Comment by sg-brcm** [comment]
Thanks for quick response.
