### ISSUE TITLE
vk_layer.h layer dispatch tables is missing a function

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-LoaderAndValidationLayers#874]
The instance layer dispatch table `struct VkLayerInstanceDispatchTable` in `vk_layer.h` has the functions from `VK_KHR_display` - `GetDisplayModePropertiesKHR`, `CreateDisplayPlaneSurfaceKHR` and others.

However the matching `struct VkLayerDispatchTable` is missing the function from the matching `VK_KHR_display_swapchain` - `CreateSharedSwapchainsKHR`.

I don't remember exactly if this is an ABI-significant struct or just informational/convenience, for now I've just appended it to my local copy, but I think either way this should be fixed upstream.

**Comment by MarkY-LunarG** [comment]
This requires updating the Layer interface version and should be evaluated so that we add all extension entry points simultaneously.  I.e. Not for the faint of heart.

**Comment by mark-lunarg** [comment]
Assigned back to MarkY.  This needs to go in a coordinated-versioned update which will take a bit of planning.

**Comment by MarkY-LunarG** [comment]
I created issue #888 to track other items that have come up and also list out a few of the concerns.  Nvidia has also expressed an interest in these changes, hence the creation of a common issue which can track the whole problem set.  Baldur, if you find any other extensions that you'd like to add as this push, please just add them to that issue.  Closing this issue for now.
