### ISSUE TITLE
Validation should check offset & size for vkFlushMappedMemoryRanges and vkInvalidateMappedMemoryRanges

### ISSUE THREAD

**Issue by courtney-g** [KhronosGroup/Vulkan-LoaderAndValidationLayers#879]
When using non-coherent, mapped memory, if an application does not align the memory regions to VkPhysicalDeviceLimits::nonCoherentAtomSize the application may not get what it wants.
Validation layer could check and report a warning in this case.

From Gitlab issue 285.

**Comment by mikew-lunarg** [comment]
Possible dup of #836 
Corresponds to Valid Usages VALIDATION_ERROR_00644 and VALIDATION_ERROR_00645, which are both marked as check_implemented=Y.

**Comment by mikew-lunarg** [comment]
Appears to have been addressed in Nov 2016 by PR #1157
