### ISSUE TITLE
Queue family check in ValidateBarriers possibly wrong

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-LoaderAndValidationLayers#88]
I think the code [starting here](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/draw_state.cpp#L6610) in ValidateBarriers is missing a logic path. It checks first that src and dst queue family must either both be `VK_QUEUE_FAMILY_IGNORED` or both be valid queues.

That is fine, but then it does "else validate that both indices are in range". This means that the case where `src == dst == VK_QUEUE_FAMILY_IGNORED` goes through to the else if and is going to definitely be `>= dev_data->physDevProperties.queue_family_properties.size()`.

I think either the second check should check that `src != VK_QUEUE_FAMILY_IGNORED && dst != VK_QUEUE_FAMILY_IGNORED`

**Comment by mark-lunarg** [comment]
Will take a look at this shortly.

**Comment by mark-lunarg** [comment]
Fix pushed to Master.  Thanks Baldur.
