### ISSUE TITLE
Improving the "A dependency must exist but one is not specified" debug call-back

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#884]
Consider a renderpass X which is built of 2 subpasses. Each subpass uses different fragment & vertex shaders, but they both render to the same attachment. The draw calls fired from within these subpasses render to non-overlapping locations in screen space, so I'm assuming no subpass dependency is needed to synchronize execution of both subpasses.

At vkCmdBeginRenderPass() call time, I'm being informed by Core Validation layer that "A dependency between subpasses 0 and 1 must exist but one is not specified" and "A dependency between subpasses 1 and 0 must exist but one is not specified". This is being reported as an error.

Now, I understand that there's no feasible way for the layer to determine the draw calls do not rasterize geometry to overlapping locations. However, the debug callback's level indicates a pretty serious situation, whereas in the discussed use case it's plainly wrong.

Can we consider either reducing the level of the call-back to a warning, or changing the message to indicate the call-back may be wrong if subpasses are actually permitted to be executed in parallel?

**Comment by TobiasHector** [comment]
Dominik - this is explicitly disallowed by the specification, the loader and validation layers are behaving correctly:

```
As stated earlier, render passes must include subpass dependencies which (either directly or via a subpass dependency chain) separate any two subpasses that operate on the same attachment or aliasing attachments, if at least one of those subpasses writes to the attachment. ...
```

**Comment by DominikWitczakAMD** [comment]
Gotcha. Thanks for spotting this.
