### ISSUE TITLE
Excessive vkCmdNextSubpass() calls crash Core Validation layer

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#885]
Here's an example call stack from what happens: (the renderpass in the example defines 2 subpasses, but vkCmdNextSubpass() attempts to move from the last valid subpass to a non-existant one):

![image](https://cloud.githubusercontent.com/assets/17761066/17971021/52c7ac76-6ad9-11e6-9800-a7005a63555b.png)

![image](https://cloud.githubusercontent.com/assets/17761066/17971011/3faba23c-6ad9-11e6-8172-96b1829f7f7f.png)

![image](https://cloud.githubusercontent.com/assets/17761066/17971054/6fe03ec2-6ad9-11e6-8abc-58787c48e76a.png)

**Comment by chrisforbes** [comment]
@mark-lunarg do you want this and #886?
