### ISSUE TITLE
Core Validation: Invalid "Descriptor in binding #X at global descriptor index Y requires an image view of type (none) but got VK_IMAGE_TYPE_.." error debug call-back fired at draw call time

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#890]
I'm seeing an interesting, yet presumably invalid, error call-back if my vertex shader uses input attachments:

![image](https://cloud.githubusercontent.com/assets/17761066/17996129/12208c40-6b67-11e6-9a1d-f3e4c268962d.png)

![image](https://cloud.githubusercontent.com/assets/17761066/17996148/2cdab614-6b67-11e6-82c6-04c66d02cf86.png)

![image](https://cloud.githubusercontent.com/assets/17761066/17996156/3c6d91d2-6b67-11e6-8f42-abc907393925.png)

If this matters, the shader defines two input attachments and two color attachments, each binding pointed at the same tuple of images. Might also be useful to point out I'm using a copy of validation layers taken yesterday from the master branch.

I can provide a Windows binary which reproduces this issue.

**Comment by tobine** [comment]
@chrisforbes can you take a look at this first? In a quick check it seems like we're gathering descriptor_req from all shader stages in validate_pipeline_shader_stage() but is there some hole related to VS?

**Comment by chrisforbes** [comment]
Yeah, we're not quite doing the right thing here. I'll fix.

**Comment by chrisforbes** [comment]
@tobine this check produced a false positive if there was /no/ view type requirement coming out of SC.

**Comment by chrisforbes** [comment]
Fixed in master.
