### ISSUE TITLE
Object tracker validation for vkGetDisplayModePropertiesKHR checks wrong ID

### ISSUE THREAD

**Issue by Themaister** [KhronosGroup/Vulkan-LoaderAndValidationLayers#897]
Validation layers assert on that the ID returned by driver in GetDisplayModeProperties doesn't exist, because it checks unique_id_mapping.

The fix seems to be a reverse mapping from driver ID -> unique ID instead.
Overall VK_KHR_display seems fairly incomplete as the VkSurfaceKHR created isn't recognized by the object tracking layer as a surface.

**Comment by lentinem** [comment]
Ian can you take a quick look at this and see what you think?

**Comment by mark-lunarg** [comment]
This coverage hasn't yet been added to object tracker.

**Comment by ianelliottus** [comment]
Sorry.  I didn't add support for VK_KHR_display.  Incomplete support went in, contrary to my feedback.  This is desktop-only functionality, that involves not having a window system; and is for setups that I don't have.  As such, I'm assigning this back to LunarG.  Again, sorry.

**Comment by mark-lunarg** [comment]
Have a patch series ready to go, but have to wait for a header bug to be fixed.  The two new objects for this extension have not yet been added to the VkDebugReportObjectTypeEXT enum.  See [vulkan-docs issue](https://github.com/KhronosGroup/Vulkan-Docs/issues/408).

**Comment by mark-lunarg** [comment]
Fixed by merge request #1257.
