### ISSUE TITLE
Link to vk_layer_settings.txt broken

### ISSUE THREAD

**Issue by tambry** [KhronosGroup/Vulkan-LoaderAndValidationLayers#9]
A link to the _vk_layer_settings.txt_ is broken in this [README](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/sdk-1.0.3/layers/README.md).
It seems to include an unnecessary extra "layers/"

**Comment by karl-lunarg** [comment]
Thanks for letting us know!  Fix applied manually to master.
