### ISSUE TITLE
loader: Add support for WSI VK_KHR_display_swapchain extension

### ISSUE THREAD

**Issue by jon-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#90]
Since this is a device extension, normally loader support is not required. However, since the entry points for WSI extensions are documented as statically exported by the loader in the Vulkan spec. The loader needs to have trampoline code for this extension.

**Comment by MarkY-LunarG** [comment]
This change will require layer versioning.  That's being discussed separately for now.  I'll keep this open since once that issue is resolved, we'll add this set of entry-points first.

**Comment by MarkY-LunarG** [comment]
Moving this to issue #888 since there are a few more extensions now to add.
