### ISSUE TITLE
Loader incorrectly handles multiple installed windows ICDs

### ISSUE THREAD

**Issue by MarkMLunarG** [KhronosGroup/Vulkan-LoaderAndValidationLayers#901]
On Windows 10, when a user installs and uses a graphics device from NVidia, and then switches to, installs, and uses an AMD graphics device (by physically removing and replacing graphics cards), the Vulkan Loader still attempts to use the NVidia Vulkan driver for Vulkan graphics.

A suitable workaround is to edit the Nvidia entry in the windows registry point such that it points to an invalid json file name: HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\Drivers

**Comment by courtney-g** [comment]
Hmm. I would expect that both the AMD and NVIDIA ICDs get called at vkCreateInstance, but when doing the vkEnumeratePhysicalDevices you should only see an AMD device since that is all that's available. When the loader calls the NVIDIA device for it's PhysicalDevices it should get a NULL list.

**Comment by MarkMLunarG** [comment]
The full ICD sequence I traversed on the given target was Intel -> AMD -> NVidia -> AMD. With Intel -> AMD I did not have an issue early on but ultimately had to expunge the Intel Vulkan driver due to known stability issues. No issues were observed going from AMD to NVidia, but NVidia back to AMD exposed the problem.

**Comment by courtney-g** [comment]
Are you saying that you get NVIDIA PhysicalDevices when calling vkEnumeratePhysicalDevices on the NVIDIA ICD, despite having removed the NVIDIA card?
I'm still confused as to what's actually going wrong.

**Comment by MarkMLunarG** [comment]
I haven't done any looking into the problem. With the NVidia card replaced with an AMD, and without any changes to the windows registry, this is the output to VulkanInfo:

===========
VULKAN INFO
===========

Vulkan API Version: 1.0.24

INFO: [loader] Code 0 : Found manifest file C:\Development\Projects\Vulkan\Build\Debug\Vulkan-LoaderAndValidationLayers\layers\VkLayer_core_validation.json, version "1.0.0"
INFO: [loader] Code 0 : Found manifest file C:\Development\Projects\Vulkan\Build\Debug\Vulkan-LoaderAndValidationLayers\layers\VkLayer_device_limits.json, version "1.0.0"
INFO: [loader] Code 0 : Found manifest file C:\Development\Projects\Vulkan\Build\Debug\Vulkan-LoaderAndValidationLayers\layers\VkLayer_image.json, version "1.0.0"
INFO: [loader] Code 0 : Found manifest file C:\Development\Projects\Vulkan\Build\Debug\Vulkan-LoaderAndValidationLayers\layers\VkLayer_object_tracker.json, version "1.0.0"
INFO: [loader] Code 0 : Found manifest file C:\Development\Projects\Vulkan\Build\Debug\Vulkan-LoaderAndValidationLayers\layers\VkLayer_parameter_validation.json, version "1.0.0"
INFO: [loader] Code 0 : Found manifest file C:\Development\Projects\Vulkan\Build\Debug\Vulkan-LoaderAndValidationLayers\layers\VkLayer_swapchain.json, version "1.0.0"
INFO: [loader] Code 0 : Found manifest file C:\Development\Projects\Vulkan\Build\Debug\Vulkan-LoaderAndValidationLayers\layers\VkLayer_threading.json, version "1.0.0"
INFO: [loader] Code 0 : Found manifest file C:\Development\Projects\Vulkan\Build\Debug\Vulkan-LoaderAndValidationLayers\layers\VkLayer_unique_objects.json, version "1.0.0"
INFO: [loader] Code 0 : Found manifest file C:\Program Files\RenderDoc\renderdoc.json, version "1.0.0"
INFO: [loader] Code 0 : Found manifest file C:\WINDOWS\system32\nv-vk64.json, version "1.0.0"
INFO: [loader] Code 0 : Found manifest file C:\WINDOWS\System32\amd-vulkan64.json, version "1.0.0"
INFO: [loader] Code 0 : Found manifest file C:\WINDOWS\system32\nv-vk64.json, version "1.0.0"
INFO: [loader] Code 0 : Insert instance layer VK_LAYER_LUNARG_core_validation (C:\Development\Projects\Vulkan\Build\Debug\Vulkan-LoaderAndValidationLayers\layers\.\VkLayer_core_validation.dll)
INFO: [loader] Code 0 : Insert instance layer VK_LAYER_LUNARG_parameter_validation (C:\Development\Projects\Vulkan\Build\Debug\Vulkan-LoaderAndValidationLayers\layers\.\VkLayer_parameter_validation.dll)
INFO: [loader] Code 0 : Insert instance layer VK_LAYER_NV_optimus (nvoglv64.dll)
WARNING: [loader] Code 0 : ICD ignored: failed to CreateInstance in ICD 1
C:\Development\Projects\Vulkan\Vulkan-LoaderAndValidationLayers\demos\vulkaninfo.c:677: failed with VK_ERROR_INITIALIZATION_FAILED

**Comment by courtney-g** [comment]
Ah, very interesting.
I'll bet that the VK_LAYER_NV_optimus is what's causing the issue. It's probably expecting to find an NVIDIA ICD and throws an error when it can't find one.

**Comment by pdaniell-nv** [comment]
The VK_LAYER_NV_optimus layer shouldn't need an NVIDIA device to work. In fact the vkCreateInstance() implementation does nothing special except to hook into the call chain just like all layers do. The only way it could return VK_ERROR_INITIALIZATION_FAILED is if chainVkCreateIntance=chainInfo->u.pLayerInfo->pfnNextGetInstanceProcAddr("vkCreateInstance") fails or chainVkCreateIntance() returns it.

Still, there may be something unexpected going on we need to debug the loader to see which layers and/or ICDs aren't behaving as expected.

**Comment by MarkY-LunarG** [comment]
Mark, a quick test would be to go to the broken scenario and disable the NV_optimus layer.  You can do this by creating a global variable "DISABLE_LAYER_NV_OPTIMUS_1" and setting it to 1.  Or go into the registry [HKEY_LOCAL_MACHINE_SOFTWARE\khronos\vulkan\implicitlayers] and removing it from the list.  If that fixes the issue, I'd be more inclined to think it is an optimus layer issue.  If it doesn't fix the issue, build a debug loader, and we can add an assert and track it down.

**Comment by MarkMLunarG** [comment]
Changing the implicitlayer value did not resolve the problem. This is the output after that:
===========
VULKAN INFO
===========

Vulkan API Version: 1.0.24

INFO: [loader] Code 0 : Found manifest file C:\Development\Projects\Vulkan\Build\Debug\Vulkan-LoaderAndValidationLayers\layers\VkLayer_core_validation.json, version "1.0.0"
INFO: [loader] Code 0 : Found manifest file C:\Development\Projects\Vulkan\Build\Debug\Vulkan-LoaderAndValidationLayers\layers\VkLayer_device_limits.json, version "1.0.0"
INFO: [loader] Code 0 : Found manifest file C:\Development\Projects\Vulkan\Build\Debug\Vulkan-LoaderAndValidationLayers\layers\VkLayer_image.json, version "1.0.0"
INFO: [loader] Code 0 : Found manifest file C:\Development\Projects\Vulkan\Build\Debug\Vulkan-LoaderAndValidationLayers\layers\VkLayer_object_tracker.json, version "1.0.0"
INFO: [loader] Code 0 : Found manifest file C:\Development\Projects\Vulkan\Build\Debug\Vulkan-LoaderAndValidationLayers\layers\VkLayer_parameter_validation.json, version "1.0.0"
INFO: [loader] Code 0 : Found manifest file C:\Development\Projects\Vulkan\Build\Debug\Vulkan-LoaderAndValidationLayers\layers\VkLayer_swapchain.json, version "1.0.0"
INFO: [loader] Code 0 : Found manifest file C:\Development\Projects\Vulkan\Build\Debug\Vulkan-LoaderAndValidationLayers\layers\VkLayer_threading.json, version "1.0.0"
INFO: [loader] Code 0 : Found manifest file C:\Development\Projects\Vulkan\Build\Debug\Vulkan-LoaderAndValidationLayers\layers\VkLayer_unique_objects.json, version "1.0.0"
INFO: [loader] Code 0 : Found manifest file C:\Program Files\RenderDoc\renderdoc.json, version "1.0.0"
ERROR: [loader] Code 0 : Couldn't open JSON file C:\WINDOWS\system32\nv-vk64HOLD.json
INFO: [loader] Code 0 : Found manifest file C:\WINDOWS\System32\amd-vulkan64.json, version "1.0.0"
INFO: [loader] Code 0 : Found manifest file C:\WINDOWS\system32\nv-vk64.json, version "1.0.0"
INFO: [loader] Code 0 : Insert instance layer VK_LAYER_LUNARG_core_validation (C:\Development\Projects\Vulkan\Build\Debug\Vulkan-LoaderAndValidationLayers\layers\.\VkLayer_core_validation.dll)
INFO: [loader] Code 0 : Insert instance layer VK_LAYER_LUNARG_parameter_validation (C:\Development\Projects\Vulkan\Build\Debug\Vulkan-LoaderAndValidationLayers\layers\.\VkLayer_parameter_validation.dll)
WARNING: [loader] Code 0 : ICD ignored: failed to CreateInstance in ICD 1
C:\Development\Projects\Vulkan\Vulkan-LoaderAndValidationLayers\demos\vulkaninfo.c:677: failed with VK_ERROR_INITIALIZATION_FAILED

**Comment by MarkY-LunarG** [comment]
I'm swamped right now.  But I plan to sit down with MarkM on Tuesday and delve into the issue.

**Comment by TiemoJung** [comment]
Hi,

just updated sdk from 21 to 24 and encountered it too (try to execute null pointer on device enum). So it was a change from 21 to 24.

**Comment by pdaniell-nv** [comment]
I think there is a bug in the loader in that it doesn't remove failed ICDs from the total_icd_count or the icd list in terminator_CreateInstance(). It just leaves the failed ICDs there so later when a function like terminator_EnumeratePhysicalDevices() tries to iterate over the ICDs it attempts to use an invalid one.

**Comment by MarkY-LunarG** [comment]
Thanks Piers.  I'm looking into it.  I think I might have a solution, but I'll need to have MarkM try it out.

**Comment by MarkY-LunarG** [comment]
Piers helped me validate my changes.  Pushed to master in Commit f1a0b7c7610b3046d0dabded820319e10a41703b

**Comment by pdaniell-nv** [comment]
FYI the latest NVIDIA driver 372.90 contains the loader with this fix and also another fix on our side which should allow the scenario described above to work.
