### ISSUE TITLE
Recent update of vulkan.hpp breaks 64-bit arch detection in vulkan.hpp

### ISSUE THREAD

**Issue by eoma** [KhronosGroup/Vulkan-LoaderAndValidationLayers#907]
The generator that produced vulkan.hpp for 1.0.25 seemed to ignore the 64-bit architecture test, thereby breaking 64-bit builds. The current version just tests for the defintion of VK_DEFINE_NON_DISPATCHABLE_HANDLE, which is always defined, according to vulkan.h.

See https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/include/vulkan/vulkan.hpp#L47 and https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/include/vulkan/vulkan.h#L57

**Comment by eoma** [comment]
Attempted a fix in #908

**Comment by lenny-lunarg** [comment]
Yeah, it looks like the generator had a bug and I didn't catch that when I updated the header. I'll put your changes into the repo shortly.

**Comment by lenny-lunarg** [comment]
Commit 30f71a34992974494f66a6f939ca0e220005b127 fixed this and is now on master
