### ISSUE TITLE
Consider removing abbreviations from core_validation error messages where they harm readability

### ISSUE THREAD

**Issue by chrisforbes** [KhronosGroup/Vulkan-LoaderAndValidationLayers#910]
From LunarG/VulkanTools#51

**Comment by karl-lunarg** [comment]
Very related to this is avoiding using "shorthand" enum type text in place of the actual enum.  For example, an email from a user prompted me to change:

PRESENT_SOURCE_KHR
to
VK_IMAGE_LAYOUT_PRESENT_SRC_KHR

in a call to log_msg().

People often do web searches using error message text, so including the actual full enum name should help.  In this case, "PRESENT_SOURCE_KHR" was never a "thing" and won't be found in a search.

I suggest that an effort to remove abbreviations should also include checking for this problem.

**Comment by chrisforbes** [comment]
Sounds good to me ...

**Comment by karl-lunarg** [comment]
Will re-assign within LunarG next week.

**Comment by mikew-lunarg** [comment]
I will make a scan for obvious "shorthand" and abbreviations, and I would like to request anyone else aware of cryptic messages or pet peeves to please add here.

**Comment by mikew-lunarg** [comment]
partly fixed by 4b5890faffa54a735782a6b0a628a991ddc86944

**Comment by mikew-lunarg** [comment]
include typo fix by a0508c7a27d892907dbd5fb16b488eba2cd914f1

**Comment by mikew-lunarg** [comment]
substantially complete by d79335137b414d5f89284a9ab3e014beb4ada3eb

**Comment by mikew-lunarg** [comment]
a couple stragglers fixed by 60fb5bb40559043ef0f00976225194cc56ab716f
