### ISSUE TITLE
vkjson_info activates all present layers

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-LoaderAndValidationLayers#914]
I don't know if I'm reporting this in the right repository, because for some unknown weird reason vkjson is present in [three](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/libs/vkjson/vkjson_info.cc) [different](https://github.com/LunarG/VulkanSamples/blob/master/libs/vkjson/vkjson_info.cc) [repositories](https://github.com/LunarG/VulkanTools/blob/master/libs/vkjson/vkjson_info.cc).

The vjkson_info utility [enumerates all instance layers](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/libs/vkjson/vkjson_instance.cc#L109), then [enables them all on the instance](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/libs/vkjson/vkjson_instance.cc#L136) when creating it. There's no good reason to do this and activating all installed layers blindly without knowing what they do is unpredictable and could lead to incompatibilities or crashes.

The utility shouldn't activate any layers except those it needs to function (which I imagine is none).

**Comment by critsec** [comment]
The goal of enabling available layers was so that any device extensions provided by layers would be included in the report.

I'm curious what kinds of problems are being caused by this in practice. Maybe I'm not being imaginative enough, but this program doesn't even touch very much of the API, so a layer breaking it just by being enabled is a bit surprising. I completely agree that blindly enabling all available layers in a "real" app would be bad practice, but doesn't seem too unreasonable for something like this.

We could add a parameter / command-line options to enable all layers or a list of specific layers.

**Comment by karl-lunarg** [comment]
> I don't know if I'm reporting this in the right repository, because for some unknown weird reason vkjson is present in three different repositories.

Vulkan-LoaderAndValidationLayers is an upstream repo for VulkanTools and VulkanSamples.  This is done mainly to support someone using the VulkanTools or VulkanSamples repo standalone, without needing to also get Vulkan-LoaderAndValidationLayers.  This is explained in the README.md files present in both VulkanTools and VulkanSamples repos.

**Comment by baldurk** [comment]
> The goal of enabling available layers was so that any device extensions provided by layers would be included in the report.

The problem is that you can't then know which device extensions are provided by which layer, or which by an ICD. Enabling all layers doesn't necessarily get you the union of all available device extensions. As a real case in point, the RenderDoc layer hides any extensions that it doesn't explicitly support, since it does object wrapping and also the frame capture/replay would break with unknown extensions. So enabling all layers will list _fewer_ extensions than enabling no layers.

> I'm curious what kinds of problems are being caused by this in practice. Maybe I'm not being imaginative enough, but this program doesn't even touch very much of the API, so a layer breaking it just by being enabled is a bit surprising. I completely agree that blindly enabling all available layers in a "real" app would be bad practice, but doesn't seem too unreasonable for something like this.

Layers reported include implicit layers that are never intended to be directly enabled by the application, and in the case of RenderDoc include layers that expect some external setup or configuration that isn't present if they're blindly enabled.

You cannot assume that layers are a) always safe to activate nor b) always add functionality, never hide/take it away, or c) are always compatible/valid in any configuration. There could be layers that are only available if validation layers are disabled, or two layers which conflict in their purpose and cannot be activated together. In a generous case this could lead just to the initialisation failing, but it could be worse. Whether the application does full rendering or just initialisation & query doesn't change that.

I only noticed this because I've been getting crash reports from users who evidently run into some scenario where there's corruption that happens when enabling all layers, including the RenderDoc layer that's not meant to be directly activated. It's not much of a stretch to imagine a layer which when activated without proper setup has other ill effects on a user's system - perhaps creating large temporary files with uninitialised data, or worse. You're essentially hitting undefined behaviour by turning on things without any idea of what they are.

FWIW the program doesn't crash for me but it just waits for a while then bails with `VK_ERROR_INITIALIZATION_FAILED` and no output, after printing "vktrace error: Client: Couldn't find any connections." so possibly the vktrace layer is failing more gracefully without proper setup.

**Comment by critsec** [comment]
Fair enough. Agree we can't blindly enable layers by default. If someone wants to be able to enable specific layers we/I can add that later.

**Comment by karl-lunarg** [comment]
Agreed and explicit layers can always be enabled via environment variables without needing to change the app.
