### ISSUE TITLE
tests: Add better helper for creating pipeline layouts

### ISSUE THREAD

**Issue by chrisforbes** [KhronosGroup/Vulkan-LoaderAndValidationLayers#930]
There are a lot of tests doing this by hand, or creating descriptor sets etc when they don't really care about bound resources at all.

**Comment by jzulauf-lunarg** [comment]
@chrisforbes  -- CreatePipelineHelper -- added 90fb6280 2017-11-11 

tests: Added PipelineMultiSample VUID tests
