### ISSUE TITLE
Layer doesn't check validity of scissor rectangles for vkCmdSetScissor

### ISSUE THREAD

**Issue by C0lumbo** [KhronosGroup/Vulkan-LoaderAndValidationLayers#934]
Section 25.2 of the spec says the following about scissor rectangles:
- The x and y members of offset must be greater than or equal to 0
- Evaluation of (offset.x + extent.width) must not cause a signed integer addition overflow
- Evaluation of (offset.y + extent.height) must not cause a signed integer addition overflow

parameter_validation_vkCmdSetScissor could do with checking these. Particularly the first of the three, which can cause some peculiar behaviour on some tiling hardware.

**Comment by karl-lunarg** [comment]
Should do viewport at the same time.

**Comment by mikew-lunarg** [comment]
partially fixed by 7572b6f915a6b3f8b5992a42d04ad20788c44b1d

**Comment by mikew-lunarg** [comment]
SetViewport part is fixed by 79a99540d19bd9a809eed9af86463eabe79261eb
