### ISSUE TITLE
Core validation complains about invalid memory regions after resolving attachments during renderpass

### ISSUE THREAD

**Issue by gary-sweet** [KhronosGroup/Vulkan-LoaderAndValidationLayers#942]
The following sequence produces a core validation warning that I do not believe to be correct:

1) Create a render pass with 2 attachments (R8G8B8A8 will do)
1st attachment: LOAD_OP_CLEAR, STORE_OP_DONT_CARE, SAMPLE_COUNT_4_BIT
2nd attachment: LOAD_OP_DONT_CARE, STORE_OP_DONT_CARE, SAMPLE_COUNT_1_BIT
The subpass uses only the 1st attachment as a color attachment.
The 2nd attachment is listed in the pResolveAttachments list (i.e. we want to multisample resolve to it).

2) Draw (or clearRect in my case) into the first (multi-sampled) attachment

3) Use vkCmdCopyImage to convert the resolved image in the to something else (after appropriate barriers etc).

This sequence gives this error:
`MEM(ERROR): object: 0x7 type: 8 location: 479 msgCode: 15: vkCmdCopyImage(): Cannot read invalid region of memory allocation 0x7 for bound image object 0x6, please fill the memory before using.`

My belief is that the code in CmdBeginRenderPass in core_validation.cpp is calling SetImageMemoryValid(..., false) because the loadOp was 'DONT_CARE'. I suspect that you need to factor in the fact that some attachments are listed in the pResolveAttachments list.

I believe it's perfectly legitimate to have an attachment that doesn't load, clear or store, but is resolved into, and therefore has valid memory content.

**Comment by chrisforbes** [comment]
If you're providing DONT_CARE as the store op for the resolve attachment, the driver is allowed to throw it away at the end of the renderpass.

**Comment by chrisforbes** [comment]
@tobine, I suspect there's plenty of other bugs in here around handling of resolve attachments, but this sounds like a candidate for a clearer warning -- an attachment is used as a resolve attachment, there are no further uses of it within the render pass, and then the contents are discarded.

**Comment by gary-sweet** [comment]
> If you're providing DONT_CARE as the store op for the resolve attachment, the driver is allowed to throw it away at the end of the renderpass.

Ah ok. I guess I had assumed that being resolved to didn't count as being 'used' by a subpass so the store op should have been ignored. Re-reading the spec with a different view of 'used' changes the meaning in this case. Thanks for clearing that up.
