### ISSUE TITLE
Layers: QueueSubmit checks & side effects not properly separated

### ISSUE THREAD

**Issue by chrisforbes** [KhronosGroup/Vulkan-LoaderAndValidationLayers#945]
CV gets confused about which command buffers are in flight when a queue submission is skipped due to a validation error.

**Comment by chrisforbes** [comment]
This is responsible for a good chunk of the unexpected errors in the tests.

**Comment by tobine** [comment]
@Tony-LunarG Here's an old bug for tracking the QueueSubmit refactor. Assigning to you as you expressed interest in untangling this.

**Comment by mark-lunarg** [comment]
@Tony-LunarG, can we close this guy now?
