### ISSUE TITLE
EnumeratePhysicalDevices resets surfaceFormatCount

### ISSUE THREAD

**Issue by heeen** [KhronosGroup/Vulkan-LoaderAndValidationLayers#948]
the following pseudocode leads to an error message, since the surfaceFormatCount is reset with every enumerate call, even though surfaceFormats have been queried between the calls.

devices = enumeratePhysicalDevices
formats = enumerateSurfaceFormats(devices[0])
enumeratePhysicalDevices
createSwapChain(devices[0])

**Comment by MarkY-LunarG** [comment]
Several questions:
 1. Is this with or without validation enabled? 
 2. Do you mean vkGetPhysicalDeviceSurfaceFormatsKHR instead of enumeratePhysicalDevices?
 3. What graphics hardware are you using?

I looked at the loader and it doesn't do much in the vkGetPhysicalDeviceSurfaceFormatsKHR call but pass it along to the proper ICD,  So, if you're not doing validation, this might be a driver issue.

**Comment by heeen** [comment]
1. this is about an validation error which I think is uncalled for
3. intel ivy bridge

I think the issue lies in the validation layers. If you enumerate physical devices a second time, it forgets that you already queried the surface formats after the first call and complains about it when you want to create a swapchain.

**Comment by heeen** [comment]
https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/fb2ef429c4951f7e23522286a438047346fe9f83/layers/swapchain.cpp#L1192

if I understand it correctly, this code resets the counts even though they were queried before

**Comment by karl-lunarg** [comment]
One possible way to reproduce this (or similar problem).

Put the following code at the bottom of demo_init_vk() in the cube demo:

```
    if (gpu_count > 0) {
        VkPhysicalDevice *physical_devices = malloc(sizeof(VkPhysicalDevice) * gpu_count);
        err = vkEnumeratePhysicalDevices(demo->inst, &gpu_count, physical_devices);
        assert(!err);
        /* For cube demo we just grab the first physical device */
        demo->gpu = physical_devices[0];
        free(physical_devices);
    } else {
        ERR_EXIT("vkEnumeratePhysicalDevices reported zero accessible devices.\n\n"
                 "Do you have a compatible Vulkan installable client driver (ICD) "
                 "installed?\nPlease look at the Getting Started guide for "
                 "additional information.\n",
                 "vkEnumeratePhysicalDevices Failure");
    }

```

This just repeats the call to vkEnumeratePhysicalDevicess later in the init process.
But we get some suspicious validation messages.

**Comment by mark-lunarg** [comment]
This has been fixed.  @heeen, please reopen if you still experience related problems.  Thanks!
