### ISSUE TITLE
Layers: Don't treat vkFree/vkDestroy* on VK_NULL_HANDLE as an error

### ISSUE THREAD

**Issue by haasn** [KhronosGroup/Vulkan-LoaderAndValidationLayers#949]
According to the vulkan spec, passing VK_NULL_HANDLE as the object parameter for vkFree/vkDestroy is perfectly valid and should generate no error, yet the layers seem to do so. (Specifically, ObjectTracker does)

This is rather inconvenient to me since re-freeing something that doesn't exist is a normal occurrence in my code base. (e.g. consider acquiring 5 resources: If the 5th acquisition fails, I can call my normal `destroy` routine to destroy anything that _did_ end up getting acquired. For another example, consider a routine that updates the swapchain to the a size, destroying and recreating stale resources as necessary. On the first frame, there are no old resources to destroy)

The work-around for now is to have an extra condition like `if (obj) vkDestroyThing(dev, obj, NULL);` in front of every free call, but it shouldn't be necessary.

**Comment by yavn** [comment]
I'd suggest changing this error to a warning, or maybe even a performance warning (a useless function call). The check has to be done somewhere, so it's good to let the app know that it's doing a redundant operation.

**Comment by chrisforbes** [comment]
I have a branch that relaxes the validation for this. Unfortunately, at least one vendor's driver throws a fit when being asked to destroy VK_NULL_HANDLE.

**Comment by yavn** [comment]
Right, no need to rush this in. CTS is just getting the coverage for this. Thanks.

**Comment by chrisforbes** [comment]
@yavn I'm not sure I agree on even having a perf warning here. Everyone's already paid for the ICD checking this to make it a noop-- you're suggesting /for perf/ that the app check too?

**Comment by yavn** [comment]
Yea, let's not make it more complicated than it is... I agree just being silent about this is perfectly fine.

**Comment by haasn** [comment]
This isn't about performance at all. One `if (!var) return` at the beginning of a function is not going to cause any measurable performance differences unless you're destroying tens thousand of objects per frame, and if you're destroying tens of thousands of objects per frame you have more problems than the `if`.

I'm mostly concerned about code readability. If I have to do all the checking myself, in my own code, every time I use one of these functions, then it makes cleanup routines uglier. Doing it at the start of every free/destroy function call is much cleaner.

Also, crashing on `destroy(VK_NULL_HANDLE` violates the spec, therefore the goal should be to make sure no Vulkan implementation does this - rather than hiding the issue by forcing everybody to do the check in application code and letting the implementation bugs go unnoticed.

**Comment by mark-lunarg** [comment]
Fixed by PR #1167 .

**Comment by haasn** [comment]
Thanks!
