### ISSUE TITLE
tests: Consider removing implicit BeginRenderPass on BeginCommandBuffer

### ISSUE THREAD

**Issue by chrisforbes** [KhronosGroup/Vulkan-LoaderAndValidationLayers#950]
This happens if the right set of initialization has happened, and doesn't otherwise. Some tests explicitly call EndRenderPass immediately after, since they need the state but don't want the render pass instance.

It would be clearer to just explicitly begin the renderpass.

**Comment by lentinem** [comment]
Can you elaborate on this? End cannot be called if Begin is not called.

**Comment by tobine** [comment]
@lentinem this is a suggestion for improving the validation test framework. Currently in the test framework if you call BeginCommandBuffer() it creates an implicit renderpass. @chrisforbes is suggesting that the framework stop doing that.

**Comment by Tony-LunarG** [comment]
Fixed with 7dc45c3
