### ISSUE TITLE
minImageTransferGranularity requirements are not validated properly

### ISSUE THREAD

**Issue by impakt73** [KhronosGroup/Vulkan-LoaderAndValidationLayers#951]
On my AMD hardware which exposes (8, 8, 8) as the image transfer granularity on the dedicated transfer queue, I get validation errors from my application. These errors don't show up on my Nvidia hardware which exposes (1, 1, 1) on a similar transfer only queue.

Here's a couple of the errors from the log:

vkCmdCopyBufferToImage(): pRegion[0].imageExtent (w=1280, h=1020, d=1) must respect this command buffer's queue family image transfer granularity (w=0, h=0, z=0).
vkCmdCopyBufferToImage(): pRegion[0].imageExtent (w=2048, h=2048, d=1) must respect this command buffer's queue family image transfer granularity (w=0, h=0, z=0).

After looking into the code a bit, it seems like the only validation that the layers do for the copy extents is checking if they're evenly divisible by the minImageTransferGranularity. (There's also a small C++ pointer usage bug that causes the granularity to be printed as (0, 0, 0) every time.)

According to the Vulkan spec, the rules for minImageTransferGranularity are more complicated than alignment checks. These rules can be found at the end of Chapter 4, Section 1 (Physical Devices). In short, the rules for extents have two parts:
1) the extents can either be even integer multiples of the granularity (what the layers currently check).
OR
2) the offset plus the extent dimensions must be equal to the corresponding image subresource extent. 
In my application's case, my usage of copy should be valid with an (8, 8, 8) granularity due to the second part of the rule. The images I'm copying to have the same dimensions as the copy extent.

There's also another part of the section on minImageTransferGranularity that details how queues which expose (0, 0, 0) are handled and none of those conditions appear to be validated either. Additionally, there wasn't any obvious handling of the special rules for block compressed image formats.

I looked at the Vulkan hardware database and it looks like AMD is the only vendor that currently exports granularity requirements greater than (1, 1, 1) so it's probably the only hardware that this issue affects. I ran into these errors when doing streaming texture uploads over the dedicated transfer queue (which I'd guess are fairly common right?) so I'd imagine this issue will show up a lot for developers on AMD hardware.

**Comment by chrisforbes** [comment]
Fixed by #952
