### ISSUE TITLE
DrawState layer: Invalid layout reported in a debug callback

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#96]
If an incompatible layout is used for an attachment, the following error is reported to the app:

![image](https://cloud.githubusercontent.com/assets/17761066/13665114/0aa187da-e6ab-11e5-8acb-409303d9da08.png)

This is as per following implementation in draw_state.cpp:

![image](https://cloud.githubusercontent.com/assets/17761066/13665132/1e954600-e6ab-11e5-90f2-e75598ca919a.png)

I believe we should be passing the "layout" field to log_msg() call instead:

![image](https://cloud.githubusercontent.com/assets/17761066/13665178/6092e5e4-e6ab-11e5-80df-30889eec8c5f.png)

For extra kudos, we should be passing a null-terminated string corresponding to the specific layout enum value.

**Comment by tobine** [comment]
Just submitted #107 to fix this. There were 3 separate messages in that function that all needed a similar fix.

**Comment by tobine** [comment]
Fix pushed to master
