### ISSUE TITLE
Is reading undefined memory an error?

### ISSUE THREAD

**Issue by Tony-LunarG** [KhronosGroup/Vulkan-LoaderAndValidationLayers#965]
Running Vulkan CTS with validation enabled, I see many "Cannot read invalid memory _address,_ please fill the memory before using." messages.  I investigated one where the test was clearing a portion of an image with STORE_OP_DONT_CARE for the color attachment in the renderpass, and then doing a CopyImageToBuffer of the whole image, and getting the validation error.  I opened an issue with CTS which was closed with "reading undefined values is not an error" and stated that although the test was reading the whole image, including the undefined memory, the validation code was not checking the undefined memory for any values, it was just verifying values outside of the undefined region.  Checking the spec, I don't see anywhere that states that reading undefined memory is disallowed or is an error, so I'm wondering if reading undefined memory should be a warning?

**Comment by lentinem** [comment]
Did you post this on the spec itself as well (it would be good to link that to this)? As I mentioned before, I cannot see how "reading undefined values is not an error" can possibly be true and I would like a strong argument from Khronos before we modify this on the validation side.

**Comment by Tony-LunarG** [comment]
One section that I did see in the spec, under 4.2.3, Lost Device, indicates that in at least that case, reading undefined memory is valid:

When a device is lost, its child objects are not implicitly destroyed and their handles are still valid. Those objects must still be destroyed before their parents or the device can be destroyed (see the Object Lifetime section). The host address space corresponding to device memory mapped using vkMapMemory is still valid, and host memory accesses to these mapped regions are still valid, but the contents are undefined. It is still legal to call any API command on the device and child objects.

**Comment by lentinem** [comment]
I believe the intent of that is to allow the client code to run without crashing after a device is lost but the same argument doesn't really apply to purposely throwing away memory and then trying to read it.

**Comment by mark-lunarg** [comment]
I agree with Tony that this should be a warning.

**Comment by tobine** [comment]
I was only slightly leaning towards error when this first came up but the more I think about it the stronger I believe it should be an error. Reading undefined values causes undefined behavior and all undefined behavior that I can think of is a validation ERROR. Happy to adjust my view if Khronos sentiment is different.

**Comment by ratchetfreak** [comment]
It's going to depend on where the line between warning and error is put. Something not quite tied down in the validation layers I believe.

**Comment by lentinem** [comment]
Errors are defined as something that should never be done; warnings are something that can be done if the user is very careful but is often the cause of an app bug.

**Comment by lentinem** [comment]
Resolve to change this to a warning.

**Comment by karl-lunarg** [comment]
Changed log messages to warning level with f48a83f5b5548cd46a12770c7542ff902537ad3e.
