### ISSUE TITLE
DrawState: "Layout for color attachment is X but can only be COLOR_ATTACHMENT_OPTIMAL or GENERAL" is not correct

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#97]
The debug callback occurs if any of the subpasses defined for a renderpass uses a layout which is not either of the two layouts the layer considers as valid. The condition is checked at vkCreateRenderPass() call time. However, there is no spec language which imposes such a restriction. If there was one, functions such as vkCmdClearAttachments() would have been illegal.

Proposal is to extend the check so that it also accepts TRANSFER_DST layout, and to optionally reduce the call-back's level to a warning.

**Comment by lentinem** [comment]
I will check this but it definitely was in the spec at some point in time. Will report back.

**Comment by lentinem** [comment]
Spec says "An image (or a sub-range of it) in this layout (TRANSFER_DST) can only be used as the destination operand of the commands vkCmdCopyImage, vkCmdBlitImage, vkCmdCopyBufferToImage, vkCmdResolveImage, vkCmdClearColorImage, and vkCmdClearDepthStencilImage." All of these commands cannot be executed inside a render pass. vkCmdClearAttachments is not a transfer operation and would need COLOR_ATTACHMENT_OPTIMAL.

**Comment by DominikWitczakAMD** [comment]
Good catch about the valid usage of the transfer-related commands.

However, as per spec language, it is still not an error to define a color attachment in a layout which is different from GENERAL or COLOR_ATTACHMENT_OPTIMAL. It is one, however, if one attempts to issue a draw call from inside such a subpass, without having transitioning the image ot the right layout first.

In principle, I do agree the condition could indicate an error, but that's not necessarily true in all cases. In order to avoid confusing the ISVs, can we reduce the level of the notification to a warning, please?

**Comment by lentinem** [comment]
I suppose I'm ok with making this a warning. Do you anticipate actually doing anything with an attachment in a render pass thats not COLOR_ATTACHMENT_OPTIMAL? If so, it might be helpful to figure out what that is as there could very well be vendors that would have problems with that and we might need to bring it up with the WG.

**Comment by DominikWitczakAMD** [comment]
Not right now, but it is not said transfer layout-dependent commands would never be introduced in the future. Also, it's fairly easy to run into this situation, if your image is earlier blitted/copied to, and then you want to render something to it. In such case, your renderpass could define that attachment to have an initial layout of TRANSFER_DST, but for the subpass it would be used in, it could have a COLOR_ATTACHMENT_OPTIMAL layout assigned. This, in turn, would let the driver perform the implicit TRANSFER_DST->COLOR_ATTACHMENT_OPTIMAL transfer at a moment most convenient for the hardware.

It is indeed a sort of a corner case not all IHVs may be aware of, so we may need a conformance test just to ensure everyone's implementation do not crash in such cases. Not sure if it's worth WG's attention though. Might consider bringing this up at the F2F.

**Comment by lentinem** [comment]
Changed to warning. Closing.

**Comment by lentinem** [comment]
I was reading this part of the spec again for a different issue and I'm not convinced this should be a warning anymore. The example above is not what the check is for as this checks to make sure the pColorAttachment layout is COLOR_ATTACHMENT_OPTIMAL which would still be true above. I'm inclined to put this back to an error as the only way I could potentially see this being valid from a layout standpoint as if the color attachment was never used but that seems like an app bug as well. Let me know if you think otherwise.

**Comment by DominikWitczakAMD** [comment]
OK. We can always re-open this issue if we hear anyone else complaining about this call-back in the future.
