### ISSUE TITLE
vkEnumeratePhysicalDevices doesn't return VK_INCOMPLETE

### ISSUE THREAD

**Issue by yavn** [KhronosGroup/Vulkan-LoaderAndValidationLayers#971]
There's a subtle problem with `vkEnumeratePhysicalDevices` function. It should be possible to get `VK_INCOMPLETE` from it, if the following conditions are met:

- `pPhysicalDeviceCount` < number of physical devices reported by the instance
- `pPhysicalDevices` != nullptr

Currently this isn't possible. The function always returns `VK_SUCCESS` and overwrites the count with the number of physical devices available. Instead, it should leave the count untouched (number of physical devices returned is zero), don't modify memory at `pPhysicalDevices`, and return `VK_INCOMPLETE`.

I'm also getting this warning, which I suppose is fine:

> DL(WARN): object: 0x0 type: 2 location: 11374 msgCode: 6: Call to vkEnumeratePhysicalDevices() w/ pPhysicalDeviceCount value 0, but actual count supported by this instance is 2.

This is needed by CTS as it leads to a failing test.

One side note: there seems to be interference between normal loader behavior and `VK_LAYER_NV_optimus`, so be sure to disable this layer if you wish to reproduce the bug. Otherwise API will return `VK_INCOMPLETE` as expected.

**Comment by MarkY-LunarG** [comment]
I don't see anywhere in the spec that VK_INCOMPLETE should be returned if pPhysicalDevices != nullptr.  The other issue appears valid.

**Comment by MarkY-LunarG** [comment]
Committed with 87070d81bca386e4a3fb1295e8d7dc232ec48622
