### ISSUE TITLE
No debug call-back reported in a vkCmdUpdateBuffer()->dispatch/draw call scenario

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#972]
Consider a command buffer A which does the following:
1. One or more vkCmdUpdateBuffer() calls which fill non-overlapping regions of buffer X with data.
2. A dispatch or a draw call which follows, and which consumes the data delivered by the previous operation.

There should be a buffer / global barrier between steps 1 and 2. Lack of one goes unnoticed by the core validation layer.

**Comment by tobine** [comment]
This is a dupe of #892
