### ISSUE TITLE
Crash when dependency.srcSubpass is VK_SUBPASS_EXTERNAL

### ISSUE THREAD

**Issue by asylum2010** [KhronosGroup/Vulkan-LoaderAndValidationLayers#978]
Call stack:

`VkLayer_core_validation.dll!core_validation::CheckPreserved(const core_validation::layer_data * my_data, const VkRenderPassCreateInfo * pCreateInfo, const int index, const unsigned int attachment, const std::vector<DAGNode,std::allocator<DAGNode> > & subpass_to_node, int depth, bool & skip_call) Line 9468	C++`

`VkLayer_core_validation.dll!core_validation::CheckPreserved(const core_validation::layer_data * my_data, const VkRenderPassCreateInfo * pCreateInfo, const int index, const unsigned int attachment, const std::vector<DAGNode,std::allocator<DAGNode> > & subpass_to_node, int depth, bool & skip_call) Line 9482	C++`

`VkLayer_core_validation.dll!core_validation::ValidateDependencies(const core_validation::layer_data * my_data, const FRAMEBUFFER_NODE * framebuffer, const RENDER_PASS_NODE * renderPass) Line 9646	C++`

`VkLayer_core_validation.dll!core_validation::CmdBeginRenderPass(VkCommandBuffer_T * commandBuffer, const VkRenderPassBeginInfo * pRenderPassBegin, VkSubpassContents contents) Line 10303	C++`

`VkLayer_object_tracker.dll!object_tracker::CmdBeginRenderPass(VkCommandBuffer_T * commandBuffer, const VkRenderPassBeginInfo * pRenderPassBegin, VkSubpassContents contents) Line 2514	C++
VkLayer_parameter_validation.dll!parameter_validation::CmdBeginRenderPass(VkCommandBuffer_T * commandBuffer, const VkRenderPassBeginInfo * pRenderPassBegin, VkSubpassContents contents) Line 4643	C++
`

`VkLayer_threading.dll!threading::CmdBeginRenderPass(VkCommandBuffer_T * commandBuffer, const VkRenderPassBeginInfo * pRenderPassBegin, VkSubpassContents contents) Line 2980	C++`

`71_Deferred.exe!Render(float alpha, float elapsedtime) Line 1107	C++`

`71_Deferred.exe!main(int argc, char * * argv) Line 815	C++`

**Comment by chrisforbes** [comment]
Fixed by #980
