### ISSUE TITLE
error message concerning un-updated descriptor refers to "draw" upon call to vkCmdDispatch

### ISSUE THREAD

**Issue by mjwach** [KhronosGroup/Vulkan-LoaderAndValidationLayers#979]
I call vkCmdDispatch after creating, updating, and binding some descriptor sets.  There's something wrong with the way I've configured the descriptor sets, so I should and do get an error message:

"DS 0x5b encountered the following validation error at draw time: Descriptor in binding #3 at global descriptor index 3 is being used in draw but has not been updated."

But the vkCmdDispatch call that triggers the message is not a "draw" call; it's just running some calculations in a compute shader.  I do have some drawing calls in other places in my code (and they are working fine, and producing no error messages).  Thus this error message tells me that I should look in the wrong place when trying to fix the error, wasting my time.

Maybe it should use the word "dispatch" rather than "draw".  Naming the exact function that triggered the message ("vkCmdDraw" or "vkCmdDrawIndexed" or "vkCmdDispatch" or whatever else) might be even better, unless it's infeasible or inappropriate for some reason.

**Comment by tobine** [comment]
Hi @mjwach 
Thanks for noting this.
We've already updated this error message in the master branch and the fix will be included in the next SDK. You can see the updated code in [core_validation.cpp](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/core_validation.cpp#L3005).
