### ISSUE TITLE
DrawState layer: "Fence X is already in use by another submission" error incorrectly reported for vkQueueSubmit() calls whose <submitCount> arg is > 1

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#98]
This is probably due to the fact the check is performed for each submission, whereas it should be done once per vkQueueSubmit() call:

![image](https://cloud.githubusercontent.com/assets/17761066/13665787/61907706-e6ae-11e5-88d8-bfdaaf8da07b.png)

**Comment by tobine** [comment]
Submitted #108 to fix this by pulling fence in-use check before the loop.

**Comment by tobine** [comment]
Fix pushed to master
