### ISSUE TITLE
support placing vk_layer_settings.txt in a directory other than CWD

### ISSUE THREAD

**Issue by jjulianoatnv** [KhronosGroup/Vulkan-LoaderAndValidationLayers#983]
The validation layers can be configured through a file named vk_layer_settings.txt. In a webinar it was claimed that this file must reside in the application's CWD at the time the layers are initialized.

Three issues:

1. Sometimes the app's CWD is a location that is not writable. I.e., there is no way to create a new file in that directory.

2. CWD at the time the layers are initialized may be different from CWD at app start, and/or different from CWD after the layers are read. Mandating that the file be in CWD at "some time" during init seems fragile for apps that change their CWD.

3. Driver and tools authors might want to configure layers when running apps that were authored by 3rd parties. Dropping a vk_layer_settings.txt file into each app's CWD (and discovering each app's CWD) could be tedious for a driver or tool author who tests against 100 different apps.

Proposed solution: Permit an optional environment variable to override the pathname to the settings file.

Since enabling of layers is already controlled through an environment variable, adding another environment variable for the location of the settings file seems no less secure than the status quo.

**Comment by karl-lunarg** [comment]
The docs on LunarXchange (layers.html) could also be clarified here.  They say that the file "must be located in the same directory as the running application", which isn't super clear, and may even be slightly misleading.

The implementation just does an fopen() using the "vk_layer_settings.txt" filename, which will try to open the file in whatever the current directory is at the time.  One interpretation of the current doc suggests that the file could be placed in the same directory as the application executable, which would be wrong.

I've verified empirically that the file is opened from the current directory of the process.

The default behavior of using the CWD in the absence of the new env var should probably be retained, but the docs should be improved to clarify that the file is opened from the process' CWD at the time the layers are initialized.  This could be done at the same time the docs are adjusted to indicate support for the new env var.

**Comment by jjulianoatnv** [comment]
Agreed that the current behavior can be retained as default when an alternate pathname is not specified (by environment variable).

Note that I proposed the env variable specify a pathname, not a directory name.  Specifying a pathname simplifies the user alternating between configuration sets, where each configuration set is stored with a different filename that self-describes the purpose of a given configuration set.  IIRC the analogous control for output file is an env variable specifying a pathname.

**Comment by lenny-lunarg** [comment]
The environment variable is called VK_LAYER_SETTINGS_PATH. You can set it to a filename, or you can set it to a directory (in which case the layers will look for vk_layer_settings.txt within that directory).
