### ISSUE TITLE
Android : clang + libc++

### ISSUE THREAD

**Issue by Sumenia** [KhronosGroup/Vulkan-LoaderAndValidationLayers#992]
I want to build for android arm64-v8a using clang toolchain and libc++ but i get errors. ( it compiles fine with libstdc++ ).

I'm using Android NDK r13 beta2

<img width="1208" alt="screen shot 2016-09-29 at 02 13 18" src="https://cloud.githubusercontent.com/assets/6384877/18942919/532e48c4-85ea-11e6-8b11-f5d26348a040.png">

**Comment by courtney-g** [comment]
I'm curious, why do you need the validation layers compiled with libc++?

**Comment by jeremy-lunarg** [comment]
Clang uses libc++; not libstdc++. They are not ABI compatible.

**Comment by mark-lunarg** [comment]
@courtney-g, if there are no short-term plans to add libc++ support can you close this one?

**Comment by courtney-g** [comment]
I can only guarantee the default build environment will work for the validation layers. So, closing this as will-not-fix.
